### ISSUE TITLE
Archiving individual assignments

### ISSUE THREAD

**Issue by fvanwijk** [education/classroom#1002]
We are using Classroom to assess candidates for our company during the interview process. There is just one classroom with an assignment. The repos are private.

After the assessment has taken place, the candidate is accepted or rejected. After the interview we want to archive the individual assignment, because:
- We don't need the solution anymore except for reference
- We run out of private repos without upgrading the Billing Plan

In our case we have a "solutions" repository with a subfolder per individual solution. The assignment repo is manually being merged into the solutions repo. We also want to keep the history of the assignment repo (being merged in).

It would be nice to archive an assignment using the GUI. I could imagine that everyone has their own preference of how assignments should be archived, so having a hook that calls a custom self made script could also be considered.

Related to #602 and #502.

**Comment by mozzadrella** [comment]
👋  hi @fvanwijk thanks for opening this issue.

We will consider archiving in the phase [of our roadmap](https://github.com/education/classroom/blob/master/ROADMAP.md) that addresses re-use and future prep.
