### ISSUE TITLE
Stafftools button misaligned

### ISSUE THREAD

**Issue by nwoodthorpe** [education/classroom#1010]
The impersonate button is a little bugged out right now.

<img width="752" alt="screen shot 2017-07-12 at 9 44 45 am" src="https://user-images.githubusercontent.com/4149056/28129147-2d66468a-66e7-11e7-9d14-35ee63769cfe.png">

**Comment by arolson** [comment]
@nwoodthorpe would you know how to replicate the issue?

**Comment by nwoodthorpe** [comment]
@arolson creating a new user, then viewing the stafftools page for that user should be sufficient. You'll need to make sure the user you're logged in as is set as an admin in your `.env`.

localhost:5200/stafftools/users/<user_id>

Just checked in prod, this hasn't been fixed yet.

**Comment by arolson** [comment]
Ok awesome I will take a look.
