### ISSUE TITLE
Multiple classroom in one organization

### ISSUE THREAD

**Issue by parejajd** [education/classroom#1049]
is possible create two o more classroom in one organization?

I am obtain an error
![image](https://user-images.githubusercontent.com/3516716/28739832-f24933d4-73c3-11e7-87fa-8ad81083648a.png)

**Comment by wilfriedE** [comment]
Hi @parejajd this is currently not support, but it's something we have on our [roadmap](https://github.com/education/classroom/projects/7#card-3489110). Feel free to sign up to test out new features  #960.

**Comment by orboan** [comment]
So is it still not available? I teach 2 subjects in my school, each one belonging to one group of students, and I'd like to create one github classroom per each group of students / subject. How can I achieve that? At this moment I created 1 classroom for one of the subjects, but trying to create the second one I cannot. Thus should I create another organization? This sounds illogical as both groups of students belong to the same school. Thanks.

**Comment by abdulmeque** [comment]
Same problem here, I just manage it by appending an extra field in the roaster identifying the course+year+term and also using "class identifying" ()names for the assignments. So I a each assignment as the entry point to monitor progress and so on.
