### ISSUE TITLE
Can add any user to an organization

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#106]
`OrganizationsController#invite_users` doesn't check that the id of the user being invited is actually part or the organization. This can be used to add arbitrary users to your organization. This *could* be an abuse vector since the new organization will show up on the user's dashboard and they will have no way to leave the organization. For example, when they go to their dashboard they might see:

<img width="732" alt="screen shot 2015-08-19 at 5 41 34 pm" src="https://cloud.githubusercontent.com/assets/1144197/9372235/96486090-4699-11e5-8c0c-3ffad9af1fc3.png">

The controller should check that the user being invited is actually a member of the GitHub organization.

**Comment by tarebyte** [comment]
This feature will be going away, see #107
