### ISSUE TITLE
New assignment view shows max. 30 commits

### ISSUE THREAD

**Issue by obcode** [education/classroom#1063]
Refering to #989 is see the following issue:

All repositories with 30 **and more** commits will only be viewed to have 30 commits.

E.g.
![bildschirmfoto 2017-08-07 um 07 55 55](https://user-images.githubusercontent.com/281558/29013913-6fe00ca8-7b46-11e7-8569-e63d53b2ee75.png)

- innovativeTeamname: 42 commits
- jularo: 54 commits
- a: 71 commits
- fancy-team-42: 58 commits
- a-team: 47 commits
- cmp: 22 commits which is viewed correctly

**Comment by nwoodthorpe** [comment]
Oh interesting. The API must be paginating the request to 30 commits. I'll :eyes: this today, thanks!

**Comment by obcode** [comment]
👍  Thank's!!!
