### ISSUE TITLE
Org invitations are a spam vector

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#107]
Organization invitations can be sent to any email address. The content of the invitation can be hijacked by modifying the Organization title, which can be quite long and even contain newlines:

*Creating an org with newlines in the title:*

```http
POST /orgs/free-viagra HTTP/1.1

utf8=%E2%9C%93&_method=patch&authenticity_token=[redacted]&organization%5Btitle%5D=Free+Viagra%21%21%21%21+https%3A%2F%2Fsketchy.site%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d%0a%0d&commit=Update+Organization
```

*Sending spam to any email address:*

```http
POST /orgs/free-viagra/invite-users HTTP/1.1

utf8=%E2%9C%93&_method=patch&authenticity_token=[redacted]&github_owners%5Bmastahyeti%5D=1144197&github_owner_emails%5Bmastahyeti%5D=[redacted]@gmail.com&commit=Invite
```

*Spam!!!*

<img width="903" alt="screen shot 2015-08-19 at 5 58 09 pm" src="https://cloud.githubusercontent.com/assets/1144197/9372459/e624e622-469b-11e5-96fd-05e20ae36b55.png">

This one is kind of hard to solve. Some options are:

1. Only send emails to addresses listed on the invited user's GitHub profile.
2. Implement some kind of rate limiting and spam detection.

**Comment by tarebyte** [comment]
@mastahyeti number 1 works for me, it'll be annoying for users, but if they don't have a public facing GitHub email address there isn't a whole lot we can do.

Thoughts? /cc @johndbritton

**Comment by johndbritton** [comment]
I think that's fine, as the organization invites are only for inviting teachers and admins.

@tarebyte is there a way for an org admin to access classroom without being invited?

**Comment by tarebyte** [comment]
We could have it so anyone who is an admin who signs in to classroom automatically gets added to the org on Classroom

**Comment by johndbritton** [comment]
> We could have it so anyone who is an admin who signs in to classroom automatically gets added to the org on Classroom

Yeah, I think that makes sense.

**Comment by tarebyte** [comment]
@mastahyeti thank you for the great feedback here, we're going to change this so that you have to add the admin on GitHub first and then we will be adding them to classroom via url, similar to the assignment flow.
