### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ghost** [education/classroom#1080]
https://classroom.github.com/g/fQrSlYuO

I created a team but used the wrong name.
Then I left the team, couldn't recreate one.
The team name was "=͟͟͞͞( •̀д•́) " (without ").
Plz fix it.

**Comment by wilfriedE** [comment]
Hi @nicksun79, you can resolve this by having your instructor/organization owner add you back to the "=͟͟͞͞( •̀д•́) " group. Your instructor can also change your group name. Let me know if this helps out.
