### ISSUE TITLE
Infinite OAuth redirect when signing up

### ISSUE THREAD

**Issue by jaggy** [education/classroom#1097]
I tried signing up today and after authorizing the app, it sends me in this infinite loop of trying to authorize my account and redirecting to the classroom.

Here's a recording of the issue: http://d.pr/v/HeMN0S

I've also disabled all browser extensions, tried it on both Safari and Chrome.

Is there anything I'm missing?

**Comment by malloc82** [comment]
Same problem here. My students cannot get authorized, it keeps going back to the authorization page. It was working yesterday.

**Comment by milindkulkarni** [comment]
Same issue here. Several of my students are getting what I assume is a variant of the same error, saying "This application has made an unusually high number of requests to access your account. Please reauthorize the application to continue."

**Comment by tarebyte** [comment]
@jaggy @malloc82 @milindkulkarni I deployed a fix for the redirect I think, mind giving it a look?

**Comment by milindkulkarni** [comment]
That seemed to fix part of the problem: I was able to log in with a test account and authorize Github Classroom successfully. But trying to set up the assignment with the assignment link still led me down a path of infinite redirects (Safari eventually stopped trying to load the page). Here's the assignment link that's causing the issue: https://classroom.github.com/g/fQrSlYuO

**Comment by tarebyte** [comment]
@milindkulkarni I'm not getting redirect on that link.

**Comment by milindkulkarni** [comment]
@tarebyte Seems to be working now! It must have been some weird caching issue on my side.

**Comment by jaggy** [comment]
Thank you! It's now working for me as well. <3

**Comment by josephwandile** [comment]
Having the same problem. Have tried clearing out caches on all browsers, etc. Any idea what could be causing the issue?

**Comment by daturkel** [comment]
I experienced this issue today, so it appears to still be around.
