### ISSUE TITLE
I didn't see all organizations in list when choose create new classroom

### ISSUE THREAD

**Issue by korel-san** [education/classroom#1104]
![screenshot at 10-40-56](https://user-images.githubusercontent.com/946369/29655272-31d78ec4-88b9-11e7-88fe-f91ee82acd1f.png)
![screenshot at 10-40-28](https://user-images.githubusercontent.com/946369/29655273-31dc1534-88b9-11e7-96a1-4cd8bd207a32.png)

**Comment by wilfriedE** [comment]
Hi @korel-san, have you tried the ProTip (at the bottom of the second screenshot)?

**Comment by mozzadrella** [comment]
Hello @korel-san, you need to authorize GitHub Classroom to talk to the organizations you created. See @wilfriedE's commend above ^^.
