### ISSUE TITLE
No option to add/edit classroom student roster

### ISSUE THREAD

**Issue by BrianEmilius** [education/classroom#1105]
I watched the [GIF](https://github.com/blog/2418-github-classroom-now-supports-deadlines-and-class-rosters) that shows how to add and manage classroom student rosters, but when I am in a classroom of my own, I cannot find any options to manage roster as shown in the GIF.

**Comment by tarebyte** [comment]
@BrianEmilius it seems as though the gif is missing a step or two 😄 

For anyone who comes along this issue, I'm going to go through the entire flow.

# Step 1
On your classrooms home page click on an existing Classroom.

<img width="1040" alt="screen shot 2017-08-25 at 07 50 37" src="https://user-images.githubusercontent.com/564113/29712957-5bee1082-896a-11e7-9322-81b807916721.png">

# Step 2
On that classroom page select "Manager classroom"
<img width="1061" alt="screen shot 2017-08-25 at 07 50 44" src="https://user-images.githubusercontent.com/564113/29713005-9ea48b22-896a-11e7-87af-f23c578e3f86.png">

# Step 3
On the side navigation select "Roster management"
<img width="1043" alt="screen shot 2017-08-25 at 07 50 52" src="https://user-images.githubusercontent.com/564113/29713034-c6dc07c8-896a-11e7-83a0-cf02e5ad74ec.png">

And you're there!

@BrianEmilius if for some reason it's not showing up for you please let us know 😄

**Comment by BrianEmilius** [comment]
Ypu, it's the roster management link that I don't have.

**Comment by tarebyte** [comment]
@BrianEmilius that's my bad, I thought we had turned on the feature flag for everyone.

**Comment by BrianEmilius** [comment]
No worries, I'm just happy we figured it out :)
Thanks for the reply!
