### ISSUE TITLE
roster system totally broken or doesn't make sense

### ISSUE THREAD

**Issue by prismspecs** [education/classroom#1107]
Can't find any info on how to add a student. Also in the video it said we would be able to just give students a link and have them join via that portal, but how? Nothing seems to work, and populating the roster fields with info yields very strange results

**Comment by sanicki** [comment]
@prismspecs Please let me know if you've already watched all three Getting Started videos found at https://classroom.github.com/videos.

**Comment by mozzadrella** [comment]
@prismspecs hope those videos got you sorted. Can also ask follow up questions at: https://education.github.community/
