### ISSUE TITLE
Get Warning icons over student team

### ISSUE THREAD

**Issue by nag92** [education/classroom#1108]
When I try to see all my student repos I sometimes get warning icons over the names.
If I refresh the page they will go away for some but appear on others. 
![image](https://user-images.githubusercontent.com/7646872/29736726-12b17f40-89d2-11e7-9154-6d17d7697a49.png)

**Comment by BelieveC** [comment]
@tarebyte, Can I go for it?

**Comment by nag92** [comment]
is this issue being worked on?

**Comment by tarebyte** [comment]
@nag92 I seemed to have resolved your issue with https://github.com/education/classroom/pull/1127

This is the view I see now:

<img width="1054" alt="screen shot 2017-09-04 at 15 40 30" src="https://user-images.githubusercontent.com/564113/30037278-6d0e415a-9187-11e7-93e6-cc4ea3684214.png">

Does this look right?
