### ISSUE TITLE
following assignment link fails to create repo

### ISSUE THREAD

**Issue by zingale** [education/classroom#1116]
I've create a simple test repo in my classroom 31287650-phy-604-stony-brook-university

when I create a simple test assignment with a single line README, and then follow the invitation link myself.  The import never finishes.  How can I actually make the link work to create a working repo?

**Comment by zingale** [comment]
update: it finished after about 20 minutes.  Is that normal for a simple repo like this?  Should I warn students that they may have to wait 30 minutes or more from following a link until the repo is created?

**Comment by tarebyte** [comment]
@zingale sorry for the delay, we don't actually have control of the importer, but it normally doesn't take that long to import a repository.

**Comment by weeser** [comment]
We have also been having issues with this.  We teach classes of about 40-50.  Most students have no problem and the repository is created and starter code is imported; however, some class periods we get 1/4 of the class getting stuck.  It will create the repository fine, but it takes 20+ minutes for it to import the starting code/commits.   I usually end up having to delete the repository and have them click the invite link again.  This usually works, but sometimes I have to manually import the code to their repo.  This can be incredibly time consuming when its only a two hour lab and leaves students frustrated.
