### ISSUE TITLE
Internal Server Error 500 When Accessing an Assignment in GitHub Classroom

### ISSUE THREAD

**Issue by gkapfham** [education/classroom#1117]
Hello! Thank you so much for developing GitHub Classroom. So far, my students and I have really enjoyed using the system. In advance of running the laboratory session today, I have tested it repeatedly with small class sizes for our first laboratory assignment and everything always worked correctly.

That is, it was possible to:

- Instructor: Create an organization for the class
- Instructor: Connect the organization to the GitHub Classroom
- Instructor: Create an assignment template in a "starter" GitHub repository
- Instructor: Create an assignment in GitHub Classroom using the starter repository
- Instructor: Share the link for the assignment so that students can begin the assignment
- Student: Accept the assignment and clone the repository
- Student: Complete the assignment and push their solutions
- Instructor: View the list of assignments that the students submitted

However, today when I had 40 people follow the last three steps in this list I could no longer see the 
list of started assignments. That is, the final step in the above list no longer works. Instead, when I click the following link:

https://classroom.github.com/classrooms/31012255-computer-science-111-fall-2017-at-allegheny-college/assignments/computer-science-111-fall-2017-lab-1

I see a message that declares "Internal Server Error" and then error code 500. It turns out that I have never seen this error after testing GitHub Classroom with the same assignment for approximately the past 1-2 weeks. However, when I was previously testing these steps, there were never more than three students working on the assignment.

I have tried to access the GitHub Classroom and the specific assignment, which is at:

https://classroom.github.com/classrooms/31012255-computer-science-111-fall-2017-at-allegheny-college

and all of those screens always appear correctly. However, when I specifically try to see the assignment submissions for the first laboratory assignment, I always see the aforementioned error.

I have tried these links using both Chrome and Firefox and I always see exactly the same error message. I also see the same error message even when I use different computer. For what is is worth, I have also created a class roster with email addresses but not yet associated the email addresses with the GitHub account for each student; I planned to do that today but could not because I saw the 500 error message.

I should also note that I quickly searched the lists of issues for GitHub Classroom and did not immediately see that this type of issue was already submitted; it if was, please point me in the right direction and I will take steps to try to further solve this matter.

Okay, I hope that this helps you to better understand the context and the error that I am experiencing. 

If your schedule permits, can you get back to me with a step that I could take to debug the issue further or to resolve it fully? Since I am not running GitHub Classroom on Heroku, but instead using your installation and server  it seems that I may need this issue to be resolved before I can grade these assignments. Of course, please let me know if there is anything that I can do to support the resolution of this issue!

**Comment by minneapolis-edu** [comment]
I believe I have the same issue. 

I have a 500 error on one of my assignments; it's also the first assignment ([here](https://classroom.github.com/classrooms/14797930-mctc-itec-java/assignments/assignment-1-variables-and-conditional-statements)) in my classroom. 

Wondering if it may be related to creating a class roster? 
The assignment was initially working fine, I shared the link, students created their own sandbox projects, they've been working, assignment is working. 
Then, I created a class roster, linked student names with their GitHub accounts
And now I see the 500 error for that assignment.

My other assignments are all viewable normally. 

Many thanks!

**Comment by jonathan-g** [comment]
I have the same issue. I created and assignment and created a class roster.

Everything was fine at first. Now I have 25 students who have submitted their assignments and when I click on either the assignment (to open the assignment page) or when I open "Classroom Management" and click on "Roster Management" I get a 500 error.

**Comment by tarebyte** [comment]
@gkapfham @minneapolis-edu @jonathan-g my apologies for the delay, I've been spending the weekend squashing some issues and perf problems.

If you're curious the massive PR is here: https://github.com/education/classroom/pull/1127

I've gone through and verified for each of your accounts that everything is working properly, please let me know if you run into any other issues.

Thanks again for your patience.

**Comment by gkapfham** [comment]
Hello @tarebyte! Thanks for making this fix. I noticed #1127 and then immediately checked to see if the "Internal Server Error" was resolved. I am delighted to report that it seems to be fixed now. Thanks for taking time over your weekend to work on this issue. @minneapolis-edu and @jonathan-g, do you also notice that the error has been resolved?

Finally, is there anything that I might have done to cause the server to get into this incorrect internal state? That is, do I need to avoid using GitHub Classroom in some way so that this does not happen again? My understanding is that #1127 resolves the issue and I can continue as before. But, please let me know if that understanding is not correct.

Thanks again! Your help is greatly appreciated!

**Comment by tarebyte** [comment]
> Finally, is there anything that I might have done to cause the server to get into this incorrect internal state?

You didn't do anything TBH, there were some issues with the way we were building the queries and loading data.

**Comment by dwrue1** [comment]
I'm having the same issue. I just created an assignment, which is showing an invitation link, but when I click the assignment I get the 500 error.

**Comment by tarebyte** [comment]
@dwrue1 we had a bad deploy which I've reverted, would you mind checking it out to see if your issue has resolved?

**Comment by dwrue1** [comment]
It's working. Thanks!

**Comment by d12** [comment]
@shaleenx Sorry about that, this should be sorted!

**Comment by gkapfham** [comment]
Hi @PatWg, I wanted to write to confirm that I am also seeing this error in exactly the same situation.

**Comment by PatWg** [comment]
@gkapfham Wait, but I thought that your problem got fixed ? Did it come back again?

**Comment by PatWg** [comment]
Huh, actually, I just checked my roster now, and everything is in order.
Do we just need to wait a bit actually?
