### ISSUE TITLE
Failure accepting an assignment

### ISSUE THREAD

**Issue by kohler** [education/classroom#1118]
Hi, I run a class (organization `cs61`) using GitHub Classroom; thanks!

Last year things worked OK, with some small glitches. The problem is that this year, students cannot seem to accept assignments.

Classroom link: https://classroom.github.com/classrooms/2374024-harvard-cs61

Here's my workflow so far.
* I reset the state of the base repository for problem sets, `cs61/cs61-psets`. I prefer to use the same repository from year to year.
* I created a new assignment (`cs61-f17-psets`) using that repository as a base. Note that this assignment has the same base a previous assignment (`cs61-f16-psets`).
* When a student tries to accept that assignment via the invitation link, GitHub reports “There seems to be a problem on github.com, please try again.” and no assignment is created.

Any pointers on how to fix this? I'd like to release the assignment soon; is the simplest thing going to be simply creating a new assignment base repository?

Thanks,
Eddie Kohler

**Comment by tarebyte** [comment]
Hi @kohler sorry about the delay getting back to you.

Looking at your classroom it looks like you had owners on your classroom that are not longer owners of your org. When this happens we may try and use their token and everything will fail.

It's a known problem that we're working on. I've removed the users described above. Mind giving it another go?

Thanks!

**Comment by kohler** [comment]
Thank you @tarebyte! It looks like things are working much better. I'll close this issue since you know about the underlying problem.
