### ISSUE TITLE
Bit.ly discloses all assignment URLs

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#112]
By taking one of the Bit.ly links generated by the application, I was able to use the Bit.ly [link info API](http://dev.bitly.com/links.html#v3_info) to find out whose account created the Bit.ly link. From there I was able to use the [user link history API](http://dev.bitly.com/user_info.html#v3_user_link_history) to find a listing of Bit.ly links generated by this user. This gives me the invitation URLs for all assignments.

**Comment by johndbritton** [comment]
I'd suggest removing Bitly and just using the standard urls.

If you want to use a shortener, we've got `git.io`
