### ISSUE TITLE
Easily Late bulk-add multiple students to a class

### ISSUE THREAD

**Issue by angrave** [education/classroom#1120]
As a teacher for large enrollment (N>200) classes I need a mechanism to upload a new roster file or late add more than one student at a time.
roster#new-student-modal
This modal could accept more than one line (ignore blanks and ignore duplicates i.e. students that are already enrolled)

Also be able to upload a new file of the roster (and again only add new students and ignore existing students)

**Comment by mozzadrella** [comment]
@angrave thanks for this--good 💡. @tarebyte has added the help-wanted label if someone wants to take this on. If not, I'll mark it down for the next sprint.

**Comment by PandelisZ** [comment]
I've roughly figured our where all the roster features live and what It does I will be looking into this and attempting to implement a late add feature

**Comment by sethb157** [comment]
@Kadaaran Quick question, should we be validating the uniqueness of roster_entry identifiers? Currently the app is not, but it seems like it should--having two "John Smith"s with no distinction could be confusing.

**Comment by sethb157** [comment]
![screen shot 2018-04-26 at 3 02 25 pm](https://user-images.githubusercontent.com/4976750/39334287-e2315fe2-4962-11e8-8eea-abbf41a8d0eb.png)

**Comment by Kadaaran** [comment]
@sethb157 I wonder if it is actually possible to have 2 identical emails given by the same university ? 🤔 If a Classroom have indeed two `John Smith` how do we deal with it ? 🤔

**Comment by sethb157** [comment]
Hmm... I'm not sure 😬. So maybe the duplicate email thing was a bad example. I do still think this allowed behavior could lend itself to a lot of confusing situations (when a student joins a class and doesn't know which identifier to link to, or for teachers if a grading feature is implemented). In the case of two `John Smith`s, we might want to reject and ask the user to provide unique identifiers: `John A. Smith` and `John M. Smith`. Still, it may be the case that we want to allow duplicates, and I'm ok with that. Just wondering 🤔

**Comment by d12** [comment]
Hey @angrave , @sethb157 , @PandelisZ ,

This got merged into master yesterday :) (#1363)
