### ISSUE TITLE
Token auth errors after removing organization owner

### ISSUE THREAD

**Issue by vonclites** [education/classroom#1121]
I've started seeing issues after removing an owner from my organization https://github.com/wvu-cs111

I was intermittently getting this error when trying to create new assignments: 
"Cannot retrieve this organizations repo plan, please reauthenticate your token."
I am now getting it every time I try to create an assignment.

My students are also sometimes getting the same error when accepting the invitation to create the repository.

**Comment by tarebyte** [comment]
@vonclites I've removed the owner from your classroom, everything should be working as expected now.

**Comment by vonclites** [comment]
Was able to create a new assignment just fine!  Thanks so much for the rapid response!

**Comment by vonclites** [comment]
I'll see if the students can create the fake forks.  If everything goes smoothly I'll close this.

**Comment by vonclites** [comment]
Yup, that resolved it.  Thanks again!
