### ISSUE TITLE
Teams are NOT working

### ISSUE THREAD

**Issue by robdotson** [education/classroom#1126]
I cannot join/leave/create a team. I get 'there's something wrong with github.com' errors or 'that team name is already taken' but then it doesn't appear in the list. This product is terrible, and should never have made it out of beta.

**Comment by robdotson** [comment]
The only way I was able to create a team that stuck around is to make the name longer than 8 characters and add spaces. I really don't know why that would matter, but it does. I was then able to add my original team, and then leave the new team.

**Comment by tarebyte** [comment]
@robdotson [your comment above](https://github.com/education/classroom/issues/1126#issue-254916787) is a violation of the [Classroom Code of Conduct](https://github.com/education/classroom/blob/master/CODE_OF_CONDUCT.md) as it is insulting or derogatory. You may consider this an official warning.

If you'd like us to help with the problems you're facing, we going to need to know a little more about what happened so we can track down the problem:

1. Step-by-step what did you do?
2. What did you expect to happen?
3. What actually happened?

You can refer [to this blog post](http://www.lee-dohm.com/2015/01/04/writing-good-bug-reports/) for tips on what information or details to include. We definitely don't intend for our software to have bugs but as you should know, all software has them. If you can forgive us for being human, then we can see about solving whatever went wrong.

**Comment by robdotson** [comment]
I retract the 'is terrible' part. My initial reaction was to an unrelated (private) repository being deleted when leaving a team. Luckily I was able to restore it, but not without significant effort. I will be more mindful of the rules in the future, and will reopen a new issue along with my workarounds.
