### ISSUE TITLE
Assignments not showing up in classroom.

### ISSUE THREAD

**Issue by srvegdahl** [education/classroom#1130]
I went to look at the assignments in my classroom this morning, and they are not visible. Each is now represented by a red rectangle with a '!' inside a triangle. See attached screenshot. Please advise me what's going on. The assignment is due tonight.
![screen shot 2017-09-04 at 6 35 52 am](https://user-images.githubusercontent.com/6766091/30028865-a7aa6092-913b-11e7-813d-bc5fe4872e62.png)

**Comment by tarebyte** [comment]
@srvegdahl I'm looking into these issues as we speak, will update you when I have it resolved, thanks for your patience ✨

**Comment by tarebyte** [comment]
@srvegdahl I think your issue is resolved, mind taking another look?

**Comment by srvegdahl** [comment]
Yes, it's fixed. Thanks much!

**********************************************************************
Steven R. Vegdahl, Ph.D.
MSC 145                                  Phone: 503-943-7215
Associate Professor of Computer Science  Fax: 503-943-7316
University of Portland                   Email: vegdahl@up.edu<mailto:vegdahl@up.edu>
5000 N. Willamette Blvd                  Web: http://faculty.up.edu/vegdahl
Portland, OR 97203-5798                  Office: Shiley 218
To make an appointment: http://stevevegdahl.youcanbook.me
