### ISSUE TITLE
Error: "Validation failed: Title is too long (maximum is 60 characters)"

### ISSUE THREAD

**Issue by fperez** [education/classroom#1134]
Hi,

I just tried to create a new classroom for [this org](https://github.com/berkeley-stat159-f17) but I get the error above. I already tried renaming it to a slightly shorter name (it used to be called berkeley...-fall2017) but that didn't help. I'd rather not keep shortening further, is there really a limit on org names for Classroom?

Thanks!

**Comment by BelieveC** [comment]
@fperez, Yes, There is a limit of `60` characters for organization `title`.

**Comment by fperez** [comment]
Thanks @BelieveC! But something seems odd: my org title is only 20 characters long: `berkeley-stat159-f17`... What could be the problem?

**Comment by fperez** [comment]
Ah, it seems the problem is with the "Organization display name" perhaps?

If so, the error message is confusing, since there's no such limit when originally creating the orgs, only (it seems) when trying to make a classroom out of it. You might want to clarify that in the error that is displayed...

**Comment by BelieveC** [comment]
> Ah, it seems the problem is with the "Organization display name" perhaps?

Yes, You are right. I tried both the cases, It works for `Organization display name` lesser equal to 60. 
Sorry for the confusion. Thanks for the feedback. We will look fix the issue :smile:

**Comment by tarebyte** [comment]
<img width="779" alt="screen shot 2017-09-05 at 09 20 19" src="https://user-images.githubusercontent.com/564113/30063107-78f2d88e-921b-11e7-81a7-572c23cc6aab.png">

@fperez does this seem more clear as an error?

**Comment by mozzadrella** [comment]
@tarebyte 💖

**Comment by fperez** [comment]
Oops, sorry for the radio silence, got busy with teaching :)

Yes, much better, thanks!
