### ISSUE TITLE
CSRF in AssignmentInvitationsController#accept_invitation

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#114]
`AssignmentInvitationsController#accept_invitation` uses a GET requests. This should be a POST. Otherwise, an attacker could post an image like

```html
<img src="https://myclassroomapp.com/assignment_invitations/f772b522f9622307106fb91b7afe745d/accept_invitation">
```

on another site, forcing every Classroom user visiting the page to accept the invitation.

**Comment by tarebyte** [comment]
See #120
