### ISSUE TITLE
Returning Students Stuck Authorizing Classroom to use GitHub

### ISSUE THREAD

**Issue by gcschmit** [education/classroom#1144]
When students that are a member of a GitHub Classroom from last year (e.g., @nnhsapcs201415), first clicked on the invitation link to accept an assignment for this year's classroom (e.g., @NNHSSE201718), they were prompted to authorize GitHub Classroom to access GitHub. I suppose this may be expected since they are now in a different classroom or the authorization had expired over the summer. However, when they click the authorization button, they remain stuck on the same authorization page and are not forwarded to the page where they can accept the assignment.

Students who were not a member of a GitHub Classroom last year didn't encounter this issue.

We worked around this issue by having students sign into GitHub and then navigate to classroom.github.com directly at which point they were prompted to authorize Classroom to have access to GitHub. This authorization worked and they were redirected to a page that said they didn't have any classrooms. At this point they could like on the link I published and were directly taken to the page where they could accept the assignment.

I don't have screen shots or exact wording. If more details are needed, please let me know. I can probably find a student from last year who isn't in this year's class to recreate the issue and capture more details.

**Comment by mozzadrella** [comment]
Nice workaround @gcschmit. We'll work on fine-tuning this in our "manage and future reuse" phase of the roadmap this fall.

**Comment by AkshayAndroid** [comment]
not able to authorize
