### ISSUE TITLE
Deleting a set of teams

### ISSUE THREAD

**Issue by gpascualg** [education/classroom#1145]
Suppose I've accidentally created a wrong set of teams or I need to dispose of one, is there any way I can delete them?

**Comment by syifan** [comment]
You can delete the team directly from your organization. However, the problem is that if you deleted one team, the team members can no longer accept assignments, if you want to stick to the same group formation. This is my current problem.

**Comment by gpascualg** [comment]
@syifan First, thank you for your answer, but I wasn't refering to a team itself but rather to the "set of teams". When creating a group task, you can create a set that will contain all teams created by the students, I meant to delete that set as a whole, not an individual team.

**Comment by syifan** [comment]
@gpascualg Thanks for clarifying. It seems that the Github Classroom does not have any team management interface. I have the same requirement for removing, modifying sets of teams.

**Comment by mozzadrella** [comment]
👋  hi @syifan. You can delete the whole Classroom and re-create connect the organization. Team management is on our Roadmap for "Manage and assess" https://github.com/education/classroom/projects/7
