### ISSUE TITLE
Deleting a set of assignments

### ISSUE THREAD

**Issue by ITSPaul** [education/classroom#1147]
Is there any quick way of deleting a set of remote repos resulting from student acceptance of an assignment? This is important if you want to reuse a group and classroom with a new set of students registering to do a new module.

**Comment by mozzadrella** [comment]
Hi @ITSPaul 👋 .
We're working on a suite of features to make it easy for teachers to reuse Classroom in our roadmap: https://github.com/education/classroom/projects/7

For now I'd recommend you create a new org and a new Classroom, push your repo there and squash the commits so there isn't a history. 

Hope that helps ✨
