### ISSUE TITLE
Dev: Enable Roster feature

### ISSUE THREAD

**Issue by PandelisZ** [education/classroom#1160]
In #1105

@tarebyte mentions that
>  that's my bad, I thought we had turned on the feature flag for everyone.

I've forked the current master branch and have set up my environment. Everything works but I don't have the roster feature. Is it locked behind a flag like mentioned above? How do I activate it?

I want to have a go at implementing #1120

<img width="491" alt="screen shot 2017-09-21 at 21 35 04" src="https://user-images.githubusercontent.com/8436717/30717423-c739fe90-9f14-11e7-9de6-3df259dc46ae.png">

Thanks

**Comment by PandelisZ** [comment]
I've managed to find the feature_flags_dependency.rb and have hard coded the flags to be enabled. I would still like to know how to do it properly though

**Comment by tarebyte** [comment]
@PandelisZ you need to add your GitHub database ID to the environment variable `NON_STAFF_GITHUB_ADMIN_IDS`, go to localhost:3000/stafftools/flipper/features, and manually create the feature flags.

This is the easiest way to get your ID:

```
curl curl -Ss -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/users/PandelisZ
```

It would be cool for someone to make a rake task that could setup all of our existing flags in it ✨

**Comment by PandelisZ** [comment]
wiiiiiicked thanks 👍
