### ISSUE TITLE
Keep the pull requests from the starting repo

### ISSUE THREAD

**Issue by syifan** [education/classroom#1164]
I am recently started to use Github classroom in my course. I use the starting repo to distribute the starting code, where the testing code is also in the starting repo. At the time student  accept the homework, there will be two branches, one master and one "start". When we grade the homework, we create a pull request from the master branch to the start branch. Any point we need to deduct or any comment to the code, we write as comments in the pull request. However, my TA has to create the pull request for every team. 

So I tried to create a pull request in my starting repo. However, the pull request is not copied to the students repo. I wonder if there is any other way to keep the pull request, or there is some other better way for grading and commenting.

**Comment by mozzadrella** [comment]
Hi @syifan thanks for opening. Other teachers like @dondi use a PR-grading workflow https://education.github.community/t/how-to-grade-assignments-on-github/13663

Your graders may want to think about doing what @gcschmit does: 

>After reading @dondi 's original workflow, I’m going to try to use pull requests in order to provide comments. However, I too don’t want to introduce branching and pull requests in my one of my classes; so, I plan to personally branch the student’s repository and submit a pull request solely for the purpose of being able to leave contextual comments. Students could then view the pending pull request to see my feedback. I will try this out when the new school year starts…

We're in the process of embedding labels and labels in repos from Classroom. Stay tuned on those developments.
