### ISSUE TITLE
"This invitation is invalid"?

### ISSUE THREAD

**Issue by geoffreywiseman** [education/classroom#1176]
Trying to invite a student into a classroom -- they click on the link, the repo seems to get created, and then they get "This invitation is invalid". A google search isn't turning up much. Is this a bug, am I doing something wrong?

**Comment by tarebyte** [comment]
@geoffreywiseman I don't think so 😄

It's probably an issue on our end, let me take a look and get back to you.

**Comment by geoffreywiseman** [comment]
Second student, same problem.

**Comment by geoffreywiseman** [comment]
Ah, I think I discovered why -- they're going in as outside collaborators on private repos, which uses a seat, and we hit the seat limit. I need to either make the assignment use a public repo (no seat required) or add seats / remove other collaborators.

**Comment by tarebyte** [comment]
@geoffreywiseman we (GitHub Education) should be able to give you more seats.

Can you reach out to education@github.com ?
