### ISSUE TITLE
Download classroom roster

### ISSUE THREAD

**Issue by gmporter** [education/classroom#1184]
Hi all.  I have been using classroom.github.com for a couple of my classes this past year.  The new roster feature is really neat.  However, it would be good to have a way to download the <student_id> <--> <githubid> mapping.  Ideally, I'd like to be able to download the roster as a CSV file or something.  Right now we have to manually copy-paste the data into a local file, which is error-prone and hard to manage for classes with hundreds of students.  Thanks!

**Comment by athityakumar** [comment]
I'd like to contribute for this feature, if this is still up for grabs. I've a rough idea of how to proceed. 😄 

@gmporter - Thanks for filing this issue in. I'd like to know what exactly are the columns that you'd expect the mapping to contain - `student_username`, `student_name`, `assignment_repository_link` and any thing more?

**Comment by ceefour** [comment]
@athityakumar github username, github real name, email, student ID (the custom identifier)

**Comment by gmporter** [comment]
Also having the team name would be useful for classroom projects where multi-person teams are allowed.

**Comment by Kadaaran** [comment]
PR #1245 merged ! 🎉
