### ISSUE TITLE
Can't accept our project 2 assignment

### ISSUE THREAD

**Issue by audstanley2** [education/classroom#1185]
I get directed to accept:
"Accepting this assignment will give your team (Deleted team) access to the project2-ghost repository in the @CSUF-CPSC-131-Fall2017 organization on GitHub."

That's not even the team name i set up, and i get an error, even if i TRY to accept.

**Comment by mozzadrella** [comment]
@audstanley2 please take screenshots of what you are seeing. 
If possible, try creating a new team and let us know what happens.
