### ISSUE TITLE
60 character limit to titles 

### ISSUE THREAD

**Issue by matteoventuri7** [education/classroom#1187]
Link: https://classroom.github.com/classrooms/new

Organization: @FITSTIC

Error message: Validation failed: Title is too long (maximum is 60 characters)

Why?
![capture](https://user-images.githubusercontent.com/5465117/31502060-45f8a9ae-af6c-11e7-9b4c-6d75c78f95c8.PNG)

**Comment by athityakumar** [comment]
In `app/models/organization.rb` file (and slugs / titles in other models as well), this configuration has been set as -

```ruby
  validates :title, length: { maximum: 60 }
```
Also, organization title for @FITSTIC exceeds this limit -

```ruby
organization_title = "FONDAZIONE ISTITUTO TECNICO SUPERIORE TECNOLOGIE INDUSTRIE CREATIVE"
organization_title.length
#=> 67
```

Changing this standard could probably fix the issue. But, as this standard of 60 characters has been chosen by the maintainers, I'd definitely wait for one of the maintainers to respond before opening a PR to fix this. 😄

**Comment by matteoventuri7** [comment]
Thanks.

Cordiali saluti.

--------------------------------------

Dott. MATTEO VENTURI


Web: http://www.matteoventuri.eu

LinkedIn: https://it.linkedin.com/in/matteo-venturi-ab180866

Mobile: +39.392/4190512

Skype: matteo.venturi7

Il 12 ott 2017 21:06, "Athitya Kumar" <notifications@github.com> ha scritto:

**Comment by mozzadrella** [comment]
@matteoventuri7 do you need more than 60 characters? Can you help us understand the use case?

**Comment by matteoventuri7** [comment]
Now it's all ok. Error message was not clear.

*Dott. MATTEO VENTURI*

P.Iva 02588850392
Web: http://www.matteoventuri.eu
Email: info@matteoventuri.eu
Mobile: +39.392/4190512
Skype: matteo.venturi7

2017-10-19 15:40 GMT+02:00 Vanessa <notifications@github.com>:
