### ISSUE TITLE
Use the commits endpoint for number_of_commits

### ISSUE THREAD

**Issue by d12** [education/classroom#1205]
A little while ago, we switched to the contributors API: https://github.com/education/classroom/pull/1064

Unfortunately, it omits a bunch of commits and is causing counts to be off. It doesn't count:

- Empty commits
- Merge commits
- Commits by users who aren't contributors.

Instead, @johndbritton suggested we can use the page numbers on the commits endpoint to calculate this. https://stackoverflow.com/a/43374518/187362

**Comment by fjorgemota** [comment]
Hi, i'm seeing this bug on a class.

Basically, the base repository has 704 commits. But Classroom only detects 660, and I think that your description is a good reason for the wrong commit count.

Shouldn't this issue be open?

**Comment by d12** [comment]
Because of an [Octokit bug](https://github.com/octokit/octokit.rb/issues/912), the contributors endpoint is causing huge perf issues. Lets try to prioritize this work :+1:

**Comment by d12** [comment]
The commits count is meant to roughly show activity on a student repository. I don't think there's much value in counting merge commits and empty commits here. Also, template repo's squash all commits into one commit authored by the teacher, so "Commits by users who aren't contributors." won't be an issue anymore.
