### ISSUE TITLE
Leaving an assignment after joining. Cannot rejoin the assignment through same link?

### ISSUE THREAD

**Issue by scorpioblk1** [education/classroom#1209]
I accepted an assignment sent out by my course instructor, I then pressed "leave" as the repo didn't completely initialize due to internet cutting out during process. Now that I have left the repo, when I try and accept assignment again, it already shows as accepted, but the link to the repo now throws up a 404 error...
Any way of re-joining and re-accepting assignment?

**Comment by tarebyte** [comment]
@scorpioblk1 there isn't ATM because the repository wasn't deleted. If you reach out to education@github.com with the details we can get you sorted out.

Thanks!
