### ISSUE TITLE
undefined method `id' for "":String

### ISSUE THREAD

**Issue by trombonekenny** [education/classroom#1213]
Hi all,

I'm trying to get @mdwheele's `feature/support-ghe` branch working against my Github Enterprise. I'm pretty n00b with Ruby on Rails, but with his PR #1163 patch I was able to get OAuth and the basic functionality working, at least in localhost:5000 mode. :smiley:

I am getting a NoMethodError in AssignmentInvitationsController#accept crash right after I accept an invite. It says: 

>undefined method `id' for "":String

and points to this line of code: https://github.com/mdwheele/classroom/blob/17bbc7f85fe33ef9be28ba918e1c55c1fbc8dc44/app/models/assignment_repo/creator.rb#L102

In GHE I can see that the repo was created, but when I look back in classroom I see that 

> "hw1" does not have any repositories.

Apologies for filing the issue in the main repo; I didn't see an issues tab when I looked at his fork. I honestly don't know enough about how this works to tell if it's something in my config (of classroom or GHE), or his branch, or...  Help?

Thanks in advance! --Dave

**Comment by d12** [comment]
Hi trombonekenny,

I can try to take a peek at this sometime this week. We don't officially support forks though, you may have better luck trying to get assistance from @mdwheele.

**Comment by mdwheele** [comment]
@trombonekenny @d12 

I've enabled issues on my fork. This branch is part of an open PR to support GitHub Enterprise and I cannot reproduce this issue currently. If there is an actual bug, I want to add a test that reproduces it because currently, the PR is passing tests.

**Comment by d12** [comment]
Thanks @mdwheele!

Let us know when your PR is ready for review, me and Tarebyte would be happy to check it out.

**Comment by mdwheele** [comment]
Go for it. I know y'all are super busy, but it's ready for review.

**Comment by trombonekenny** [comment]
I followed up on the issue in his fork repo. I think it makes more sense to track it there. I just wanted to update here for completeness. Thanks all!
