### ISSUE TITLE
I cannot seem to fully remove stranger member from an assignment team

### ISSUE THREAD

**Issue by bvelez** [education/classroom#1215]
I was able to remove team member AmbujaAK from team:

https://github.com/orgs/UPRM-CIIC4010-F17/teams/tem-240db.

![image](https://user-images.githubusercontent.com/5605641/33033548-199059ea-cdfb-11e7-85f9-105a92166161.png)

But it still appears in the list of teams in the assignment screen:

![image](https://user-images.githubusercontent.com/5605641/33033506-edefc2c6-cdfa-11e7-826b-a9c51f92c195.png)

The assignment does not allow the other team member to join the team

This person is not part of my classroom. I have no idea how he managed to join the team.

**Comment by drbeco** [comment]
This request seems to be related to my new issue (feature-request), so I'm linking here ( #1216 ) for organization. Please take a look if that would address this matter. Thanks.
