### ISSUE TITLE
Number of group members wrong

### ISSUE THREAD

**Issue by drbeco** [education/classroom#1216]
(feature-request, but also a _bug_ imho)

It should be important for classroom to keep updated with the real group teams after they are created.

For now I have a group assignment where one of the groups had a problem and a member simply left the "team", the other I removed.

Now the assignment states there are 8 members, while the team sees only 6.

This prevented another member to join, since the limit was seven (and I solved by raised it to 8).

Whenever I had this problems before, I asked an admin here ( @tarebyte ) to help and he was always so kind to do so. This time I didn't want to bother him yet again with such problems to be "manually" handed. So I ended up with this solution that breaks the coherence of the system.

It would be very nice if we could manage classroom (or it be aware of the changes) by simply and only going to our github account and manage teams there. I reckon classroom has reading rights to see the teams, how it goes, what it changed, and update itself on that base, right? 

It does not have to be "instantaneous", mind you. It may be a daily cron-job, or half-a-day, or two days, no problem. That depends on how you see the demand for this task would increase the load on the server. But still, a nice feature to have, if not a bug to solve.

Thanks!

---

(edited: typo)

**Comment by Kadaaran** [comment]
Hi @drbeco  , thank you for reporting this issue.

I've been trying to find a fix for this issue this week and I think I have found how to do so.

I'll try to ship a first try this week 🚀

**Comment by drbeco** [comment]
Merci

**Comment by Kadaaran** [comment]
Hi @drbeco  👋 

We finally merged the PR #1254 that should fix this issue 🚀 
Next one will be #1274 

Thank you for again your patience !

**Comment by Kadaaran** [comment]
Merged #1274 & #1254

**Comment by drbeco** [comment]
Great news, thank you and all the team for the effort.
