### ISSUE TITLE
Organization missing from add organization dropdown

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#122]
I'm trying to add my organization, https://github.com/classroom. For some reason it's not showing in the dropdown. :question: 

<img width="509" alt="screen shot 2015-08-24 at 3 23 22 pm" src="https://cloud.githubusercontent.com/assets/123345/9442491/1d1140c8-4a74-11e5-90b2-bdf424854fb8.png">

**Comment by tarebyte** [comment]
Is it just that org? Or is it multiple?

**Comment by johndbritton** [comment]
It only lists one org in the dropdown, but I'm an admin on a bunch of orgs.

**Comment by tarebyte** [comment]
Weird, that should not be the case. All of my orgs show up.

Will investigate

**Comment by johndbritton** [comment]
Maybe I'm doing it wrong, it worked before.

**Comment by johndbritton** [comment]
I've since deleted an org a bunch of times and don't have this issue any more. Was it just that the DB records weren't cleaned up?

**Comment by tarebyte** [comment]
yup!
