### ISSUE TITLE
Math rendering support?

### ISSUE THREAD

**Issue by jlperla** [education/classroom#1223]
It is pretty difficult to use github for a classroom when you can't post up math in latex within the markdown in classrooms.  I don't see any open issues for this, is it on the radar?  If not, please!

**Comment by tarebyte** [comment]
@jlperla this sounds like more like a feature request for GitHub than it does for GitHub classroom.

Would you mind reaching out to support@github.com?

Thanks!

**Comment by jlperla** [comment]
I will, thank you.  And to whatever extent possible when discussing with higher-ups, please press the need for math.  The irritation it is causing, relative to the amount of work it requires for github to do, is quite high.
