### ISSUE TITLE
Assignment question

### ISSUE THREAD

**Issue by daveogle1818** [education/classroom#1225]
I have 40 students in my classroom. I can only see 20 of their assignments, although I know the other 20 have submitted the assignment. One student sent me the link to his assignment but I get a 404 when I access it. Is there a help section available to help figure out what is going wrong/

dave

**Comment by tarebyte** [comment]
@daveogle1818 so I think there is something wrong with the assignment view, our database says that all 40 assignments are there and I can verify that those repos are on GitHub.

I'm not sure why the GitHub link would 404 for you though.

Would you mind emailing education@github.com so we can talk more specifically?
