### ISSUE TITLE
Could not join the team again...??

### ISSUE THREAD

**Issue by mfk2909** [education/classroom#1229]
I accidentally created a team with wrong name but was able to see all the assignment stuff....but when my instructor deleted that faulty name team n readded me to the repository....I wasn't able to join the assignment .....as it always shows....could not join the team

**Comment by tarebyte** [comment]
@mfk2909 we would have to delete the resource on the classroom side. Right now we don't listen for a team deletion even and make the appropriate action.

**Comment by Kadaaran** [comment]
Hi @mfk2909 👋 

We recently merged the PR #1254 that should fix this issue 🚀 
Thank you for your patience.

**Comment by Kadaaran** [comment]
Merged #1274 & #1254
