### ISSUE TITLE
Move sidekiq link to peek bar

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#123]
Having a link to Sidkiq is cool, but I'd prefer if we could keep all staff only links out of the main application. Can you add it to the peek bar instead?

<img width="54" alt="screen shot 2015-08-24 at 3 28 42 pm" src="https://cloud.githubusercontent.com/assets/123345/9442648/dae14080-4a74-11e5-8322-80c877383ada.png">

Here's what I did in another app:

<img width="154" alt="screen shot 2015-08-24 at 3 30 20 pm" src="https://cloud.githubusercontent.com/assets/123345/9442686/0eaa5be0-4a75-11e5-85bc-9ecf41c9f49a.png">

**Comment by tarebyte** [comment]
:+1: great suggestion
