### ISSUE TITLE
Disable Import Email

### ISSUE THREAD

**Issue by gchallen** [education/classroom#1230]
I've disabled automatic repository email watching, but I'm still getting "Import to ... succeeded" emails each time a student accepts an assignment invitation.

Yes, I know how to filter these into a folder. But is there a way to disable this notification entirely? I'm about to deploy this assignment to 600 students... 🙂 .

**Comment by tarebyte** [comment]
@gchallen unfortunately the Import API we use doesn't give us that ability 😢 

I wish we could, that would save folks a _lot_ of spam.

**Comment by gchallen** [comment]
OK thanks for letting me know.
