### ISSUE TITLE
After re-granting access to github classroom, cannot create a new class. WebHook error.

### ISSUE THREAD

**Issue by DavidGoedicke** [education/classroom#1231]
It was admittedly a stupid thing to do but after revoking access to GitHub classroom I granted it access again. Now, whenever I try to use my organization to create a class I get the error:

> Could not create WebHook, please try again. 

Any ideas what might be going on?

**Comment by tarebyte** [comment]
@DavidGoedicke you probably need to go remove the webhook from your organization and then and create the classroom again.
