### ISSUE TITLE
github account only associated with ghost user

### ISSUE THREAD

**Issue by jdkent** [education/classroom#1232]
We had a user delete their account before they signed up for the class, and when they re-created their account, every time they try to accept the assignment, their account is associated with the [ghost](https://github.com/ghost) account, even though I can visit their existing account. 

I even had them make another account with a different username (but same email) and we got the same result. 

The only other thing I can think of trying is to make sure when they accept the invite is that they also logged into the correct account on [github classroom](https://classroom.github.com/)

Here is a screenshot:
![ghost](https://i.imgur.com/ZgJEYWv.png)

Thanks for making this awesome resource!

**Comment by tarebyte** [comment]
Thanks for letting us know @jdkent!

Yeah there was probably some session confusion there. So just logging out of classroom and GitHub, signing back into GitHub then trying to accept the assignment should fix it.

**Comment by jdkent** [comment]
Yep, that was it, just had them log in/out of classroom and it worked. Sorry for causing an unnecessary fuss.
