### ISSUE TITLE
Can't make new assignment

### ISSUE THREAD

**Issue by rsardinas** [education/classroom#1234]
I am having issues making new assignments for my students in github classroom. I just get errors when I create new assignments.

**Comment by tarebyte** [comment]
@rsardinas would you mind what settings and type of assignment you are trying to create?

I'm trying to recreate your issue to see what the problem is.

**Comment by rsardinas** [comment]
Absolutely.
Individual Assignment
I've tried Public and Private repos
Give students admin permission box checked and unchecked
Once I hit create, I land on the error page shown in the word document I've attached.

I was able to create an initial assignment. Since then, I am unable to.
[github_assgn_error.docx](https://github.com/education/classroom/files/1645007/github_assgn_error.docx)

Thanks in advance,
Rodrigo

**Comment by rsardinas** [comment]
Also, once I try to create the assignments, it does actually create an assignments link on my assignments page, but clicking the links will simply take me to the same page shown in the word doc.

**Comment by rsardinas** [comment]
It seems the problem has gone away. Maybe it was a server issue? I am now able to see the assignments I made before and I am able to create new ones. Thank you for looking into it.

**Comment by tarebyte** [comment]
@rsardinas not a problem, we had a pull request out that we were testing.

Thanks for the bug report!
