### ISSUE TITLE
Assignments links do not work (error 500)

### ISSUE THREAD

**Issue by johnboat** [education/classroom#1236]
I've set up two assignments in Classroom, but when I go to the main page listing Assignments, the link to each assignment page is broken (I'm referring to clicking the name of the assignment), Internal Server error 500.

**Comment by tarebyte** [comment]
@johnboat we had a pull request out for testing, but I've reverted and deployed master.

Mind giving it another try?

**Comment by johnboat** [comment]
It works. Thank you. Sorry, I thought I looked through everything before posting, but obviously missed that. Thanks again.
