### ISSUE TITLE
Git Authentication page continuously reloading

### ISSUE THREAD

**Issue by anyaevostinar** [education/classroom#1238]
Hello, I have had several students get stuck when trying to join my git classroom where they are at the Git account authentication page and they click the authenticate button and it just reloads the page. I was able to fix most of the students' problems by having them logout, quit the browser and try again, but one student still can't get it to work. Help would be appreciated greatly.

**Comment by Kadaaran** [comment]
Hello @anyaevostinar, thank you for reporting this bug.
The quickest solution I can think of right now would be for your students to go into `[](https://github.com/settings/applications)` and to revoke Classrooms access. 
Then they can try to join your classroom again.

Can you keep me updated if it works on your end ?

**Comment by anyaevostinar** [comment]
Hi @Kadaaran That seems to have worked for the student. Thank you!

**Comment by Kadaaran** [comment]
Amazing ! Thank you for letting us know !
