### ISSUE TITLE
Sort ids in roster alphabetical for first log-in

### ISSUE THREAD

**Issue by amueller** [education/classroom#1239]
When a student first logs in, they are shown a roster to select their ID from.
That roster is not sorted alphabetically, which makes it really painful for users to find their ID.
It should probably be easy to sort it, and that would make students life much easier.

I'm using student IDs, which is usually two characters followed by 4 numbers. Imagine scrolling through 150 of those trying to find yours. And that's not a big class.

**Comment by ashleytqy** [comment]
I'd like to contribute to this issue, if possible!

**Comment by Kadaaran** [comment]
@ashleytqy Sure, go ahead ! ✨ In the meantime feel free to ask if you have any questions.
