### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#124]
<img width="147" alt="screen shot 2015-08-24 at 3 43 05 pm" src="https://cloud.githubusercontent.com/assets/123345/9443062/f5a220ea-4a76-11e5-9d75-ac69b3dccae0.png">

@jasonlong @jglovier How do you feel about this favicon? Would you prefer that we swap it out with something else? If so, PRs welcome :grin:.

**Comment by jglovier** [comment]
LGTM! :+1:

**Comment by jasonlong** [comment]
Yeah, I made the green one for lack of better ideas. I'm not sure what else makes sense at this point w/o some more branding work.

**Comment by johndbritton** [comment]
:cool: just wanted to check
