### ISSUE TITLE
Unable to create classroom, after deleting the old clasroom

### ISSUE THREAD

**Issue by pmantini** [education/classroom#1240]
I had a classroom created last semester, that was associated with an organization. I realized that one could only create single classroom under one organization. So I deleted the old classroom hoping to create a new one. 

How ever, it does not give me an option to create a new classroom. Please see screen shots

![gh_2](https://user-images.githubusercontent.com/9559602/35401546-705ab584-01bf-11e8-8fe9-107575e63f3f.png)
![gh_1](https://user-images.githubusercontent.com/9559602/35401554-7901f224-01bf-11e8-86af-0aa57d1f3677.png)

The organization button is disabled with a popup
 "@<username> has already added this organization to github classroom"

**Comment by Kadaaran** [comment]
Hi @pmantini 👋 
Sorry for the delay !

A quick fix would be to go on the `settings` page of your Organization and to remove the Classroom's webhook used for your Organization, then to try again.
It should work and create a new webhook.
