### ISSUE TITLE
How to prevent graders names showing up

### ISSUE THREAD

**Issue by anyaevostinar** [education/classroom#1244]
Hello, I've run into a problem that when my graders go to grade the classroom assignments, their names are revealed, for example:

![received_10214175171473708](https://user-images.githubusercontent.com/868594/35459597-749bb53e-02a6-11e8-8281-01cb6ce3f12f.jpeg)

Is there a way to avoid this other than anonymous grader accounts?

**Comment by tarebyte** [comment]
@anyaevostinar unfortunately yes since that's on the GitHub side, we really don't have control over that.
