### ISSUE TITLE
Teachers onboarding & organization teams and members issues

### ISSUE THREAD

**Issue by Kadaaran** [education/classroom#1250]
Hi 👋

I've seen a few teachers in the education community page which thinks GitHub and Classroom are connected and are the same without knowing in what they are different. They use both at the same time and then encounter issues based on that.

The result is that teachers add their students to their organization as members instead of outside collaborators (this may be a huge security issue for them) and create teams on GitHub when the students are the ones who needs to create their own teams.

Also while the roster page is a more than useful feature some do not understand that the roster page is not a reflection of the organization's members/outside collaborators.

I think we have those issues mainly because Classrooms does not keep track of users students that leave team or leave the organization and then the teachers have two different informations on two platforms, which can be a bit odd.

There is an open PR #1174 that aims to solve the issue by keeping track of the member_removed and/or a team_member being removed.
I think it would be great to have some onboarding or some little tour to explain to teachers how Classroom works.

@tarebyte suggested we fix the issues with the wrong numbers of team members and that we create and a little onboarding for teachers 👍
I thought about [Shepherd](https://github.com/HubSpot/shepherd) to implement it nicely.

I just arrived a few weeks ago and I have a lack of informations about teachers experience with Classroom, if you have any suggestions or ideas I'd happy to read them ✨

**Comment by d12** [comment]
Closing in favor of https://github.com/education/classroom/issues/2387
