### ISSUE TITLE
Students cannot clone repositories

### ISSUE THREAD

**Issue by nved1990** [education/classroom#1255]
Hi,

We have a assignment in a repository which cannot be cloned by students. Can you help with this.

Thank you.

Best,
Niharika

**Comment by tarebyte** [comment]
@nved1990 by clone are you referring to the assignment creation process? Or do you mean an actual `git clone` ?

**Comment by nved1990** [comment]
I mean the assignment creation process. This is the link: https://classroom.github.com/a/FhwqBtZ0

**Comment by nved1990** [comment]
Hi, can I get some help with this? The students need access to the assignment asap.

**Comment by tarebyte** [comment]
@nved1990 I went through the assignment flow (as @tatooine-moisture-farmer) and the process was successful.

Are your students receiving errors? Or are the repositories coming up with no content?

**Comment by nved1990** [comment]
Their repos do not have any of the 6 commits made by the teaching team. They are not able to see the assignment. Something seems to be broken. Students have to delete their repository and try again.

**Comment by nved1990** [comment]
Could you rerun this process and see if the repository is being created correctly?

**Comment by hswift1** [comment]
I am having this same type of issue - my students' links are not even getting through the repo creation. I have tried with two different types of assignments - one with starter code and one without - they both continue to error out.

Any assistance is greatly appreciated!
Sincerely,
Heather

**Comment by BenEmdon** [comment]
@hswift1 Please open a new issue and fill out the issue template. Your issue sounds different from this one.
