### ISSUE TITLE
Unable to verify repo plan...

### ISSUE THREAD

**Issue by rjsvcs** [education/classroom#1256]
I managed to convince the faculty for Computer Science 2 at my university to start using GitHub Classroom for our weekly lab assignments. There are approximately 20 lab sessions per week, each of which has about 20 students in it (there are over 400 students in the class).

I have two sessions at 8am (Tuesday and Thursday). During those sessions my students experienced several errors, but the most annoying was an error when trying to accept the assignment. A pink banner displayed over the accept button indicating that the repo plan for the organization couldn't be verified. This caused several problems:

1. In many cases, if a student hit the "accept" button more than once, multiple repositories were created for that student (assignment_name-student_username-1, -2, -3, etc.). The error kept popping up on the screen, but a repository WAS created several times.
2. Even worse, in the classroom view, the button to visit the repository is deactivated and is labeled "REPOSITORY NOT FOUND." When I check the organization, those students actually have 2 or more repositories that have been created, but they are not connected to the classroom.

I also have two afternoon sections (12:20pm on Tuesday and Thursday) and did not see that problem at all. It only seemed to show up at 8 am for some reason, and none of the other faculty reported it.

**Comment by Kadaaran** [comment]
Hi @rjsvcs ,

On the 1st of February we experienced some issues with the service we rely on to create repositories and then a lot of repos ended up empty, were not even created or were under some other issues.

Also we are working on a better solution to make the UX more convenient and let know the user if something is wrong during the process.

Thank you for reporting this issue !
Let us know if we can help you with anything else.

**Comment by Kadaaran** [comment]
Hi @rjsvcs !

> In many cases, if a student hit the "accept" button more than once, multiple repositories were created for that student (assignment_name-student_username-1, -2, -3, etc.). The error kept popping up on the screen, but a repository WAS created several times.

Can you tell me for which assignment it happened and on which Classroom ?

**Comment by rjsvcs** [comment]
Sure: https://classroom.github.com/classrooms/29046939-csci-142-03/assignments/lab-03

**Comment by Kadaaran** [comment]
Hi @rjsvcs , 

Sorry for the delay.

So here's what happened, your organization's owner changed on GitHub, but Classroom did not update this informations. 
We still used the old owner's token to check the repo plan which explains the banner saying the organization could not be verified and might explains also some issues with the repo as well (and also with the fact that the service we rely on to create the repo had issues on the same day).

We removed the old owner from Classroom, you should be all right now.

In the meantime I'm working on updating the organization informations in Classroom so it won't happen again.

Sorry about it and thank you again for submitting this issue.
Tell me if you need help with anything.

**Comment by Kadaaran** [comment]
Merged #1274
