### ISSUE TITLE
Automatically merge teams

### ISSUE THREAD

**Issue by alsuhr** [education/classroom#1264]
Hello,

Is there any way to merge teams (either as a student or an instructor)? I have an assignment where students work in pairs, and some students created individual teams before finding a partner. It seems like students don't have the permissions to modify their teams (e.g., change team name or delete the team), so I have just been manually deleting one team and telling them to join the other. 

However, I'm wondering if it's just possible for them to do this themselves (while making sure they are following the guidelines, e.g. can't merge teams if it means the team has too many people), or if there is a setting where I can give them more privileges to modify their teams. 

Thanks,
Alane

**Comment by Kadaaran** [comment]
Hi @alsuhr 👋 
Sorry for the delay.

We recently merged the PR #1254 
If a student leaves a team Classroom now updates the team and removes the student. Then the user can re-accept the assignment and join another team.

I hope it solves your issue 🙏 
Thank you for your patience !

**Comment by d12** [comment]
Closing in favor of https://github.com/education/classroom/issues/292
