### ISSUE TITLE
I was forbidden from performing accept assignment

### ISSUE THREAD

**Issue by jinchenxiangdan** [education/classroom#1266]
most of us are forbidden when we try to accept assignments. some of us can accept them after refresh pages, but some of us cannot accept assignments for several days.

**Comment by Kadaaran** [comment]
Hi @jinchenxiangdan , thanks for reporting this issue.

Can you tell me more about it ? What error message do you get ? Can you provide a screenshot ?

**Comment by jinchenxiangdan** [comment]
Hi
this is the screenshot.

Thank you for your time

2018-02-12 3:53 GMT-07:00 Kassandre Pedro <notifications@github.com>:

**Comment by Kadaaran** [comment]
Hi @jinchenxiangdan 👋 I don't see your screenshot, did you send it ? 🤔

**Comment by jinchenxiangdan** [comment]
yes, but I have attached the file.  this is the screenshot.
sorry about that.




2018-03-01 10:36 GMT-07:00 Kassandre Pedro <notifications@github.com>:

**Comment by Kadaaran** [comment]
I'm sorry @jinchenxiangdan but I can't found here here or in my emails notifications. Do you mind sending me over to `kadaaran@github.com` so I can have a look ?  Thank you again.

**Comment by Kadaaran** [comment]
Hi @jinchenxiangdan , sorry for the delay.

Unfortunately I can't reproduce this bug on my side... 
But I will fix it as soon as I can reproduce it.

I'll keep you updated. Thank you for your patience 🙏

**Comment by d12** [comment]
:wave: This sounds like an importer problem. Classroom now has a template repo option you can use when creating an assignment, it'll make accepting assignments much faster and more reliable. https://classroom.github.com/help/using-template-repos-for-assignments
