### ISSUE TITLE
Suggestion: Enable sorting of assignments

### ISSUE THREAD

**Issue by dwrue1** [education/classroom#1269]
I thought I could get around the problem of having multiple classes sharing one github classroom by adding a prefix to each assignment that would designate the classroom it belonged to. The problem is that the assignments don't seem to be sorted in alphabetical order - or any order for that matter. Simply put I am looking for a way to organize assignments by prefix (i.e. alphabetical order). The page I am referring to is the classroom view.

**Comment by ashleytqy** [comment]
I'd like to contribute to this feature if possible!

**Comment by Kadaaran** [comment]
Hi @dwrue1 thanks for reporting this issue.
I believe they are order by creation date (it seems) 🤔 

@ashleytqy Sure !

**Comment by ashwinvidiyala** [comment]
I want to contribute to this feature if it hasn't been built out already.

**Comment by ashleytqy** [comment]
@ashwinvidiyala I'm still working on it! Sorry for the delay, was busy with school.

**Comment by Kadaaran** [comment]
Merged 🚀
