### ISSUE TITLE
Suggestion: copy branch settings from source repo

### ISSUE THREAD

**Issue by Kadaaran** [education/classroom#1270]
Suggestion from Slack Education: 

> I really really wish GitHub Classroom would copy branch settings from a source repo. Having to go in and protect every repo’s master branch as it is created is a lot of work with 80 students.

Also that could also help protect the assignment so student can't copy from others (maybe? not sure about that yet).

**Comment by johndbritton** [comment]
Rather than copying the settings from the source repo, when we do implement this it should be as a config file on the `github-classroom` branch of the source repo like we do for issues and labels currently.

**Comment by BU-AWolfe** [comment]
What's the problem with students working on master?

**Comment by mir-ch** [comment]
？

在 2018-03-28 00:18:16，"Andrew D Wolfe Jr, MSCS" <notifications@github.com> 写道：


What's the problem with students working on master?

**Comment by d12** [comment]
Closing in favor of https://github.com/education/classroom/issues/846
