### ISSUE TITLE
Inconsistency in the teams structure between GitHubClassroom and the organization

### ISSUE THREAD

**Issue by emanMarcu** [education/classroom#1273]
Hello and thank you for maintaining GitHub Classroom.

I have distributed an assignment and ran into a strange inconsistency. There is a team for which in the GitHub Classroom page it shows there are **two** members but when I click on the team I see there is only **one** member.

Here is a screenshot. I am referring to the team called DynamicTeam, which here shows two members:

![screenshot 2018-02-15 22 53 57](https://user-images.githubusercontent.com/29737399/36283185-f861a538-12a3-11e8-8e21-d928df394b76.png)

whereas when I click on the team, I am sent to the following page, which shows there is only one team member:
![screenshot 2018-02-15 22 54 05](https://user-images.githubusercontent.com/29737399/36283218-17695d7c-12a4-11e8-8062-a6c8b92a080d.png)

Is this a bug? Or did distribute the assignment in an incorrect manner? Thank you kindly in advance.

**Comment by Kadaaran** [comment]
Hi @emanMarcu ,

Sorry for the delay and thank you for reporting this issue.

It is indeed a bug 🙇 
Classroom does not keep informations about teams and organizations members updated. 
If a user leaves the team Classroom will still display outdated informations.

However two PR to fix these bugs are on their way ! ✨ (#1274 & #1254 )
It'll be soon released I believe.

**Comment by Kadaaran** [comment]
Hi @emanMarcu 👋 

We recently merged the PR #1254 that should fix this issue 🚀 
Thank you for your patience.

**Comment by Kadaaran** [comment]
Merged #1254 & #1274
