### ISSUE TITLE
Students cannot accept assignment

### ISSUE THREAD

**Issue by laleese** [education/classroom#1275]
I created a new assignment today. You can find it at: https://classroom.github.com/a/UvQiVcNw
My test student gets the message "We were not able to add you to the Assignment as a collaborator, please try again." This is our third assignment, but the first one to have this problem. 

Can you help?

**Comment by Kadaaran** [comment]
Duplicate of #1272

**Comment by filalano** [comment]
But the problem still exists. why is this issue closed?

**Comment by Kadaaran** [comment]
Hi @filalano ,

Yes the problem still exists. This issue is a duplicate fo the #1272 that's why I closed it (to avoid having multiple issues open for the same issue)
