### ISSUE TITLE
Unable to give students admin privileges for their private assignment repositories.

### ISSUE THREAD

**Issue by mfagan451** [education/classroom#1285]
When creating an assignment, we checked the "Give students admin permissions on their repository".
The assignment was marked "Private".

The admin permissions, however, did NOT go through for any of the students.

As an additional point of concern, we did the exact same thing on our previous assignment and everything worked as intended.

**Comment by Kadaaran** [comment]
Hi @mfagan451 👋 
Sorry for the delay !

I've been trying to reproduce your issue on my side but I am unable to do so...
I will fix it as soon as I can reproduce it.

Can you give me the assignment name so I can check if the admin rights are set ?

Thank you.
