### ISSUE TITLE
Unacceptable number of empty repositories

### ISSUE THREAD

**Issue by mfagan451** [education/classroom#1287]
For each of our 11 assignments this semester, we have gotten 5-10 empty repositories generated
(out of 140 students). Furthermore, it is not the same students each time. In addition, the empty
repos occur at random times.

**Comment by Kadaaran** [comment]
Hi @mfagan451 ,

First thank you fo reporting this issue. Unfortunately your issue is a duplicate of #1148 
I invite you to go there so I can keep everyone updated about it.

Thank you !
