### ISSUE TITLE
Roster Download

### ISSUE THREAD

**Issue by robertcduvall** [education/classroom#1291]
Only downloads the first page (20) of students --- it needs to do all the pages.

**Comment by johndbritton** [comment]
@Kadaaran Can you verify this bug, write a failing test, and fix?

**Comment by Kadaaran** [comment]
Hi @robertcduvall , the PR is now merged this issue should be fixed.
Please keep me updated if it's (or not) the case.

Thank you for your patience and for reporting this issue.

**Comment by markpolyak** [comment]
I had the same issue when I tried to download the rooster a couple of weeks ago. I can confirm that now the "Download" button on "Rooster management" page downloads a CSV file with all students, not just 20 shown on the web page.
