### ISSUE TITLE
Merging teams, adding new member or other operations on previously created team

### ISSUE THREAD

**Issue by majid169** [education/classroom#1295]
Hi,
We are using the organizational repo for our class, which is a very large class with 400 students and 200 teams. We let students to create their own team and now I need to merge 2 teams, switch partner for 2 teams and create a new team. However, it seems that I am not allowed to do any of these with existing teams.
For example, I added a member to a new team and deleted the old team, however, the student gets the link to his old team yet and the system does not recognize th new membership. Any idea?
Thanks

**Comment by Kadaaran** [comment]
Hi @majid169 👋 
Sorry for the delay.

About your issue, only students can create teams when accepting the assignment. 
> For example, I added a member to a new team and deleted the old team, however, the student gets the link to his old team yet and the system does not recognize th new membership

We recently merges #1254, now if your students leave teams on GitHub, Classroom will update all the informations.

Hope it helps, thank you again for your patience !

**Comment by d12** [comment]
Closing in favor of https://github.com/education/classroom/issues/292
