### ISSUE TITLE
script/setup fails because of java8 in Brewfile

### ISSUE THREAD

**Issue by talsafran** [education/classroom#1297]
When I run `script/setup` it yells at me that the `java8` cask is not available:

```bash
15:29 $ script/setup
==> Ensuring Homebrew macOS dependencies...
Updated 1 tap (caskroom/cask).
No changes to formulae.
==> Installing Homebrew dependencies...
Using caskroom/cask
Using github/bootstrap

Error: Cask 'java8' is unavailable: No Cask with this name exists.
Installing java8 has failed!

...

Homebrew Bundle failed! 1 Brewfile dependency failed to install.
```

I was able to run `script/setup` successfully by using `java` instead of `java8` in the Brewfile, but noticed that in https://github.com/education/classroom/pull/1227 we specifically wanted `java8`. Not sure how to proceed here, thoughts?

---

cc @Kadaaran @tarebyte

**Comment by Kadaaran** [comment]
It appears that ElasticSearch *finally* [supports](https://www.elastic.co/blog/elasticsearch-java-9-and-beyond) Java9 🎉 

I was able to run successfully `script/setup` and `script/server` as well. I think we can definitely remove `java8` and put back `java` 👍

**Comment by talsafran** [comment]
w00t thanks @Kadaaran!
