### ISSUE TITLE
Student join API 

### ISSUE THREAD

**Issue by pesehr** [education/classroom#1299]
Hey,
We want to use GitHub classroom and we have a designed registration website ([here](https://register.imantabrizian.me/)).
I'm wondering if there any API for calling?

**Comment by Kadaaran** [comment]
Hi @pesehr 👋 
You mean if Classroom has a dedicated API ?
If I understand, you want to push all your entries from your form to Classroom directly each time someones registers to the form ?

**Comment by pesehr** [comment]
@Kadaaran tanks for your attention.
Yes, I need an API.

**Comment by pesehr** [comment]
Sorry I've closed the issue.

**Comment by Kadaaran** [comment]
Unfortunately Classroom does not have an API. Classroom is built on GitHub API though.

Can you explain to me what you are trying to do ? Maybe I can help you to find something that would work on your end.

**Comment by pesehr** [comment]
@Kadaaran 

OK, it's important for us the students join Github first and after that join homework repository. 
so it's the scenario:
1. the student submit the form and we check if he/she has GitHub account.
2. invite the student to GitHub if doesn't have an account (GitHub has an API for it and works and also GitHub send an invitation to the classroom after joining).
3. if he/she has an account, map student to the student number and join him/her to the classroom. (we need help for this)

**Comment by Kadaaran** [comment]
@pesehr 

Just to make sure we are on the same page here:
 
You need an Organization to create a Classroom.
You can't actually *add* students to a Classroom itself. However you can add them to the roster page which makes it easier for the teacher to know which GitHub accounts is linked to which student ID.

The students will be added to the Organization as `outside_members` through the assignments they will accept.
You will be able to keep track of the assignments in Classroom from the students that were added to your Organization through the assignment they accepted.

Tell me if it's not clear or if it does not answer your questions ✋

**Comment by d12** [comment]
Closing in favor of https://github.com/education/classroom/issues/377
