### ISSUE TITLE
Search submissions

### ISSUE THREAD

**Issue by amueller** [education/classroom#1300]
It would be great if there was a way to search the submissions.
Let's say I want to find the repository that corresponds to homework 1 of a particular student.
There's no way to do this, and doing it manually by scrolling to the paginated assignment submissions is not really feasible (the interface is sluggish and I have 8 pages).
Sorting by the identifier as suggested in #847 would help a bit (I could do manual binary search instead of linear search) but really there should be a search.

**Comment by Kadaaran** [comment]
Hi @amueller 👋 

There is an ongoing PR #1182 that might be linked to your issue.
It lets the teacher re-order the assignments (oldest - newest - student_id etc). 

We can indeed think of implementing a search bar on the assignments submissions.

**Comment by amueller** [comment]
Thanks @Kadaaran. That still means I need to do manual binary search if I want to find a particular student.

**Comment by shaquillie23** [comment]
👍

**Comment by n2o** [comment]
A simple search mechanism (e.g. search by the student's github nickname) would be great. It is very annoying to jump to the organization to search the repo there. It would be easier and more comfortable to be able to get a focused search form, which searchs in the current assignment.

**Comment by mozzadrella** [comment]
@n2o @amueller we hear you. We're shipping some things in the near-team that will hopefully make this easier for you.
