### ISSUE TITLE
assignment repository web page "next" (page 2, 3, ...) buttons don't work

### ISSUE THREAD

**Issue by cindyanorris** [education/classroom#1303]
I'm unable to get to the second, third, etc page of classroom assignment repositories.  Clicking on next or manually changing the URL doesn't work.  It only returns the first page. 

![page1](https://user-images.githubusercontent.com/6600260/37316186-100d7a2e-2634-11e8-83df-420f3feca9d5.png)
![page2](https://user-images.githubusercontent.com/6600260/37316187-101ffac8-2634-11e8-9ee1-a3f04ea424a6.png)

**Comment by Kadaaran** [comment]
Hi @cindyanorris 👋 First thank you for reporting this issue.

Unfortunately for now after trying a few times, I can't reproduce your issue on my end. 
Did it happen suddenly or did you already have this issue before ?

As soon as I can reproduce it I'll fix it.
Thank you for your patience.

**Comment by sfikas** [comment]
Hi, I'm having the same problem.

The 'next page' button takes me back to the same page.
The list is a set of *group* assignments:
https://classroom.github.com/classrooms/23520047/group-assignments/psee-heim-2017-2i-seira-askiseon

I see the problem for @cindyanorris 's list is also with a list of *group* assignments, this likely makes the difference (?)

**Comment by Kadaaran** [comment]
Hi @sfikas 
Yes it does you're right it's only on _group assignments_ ! 

I started to dig more into it but I'm still not able to reproduce the issue on my end in dev 😞

**Comment by Kadaaran** [comment]
Hi everyone 👋 
I *finally* found what causes this issue and I'm working on a fix right away.

Thank you for your patience 🙏

**Comment by Kadaaran** [comment]
Hello everyone,

Just to let you know that the fix is now merged and the issue should be fixed 🎉

**Comment by sfikas** [comment]
It works, thanks!
