### ISSUE TITLE
Changelog for Classroom

### ISSUE THREAD

**Issue by Kadaaran** [education/classroom#1304]
Hi everyone 👋 

For now we are keeping the community updated through [forums](https://education.github.community/c/github-classroom) and the [issues](https://github.com/education/classroom/issues) on GitHub.
It would be great to have a `changelog` in Classroom (thanks @johndbritton  👋) to keep the community updated about new updates, bug fixes and new features on Classroom ✨ 

The first version will be an icon in the navbar which will redirect to a [filtered](https://github.com/education/classroom/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc) pull request page on GitHub.

In the future it would be nice to:
- send notifications to the users when a feature is released (use ActionCable)
- have our own changelog page on Classroom

Feel free if you have any ideas or suggestions !

**Comment by d12** [comment]
Closed by #1305
