### ISSUE TITLE
Lost admin access to created repository

### ISSUE THREAD

**Issue by volltin** [education/classroom#1306]
After assignment has been created, I carelessly deleted the created team (only my own account) from settings of the created repository. Now I can't delete the existing repository (because the team has no access to that repository) or recreate a new one (because I had created one).

**Comment by Kadaaran** [comment]
Hi @volltin  👋 
Did you remove yourself from the team or did you delete the team itself ?

**Comment by volltin** [comment]
I deleted the team itself. Maybe removing myself from the team will cause the same problem.
Actually the behaviors are expected. But adding a "recover access to my assignments" or "forbidding making the assignment repository without admin access" is better.

**Comment by Kadaaran** [comment]
Actually no it will not. 
Removing yourself from the team would have let you join another one right away.

Now in Classroom we still have a record of you in the team linked to the repository.
I'm going to find a solution and I'll come back to you when I'll have one, thank you for your patience 🙏

**Comment by Kadaaran** [comment]
Hi @volltin I've been digging into it. 
Just a few questions: how were you able to delete the entire team as you are not a teacher in the classroom ?

**Comment by volltin** [comment]
I clicked the revoke button on `https://github.com/<my-classroom>/<my-repo>/settings/collaboration`. Before that my team's role was 'admin'.
I think I'm not set as a teacher. Because my teacher can recover my access while I can't do that.

**Comment by Kadaaran** [comment]
I see ! 
You did not delete the team actually, just removed the teams access to the repo :)

Your teacher can add your team back to the repo via GitHub and it should work again and won't have an impact on Classroom.
