### ISSUE TITLE
Buggy paging mechanism?

### ISSUE THREAD

**Issue by trondaal** [education/classroom#1307]
I am using github classroom for a course with a large number of groups, but it seems like the paging mechanism for browsing the groups is bugged. I have around 50 groups for each assignment which is presented on 3 pages, but the page numbers at the bottom always give the first page and so does the button for browsing...

**Comment by Kadaaran** [comment]
Hi @trondaal 👋  
Your issues is a duplicate of #1303 

I'll close this one and invite you to go to the other one to talk about the issue, thanks a lot !
