### ISSUE TITLE
Bad credentials when running RSPEC

### ISSUE THREAD

**Issue by Kadaaran** [education/classroom#1308]
Thanks to @d12 👋for this one.

I was getting `401 - Bad credentials` all over again and again, it seems that it comes from this line.

https://github.com/education/classroom/blob/a0f29d2742e315f7e093dd2270b1e28d98d2119a/app/models/organization.rb#L39

When running test we might use the token of a test account whom do not have rights over the `organization` which results with `401 - Bad credentials`.

A quick fix would be to  get the token from the first user in the database (who is the owner of the `organization`) to make sure we don't get 401, of course it runs only if we are in a test environment.

**Comment by d12** [comment]
We fixed this a little bit ago here:

https://github.com/education/classroom/blob/fa60bc4a1be4b657cddf38a4670c5627be53b96a/app/models/organization.rb#L68-L72
