### ISSUE TITLE
Possible GeoPattern Header

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#131]
Took a quick break and was playing around with a geo_pattern header, wanted to see if anyone liked the idea.

/cc @jasonlong 

```ruby
pattern = GeoPattern.generate(@organization.title, color: '#5fb27b')
```
<img width="1552" alt="screen shot 2015-08-24 at 19 24 45" src="https://cloud.githubusercontent.com/assets/564113/9455125/f6b180d8-4a95-11e5-903d-3b45066b6284.png">

**Comment by jasonlong** [comment]
I could go either way to be honest. It's definitely "on brand" and if we lock the color in, it should be :ok_hand:. I'll leave it up to you @tarebyte unless anyone else has strong feels.

**Comment by johndbritton** [comment]
:+1: from me. It's a good way to distinguish between different orgs. This also makes me wonder if we should be displaying the org avatar anywhere.

**Comment by tarebyte** [comment]
Closed with #139

**Comment by johndbritton** [comment]
What do you think about using the Organization `id` for the pattern seed, that way changing the name of the class doesn't change the header.

**Comment by jasonlong** [comment]
Seems :ok_hand: to me. 

FWIW, we use the title on GitHub Guides (which would indeed change the pattern w/ a rename – though you can specify a pattern in the front matter) and we use the user ID for identicons on dotcom (which is a very similar generative thing) so name changes wouldn't effect the pattern.
