### ISSUE TITLE
Suggestion: Roster downloads should include GitHub IDs

### ISSUE THREAD

**Issue by robertcduvall** [education/classroom#1310]
In addition to including the GitHub account and name for each student in the roster, please include their GitHub ID since both of those fields can be changed during the class by the student.

Note, this suggestion actually came from John B during our conversation about the roster in general.

**Comment by ashleytqy** [comment]
Hi! Can I help out with this if it hasn't been worked on yet?

**Comment by Kadaaran** [comment]
@ashleytqy Not yet, go for it 🚀

**Comment by Kadaaran** [comment]
Thank you @robertcduvall for opening this issue 🙏, thanks @ashleytqy for the PR 👏
