### ISSUE TITLE
Error when entering an assignment

### ISSUE THREAD

**Issue by rainywang** [education/classroom#1311]
I use GitHub classroom service for my course. I have already set up several assignment, but when I click one of the assignments, it takes long time to wait and finally enters a page showing "500 Internal server error. We're sorry, but something went wrong. Try going back to classroom dashboard". 

But for my other assignment, it has no such error. I can enter and change the settings. 

Can I get help here?  Thanks a lot!

**Comment by Kadaaran** [comment]
Hi @rainywang 👋 Thank you for reporting this issue.

Can you give me the name of the assignment so I can take a look ?

**Comment by rainywang** [comment]
Hi Kassandre, thank you for attention! The assignment is Lab2: ADT and OOP (https://classroom.github.com/classrooms/35315614-software-construction-for-spring-2018/assignments/Lab2)




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            Zhongjie Wang
                            
                            
                                
                                    邮箱：rainy.wang@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
On 03/15/2018 21:55, Kassandre Pedro wrote: Hi @rainywang 👋 Thank you for reporting this issue.
Can you give me the name of the assignment so I can take a look ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/education/classroom","title":"education/classroom","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/education/classroom"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Kadaaran in #1311: Hi @rainywang 👋 Thank you for reporting this issue.\r\n\r\nCan you give me the name of the assignment so I can take a look ?"}],"action":{"name":"View Issue","url":"https://github.com/education/classroom/issues/1311#issuecomment-373383486"}}}

**Comment by Kadaaran** [comment]
Hi @rainywang 👋 
Just to keep you updated, we are currently working on a fix.

Thank you for your patience.

**Comment by d12** [comment]
This is caused by an octokit bug: https://github.com/octokit/octokit.rb/issues/912

**Comment by d12** [comment]
Hey @rainywang 

Sorry about the delay. This perf bug was caused by an upstream problem in Octokit. We finally got that sorted, and just bumped our Gem version to the newest, fixed version.

The assignments that were previously not loading for you should now work. The performance still isn't quite where we want to be, but we have plans to work towards something better in the coming weeks.
