### ISSUE TITLE
Validation failed: Title is too long (maximum is 60 characters)

### ISSUE THREAD

**Issue by nlazaridis** [education/classroom#1315]
Hello there, 
I'm trying to set up a new classroom for the second organization called aLIS-UWA (Department of Archives, Libraries and Information Systems @ University of West Attica, Greece) and receive the message "Validation failed: Title is too long (maximum is 60 characters)" with no further steps to follow. How can we fix that?

**Comment by Kadaaran** [comment]
Hi @nlazaridis ,
Your Classroom name is way too long, just make it shorter and it should work 👍
