### ISSUE TITLE
Admin list in Classroom settings

### ISSUE THREAD

**Issue by Kadaaran** [education/classroom#1319]
## Feature Request

**What happens now**:  Classroom is not fully synchronised with GitHub, teachers can't track who has admin access on Classroom or not.
Ex: An `organization` has 2 owners on GitHub, but only one of them signed in into Classroom. Classroom tells us that the `organization` has only one member.

Even if we keep track of whom is no longer part of an organization because we merged #1274 , I really like the idea for the teachers to have a page where they can check who has admin access over their Classroom and be able to revoke accesses when necessary (which we don't have for now).

**How**: The idea would be to add a section under the admin invitation link a page where the owner can revoke directly teachers access over the Classroom and check who has admin access.

<img width="800" alt="screen shot 2018-03-22 at 16 48 22" src="https://user-images.githubusercontent.com/11220823/37781381-e270aaa4-2df0-11e8-9b2b-c68541353df5.png">

Feel free to comment if you have any suggestions 🙏

**Comment by johndbritton** [comment]
@Kadaaran For the implementation, would removing a classroom administrator also remove the user as an owner of the GitHub organization?

**Comment by Kadaaran** [comment]
@johndbritton No it just removes access on Classroom side. 
But a few weeks ago we merged a PR that gets the event of when an owner leaves an org so we can update the org in Classroom as well.
