### ISSUE TITLE
Option to view all assignment submissions

### ISSUE THREAD

**Issue by sfikas** [education/classroom#1324]
It would be useful to have a button to view all submissions for an assignment in one page.

**Comment by Kadaaran** [comment]
Hi @sfikas 👋 

The submissions are all paginated because in the case of an assignment with a lot of submissions (300 for example) it will take to much time for the request to be done and the result to render.

**Comment by sfikas** [comment]
Is it possible then to have an option to choose the number of submissions to appear on a single page?

On its present state, it's also difficult to search for a specific submission. For example, I've got 80 participants on my course. If I want to look for the current state of submission of user, say, "george", I have to go through all 4 pages and hit Ctrl+F.

**Comment by Kadaaran** [comment]
Wouldn't a search bar or filters be more useful to your use case ? 🤔 

This PR #1182 adds filters (student id, student name, repo name etc) in submissions so the search becomes easier.

**Comment by sfikas** [comment]
Yes, #1182 sounds quite appropriate to me.. thanks!
