### ISSUE TITLE
Blank invite users page

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#133]
The invite users page is a bit weird when there are no people that you can invite.

<img width="477" alt="screen shot 2015-08-25 at 3 10 42 pm" src="https://cloud.githubusercontent.com/assets/123345/9468814/7c97a15a-4b3b-11e5-8435-12c27cafeaa8.png">

Maybe add some help text and handle the zero users to invite case.

**Comment by tarebyte** [comment]
I'll add this to #132

**Comment by tarebyte** [comment]
@johndbritton actually this part is going away.

What do you think about this page walking the user through adding admins to their github org? And then giving them their org url to give to their TA's?

**Comment by johndbritton** [comment]
> What do you think about this page walking the user through adding admins to their github org? And then giving them their org url to give to their TA's?

Yep, that makes sense to me.

**Comment by tarebyte** [comment]
Closed with #132
