### ISSUE TITLE
Accepting Classroom Assignment requires students grant access to all their orgs

### ISSUE THREAD

**Issue by BU-AWolfe** [education/classroom#1330]
From a student:

> I have run into this problem before with github app installs (see permissions message in photo below).  I don't want to open up access to the organizations I am involved with on github.  I ended up creating a new github account just for BU stuff for this reason, and also because it seems easier for Andrew to manage the classroom with the bu email address accounts.
> 
> I can't un-check the permission for my organizations that says "This organization allows the application to access organization data as described in the permissions above."
> 
> I read some forums where this is discussed and I guess there are some settings within the organization that can prevent users from giving out access to third-party apps.  But I am not an admin on one of the organizations.  Plus, what you'd really want is to be able to choose on install whether to just provide access to your personal repos, or check each organization individually.

At BU Metropolitan College, our mandate is teaching part-time, non-residential adult students.  In our Master's programs, students are largely active professionals who want to deepen their knowledge of computer science and IT.  Many, like this student, have other GitHub accounts.  Some have accounts they use for contributing to open-source projects.

_Asking my students to expose their other GitHub accounts to an application is not something I consider necessary, and I find it highly undesirable._  Obviously the creators of Classroom have no intention of breaking in to a student's other work, but I see this as a possible attack vector.  Bear with me - I'm a security guy.

When a student enables Classroom, he/she does this in response to getting an Assignment invite from a Classroom that already has an organization.  I assume the following about how this works:

- Classroom needs access to student work in order to create repositories for them
- "Access to student work" requires access to at least one student org
- Organizations currently used in Classroom are primarily for instructors and graders, not students

Suggested:
- creating an assignment creates a 'student' org for that assignment, ideally linked in some way to the Classroom org - like by the Roster
- Classroom requests permission to add student to org, and this permission includes permission to create and administer repositories for that student in that org only

![github classroom wants orgs](https://user-images.githubusercontent.com/31358179/37985223-31862406-31c6-11e8-8ba1-6c956758caa5.png)

**Comment by rhewett** [comment]
This is an issue when trying to create something with classroom too.  I created a test organization to play around with this tool and it wants admin access to all repositories in completely unrelated organizations.  I have no way to uncheck that authorization request.

I can't even test the tool, so there is no way I'm going to adopt it for my classes...

**Comment by boardfish** [comment]
Personally I'm not sure if this issue can be fixed – when GitHub.com requests access, there's no fine-graining this down to particular orgs. At a lower level, when you're authorising access on the site, one permission it requests is the read:org [scope](https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/) (and potentially write:org, but any sign of that's obscured in the screenshot).

I totally understand that that's concerning, what with all the reports of Android apps, for example, requiring too many system-level permissions, but as far as I can see, I think that's how it is, unfortunately. I think Classroom can be trusted not to take destructive action against anything it's not supposed to touch, however. (Please don't take this as gospel – hopefully a maintainer can confirm/deny my answer.)

**Comment by ThierrySans** [comment]
I am facing the same problem. Some of my students are working professionals and they are quite reluctant in giving access to their company's organization. I totally understand that and I see no reason why they should. To prevent that, they are creating new Github accounts. This is not ideal. It would be great to solve this problem.

**Comment by BenEmdon** [comment]
@BU-AWolfe thank you for your detailed issue. 


## How OAuth App organization access works 
The OAuth App permission model doesn’t allow apps to request fine grain organization access, but it does allow users to grant fine grain access. 

By default, GitHub Classroom will **not** get access to all of a users organizations. To give GitHub Classroom access to each organization, the user must be explicitly **grant** or **request** access for each organization. 

### How to grant/request organization access 

If you are an **member** of an organization you must **explicitly request**  that classroom is granted access to that organization. 
See this _requesting access page_ below:

> <img height="700" src="https://user-images.githubusercontent.com/11095731/51445267-3a197400-1cd1-11e9-9094-aa2555812d92.png">

If you are an **admin** of an organization you must **explicitly grant**  classroom access to that organization. 
See the _granting access page_ below:

> <img height="700" src="https://user-images.githubusercontent.com/11095731/51445278-4b628080-1cd1-11e9-9088-4cb18a9b2a8d.png">

### How students can prevent Classroom from accessing their organizations 
This permission model allows your students to **not grant access** to their professional organizations. By pressing `authorize github` without _granting_ or _requesting_ access, the user will _not_ grant GitHub Classroom access to their organization. 
See above screenshots where a grey "x" beside a organization name denotes that access will not be granted ☝️ 

## The situation in the screenshot posted

The image you provided depicts two organizations with green check marks:
> <img height="700" src="https://user-images.githubusercontent.com/31358179/37985223-31862406-31c6-11e8-8ba1-6c956758caa5.png">

The green checkmarks denote that these organizations have already granted access to GitHub classroom (by a prior admin of each organization). Pressing `authorize github` in this case won't grant any further access to these organizations.

---

I am closing this issue as the security requirements requested already exist. If you feel that this explanation doesn't resolve the issue, please reopen this issue. If you have any questions/concerns feel free to comment in this thread.
