### ISSUE TITLE
Trying to recover deleted repository

### ISSUE THREAD

**Issue by jakethesnnake** [education/classroom#1332]
I was having trouble with my GitHub project (because the README was the only file attached, instead of the two solutions), so I  to delete it/leave the project. I then attempted open the invitation again, hoping that it would open a new project that was unmodified and fit the assignment criteria. FYI, I am cloning the url to Visual Studio for a school project.

Instead of my actions solving the project, it erased the project and I am incapable of recovering it

Account name: jakethesnnake
Class: CIS300
Author of incomplete project (professor): Rod Howell
Assignment: Homework4

Please help me recover it. As of now, it is nowhere to be found.

I would greatly appreciate any help because it is a 100 point assignment.

Thank you!

(P.S. URL == (https://classroom.github.com/a/WoyezM4J)) -- the URL does not work. But there it is (just in case it's relevant)

**Comment by Kadaaran** [comment]
Hi @jakethesnnake 👋 

You should be alright now, can you retry to accept the assignment and keep me updated about it ? 

Thanks a lot !

**Comment by jakethesnnake** [comment]
You are a lifesaver, thank you so much!

**Comment by jakethesnnake** [comment]
Yes i greatly appreciate the help

Sent from my iPhone

On Mar 29, 2018, at 9:22 AM, Kassandre Pedro <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @jakethesnnake<https://github.com/jakethesnnake> 👋

You should be alright now, can you retry to accept the assignment and keep me updated about it ?

Thanks a lot !
