### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by parthh98** [education/classroom#1333]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to create a new assignment ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

##
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by Kadaaran** [comment]
Hi @parthh98 is your issue the same as the template ? Can your provide more informations ? Thank you !
