### ISSUE TITLE
Settings page is repetitive

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#134]
Maybe just use `Settings`, `Classroom settings`, or `Organization settings` for the title:

<img width="560" alt="screen shot 2015-08-25 at 3 12 49 pm" src="https://cloud.githubusercontent.com/assets/123345/9468851/caec4496-4b3b-11e5-9de6-a4ba4cbf942b.png">

**Comment by tarebyte** [comment]
I like `Organization settings`
