### ISSUE TITLE
Error resetting classroom

### ISSUE THREAD

**Issue by jmcda001** [education/classroom#1341]
Please choose either _issue_

##
#### What you were trying to do ?
I tried to reset the classroom. It said it was in the process of resetting. 

#### What happened (include screenshot if you can) ?
The classroom was removed from my list of classrooms, but it wasn't fully reset. As can be seen in attached screenshots, the organization still has all members and repos, I can't add a classroom because it thinks I still have one, but I can't see it. I have anonymized other orgs/classrooms I am a part of, but they aren't the ones causing problems. I have also anonymized user details, but as can be seen by repo, people and team counts the org was not reset. 
![notresetanonymized](https://user-images.githubusercontent.com/5721511/38473874-a5b435e6-3b4b-11e8-83d5-22b72a5c1110.png)
![notthereanonymized](https://user-images.githubusercontent.com/5721511/38473875-a5d37906-3b4b-11e8-877e-3ff4b0d47e68.png)
![alreadyaddedanonymized](https://user-images.githubusercontent.com/5721511/38473876-a5fedc7c-3b4b-11e8-8782-4accdea8602c.png)

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:
I don't know how to recreate as I am unable to create a new classroom now. 
I believe what happened is that another owner of the organization changed the name of the classroom before I hit reset, and somehow that caused this error. That is the only thing I can think of that would have caused this.

**Comment by Kadaaran** [comment]
Hi @jmcda001 👋 
Thank you for opening this issue.

Can you go in your organization settings and revoke access to Classroom. 
Then you should be able to recreate a classroom and it will initiate a new token when you will authorize Classroom again in your Organization. 

Can you keep me updated about it and tell me if it worked ? Thank you 🙏

**Comment by Kadaaran** [comment]
@jmcda001 We checked why some repositories are still available. 
It seems that your students transferred their repositories to themselves therefore we can't delete them (if you enabled admin access in the assignment then they have admin access on those repositories)

**Comment by jmcda001** [comment]
@Kadaaran Thank you for the assistance! I was able to get a new classroom set up by revoking access and re-adding it. I still have those other repositories, but I suppose I will have to manually go through and remove them.

**Comment by Kadaaran** [comment]
Perfect ✨ I consider this on as closed for now then 👍

**Comment by prateekkumarweb** [comment]
Hi @Kadaaran,
I am facing the same problem with organisation https://github.com/IITH-SBJoshi
I deleted the previous classroom and now I am unable to create a new classroom with the same organisation.
I tried removing the third party access (from Organisation settings) but that doesn't help.
Could you please try re-run a delete for this organisation as well?
Thanks.
