### ISSUE TITLE
Creating a team containing the word "null" such as "NullPointer" or "Team NullPointer" results in weird issues.

### ISSUE THREAD

**Issue by hdiep2015** [education/classroom#1344]
#### What you were trying to do ?
I tried to create a team for my group project containing the word "null"...

#### What happened (include screenshot if you can) ?
For the following words containing "Null" I got the following responses:

1. NullPointer -- "Team: Name has already been taken"
2. Team NullPointer -- "Team: Name has already been taken"
3. NullRef -- "You are forbidden from performing this action on github.com"

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix 
1. Create a assignment in which the users can create different teams.
2. As a student, create a team that contains "Null"

![image](https://user-images.githubusercontent.com/35982743/38586014-f1d9601e-3ce9-11e8-9ba9-3e9c59841ba1.png)

(I feel like this might be an input sanitizing issue -- I don't know if this could lead to any security issues.)

**Comment by Kadaaran** [comment]
Hi @hdiep2015 👋 

I checked and it seems that the teams already exists:
<img width="297" alt="screen shot 2018-04-11 at 21 08 31" src="https://user-images.githubusercontent.com/11220823/38637821-9b9f662e-3dcc-11e8-9e9f-616adfdb9f05.png">
The error messages were accurate.

The thing is that the teams have no students so we deleted them and you should be alright 👍 

Keep me updated if it worked or not 🙏

**Comment by hdiep2015** [comment]
I can't test it out as I'm a student and I've already made another team. I didn't know teams were global to all classrooms. Thanks!

**Comment by Kadaaran** [comment]
No they're not, they already existed on the assignment but were just empty. Thanks!
