### ISSUE TITLE
"Remove this organization" improvements

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#135]
The terminology used for removing an organization may be confusing:

<img width="334" alt="screen shot 2015-08-25 at 3 15 24 pm" src="https://cloud.githubusercontent.com/assets/123345/9468904/2264d742-4b3c-11e5-8771-544f651b56b6.png">

"Remove and reset organization" along with an explanation that the organization will be removed from classroom and all of the repositories, teams, and users created by the app will be removed.

Also, we might want to guard against accidental clicks by requiring a confirmation step. Check out the flow for deleting a repository on GitHub for some inspiration.

Maybe even separate out the two functions: `reset` deletes everything created by classroom, while `remove` just takes the org off of classroom's list. If you re-add a removed org, everything just comes back (since it's all still in the db maybe).

**Comment by tarebyte** [comment]
Since we already have the ability to soft delete this should be pretty easy to implement.
