### ISSUE TITLE
Allow download of CSV containing an association between team and roster data from it's members

### ISSUE THREAD

**Issue by fjorgemota** [education/classroom#1350]
##
### Feature request :sparkles:

Hey! Here i'm again..

Actually, I do not see a great integration between rosters and the teams created for a group assignment. So I'm suggesting I feature that I think it would be helpful (not only for me, but for other teachers, too): provide a link to download a CSV (or spreadsheet) on the following format (it's just a suggestion, by the way):

| Group Name | Member Identifier | Member Github Username | Member Github ID | Member Name |
|------------------|------------------------|------------------------------------|------------------------|---------------------|
| Team 1          | 123                       | github_user1                       | 1234                     | John                 |
| Team 1          | 124                       | github_user2                       | 1244                     | Raphael            |
| Team 2          | 144                       | github_user3                       | 3214                     | Fernando          |

And so on, for a assignment with the following teams and it's members:

- Team 1
    - John
    - Raphael
- Team 2
    - Fernando

This way, it would be easy to directly associate the roster data with each group, and with each member of the group. So it would integrate nicely with a external LMS, for example, and facilitate the grading process of each student/group.

I can, actually, get that data using some javascript to get the members data from the page and use a python script to associate the member data with the roster data on CSV format exported by github classroom (it's what I plan to do for now, actually), but it would be nice if Github Classroom provided that feature natively for each group assignment. 

A small observation is that this feature would be great mostly for group assignment. Individual assignment can use the roster data on CSV format as far I know, but I've not created an individual assignment to see how it works on Classroom and to check if such export option would be needed for that type of assignment too.

**Comment by Kadaaran** [comment]
Hi @fjorgemota 👋 
No worries, the community's feedback is what makes Classroom better and better ✨ 

I don't see why not it's a great idea 👍 

> A small observation is that this feature would be great mostly for group assignment
I agree on this point, there is no need for it on Assignment (imo 😄)

**Comment by ashleytqy** [comment]
hi! can i help out with this?

**Comment by d12** [comment]
@ashleytqy Absolutely! Feel free to ping me on a PR if you get this working.

**Comment by ashleytqy** [comment]
will work on it! sorry for the delay – didn't receive notifications for the thumbs up and this issue slipped my mind

**Comment by d12** [comment]
No worries, and no rush! Thank you for taking this on :)

**Comment by ashleytqy** [comment]
hey @d12 !

Right now, the `Download` button for rosters is under the roster management page, but this may be problematic if we want to include group names since students can be in different groups for different assignments. 

A solution would be having a `Download CSV` (with group names) function live on the assignment page, e.g.:

<img width="1067" alt="screen shot 2018-06-18 at 9 44 56 pm" src="https://user-images.githubusercontent.com/11889765/41571414-10549666-7341-11e8-978e-25f6349bd097.png">

Let me know what you think, and if there are any problems I might miss with this solution!

**Comment by ashleytqy** [comment]
a related note: I've created "fake accounts" with [my_email]+test@gmail.com, but have been marked as spam – is there another way to test Classrooms?

**Comment by d12** [comment]
@ashleytqy I'm not sure this option belongs on the group assignment page.

We have a concept of `Groupings`  which is a specific configuration of teams, and Groupings can be shared across multiple group assignments. Perhaps the existing `Download` button could open a modal of some sort where you can specify whether or not you want to group students by teams, and if so, which Grouping to use.

As far as your banned accounts, support may be able to take care of that for you! https://github.com/contact

Just let them know why you need more than 2 GitHub accounts and hopefully they're able to help.

**Comment by d12** [comment]
Hey @fjorgemota , this has just shipped. You'll find it under the roster management UI :)
