### ISSUE TITLE
Trying to access repository assigned to me

### ISSUE THREAD

**Issue by aionutas** [education/classroom#1352]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
Tried to access repository assigned to me
#### What happened (include screenshot if you can) ?

![](https://ci6.googleusercontent.com/proxy/6d44bQcvirDUVgj2E2fqDR-sfAPNctP-hQYlhMQYlaIx_dInAwS_KPGy57EwveEX3dLl6gY0AWT8bY9K5gRvxpFnP9_ui3A8zup9sraRtBhcqceSfVn4WZvHkcSQ2enU9Glw0xqsk9DuzG1UO-g4ZBnMHKhVaVkBiF4=s0-d-e1-ft#https://user-images.githubusercontent.com/37578596/39040948-b3451c22-4490-11e8-8783-9e5ba0f13e46.png)

![](https://ci6.googleusercontent.com/proxy/8Q5YaUIsLlvJIeChDneQlh-_7BbvXqknNo_l1X4lZXnIInx95vLKqxK5AHOC7qr2ukprPgxTg2nn1g3UMjc3XP-VRlELe0Tte7Ll8jC-j8pomj1Wyy5nmrkDcE5pKxzMRSV3qTxX181z1XNCa8o0cjOy7YL8in7Wc3g=s0-d-e1-ft#https://user-images.githubusercontent.com/37578596/39041041-d55ad4aa-4490-11e8-9c54-7f98b45aa89d.png)

And after I clicked on Restart:

![](https://ci5.googleusercontent.com/proxy/fL0-p6PvpEsOX7ZItwmPN50MU3j-EiEgysoRdlMWuOMHyRaPvADSkZ9LKqhqRWWcE-xfvBtCDQB-ZRKVUnbm8ZXWoCi7_awURWqm6z-6ewXdQmOBu9G-8t__3kgFGzFVV9RJ6ddIbqv5AbckKTMoayqO4_iZGP8gp1c=s0-d-e1-ft#https://user-images.githubusercontent.com/37578596/39041115-ed51fc8c-4490-11e8-8cd7-e1e6008fa0d3.png)

**Comment by Kadaaran** [comment]
Hi @aionutas 👋 

It appears the import of your repository led to an `error`
I deleted the empty repo, you should be able to recreate a new repository just by clicking on the invitation link.

Thank you for your patience 🙏

**Comment by d12** [comment]
Looks like this has been sorted, please re-open if this comes back up!
