### ISSUE TITLE
Issue Importing and Opening Module-1

### ISSUE THREAD

**Issue by swoicik** [education/classroom#1355]
##
#### What you were trying to do ?
Trying to start Module 1

#### What happened (include screenshot if you can) ?
Error when importing content to repository for Module 1. 404 Error when trying to restart. 

![screenshot-classroom github com-2018 05 14-07-00-39](https://user-images.githubusercontent.com/438490/40001667-bd8411f0-575c-11e8-871c-f81182812659.png)
![screenshot-github com-2018 05 14-07-01-05](https://user-images.githubusercontent.com/438490/40001674-c04a378e-575c-11e8-97e9-fc5ca5128547.png)
![screenshot-github com-2018 05 14-07-01-21](https://user-images.githubusercontent.com/438490/40001679-c1f0fd34-575c-11e8-8646-154da0b9e23a.png)

#### Step-by-step reproduction instructions
- Go to https://education.github.com/teachers/advisors#complete-the-training 
- Click Module 1 Git Basics 
- Next screen is You Are Ready To Go. 
- Click the link to your repository. 
- Next screens hows import error message
- Click to restart import
- 404 Error Page comes up

**Comment by d12** [comment]
Hey @swoicik ,

I think we've sorted this out, would you mind trying to accept the assignment again? It should work this time :)

**Comment by swoicik** [comment]
Thank you @d12, it is working properly now.
