### ISSUE TITLE
Link student in rooster to GitHub account

### ISSUE THREAD

**Issue by sauerwald** [education/classroom#1356]
##Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
I tried to link a student in the classrooster to his github account.

#### What happened (include screenshot if you can) ?
No unlinked github account is shown to select.
![github_rooster](https://user-images.githubusercontent.com/12443233/40040645-998b2c94-580a-11e8-8a06-2fbf0516b8f6.PNG)

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix 
I selected manage classroom to add my students to the rooster. 
Before, i used github without classroom and added all my students to my organization and formed teams. Now i want to link the team members to the rooster to create and deliver assignments for them.

**Comment by dicer2000** [comment]
I'm having this same problem.  Was it resolved for you?
