### ISSUE TITLE
Unprocessable entity 

### ISSUE THREAD

**Issue by drbeco** [education/classroom#1357]
Hello guys,

I'm having this problem lately:

![image](https://user-images.githubusercontent.com/5805111/40199180-0ce8c6ca-59ef-11e8-9beb-5efc4256aa2c.png)

I tried login out and in again, to no avail.

Any tips of what is the problem?

Thanks

**Comment by d12** [comment]
Hey @drbeco ,

Are you still seeing this issue?

**Comment by drbeco** [comment]
No, it is clear now. I don't know what it was, but it was temporary. After a few retries, it went through. Thnaks a lot!

**Comment by d12** [comment]
Great to hear! If this happens again, please let us know and we'll try to sort it out :)
