### ISSUE TITLE
Github Classroom Assignment Overview - Not showing correct commits

### ISSUE THREAD

**Issue by FlyteWizard** [education/classroom#1358]
#### What you were trying to do ?

I want to be able to log into Github Classrooms and from a glance see who has been committing to their repositories. However, the commits still show initial commits despite them updating their repository. 

#### What happened (include screenshot if you can) ?
The commits do not reflect the commits on their repository. 

**What Github Classroom shows:**

<img width="402" alt="capture d ecran 2018-05-30 a 10 07 48" src="https://user-images.githubusercontent.com/10472448/40736068-cb248e88-63f1-11e8-9aa4-c93b36a0d5ac.png">

**What their repository shows:** 

<img width="289" alt="capture d ecran 2018-05-30 a 10 07 58" src="https://user-images.githubusercontent.com/10472448/40736081-da1ee410-63f1-11e8-8710-3e3a93bafebb.png">

#### Step-by-step reproduction instructions

1. Create an Assignment with a base repository. 
2. Students accept the assignment and create a repository.
3. Students commit to their repositroy
4. Teacher looks in Github Classroom and sees no new changes. 
5. Teacher looks at their students repository and sees new changes.

**Comment by jmfarrow** [comment]
Seeing the same thing. Number of commits seems to reflect a point in time in the past not necessarily the initial setup.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/119180/41445072-5ee5e456-708a-11e8-98c9-14d46df1cfc4.png">

Whereas the actual commits for these groups are 82, 43, 101, 17 and 53.

**Comment by siddhantbajaj** [comment]
Hi @FlyteWizard and @jmfarrow 
I think this issue is similar to #1205.
 @d12 can I create a PR for this?

**Comment by jmfarrow** [comment]
Sounds plausible. At least one student in each group this semester didn't configure their git correctly and so were not committing using identities that would appear as contributors.

**Comment by d12** [comment]
Hi @FlyteWizard , @jmfarrow , @siddhantbajaj ,

The fix here is to ensure your students have properly set up their local git environment and their GitHub account. Specifically, their local git email needs to match a verified email on their GitHub account.

**Comment by d12** [comment]
If this keeps happening with properly configured Git, please re-open and we'll dig into this :)
