### ISSUE TITLE
help-wanted: gitlab classroom

### ISSUE THREAD

**Issue by drbeco** [education/classroom#1361]
## 
### Help Wanted :sparkles:

**Dear developers**, it is so great that this project is open source and encourages us to clone it or run our own version of it, for that I can't thank you guys enough. I guess that is the spirit, that is why we do open source the way we do, and the community just grows bigger.

I'm sure this clone at gitlab isn't going to be big, an I just want really if we could manage to run "the current state of art" with their API.

I've cloned and set up the domain page already, but that is about it.

The classroom for gitlab will rest at:

https://classroom.gitlab.io

Oh, I also edited the 404 html page. Now that is the extent of all I did so far. The work will be huge, but if you have some spare time, please help us to at least be able to _run_ it _as it is_ now.

Things that is deeply linked with github API we can (at least temporarily) disable, and so on.

Can we put it up and running? Please invite yourself to join. If you are a great developer here (many commits), I can surely give you the permissions you need to work directly on the project as a team.

Thanks a lot.

@drbeco 

PS. Link for the repository (currently) at:

https://gitlab.com/classroom/classroom.gitlab.io

Issue number 1: help wanted, port classroom

https://gitlab.com/classroom/classroom.gitlab.io/issues/1

PPS. If you know the user that currently holds the inactive group "education" there at gitlab, please contact me. Maybe he is kind to surrender it to us, so the path would be education/classroom like here. Thanks.

PPPS. If you are admin or from the http://gitlab.com team and you are reading this, please help to get us classroom.gitlab.com. Thanks.  :wink:

**Comment by drbeco** [comment]
What Mark said there ( https://gitlab.com/gitlab-org/gitlab-ce/issues/47561 ), I think it would apply here as well.

This post is not a _feature request_ nor an _issue_, so it is ok to close it labeled as _invalid_.

Thanks, and I'm still looking forward to your help.

**Comment by mozzadrella** [comment]
@drbeco we welcome development in the wider open ecosystem, but yes, this is not a feature request or a bug for GitHub Classroom. Thanks for using GitHub Classroom to help future developers learn to code.
