### ISSUE TITLE
Rejected access token owner not kicked out

### ISSUE THREAD

**Issue by srinjoym** [education/classroom#1365]
Related to https://github.com/education/classroom/issues/1366
Organization owner is not removed from admins after rejecting access token on the Github side and can still browse Classroom without getting kicked out until they log out. We should be logging out the user when they try to navigate to a new page if the access token is invalid.

**Comment by srinjoym** [comment]
Looks like we already had functionality to check scopes but there's a bug. We only add to the current scopes since we're using `||=` so the current_scopes points to the old scopes even after the user has an invalid token. @tarebyte is there any reason we're doing this?

https://github.com/education/classroom/pull/1367/commits/0c8c2bded86c4a410ae544c3ff428793029b7a6c#diff-1970c1941ce84ff0887a84ebdc67ca49

**Comment by johndbritton** [comment]
`current_scopes` is used because we need more scopes for org admins than we need for student users.

Can you write a test case that reproduces the bug you're experiencing?
