### ISSUE TITLE
Replace placeholder copy on create assignment page

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#137]
Likely just an oversight:

<img width="996" alt="screen shot 2015-08-25 at 3 24 38 pm" src="https://cloud.githubusercontent.com/assets/123345/9469166/7748b1ec-4b3d-11e5-84b6-f268ddac308c.png">

**Comment by tarebyte** [comment]
Thoughts on the wording.

### Individual assignment
Each student gets their own assignment repository, and works by themselves.

### Group assignment
Students form teams and work together on the assignment.

**Comment by johndbritton** [comment]
### Individual assignment
Each student gets their own assignment repository, and works by themselves.

### Group assignment
Students form teams and work together on the assignment.

**Comment by johndbritton** [comment]
> ### Individual assignment
Each student works individually in their own repository.
> ### Group assignment
Students form teams and each team works together using a shared repository.

**Comment by johndbritton** [comment]
@tarebyte What do you think of :arrow_up:

**Comment by tarebyte** [comment]
I like that, will :ship:
