### ISSUE TITLE
Editing assignments errors when its starter code repository isn't reselected

### ISSUE THREAD

**Issue by mic-max** [education/classroom#1370]
#### What you were trying to do ?
I tried to edit an assignment

#### What happened (include screenshot if you can) ?
After pressing "Save changes" without making any changes the error message "Invalid repository name, use the format owner/name." was displayed.
![screenshot of the error](https://i.imgur.com/C9naDwN.png)

#### Step-by-step reproduction instructions
Create an assignment, fill out all the fields properly.
Click on the newly created assignment's "Assignment settings"
Press "Save changes"

#### Note
It lets me save changes I make to the assignment if I retype the repository name and select the same repository that appears in the little dropdown below the text field.

**Comment by BenEmdon** [comment]
Hey @mic-max thanks for reporting this!
Looks like this is only happening when you edit assignments that have the character `.` in their name. The `.` doesn't match against the regex here https://github.com/education/classroom/blob/0638f37ce1ebc978926899cb8f64cc2b7fd4e8bf/app/controllers/concerns/starter_code.rb#L12

I can go ahead with a fix.
