### ISSUE TITLE
Error deploying assignments

### ISSUE THREAD

**Issue by cooganb** [education/classroom#1408]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
Deploy a previously-created assignment

#### What happened (include screenshot if you can) ?
Students first not able to access the page, then were stuck in the duplicating phase.

#### Step-by-step reproduction instructions
Screenshots below:

![screen shot 2018-07-17 at 8 04 11 pm](https://user-images.githubusercontent.com/8144425/42854257-a498ff94-8a00-11e8-9a35-6e6e7592117a.png)

![screen shot 2018-07-17 at 8 02 23 pm](https://user-images.githubusercontent.com/8144425/42854262-a85eb614-8a00-11e8-9bbe-212b86220c67.png)

**Comment by BenEmdon** [comment]
Hey @cooganb,
Thanks for reporting this!
Mid checking if its still happening? 
We just deployed a possible fix #1410

**Comment by cooganb** [comment]
Hey @BenEmdon , thanks for getting back to me!

Students are reporting still getting stuck at the "duplicating" process, but the repo still gets cloned and populated. Perhaps something is getting snagged there?

Thanks again for taking care of this, is there some migration happening which is causing this?

**Comment by cooganb** [comment]
The bottom window. Students this morning reported getting stuck at "1.
Importing complete," but the repo is cloned and populated. Will be able to
report more in a few hours when class starts.

**Comment by BenEmdon** [comment]
Good news is that flow was deprecated this morning in #1410 so your students shouldn't be stuck at that step anymore!
Thanks again for catching this!

Closing this since the old flow was removed.

**Comment by cooganb** [comment]
Great! Thank you for taking care of it!
