### ISSUE TITLE
Explain groups of teams

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#142]
It may not be immediately obvious to users what this means:

<img width="461" alt="screen shot 2015-08-25 at 3 48 32 pm" src="https://cloud.githubusercontent.com/assets/123345/9469767/c4890774-4b40-11e5-8dc2-f20e51653e24.png">

Also, we should be consistent about how we refer to teams and groups. Maybe we should always use the word team, like we did with organization in the organization / classroom terminology.

**Comment by tarebyte** [comment]
I had a professor give the suggestion of calling it a set of teams for reuse

**Comment by johndbritton** [comment]
"Create a reusable set of teams">

**Comment by tarebyte** [comment]
That sounds more clear to me
