### ISSUE TITLE
Better title for `setupv2.html.erb`

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom#1421]
Currently on `setupv2.html.erb` we have this: 
![current-screen-flow](https://user-images.githubusercontent.com/11095731/42974531-8388bbc4-8b6c-11e8-87f1-185e8fa7e7b2.gif)
> Please wait for repository setup to finish. Do not leave this page.

Since students should be able to leave the page we should think of a better title.

Any ideas?
CC: @d12 @johndbritton @srinjoym

**Comment by BenEmdon** [comment]
How about:
`Your assignment repository is being setup`
👍 👎 ❓

**Comment by d12** [comment]
What happens if they leave the page though, how do they go to their new repository? Would they have to re-click the assignment invitation link later?

**Comment by BenEmdon** [comment]
If they leave the page and go back to the `#show` page it should redirect them to `#setupv2` if the repo is still being setup or `#success` if the repo is successfully setup.

If they come back to the `#setupv2` it should show the correct state of the repo setup and redirect them to `#success` if the setup is complete
