### ISSUE TITLE
Error Installing Gem dependencies

### ISSUE THREAD

**Issue by officialgabzz** [education/classroom#1469]
Trying to run the application locally. i am running on linux(Ubuntu). i have installed all thats required on me to install, but whenever i run "script/server", its scripts bootstrap not found... the i run script/bootstrap ,it says script/bootstrap bundle not found... please how do i fix this???

**Comment by BenEmdon** [comment]
Hey @GABZZsoft 👋 
Thanks for writing in!
Can you please provide a code snippet of the command you ran and its output?

**Comment by GABZZsoft** [comment]
![screenshot from 2018-08-16 07-12-25](https://user-images.githubusercontent.com/29066025/44193866-d7212100-a123-11e8-9e5f-9764fdb361fa.png)
Thanks @BenEmdon  for your response...

**Comment by BenEmdon** [comment]
They the following commands:
```sh
gem install bundler # install bundler
rbenv rehash
```

**Comment by JessRudder** [comment]
Since it's been a while since we've heard an update, I'm going to close this issue out. If you're still experiencing a problem, please let us know.
