### ISSUE TITLE
I can't create a new group and the message error is not explaining anything

### ISSUE THREAD

**Issue by LoyGabriel** [education/classroom#1476]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to create a new assignment ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

##
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by BenEmdon** [comment]
Hey @LoyGabriel, thanks for writing in!
Would you mind providing step-by-step reproduction instructions and screenshots?
If you can provide a link to the assignment that would also be great 🙌 
The details you provided aren't sufficient for us to figure out the problem.

**Comment by LoyGabriel** [comment]
![image](https://user-images.githubusercontent.com/26697041/44186477-03bb4580-a0f0-11e8-824d-e2f22590ac92.png)

**Comment by BenEmdon** [comment]
The problem is related to https://github.com/octokit/octokit.rb/issues/1051.

Thanks again for reporting this ❤️  Sorry for the inconvenience. A fix should come out soon.

**Comment by BenEmdon** [comment]
It turns out the issue was in GitHub's API. 
The problem has since been resolved. If you experience any more issues feel free to write back.
