### ISSUE TITLE
Can't accept new homework

### ISSUE THREAD

**Issue by manu-msr** [education/classroom#1481]
My students can't accept new homework in Classroom platform. There's only a message "An errror has occured".

Is this normal?

![unnamed](https://user-images.githubusercontent.com/15841718/44218472-6425a380-a13f-11e8-8492-bb2ac1d5bceb.png)

**Comment by BenEmdon** [comment]
Hey @manu-msr 👋 thanks for writing in.
This is definitely _not normal_. 
Mind providing some steps to reproduce the behavior?
If you have a link to your classroom assignment that would be very helpful too!

**Comment by manu-msr** [comment]
It is happening with all the assigments of the classroom. 

The link for that asigment is: https://classroom.github.com/g/WgweRVm3

Thank you!

**Comment by BenEmdon** [comment]
It appears that classroom is creating private repositories, but not giving your students access to them.
Would you mind checking if the repository [`lenguajesfc/actividad2-github-staff-team-1`](GitHub.com/lenguajesfc/actividad2-github-staff-team-1) has starter code in it?

**Comment by BenEmdon** [comment]
A work around for now is to go to each team individually on `GitHub.com` and give each team access to their respective repositories. 

The problem is related to https://github.com/octokit/octokit.rb/issues/1051.

Thanks again for reporting this ❤️  Sorry for the inconvenience. A fix should come out soon.

**Comment by BenEmdon** [comment]
It turns out the issue was in GitHub's API. 
The problem has since been resolved. If you experience any more issues feel free to write back.
