### ISSUE TITLE
GraphQL + Classroom

### ISSUE THREAD

**Issue by d12** [education/classroom#1496]
I've been spending occasional weekends and evenings prototyping a GraphQL API for Classroom that stitches into the GitHub API for some time now, and I have the API fully working end to end locally and backing one view. Now that I know it's feasible, I want to open this issue to raise one question: **Is this something we should do?**

## The Problem

Classroom currently uses the GitHub REST API to fetch a lot of information used in our views, especially `assignment/show` and `group_assignment/show`. This includes user logins, user URLs, organization logins and URLs, avatars, repo URLs, repo commit counts, and so on. Typically, we make a fair number of requests to GitHub before we can render a view for the user.

This is especially a problem for large Classrooms. Because the number of API requests linearly scales with the number of assignment repos, assignments with a large number of students can require 20, 50, or hundreds of requests to the GitHub API before we can render the view.

As a result of hitting the GitHub API so many times per page load, users often experience page load times of more than 5s, and often hit rate limits on their tokens if Classroom pages are loaded enough times in a day.

## The Solution

GitHub has 2 main integrator APIs, REST and GraphQL. In REST, the server defines resources and the client requests the resources it needs, one resource per request. In GraphQL, the server defines a static schema defining all the data that the client is allowed to ask for. The client crafts a single query specifying all the data the client needs, and the server resolves the query in a single HTTP request.

Explained in another way, in REST, you might ask the server 30 questions, one after another. "I want user A. I want user B. I want repo C. I want repo D." In GraphQL, you would ask "I want the login and url from users A and B, and the url from repos C and D" all in one request.

By moving to GraphQL, load times on complex pages like assignment/show become effectively constant, and our large classrooms will experience the same fast page load times as the rest of our users.

## Why we should do this

Two reasons:

a) By moving to GraphQL, we will resolve most of GitHub Classroom's performance issues. 

b) By moving to GraphQL, we open the possibility of creating an integrator API in the future. Via [schema stitching](https://www.apollographql.com/docs/graphql-tools/schema-stitching.html), Classroom can define an API containing all information relevant to a teacher using GitHub Classroom. Some of this information will come from our database, and some will come from GitHub.com. The great thing about schema stitching is that where this data comes from isn't exposed to integrators, they're given a single interface. By providing an API, we're empowering teachers to use Classroom data in whatever way suits their workflow.

c) If we move to GraphQL, we get to rip out the entire `github_<resource>.rb` namespace.

## Why should we not do this

For one, moving Classroom to GraphQL may increase the application complexity. Everything will move from ActiveRecord calls to GraphQL queries in our controllers. This isn't all bad, the information a view needs would be defined by a GraphQL fragment defined in the view which means views define the data they need, not controllers. Regardless, it does add a fairly chunky layer to the data access step in our controllers. [This](https://github.com/github/github-graphql-rails-example/blob/master/app/views/repositories/_repositories.html.erb) is an example of what the views may look like, and [this](https://github.com/github/github-graphql-rails-example/blob/master/app/controllers/repositories_controller.rb) is an example of what controllers may look like.

Moving to GraphQL would also add to the list of barriers an OS contributor or a GitHub employee faces when looking to develop for GitHub Classroom. Some familiarity with GraphQL will be required to work in the views.

## If we do this, what will it look like?

- We will have an internal GraphQL API defined using [graphql-ruby](https://github.com/rmosolgo/graphql-ruby), the same gem that powers GitHub's GraphQL API.
- Our API will be partially backed by data coming from GitHub.com via a process called schema stitching. The schema stitching implementation is available via [a gem](https://github.com/d12/graphql-remote_loader).
- Our controllers will slim. They will call out to the views to define what data they need, perform the query, and render the layout view.
- Our views will fatten. When working with GraphQL in Ruby, we define GraphQL queries in our views. This is done because views can generally determine what data they need. Defining this data in the controller may lead to not remembering what data is needed in what views/partials.

## Conclusion

I wrote up this monster of an issue to propose a solution to the performance issues surrounding GitHub Classroom. It's a fairly significant change to the way we develop Classroom, so I don't want to move forward without approval from the other maintainers of Classroom. 

If anyone has questions, opinions, yays, or nays, I'd LOVE to hear them.

cc @srinjoym @BenEmdon @tarebyte @johndbritton @talsafran @damaneice @tessgriffin

**Comment by BenEmdon** [comment]
Thanks @d12 for summing up the pros/cons. 
I feel that GraphQL is the right way forward for classroom, since it aligns with GitHub's efforts with the v4 GraphQL API. The nice part about your approach is that it can be done iteratively (screen by screen) giving us all the time we want to migrate over from REST to GraphQL. 

### Some thoughts on your points:

> Explained in another way, in REST, you might ask the server 30 questions, one after another. “I want user A. I want user B. I want repo C. I want repo D.” In GraphQL, you would ask “I want the login and url from users A and B, and the url from repos C and D” all in one request.

This may be the simplest/easiest to understand analogy of GraphQL I’ve seen thus far 👏❤️ 

> b) By moving to GraphQL, we open the possibility of creating an integrator API in the future. 

I imagine a public classroom API being quite valuable to teachers, a fair amount of schools already write their own tools to pair with classroom. With a public API we will be empowering these schools 💪 

> c) If we move to GraphQL, we get to rip out the entire `github_<resource>.rb` namespace.

While the `github_<resource>.rb` was a smart idea before GraphQL, schema stitching totally solves this. The migration might might not be trivial though. Im interested to see what you did on `assignment/show` and `group_assignment/show`.

> Moving to GraphQL would also add to the list of barriers an OS contributor or a GitHub employee faces when looking to develop for GitHub Classroom. Some familiarity with GraphQL will be required to work in the views.

I totally agree. GraphQL is still not widespread knowledge yet. Maybe documenting our architecture could aid this? Possibly we could have a `/docs` directory that could fill in the gaps of knowledge needed to contribute.

While GraphQL might not be widespread knowledge, I imagine it will be. Especially with GitHub and other major companies betting on it.

> Our controllers will slim. They will call out to the views to define what data they need, perform the query, and render the layout view.

Yes 👏 please 👏 
By abstracting away our models behind a GraphQL API we will reduce code duplication bugs. I imagine it will make the codebase easier to maintain, and possibly increase test coverage (since a GraphQL API is very testable).
---
I definitely have a bias towards GraphQL, so I'd like to hear what others think. You definitely have the +1 from me.

**Comment by talsafran** [comment]
I'm gonna defer to @damaneice and @tessgriffin, since they're spending more time with education apps these days, but generally speaking I'm 👍:+1: this effort.

> c) If we move to GraphQL, we get to rip out the entire github_<resource>.rb namespace.

Lol, yes plz 😄

**Comment by d12** [comment]
Thanks for the feedback @BenEmdon @talsafran . Since I've only heard good feedback in the last week, I'm going to start working on making this a thing! 🎉 

I've put together a checklist that I'll be working through for those curious: #1518

**Comment by damaneice** [comment]
I haven't worked on this app yet.  I would deter to @tarebyte @BenEmdon
