### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#150]
* [x] `README.md`
  * [x] Describe the app
  * [x] Screenshots
  * [x] Link to the app
  * [x] Environment setup
  * [x] Link to `CONTRIBUTING.md`
  * [x] Shoutout to @tarebyte and Summer of Code
* [x] `CONTRIBUTING.md`
  * [x] GitHub CLA
  * [x] Requirements (tests, etc.)
 
cc/ @bkeepers Anything else you'd recommend documenting about this open source project?

**Comment by bkeepers** [comment]
Here's the checklist we use for releasing a new open source project: https://gist.github.com/bkeepers/f1b6b2ed8e85f80f561c
