### ISSUE TITLE
bug in "reset" classroom

### ISSUE THREAD

**Issue by cboettig** [education/classroom#1500]
I am teaching a new semester of my course using an existing GitHub organization for my course.  I use the "reset classroom" link provided to try and delete the previous semester's students and assignments.  Instead, this deletes the Classroom entirely, and I cannot re-add it to Classroom because the GitHub Classroom still says "this organization has already been added". 

---

My apologies, it seems logging out and logging back in is sufficient to resolve this issue!  Could still be fixed perhaps by triggering an automatic refresh, but that's a very minor concern, so I will close this out.  (panic averted)

**Comment by BenEmdon** [comment]
Glad it you were able to resolve it 🎉

**Comment by prateekkumarweb** [comment]
I am facing the same issue currently. I reset and removed the classroom but I am unable to create a new classroom using the same organization. It says "@pratekkumarweb has already added this organization to GitHub Classroom"

**Comment by BenEmdon** [comment]
@prateekkumarweb Multi classroom organizations are on our roadmap and will be released soon! 
CC: @srinjoym is there a place where we are providing updates on multi classroom organizations?

**Comment by prateekkumarweb** [comment]
@BenEmdon Since I have deleted my previous classroom. There is no classroom with the organisation. Still I am unable to create a new classroom using the previous organisation. (I am guessing this is not what you meant when you said multi classroom organisation).
