### ISSUE TITLE
Repository not downloading

### ISSUE THREAD

**Issue by ScottGR1** [education/classroom#1502]
It seems the repository I'm trying to download is stuck. The progress bar has been in the same location for the last hour: 
![image](https://user-images.githubusercontent.com/14166596/44633916-31598780-a957-11e8-96c4-9300ffde0700.png)

Not sure what else I can do, already refreshed and reopened page several time.

Thanks for the help,

Scott

**Comment by kmayerpatel** [comment]
Just FYI, some (I would say at least 5, maybe more) are seeing this issue in my class (about 400 students). Don't know if this is related, but it cropped up when I published an assignment invite link as an example to do in class and so there was probably a bit of a flash crowd as they all accepted the invitation within minutes of each other.

**Comment by BenEmdon** [comment]
This issue has since been resolved after we fixed this bug #1534

**Comment by BenEmdon** [comment]
If you continue to experience this bug please reopen the issue.
