### ISSUE TITLE
Unable to create private repository for classrooms

### ISSUE THREAD

**Issue by rjhoyle** [education/classroom#1516]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?

It is not letting me create a homework assignment with private repositories, saying that I have to apply, sending me to https://education.github.com/discount_requests/new which shows that the organization is approved.

Deleting and recreating the classroom did not fix the issue.

The classroom is https://classroom.github.com/classrooms/42414948-oberlin-csci241-fall2018

The organization is https://github.com/Oberlin-cs241-fall2018

**Comment by BenEmdon** [comment]
Hey @rjhoyle 👋 thanks for writing in!

Im wondering if someone from @education/github might be able to take a look? (since this has to deal with discount_requests)

**Comment by rjhoyle** [comment]
I have not heard yet from anyone in education.  

r.
--
Roberto Hoyle
Assistant Professor
Computer Science Department
Oberlin College
rhoyle@oberlin.edu

**Comment by BenEmdon** [comment]
Did you make a support request to https://github.com/contact?

**Comment by rjhoyle** [comment]
I have not made a new request.  I submitted the original ticket through the GitHub Classroom page.  Are they different systems?

r.
--
Roberto Hoyle
Assistant Professor
Computer Science Department
Oberlin College
rhoyle@oberlin.edu

**Comment by BenEmdon** [comment]
Closing this for now. Please re-open the issue if it doesn't get resolved.
