### ISSUE TITLE
Http 500 when visiting classroom.github.com

### ISSUE THREAD

**Issue by pvoosten** [education/classroom#1523]
**Describe the bug**
There is an HTTP 500 message when visiting classroom.github.com, whether signed into GitHub or not

**To Reproduce**
The error is shown in both Safari on iPhone and Chrome and Edge in Windows.

**Expected behavior**
the normal classroom

**Screenshots**

**Additional context**
No idea whether it's related, but I got the 500 after deleting a roster.

**Comment by mozzadrella** [comment]
@pvoosten we're on it. Updates to come.

**Comment by mozzadrella** [comment]
We're back up. Thanks @pvoosten 

![screenshot 2018-08-30 12 51 29](https://user-images.githubusercontent.com/1874003/44866504-703b5600-ac53-11e8-9188-0615fbe2e47e.png)
