### ISSUE TITLE
Login error when tried to access forum

### ISSUE THREAD

**Issue by astutiwidi** [education/classroom#1529]
##
#### What you were trying to do ?
_I tried to access https://education.github.com/forum ..._

#### What happened (include screenshot if you can) ?
_Login error ..._
![github login error](https://user-images.githubusercontent.com/39181853/44915776-107da180-ad5e-11e8-8e87-3dafb251f9fc.JPG)

#### Step-by-step reproduction instructions
I was on https://classroom.github.com/classrooms and already logged in
I tried to click "forum" and go to https://education.github.com/forum
After that I prompted to login, but error

cc @ceefour

**Comment by BenEmdon** [comment]
Hey @astutiwidi, 
this problem doesn't appear to be related to GitHub Classroom, but is rather related to the GitHub Education Community site. 

To get support for that site please contact GitHub support at 
https://github.com/support
