### ISSUE TITLE
"creating repository" indefinitely loads and never creates the project

### ISSUE THREAD

**Issue by rv-cadams** [education/classroom#1533]
**Describe the bug**
External Users Pulling Project; candidates click on the link to create a repo and "creating repository" indefinitely loads and never creates the project. The repository set-up bar is half loaded and never comes to resolution so candidates cannot work on the Scoring Project.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BenEmdon** [comment]
Hey @rv-cadams 👋 thanks for writing in. Does it look like this:
> ![](https://user-images.githubusercontent.com/14166596/44633916-31598780-a957-11e8-96c4-9300ffde0700.png)

Also for some context:
* are you seeing any error messages?
* if you have a link to the assignment would you mind providing it?
* Does the loading ever end? 
* What happens when the user refreshes the page?

This might be related to #1502

**Comment by rv-cadams** [comment]
Thank you for getting back to me! Please find the picture attached. Additionally:


  *   No error messages
  *   Here is the link: https://classroom.github.com/a/1jq8TY3v
  *   The loading does not end, candidates wait 2+ hours, have tried different machines, and have tried refreshing
  *   When refreshed, it goes back to the same view with no change.




[ignature_1745433566]
Caroline Adams
Senior Recruiter, Software Engineering
1101 Red Ventures Drive
Fort Mill, SC 29707
704-612-0476 direct line
704-971-2300 main
cadams@redventures.com<mailto:cadams@redventures.com>
www.redventures.com<http://www.redventures.com/>

[ignature_395073252]

**Comment by BenEmdon** [comment]
I have identified the problem and I am working to resolve it now. 
Sorry for the inconvenience!

**Comment by rv-cadams** [comment]
Awesome, thank you!


[ignature_1440279369]
Caroline Adams
Senior Recruiter, Software Engineering
1101 Red Ventures Drive
Fort Mill, SC 29707
704-612-0476 direct line
704-971-2300 main
cadams@redventures.com<mailto:cadams@redventures.com>
www.redventures.com<http://www.redventures.com/>

[ignature_643036191]

**Comment by BenEmdon** [comment]
We just deployed a fix . I tried out your invitation link and everything looked good. 
Thanks again for all the details 😄 

If you feel that the issue is still happening please reach out again and re open this issue.
