### ISSUE TITLE
Cannot create repo and accept assignments

### ISSUE THREAD

**Issue by djlin** [education/classroom#1535]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
I tried to create a new assignment and accept the existing assignments.

#### What happened (include screenshot if you can) ?
I created new personal token and changed the default organization member's permission (from None to Adm and others) to test the GitHub API. After than, I was unable to create/accept assignments.
I received the error message "Cannot retrieve this organizations repo plan, please reauthenticate your token." for both actions.

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

Just add new assignment or accept assignments.

**Comment by djlin** [comment]
Just figured out the problem was caused by the removal of Classroom access to my Organization. Once added it back, the problem is resolved.

**Comment by BenEmdon** [comment]
Hey @djlin 👋 thanks for writing in. 
Glad you figured it out before we had a moment to investigate 🎉
