### ISSUE TITLE
Source import (Starter Code Import) API is down

### ISSUE THREAD

**Issue by wz337** [education/classroom#1536]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to create a new assignment ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

##
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by gchallen** [comment]
I'm seeing dozens of failed repository creations. Is this a general GitHub Classroom problem or something about our organization? (We have ~4500 private repositories already, but I did request many more than that.)

**Comment by BenEmdon** [comment]
Hey @wz337 @gchallen 👋 

We have identified the problem, it appears part of GitHub's API is down. The team responsible for the outage is currently responding. Sorry for the inconvenience.

I'll post back with updates.

**Comment by gchallen** [comment]
👍

**Comment by gchallen** [comment]
@BenEmdon : any idea on an ETA for this, even in terms of minutes v. hours? I have the better part of 900 students banging against GC and I want to make a call about what to do...

**Comment by BenEmdon** [comment]
Hey @gchallen,

The problem appears to be that that there was a influx of code imports, which caused the service to throttle GitHub. It will take a while before the queues of jobs die down.

We can't really say at this point. I'd estimate 1-2 hours for the situation to improve. I'll continue with updates here.

**Comment by gchallen** [comment]
Fair enough. Should I shut down the invitation link in the mean time to avoid generating more traffic?

**Comment by BenEmdon** [comment]
Up to you 🙂 it would definitely send your students the right message if you do so.

**Comment by gchallen** [comment]
Hmm... OK. Well, right as I said that things seem to have improved.

**Comment by gchallen** [comment]
OK, shut off. Can you ping us when this is fully resolved? I guess my students will be able to thank GitHub for a small extension 😉.

**Comment by BenEmdon** [comment]
@gchallen we investigated and it looks like it was your token was the reason for the large influx of users 😅 The situation has since improved (not fully). 
We have an idea on how to quickly support classes the size of yours (we don't often have 900 students in a single classroom accept a assignment). 
I apologize for the inconvenience, I will investigate a more stable solution right away.

**Comment by gchallen** [comment]
OK great. So is it safe to turn the link on again? Happy to provide more information about this as needed. I'm surprised it was such a huge influx, given that we released the assignment last night. But we have labs today and tomorrow and our TAs are pushing students to get started.

**Comment by BenEmdon** [comment]
It looks like everything has calmed down for now. Please write in if the problem persists for you.

**Comment by BenEmdon** [comment]
We merged a change that should reduce the chance of this happening again. We will focus our efforts in finding the most scalable approach so that incidents like this don't happen again.

Again, apologies for the inconvenience. If you continue to experience problems please reopen this issue.
