### ISSUE TITLE
Students can't clone a repository from an acceptance link

### ISSUE THREAD

**Issue by sbailey6** [education/classroom#1537]
**Describe the bug**
I made an individual assignment, using starter code from a private repository I created. Last week, the acceptance link worked fine, but today, when students went to use the acceptance link in a later lab section, the following error occurred.

![image](https://user-images.githubusercontent.com/11618866/45055310-6f446300-b05d-11e8-9f24-f3f93dcf7994.png)

I had to keep retrying multiple times by refreshing the page, but eventually the error went away on its own. 

Any advice on how to avoid this in the future?

**Comment by BenEmdon** [comment]
Hey @sbailey6 

We have identified the problem, it appears part of GitHub's API is down. The team responsible for the outage is currently responding. Sorry for the inconvenience.

I'll post back with updates.

**Comment by BenEmdon** [comment]
The problem appears to be that that there was a influx of code imports, which caused the service to throttle GitHub. It will take a while before the queues of jobs die down.

We can't really say at this point. I'd estimate 1-2 hours for the situation to improve. I'll continue with updates here.

**Comment by DbCrWk** [comment]
Having the same issues—thanks for responding so fast!

**Comment by BenEmdon** [comment]
The problem appears was that starter code imports were being throttled by GitHub.com
The situation has improved slightly in the last 30 min. As we have reduced the import traffic.
I have a longer term solution in mind about how we will avoid throttling 🙂
I'll continue to  keep this thread posted with updates.

**Comment by umasshokie** [comment]
Does this mean that we can tell students to try to create their repositories again? This caused us mass havok in our intro courses this afternoon, which of course isn't great to convincing students that GitHub is worth their time (but we'll still try). Don't want to tell them it works too soon though.

**Comment by BenEmdon** [comment]
It looks like everything has calmed down for now. Please write in if the problem persists for you.

**Comment by danwallach** [comment]
We ended up with half of the class in and half of the class out. The painful workaround is to create new repos manually with the right names, manually push to the new repo from your PC, and then manually give the student write-access to their repo. Takes about two minutes per student, and you've got about a 10% chance of some sort of typo making you have to rewind and do everything from scratch.

**Comment by BenEmdon** [comment]
The issue has been resolved. If you experience it again, please reopen this issue.
