### ISSUE TITLE
project 1

### ISSUE THREAD

**Issue by Tanner164** [education/classroom#1545]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to create a new assignment ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

##
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by Tanner164** [comment]
I dont want to get a bad grade in this class

**Comment by BenEmdon** [comment]
Hey @Tanner164,
The information you gave us isn’t sufficient for a big report. Please report your problem to your professor/TA/teacher.
Please open a new issue with a more details. Sorry for your inconvenience.
