### ISSUE TITLE
Group Created in Organization but not Classroom

### ISSUE THREAD

**Issue by jagodwin** [education/classroom#1549]
I created a Group assignment in classroom and linked it to a repository in our class organization. I received three notifications from classroom that new imports into a repository had been created automatically by classroom. When I opened classroom to verify that each one corresponded to a group, I found that only two of the teams exist in classroom. However, all three are present in the classroom organization. I am not certain what, if anything, the student did for Team 3 that was different from team 1 & 2, but from my email, it looks like it was created in the same way - by following the link created by classroom. 

Is there any way to link the organization team to classroom at this point? How can I keep this from happening again?

**Comment by BenEmdon** [comment]
Hey @jagodwin 👋 thanks for writing in!
Interesting, sounds like something is behaving unexpectedly. 
Would you mind providing a link to the GitHub classroom affected and the GitHub organization where the problem occurred?

Currently there isn't a way link a team to a classroom at this point.

**Comment by BenEmdon** [comment]
Hey @jagodwin,
After investigating with my team we think that this behavior is related to one of the outages we experienced earlier this week. We don't expect this behavior to happen again.

### Work arounds you can do
<ol type="a">
  <li>You could continue to let these students work on the repo they already have access to on GitHub.com. This would require you to manually monitor the repo and keep track of it on GitHub.com.
  </li>
  <li>You could delete the team off GitHub.com and it's associated repo. Then ask your students to re-accept the assignment invitation. 
  
  * If you don't want to lose the teams progress you could clone their repo and push their progress to their newly created assignment repo.
  </li>
</ol>

Apologies for the inconvenience. If this happens again don't hesitate to reopen this issue.
