### ISSUE TITLE
Roster Managegement down

### ISSUE THREAD

**Issue by drmarcopapa** [education/classroom#1558]
Please choose either _issue_

##
#### What you were trying to do ?
_I tried to access Roster Management for 
https://classroom.github.com/classrooms/39249536-web-technologies-fall-2018

#### What happened (include screenshot if you can) ?
_error 500 Internal Server error
![screen shot 2018-09-12 at 10 32 01 am](https://user-images.githubusercontent.com/39249407/45442623-59472b80-b677-11e8-925b-1ac48dd57de3.png)
 ..._

#### Step-by-step reproduction instructions
Just access Manage Classroom - Roster Management
 :raised_hands:

**Comment by d12** [comment]
@drmarcopapa We've just deployed a fix, would you mind trying again and letting us know if it works?

**Comment by drmarcopapa** [comment]
Nope. Tried with both Firefox and Chrome. Same error 500.

Marco Papa, Ph.D.
Adjunct Assistant Professor of Computer Science Practice
Computer Science Department
University of Southern California
941 Bloom Walk
Los Angeles, California 90089-0781
Voice: +1-213-830-0120<http://s.wisestamp.com/links?url=tel%3A%252B1-213-974-2137&sn=cGFwYS5tYXJjb0BnbWFpbC5jb20%3D> Cell: +1-310-944-5468<http://s.wisestamp.com/links?url=tel%3A%252B1-310-944-5468&sn=cGFwYS5tYXJjb0BnbWFpbC5jb20%3D>
E-mail: papa@usc.edu<mailto:papa@usc.edu>


On Sep 12, 2018, at 11:34 AM, Nathaniel Woodthorpe <notifications@github.com<mailto:notifications@github.com>> wrote:


@drmarcopapa<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_drmarcopapa&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=F1h1d1R4l7RqoSXs-2EWbw&m=k0fGz80Ypi2_cFE0gkxIeY-dXAFyF_q0fTKdza12wi0&s=XHuGzb-vd7e_vdX5SQLa9Bvaj3MUz7FIchC2g2-_Dgo&e=> We've just deployed a fix, would you mind trying again and letting us know if it works?

**Comment by BenEmdon** [comment]
Hey @drmarcopapa, just deployed another fix. 
Would you mind taking another look?

**Comment by drmarcopapa** [comment]
That worked!! Thanks.

Marco Papa, Ph.D.
Adjunct Assistant Professor of Computer Science Practice
Computer Science Department
University of Southern California
941 Bloom Walk
Los Angeles, California 90089-0781
Voice: +1-213-830-0120<http://s.wisestamp.com/links?url=tel%3A%252B1-213-974-2137&sn=cGFwYS5tYXJjb0BnbWFpbC5jb20%3D> Cell: +1-310-944-5468<http://s.wisestamp.com/links?url=tel%3A%252B1-310-944-5468&sn=cGFwYS5tYXJjb0BnbWFpbC5jb20%3D>
E-mail: papa@usc.edu<mailto:papa@usc.edu>




On Sep 12, 2018, at 12:43 PM, Ben Emdon <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @drmarcopapa<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_drmarcopapa&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=F1h1d1R4l7RqoSXs-2EWbw&m=VGy4qhTpCni433FBEaFhux7GrFVTo5CSxF-4RbZtx8M&s=zMPEbB3iOoj-4duD4YGXuE2ia59YQlVSonXWFyaAhHc&e=>, just deployed another fix.
Would you mind taking another look?

**Comment by BenEmdon** [comment]
Glad to hear 🎉 Thanks for reporting this!
Closing this for now. If you run in to any more issues, open a new issue.
