### ISSUE TITLE
cannot join classroom

### ISSUE THREAD

**Issue by bradleygoldmeier** [education/classroom#1562]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
i tried to join a github classroom.
my teacher sent me this link  https://classroom.github.com/a/JdxDX-uI 
and when i clicked it github started to try to make a new repo but ut just keeps waiting

#### What happened (include screenshot if you can) ?
nothing happened (thats the issue. a repo was supposed to be created but it didnt)

![githubbug](https://user-images.githubusercontent.com/29414754/45449900-8231e580-b6a4-11e8-80b8-fc762d358f65.png)

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix 
every time i click the link it takes me to the same page and never creates the repo

##
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by BenEmdon** [comment]
Hey @bradleygoldmeier, I just took a look and it looks like your assignment was created (just took some time). 
Mind going back tohttps://classroom.github.com/a/JdxDX-uI to confirm your assignment exists?

**Comment by bradleygoldmeier** [comment]
thank you so much for all your help. have a wonderful weekend
    On Wednesday, September 12, 2018, 4:55:40 PM EDT, Ben Emdon <notifications@github.com> wrote:  
 
 
Hey @bradleygoldmeier, I just took a look and it looks like your assignment was created (just took some time).
Mind going back tohttps://classroom.github.com/a/JdxDX-uI to confirm your assignment exists?
