### ISSUE TITLE
Standup 17 September 2018

### ISSUE THREAD

**Issue by mozzadrella** [education/classroom#1563]
# Agenda

1. User testing @courtkh

- discrete project: the onboarding and creating assignments process
- aim to focus on usability of the experience
- where can something use design love / what exactly is confusing
- power users 
- @courtkh: skim all the open issues

2. CI @mozzadrella @johndbritton @d12's master plan (related https://github.com/education/classroom/issues/582)

3. Design review of front page @brandonrosage @johndbritton @srinjoym @mozzadrella
4. Disabling source import emails, source import webhook ideas, and progress on group assignment repo resiliency @BenEmdon
5. ES fixes and outages @BenEmdon @d12 (https://github.com/education/classroom/issues/1556, https://github.com/education/classroom/issues/1569)
6. Classroom Assistant Launch update @srinjoym

**Comment by BenEmdon** [comment]
@mozzadrella what does one usually do with agenda issues? When should we close this?
