### ISSUE TITLE
Cannot make this private assignment, your limit of 0 repositories has been reached. You can request a larger plan for free at https://education.github.com/discount

### ISSUE THREAD

**Issue by bessermt** [education/classroom#1576]
##
#### What you were trying to do ?
_I tried to create a new assignment ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

Just get the following message:

Cannot make this private assignment, your limit of 0 repositories has been reached. You can request a larger plan for free at https://education.github.com/discount

**Comment by johndbritton** [comment]
Your account doesn't have private repositories, you can request free private repositories for educational use at https://education.github.com/discount.

Alternatively, you can use public repositories.
