### ISSUE TITLE
Cannot make this private assignment, your limit of 0 repositories has been reached. You can request a larger plan for free at https://education.github.com/discount

### ISSUE THREAD

**Issue by labermt** [education/classroom#1577]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
_I tried to create a new assignment ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

Message:

Cannot make this private assignment, your limit of 0 repositories has been reached. You can request a larger plan for free at https://education.github.com/discount

#### Step-by-step reproduction instructions
Sign up for Github classroom and created and assignment.

**Comment by johndbritton** [comment]
Your account doesn't have private repositories, you can request free private repositories for educational use at https://education.github.com/discount.

Alternatively, you can use public repositories.
