### ISSUE TITLE
No Links

### ISSUE THREAD

**Issue by labermt** [education/classroom#1578]
#### What you were trying to do ?
_I tried to create a roster entry ..._

#### What happened (include screenshot if you can) ?
_The assignment was not created ..._

Message:

![image](https://user-images.githubusercontent.com/26236731/45671787-3edbda80-badb-11e8-86fd-420cf501ab6b.png)

**Comment by johndbritton** [comment]
I'm closing this issue as not enough details were provided. If you choose to re-open, please be sure to include a full description with steps to reproduce.
