### ISSUE TITLE
  labermt@gmail.com  or upload proof of your current school affiliation

### ISSUE THREAD

**Issue by labermt** [education/classroom#1579]
Please choose either _issue_ or _feature request_

##
#### What you were trying to do ?
Create school email

#### What happened (include screenshot if you can) ?
Unable to create a school email. Entered, but never shows. 

#### Step-by-step reproduction instructions
Please provide as much explanations as you can, reproduce a bug is the first step to write a fix :raised_hands:

**Comment by johndbritton** [comment]
I'm closing this issue as not enough details were provided. If you choose to re-open, please be sure to include a full description with steps to reproduce.
