### ISSUE TITLE
Unchecking "enable assignment invitation URL" fails to stop URL from working

### ISSUE THREAD

**Issue by dmusican** [education/classroom#1592]
**Describe the bug**
Unchecking "enable assignment invitation URL" has no effect. Even with the box unchecked, the link generated still works, and people can create new repos in the organization.

**To Reproduce**
1. Create an assignment, and make sure check "enable assignment invitation URL" in the settings.
2. With a different GitHub account, verify that the URL works.
3. In the original GitHub account, go back to settings for that assignment, and uncheck "enable assignment invitation URL." Click "Save settings" button.
4. With yet another GitHub account, visit the public link. It still creates repos (even though it shouldn't anymore).

**Expected behavior**
With that checkbox unchecked, the public link should no longer work.

**Additional context**
Here's why this bug is important. I put the link on my assignment webpage, which was public, and now I’ve got a dozen random people worldwide who have forked and cloned my repo. Worse, these people now have a shared private repo with me. Ok, live and learn – I’ll delete those repos. The problem that I’m having is that I can’t figure out how to stop more people from coming through. Since I can't uncheck “Enable assignment invitation URL” with any effect, I can't stop people from adding repos. I thought about deleting the assignment entirely, but GitHub classroom popped up a pretty severe looking message claiming that if I did that, I’d lose all of the repos that my students had in fact created for their assignment. So I can't use that route either.

**Comment by johndbritton** [comment]
Thanks for reporting this issue @dmusican, we'll take a look and see what change might have introduced this bug.

**Comment by EricPickup** [comment]
@johndbritton Were you able to reproduce this bug? I've tried with individual and group assignments and can't reproduce it.

**Comment by AmeliaMN** [comment]
Not completely related, but I didn't want to start an entirely new issue. What is the *intended* behavior when this box is unchecked? I'd love students to be able to go to a centralized "classroom" page for my class, and see all the assignments, rather than me having to send out the links for each assignment. Is that what's supposed to happen if I uncheck the "enable assignment invitation URL" box?

**Comment by AmeliaMN** [comment]
Not sure the stale bot made the right call here! Do stale issues eventually get addressed?

**Comment by EricPickup** [comment]
@AmeliaMN That sounds like an unrelated but good idea, would you mind creating a separate issue for your feature request?

The invitations URL is what students use to accept an assignment and create a repo. Disabling the invitation URL would disable the link and prevent students from accepting the assignment/creating a repo for it.

**Comment by EricPickup** [comment]
Myself and other contributors have tried to reproduce this with no luck. It was also last reported 6 months ago so I'm assuming the issue was resolved.

**Comment by melvidoni** [comment]
I'm also having this issue. Unchecking doesn't work, and the link is still shareable.
