### ISSUE TITLE
Repository setup progressbar hangs at "Importing starter code..."

### ISSUE THREAD

**Issue by hroncok** [education/classroom#1636]
**Describe the bug**
The repository setup progressbar when clicking on assignment link hangs forever.

**To Reproduce**
1. Go to classroom.github.com
2. In a classroom, create a new (individual) assignment
3. Use **Add your starter code from GitHub**
4. Make sure to **Enable assignment invitation URL**
5. Later, click on the assignment invitation URL and follow the steps

**Expected behavior**
After the repo is created, you are redirected to it or see a message that says where you should continue.

**Screenshots**

Hangs here. Repo is created, but the progressbar just hangs. Reproduced in Chromium, but probably also happens in Firefox.

![_](https://user-images.githubusercontent.com/2401856/46615272-1a8e7f00-cb18-11e8-9d87-9c6dffd2bda9.png)

cc @syky27 @mmajko @Hanyman8

**Comment by syky27** [comment]
Reproduces in Firefox and Safari.

**Comment by syky27** [comment]
Duplication of https://github.com/education/classroom/issues/1623

**Comment by BenEmdon** [comment]
Thanks for writing in 👋 
We have escalated this issue to the source imports team. 
This problem occurs when there is a high demand on the source import infrastructure, unfortunately it happens sporadically.

**Comment by BenEmdon** [comment]
The source import team is working on scaling their infrastructure. In the meantime, I would suggest trying the assignment creation process again (by going back to your invitation link).

If that doesn't work for you, please report back in on this issue.

**Comment by hroncok** [comment]
The import works fine. It's just that the progressbar gets stuck. The repo is created and has the proper content.

**Comment by BenEmdon** [comment]
> The import works fine. It's just that the progressbar gets stuck. The repo is created and has the proper content.

Interesting 🤔 
Would you mind looking at:
https://github.com/organizations/3dprintfit/settings/hooks

Do you see this symbol?
> <img width="30" alt="screen shot 2018-10-09 at 6 02 16 pm" src="https://user-images.githubusercontent.com/11095731/46701438-ac1bf080-cbed-11e8-9517-889b26e61b47.png">

**Comment by hroncok** [comment]
I see one webhook, not classroom, it pings fine (has check mark). I see no classroom related webhook at all. Maybe we need to (re)add it?

**Comment by BenEmdon** [comment]
That seems very unusual. I'll get my team to investigate. Thanks for providing that information 👏

**Comment by johndbritton** [comment]
@hroncok Can you give this another go? Your webhooks should be configured correctly and the issue should be resolved.

We'll roll out the fix to other effected organizations asap.

**Comment by johndbritton** [comment]
> Reproduced in Firefox and Safari.

@syky27 Can you also try this and see if you're still facing the same issue?

**Comment by johndbritton** [comment]
I'm pretty sure this is resolved, so I'm closing the issue but please reopen if you are still facing the same problem.

**Comment by hroncok** [comment]
I see a GitHub Classroom hook now. The progressbar now goes to the end just fine. This is indeed fixed.

Thank You very much!

**Comment by syky27** [comment]
@johndbritton @BenEmdon Yeah, awesome quick fix, thank you guys!

**Comment by macaines** [comment]
Still having this problem......starter code progress bar gets nearly to the end and then it retracts to the beginning and tries again endlessly. Firefox 66.0.3

**Comment by johndbritton** [comment]
@macaines this is likely specific to your account, please email `education@github.com` with reference to this issue.

They probably need to configure hooks on your account.

**Comment by katriendeleu** [comment]
I have a student with the same problem: .starter code progress bar gets nearly to the end and then it retracts to the beginning and tries again endlessly, no matter what browser she uses.
