### ISSUE TITLE
Problem authenticating with GitHub

### ISSUE THREAD

**Issue by Ololoshechkin** [education/classroom#1645]
I am trying to access https://goo.gl/GdnT5A (classroom link suggested by my teacher) and I always get
"There was a problem authenticating with GitHub, please try again." message. 
What is the workaround to fix this?

Thanks in advance

<img width="1090" alt="screen shot 2018-10-11 at 17 05 42" src="https://user-images.githubusercontent.com/24360128/46809793-f16c2980-cd77-11e8-92fd-f151103b491b.png">

**Comment by BenEmdon** [comment]
@Ololoshechkin thanks for reporting this.
@johndbritton @srinjoym Have we seen this before? Any idea on what might be causing this?

**Comment by BenEmdon** [comment]
Clicking that link you shared, worked for me (I was able to successfully create an assignment).
@Ololoshechkin Have tried again after this first occurrence?

**Comment by johndbritton** [comment]
This seems to have been a temporary issue. @Ololoshechkin please try again and reopen if you're still facing issues.
