### ISSUE TITLE
Duplicate GitHub Repositories

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom#1646]
So recently it has been reported that classroom is creating duplicate assignment repositories.
Related issues:
- https://github.com/education/classroom/issues/1586 
- https://github.com/education/classroom/issues/1462 
- https://github.com/education/classroom-assistant/issues/110

One source of this problem is that we have the following logic:
https://github.com/education/classroom/blob/c5aaa8af44d0b94d58b97de446dc777ab79d66f3/app/models/assignment_repo/creator.rb#L200-L223

## Questions for the team
* Should we instead not generate a suffix when a GitHub repository of the intended name already exists? 
* Is it possible to have conflicting repository names?

CC team: @d12 @tarebyte @johndbritton @srinjoym

**Comment by johndbritton** [comment]
@BenEmdon The suffixing code above isn't the _cause_ of the duplicate repositories, it's just the way that Classroom handles the case.

This code should not be called if the repository creation process is working correctly. If the repo creation process fails, it should clean up the repository it created. The only way this code would run is if a repository creation failed during import or granting access to the user AND the creator did not successfully clean up the unfinished repository.

My suggestion is to investigate the code that is creating the repositories and ensure that the cleanup code is being executed.

One path to follow would be to investigate the specific instances where duplicate repositories have been created and try to reproduce the issue.

**Comment by BenEmdon** [comment]
In https://github.com/education/classroom/issues/1462 I checked to see if each duplicate GitHub repo had an associated `AssignmentRepo` and I found that there were two assignment repos for the same `<User, Assignment>` key.


```
PRODUCTION [2] pry(main)> a1 = AssignmentRepo.find_by(github_repo_id: 142300727)
D, [2018-10-15T19:22:26.217594 #4] DEBUG -- :   AssignmentRepo Load (1.2ms)  SELECT  "assignment_repos".* FROM "assignment_repos" WHERE "assignment_repos"."github_repo_id" = $1 LIMIT $2  [["github_repo_id", 142300727], ["LIMIT", 1]]
=> #<AssignmentRepo:0x0000000008381eb0
 id: 741547,
 github_repo_id: 142300727,
 repo_access_id: nil,
 created_at: Wed, 25 Jul 2018 13:02:41 UTC +00:00,
 updated_at: Wed, 25 Jul 2018 13:02:41 UTC +00:00,
 assignment_id: 32794,
 user_id: 146696,
 submission_sha: nil,
 github_global_relay_id: "MDEwOlJlcG9zaXRvcnkxNDIzMDA3Mjc=",
 configuration_state: "not_configured">
PRODUCTION [3] pry(main)> a2 = AssignmentRepo.find_by(github_repo_id: 142668458)
D, [2018-10-15T19:22:54.993108 #4] DEBUG -- :   AssignmentRepo Load (1.4ms)  SELECT  "assignment_repos".* FROM "assignment_repos" WHERE "assignment_repos"."github_repo_id" = $1 LIMIT $2  [["github_repo_id", 142668458], ["LIMIT", 1]]
=> #<AssignmentRepo:0x00000000083c57f0
 id: 742859,
 github_repo_id: 142668458,
 repo_access_id: nil,
 created_at: Sat, 28 Jul 2018 10:28:55 UTC +00:00,
 updated_at: Sat, 28 Jul 2018 10:28:55 UTC +00:00,
 assignment_id: 32794,
 user_id: 146696,
 submission_sha: nil,
 github_global_relay_id: "MDEwOlJlcG9zaXRvcnkxNDI2Njg0NTg=",
 configuration_state: "not_configured">
```

**Comment by BenEmdon** [comment]
> @johndbritton The suffixing code above isn't the cause of the duplicate repositories, it's just the way that Classroom handles the case.

Why should we continue to suffix GitHub repositories? What is the use case for suffixing them?

If we don't suffix GitHub repositories, then we can treat the repository names as a source of truth. 
This means that if a repo already exists, something has gone terribly wrong and we shouldn't allow anyone to create a second GitHub repository.
