### ISSUE TITLE
Repo setup stuck at assignment acceptance

### ISSUE THREAD

**Issue by ProfKolta** [education/classroom#1654]
**Describe the bug**

**To Reproduce**
1. Go to https://classroom.github.com/assignment-invitations/91340792943671c7b9a688078065dffd
2. Click on 'accept this assignment
the click registers but it remains on the same page, essentially nothing happens...

**Expected behavior**
I would be moved to the first part of the first tutorial

**Screenshots**

**Additional context**

**Comment by BenEmdon** [comment]
Hey @ProfKolta, thanks for writing a detailed bug report. I should be able to unstick your assignment for you.

I checked the progress at https://classroom.github.com/assignment-invitations/91340792943671c7b9a688078065dffd/progress and got:
```json
{
  "status" : "unaccepted",
  "repo_url" : "https://github.com/Campus-Advisors/module-0-welcome-ProfKolta"
}
```
So it looks like you have a repo! (https://github.com/Campus-Advisors/module-0-welcome-ProfKolta)  Mind checking if that repo is populated with content?
Weird that it ended up in this state 🤔

**Comment by BenEmdon** [comment]
@ProfKolta I went ahead and unstuck your assignment. You can access it via: 
https://classroom.github.com/assignment-invitations/91340792943671c7b9a688078065dffd
