### ISSUE TITLE
Repositories missing

### ISSUE THREAD

**Issue by TianXieUSC** [education/classroom#1661]
**Describe the bug**
After students created their repositories and committed. Some students' repositories in the classroom are missing and some are repeating.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BenEmdon** [comment]
Hey thanks for writing in.
This appears to be a duplicate #1659

**Comment by TianXieUSC** [comment]
Do you have any solutions? Have you fixed the issue and can I recover the
classroom repositories?

Best
Tian

**Comment by BenEmdon** [comment]
I have been debugging and should have a fix up soon!

**Comment by BenEmdon** [comment]
Mind checking back? The fix has been deployed!

**Comment by TianXieUSC** [comment]
I think my problem has been solved. Thanks!

Tian
