### ISSUE TITLE
Classroom landing page not working

### ISSUE THREAD

**Issue by caw13** [education/classroom#1663]
**Describe the bug**
Trying to access the classroom landing page via either https://classroom.github.com/ or https://classroom.github.com/classrooms results in 500 internal server error 

**To Reproduce**
Be already authenticated go to https://classroom.github.com/classrooms, results in 500 internal server error.

Can also recreate by accessing https://classroom.github.com in a new browser session, after prompting to authenticate on successful authentication, results in 500 internal server error.

**Expected behavior**
Expect to show the list of organizations that have been registered as classrooms

**Screenshots**
![image](https://user-images.githubusercontent.com/10552669/47128133-11ab5500-d25e-11e8-97fd-0030bb5655d8.png)

**Additional context**
Note clicking on the "Try going back to classroom dashboard" on the error page redirects back to the same URL and 500 internal server error

**Comment by BenEmdon** [comment]
Thanks for reporting this!

This seems to be related to https://haystack.githubapp.com/classroom/rollups/1ddf8567c0a6be4c3dc02b9ce7a6f8e9
https://haystack.githubapp.com/classroom/rollups/fa5d1a28578eb52913dd7c01a391731e 

@srinjoym looks like you introduced the token error at:
https://github.com/education/classroom/blob/60d3f87e62c2b3ade4cf5d96dc62ad883b643f1f/app/models/organization.rb#L48

**Comment by BenEmdon** [comment]
Hey @caw13 mind talking a look now? We just reverted a change.

**Comment by caw13** [comment]
@BenEmdon The landing page is working once again.  Thank you!

**Comment by BenEmdon** [comment]
Awesome, glad to hear 🎉
