### ISSUE TITLE
Mixin of Github and Classroom polluting github accounts.

### ISSUE THREAD

**Issue by yanntm** [education/classroom#1678]
**Describe the bug**
A teacher using classroom sees *all* the student repositories *all the time* in GitHub.
Teaching is a specific activity, separate from "normal" github use. 
These repositories and accounts should only be visible in github after specifically logging in through/doing a procedure from the ClassRoom interface, i.e. the place we sent the invitations to create private repos in the first place.

At the minimum we need a global "filter all ClassRoom related" on personal setting of github profile or something, so teachers can also do research.

I realize this is an interaction between how ClassRoom uses github to mascarade teaching into a git image. It is still a messy bug in the sense that I would need to open a second github account specifically for teaching at this stage, but I like my account.

**To Reproduce**
1. Use github for normal github usage : develop open source
2. Enroll into classroom
2. Click on 'Send Assignment Link' to about 100+ students, 3 weeks in a row
3. Add a github filter to your mailbox
4. Connect to github, try to find any of your repositories in the "repos" search box.
5. Admire the fact the bar is trailing off screen

**Expected behavior**
These accounts/repositories should not be visible under github unless I explicitly am doing "teaching/grading", i.e. accessing github through ClassRoom provided links.

**Screenshots**
see attached
![bugclassroom](https://user-images.githubusercontent.com/15147867/47394329-ca700900-d722-11e8-875e-12702a48d595.png)

**Additional context**
I have a lot of students.

**Comment by BenEmdon** [comment]
Hey @yanntm, this is behavior is managed in GitHub.com and therefore we are not the best place report this to. The best you can do is contact GitHub support about this https://github.com/contact.

**Comment by yanntm** [comment]
I feel I am not the one that has to setup collab with github services to get them to ackowledge problem, from my pov it comes from use of ClassRoom not github.You're all the same company, sort it out, or not and we look for service elsewhere.

**Comment by johndbritton** [comment]
@yanntm GitHub Classroom is built on the GitHub API, it does not alter the functionality of github.com.

When you connect an organization to Classroom, we automatically create student repositories for you from your GitHub account.

As such, all of the repositories will be visible from your GitHub account.

While I understand why you might want this, it is not something that we can change.
