### ISSUE TITLE
Logout button missing on invitation pages

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#168]
When navigating to a unique invitation url there's no link to log out.

<img width="259" alt="screen shot 2015-09-02 at 3 58 31 pm" src="https://cloud.githubusercontent.com/assets/123345/9634862/7dbf3042-518b-11e5-801d-618b9f67074f.png">

**Comment by tarebyte** [comment]
That was by design, is there a reason they need to logout?

**Comment by johndbritton** [comment]
I think we should always give them the option to log out.

In my case, I wanted to log out to use a different account for testing.
