### ISSUE TITLE
500 Internal server errors in very large group assignments

### ISSUE THREAD

**Issue by kevinlin1** [education/classroom#1682]
**Describe the bug**
When students attempt to visit the assignment invitation link for a group assignment, the application often gives a 500 Internal server error. Occasionally, after refreshing several times, the page will eventually load which suggests that the application is sometimes timing out on the request.

**To Reproduce**
Visit <https://classroom.github.com/g/WrZUiXxO>. It often (but not always) results in a 500 Internal server error.

**Expected behavior**
The signup listing of existing groups for the assignment with options to join an existing team or create a new team.

**Additional context**
We are using GitHub Classroom to serve a very large classroom of about 900 students working in teams of up to 2 students. There may be on the order of 500 team repositories. I suspect that increasing the server timeout or improving the performance of the request will resolve the problem.

**Comment by BenEmdon** [comment]
@kevinlin1 The issue has been resolved! You can confirm by going to your assignment at https://classroom.github.com/group-assignment-invitations/f0ded2634591597e67f1e52912ecb637?roster=ignore
