### ISSUE TITLE
Tag or commit for starter code repo

### ISSUE THREAD

**Issue by winterer** [education/classroom#1698]
### Feature request :sparkles:
It would be helpful if the teacher could specify a tag (or commit) of the starter code repo when creating a new assignment. This tag (or commit) will then be used as HEAD for the cloned student repos.

**Comment by ejgutierrez74** [comment]
But you can create a repo with initial commit or tag, and then use that repository as starter code ( repo) to students.....At least i ve done this way....

**Comment by winterer** [comment]
Yes sure, but it is not possible to fix the assignment to this tag - if a student accepts the assignment, the HEAD of master will be copied.
But: In the meantime I'm pretty happy with this "sliding" behavior, as it allows me to do some minor fixes on the starter code repo after creating the assignment (but before sending the link to the students).
