### ISSUE TITLE
Use a spinner when waiting for an invite link

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#170]
I've seen this case a couple times:

<img width="996" alt="screen shot 2015-09-02 at 4 16 56 pm" src="https://cloud.githubusercontent.com/assets/123345/9635487/9bef2d94-518e-11e5-956a-1b648d5ba0de.png">

> Hang tight your students invitation is on the way!

It'd be better to wait or display a spinner so that the link is immediately available.

**Comment by tarebyte** [comment]
Currently creating the invitation is a background job which is why that message is there. I don't think it has to be the case though since it's not very memory heavy.

**Comment by johndbritton** [comment]
:cool: Yeah, I don't think a background job is necessary here.
