### ISSUE TITLE
Too many redirects error on group assignment

### ISSUE THREAD

**Issue by mozzadrella** [education/classroom#1704]
**Describe the bug**

When teachers attempt to accept [the team assignment](https://classroom.github.com/group-assignment-invitations/d6781417e41ebad9dfde584fbba07f6b) for Campus Advisors they get an error showing too many redirects.

**To Reproduce**
1. Go to '...'https://education.github.com/teachers/advisors
2. Click on '....'Module 3 Group work
3. Scroll down to '....'Wait to accept assignment

**Expected behavior**

Accept a group assignment and choose a team.

**Screenshots**

![screenshot 2018-11-20 08 39 16](https://user-images.githubusercontent.com/1874003/48777174-e45c2780-ec9f-11e8-806f-97cfbbea11a4.png)

**Additional context**

cc @ccannon94

**Comment by BenEmdon** [comment]
## Notes from investigating:
* the assignment is marked as `unaccepted`
* the assignment repo exists

Will reproduce and submit a fix soon 🛠

**Comment by BenEmdon** [comment]
Proposed a fix in #1720

**Comment by BenEmdon** [comment]
Apologies for the lengthy wait 😅 Just merged a fix for this! 

@ccannon94 if you got to your [assignment invitation link](https://classroom.github.com/group-assignment-invitations/d6781417e41ebad9dfde584fbba07f6b), all should work as expected!

Please reopen this if you feel that the issue hasn't been resolved!

**Comment by ccannon94** [comment]
Confirmed error no longer occurs! thanks so much @BenEmdon
