### ISSUE TITLE
i cant join a class on github even though i have a code

### ISSUE THREAD

**Issue by nikhilvicctor** [education/classroom#1717]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by BenEmdon** [comment]
Hey @nikhilvicctor sorry to hear about your issue. Would you mind providing the following information:
* the link of the assignment you were given
* a screenshot of the error you saw

Also would you mind clarifying what you mean by:
>  even though i have a code

Do you have access to the repo on GitHub? If so, what is the url to the repo?

**Comment by BenEmdon** [comment]
This issue doesn't provide enough information. I am going to go ahead and close the issue for now. @nikhilvicctor please reopen this issue if you are still affected and have some more information to help us debug.
