### ISSUE TITLE
Roster management Page is too slow

### ISSUE THREAD

**Issue by AhmedKamal20** [education/classroom#1726]
When opening the roster page while you have a lot of unlinked users it will take a lot of time loading 
It takes around 30-45 Seconds with me.

I tracked what is causing this delay and found that the issue is on this line below:

https://github.com/education/classroom/blob/6d3fa4663268345a264a0e77e031eb0da81471ca/app/views/orgs/rosters/_link_to_github_account_modal.html.erb#L14

It's not a bug but the way its done now slow things down. 
It have to connect to github.com for every unlinked user.

What do you think?

**Comment by BenEmdon** [comment]
@AhmedKamal20 good catch! This appears to be a typical n+1 request. I will create the tag `slow request` so we can keep a tab on these pain points.

**Comment by EricPickup** [comment]
I've been looking into this - It seems that the cache is working properly and we are making a request to github's API for each user only _once_ since the user info is cached. This is necessary for us to list the `login` (handle) of each unlinked user. We do the same request for linked users.

**Comment by d12** [comment]
This instance of loading GitHub data is especially bad because it's happening before we render the view, most of our other GitHub API requests are in AJAX requests and have less of an effect on UX. 

@AhmedKamal20 I'm working on https://github.com/education/classroom/pull/1964 which will fix this problem.

**Comment by d12** [comment]
@AhmedKamal20 Could you try your roster page again and see if this has made it better? I've shipped a fix for the `user.github_user.login` bit, and I'm digging into some performance issues on the assignment page now.

**Comment by d12** [comment]
I tried this out on a class of over 1000 and it seems to be working a lot better now. I'll close this out, but please re-open if you're still having issues.

**Comment by AhmedKamal20** [comment]
@d12 Yeah, it's a lot faster than before, especially after the first time

Thank you.

**Comment by d12** [comment]
Glad to hear. That first time slowness is because of how the cache is implemented, you should be good to go now that the caches are warmed. Thanks for the issue!
