### ISSUE TITLE
Github Actions in starter code makes import fail

### ISSUE THREAD

**Issue by maxsumrall** [education/classroom#1728]
**Describe the bug**
Importing starter code step fails when starter code contains Github Actions.

**To Reproduce**
1. Create classroom assignment 
2. Choose a base assignment (the starter code) which contains any simple Github Actions workflow.
3. Give assignment link to students
4. During "Import starter code" step, the process fails with "Errored". 

**Expected behavior**
A new respiratory with starter code contained in the new repository. 

**Additional context**
We've been using classroom successfully for a few weeks now. I wanted to add a Github Actions workflow that simple does a compile check. However, any Github workflow, even a minimal example, also fails. 

If I check Setting > Webhooks > Github Classroom > Recent Deliveries, there are the events corresponding with creating the new repo for the student. However the event `X-GitHub-Event: repository_import` has in the beginning of the payload `"status": "failure",`.

If I remove the workflow from the starter code, the import process works correctly. 

**Extra info**

Example simple workflow that causes import to fail:
```
workflow "New workflow" {
  on = "push"
  resolves = ["Filters for GitHub Actions"]
}

action "Filters for GitHub Actions" {
  uses = "actions/bin/filter@b2bea07"
}
```

Example starter code:
<img width="516" alt="problem_starter_repo" src="https://user-images.githubusercontent.com/628843/50631065-54b6c380-0f43-11e9-9335-7105e2c48d09.png">

Assignment config:
<img width="551" alt="github_classroom-2" src="https://user-images.githubusercontent.com/628843/50631094-7152fb80-0f43-11e9-8a23-8ac890ce1101.png">

When someone accepts invitation:
<img width="1047" alt="github_classroom" src="https://user-images.githubusercontent.com/628843/50631106-8039ae00-0f43-11e9-9f02-8fdb1f5428ac.png">

Another view:
<img width="585" alt="picnicnext_work-in-progress-test-maxsumrallpicnic__importing" src="https://user-images.githubusercontent.com/628843/50631122-8b8cd980-0f43-11e9-9e81-a961aad20523.png">

**Comment by BenEmdon** [comment]
Hey @maxsumrall ,

I have notified the appropriate teams about this issue. 
I'll report back with updates when I hear them. 

Excited to see Classroom users picking up GitHub actions!

**Comment by BenEmdon** [comment]
Just spoke with the GitHub Actions team and they said that integrations (OAuth apps like GitHub Classroom) are restricted from creating/writing/editing the `.github/main.workflow` file. This restriction is in place for the purpose of security. 

At the time we are unsure if this restriction will loosen up, as it is still the early days of GitHub Actions. 

I'm locking and closing this issue for now.
