### ISSUE TITLE
not receiving notifications

### ISSUE THREAD

**Issue by kyleiwaniec** [education/classroom#1729]
**Describe the bug**
I am no longer receiving notifications when students click the assignment link to create their repos in my classroom

**To Reproduce**
1. create an assignment
2. send auto generated link to student
3. student clicks the link and a repo is created as expected
4. I used to get an email notification when this was completed. I no longer receive any notification.

**Expected behavior**
An email should be sent to my email address notifying me that a student repo was created

**Screenshots**
Until today, the notification looked like this:
![image](https://user-images.githubusercontent.com/840903/50700976-ffaea680-1043-11e9-912b-8a084d041f27.png)

**Comment by yanntm** [comment]
can I ask for the opposite ? ie. that the mail and notification come from ClassRoom and be configurable, but *NOT* from github proper ?

**Comment by BenEmdon** [comment]
@kyleiwaniec It appears as if GitHub.com no longer sends these email notifications. If these notifications are important to your workflow [contact support](https://github.com/contact), as they are better equipped to assist you.

@yanntm If you have a feature request please open a new issue.

I am closing this and locking this as this issue relates to GitHub notifications which aren't worked on by the classroom team. If you have problems with notifications please [reach out to GitHub support](https://github.com/contact).
