### ISSUE TITLE
Importing starter code hangs

### ISSUE THREAD

**Issue by mhrmm** [education/classroom#1731]
Possibly related to #1623 or #1616. 

Importing starter code takes an interminable length of time when accepting an assignment.

Here is the invitation link for repro:
https://classroom.github.com/a/zidPHJ4R

**Comment by BenEmdon** [comment]
@mhrmm I have gone ahead and unstuck your assignment. Go to the assignment invitation link to see: https://classroom.github.com/a/zidPHJ4R.

Apologies for the wait! Please reopen this issue if experience any more problems related to this.

**Comment by mhrmm** [comment]
Thanks!
