### ISSUE TITLE
Stuck on importing starter code when accepting assignment

### ISSUE THREAD

**Issue by sethanderson8** [education/classroom#1732]
**Describe the bug**
When I accept my professors assignment, it creates the repository but ends up being stuck on the import starter code bar

**To Reproduce**
1. Go to https://classroom.github.com/a/jh95IfbH
2. Click on Accept Invite
3. See error. Stuck on import starter code

**Expected behavior**
It is meant to create the repo and import the starter code.

**Comment by BenEmdon** [comment]
This appears to coincide with the [outage on January 9th](https://status.github.com/messages/2019-01-09). In the next day or two I will go ahead and unstick your assignment.

**Comment by BenEmdon** [comment]
@sethanderson8 I have gone ahead and unstuck your assignment. Go to the assignment invitation link to see: https://classroom.github.com/a/jh95IfbH.

Apologies for the wait! Please reopen this issue if experience any more problems related to this.

**Comment by sethanderson8** [comment]
Thank you so much for your help but now when I open the invitation. It doesn't even begin to create the repository. It is completely stuck with no bars moving at all

**Comment by BenEmdon** [comment]
@sethanderson8 would you mind going to the assignment link and recording a screenshot? Just so we can get an idea of what you are seeing?

**Comment by sethanderson8** [comment]
It worked this morning!
