### ISSUE TITLE
Student repositories not being created

### ISSUE THREAD

**Issue by zerbash** [education/classroom#1738]
**Describe the bug**
The students accept the invitation, but the screen errors out trying to create repositories.

**To Reproduce**
1. Go to https://classroom.github.com/a/fmUJguaJ
2. Log in
3. Watch the process go from green to red.

**Expected behavior**
A private repository created on the student's account

**Screenshots**
![screen shot 2019-01-15 at 6 12 51 pm](https://user-images.githubusercontent.com/19747758/51222171-6c059180-18f1-11e9-8600-007da649050a.png)

**Comment by zerbash** [comment]
Ah... Googling that error turns up the source code...  No private repositories.  Do "classrooms" not get private repositories by default?

**Comment by BenEmdon** [comment]
@zerbash organizations don't get private repositories by default. The good news is that GitHub gives free private repositories to organizations for education purposes. Have you signed your institution up yet at https://education.github.com?

**Comment by zerbash** [comment]
Yes, but apparently I got lost somewhere along the way and created a new _organization_ for the classroom. Went through the steps again with my original organization, and it seems to be working now. Thanks!
