### ISSUE TITLE
Students can't create repository

### ISSUE THREAD

**Issue by Wind4Greg** [education/classroom#1739]
**Describe the bug**
Using the assignment link: https://classroom.github.com/a/tbEi0vGr

Students repeatedly get the: `GitHub repository could not be created, please try again` error

**To Reproduce**
1. Go to link: https://classroom.github.com/a/tbEi0vGr
2. Wait and see error

**Expected behavior**
Student repo creation

**Screenshots**
![image](https://user-images.githubusercontent.com/1444268/51271848-753c4000-197d-11e9-9036-f03a2fb62ea1.png)

**Additional context**
Things worked fine last semester for me.

Cheers
Greg B.

**Comment by BenEmdon** [comment]
I investigated what was going on under the hood and found the following error:
```
422 - Visibility can't be private. Please upgrade your plan to create a new private repository. // See: https://github.com/pricing
```

GitHub organizations don't get private repositories by default. The good news is that GitHub gives free private repositories to organizations for education purposes. Have you signed your institution up yet at https://education.github.com?

**Comment by Wind4Greg** [comment]
Hi Ben, yes I got a grant for this semester. Note that I have two emails on my account my usual email: gregb@grotto-networking.com, and my academic email: greg.bernstein@csueastbay.edu.

This is a screen shot of the email I received at my academic account:

![image](https://user-images.githubusercontent.com/1444268/51286359-8306bb00-19a7-11e9-8cce-45e98f9fe131.png)

It didn't seem any different from last semester.  Please advise on next steps.
Thanks

Greg B.

**Comment by BenEmdon** [comment]
@Wind4Greg yesterday we checked which plan your organization is on, and it was still on the "free" plan. You can confirm this by going to https://github.com/organizations/CSUEB-CS351-Spring2019/settings/billing. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.
