### ISSUE TITLE
GitHub classroom - repo cannot be created

### ISSUE THREAD

**Issue by msalloum** [education/classroom#1740]
i created a github classroom and gave students link. Each time they try to use link to create repo, they get an error.

**Comment by BenEmdon** [comment]
Hey @msalloum 👋 

Your issue description doesn't provide us enough information to help you.

Could you please provide: 
* the assignment invitation link
* a screenshot of the error your students are experiencing

**Comment by msalloum** [comment]
Thank you for the reply. Attached is the snapshot of the error.

Here is the repo: https://github.com/CS172-UCR/PS1

Find the invite link to Github Classroom here:
https://classroom.github.com/a/n4qYsrML

**Comment by BenEmdon** [comment]
I just checked your organization (https://github.com/CS172-UCR) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/CS172-UCR/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories. 

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.

**Comment by msalloum** [comment]
Hi Ben,

I had signedup for github education more than 2 weeks ago. I created a new
assignment here:
https://classroom.github.com/assignment-invitations/549da1cfa3a4896471a8c57496d2af8a/setup

But i'm having the same issue as last time. Since i requested education
account for @msalloum shoudn't this work this time around?

**Comment by BenEmdon** [comment]
Hey @msalloum, you need to request an education discount for your organization (https://github.com/CS172-UCR). 

Here's a guide on what you need to do https://help.github.com/articles/applying-for-a-classroom-discount/

**Comment by msalloum** [comment]
Thank you for your response, but i believe I did this last time.

Is it possible my other account has this access:
https://github.com/organizations/UCR-ComputerScience/settings/profile
I know i went through this process last time

**Comment by msalloum** [comment]
So on the site it states: Once your application has been reviewed and you
receive an email notifying you that your GitHub Education individual
faculty membership has been approved, you may return to
https://education.github.com to upgrade your GitHub organizations used for
academic purposes.


So how do i do this step?
