### ISSUE TITLE
Error creating assignment repository

### ISSUE THREAD

**Issue by ArthVader** [education/classroom#1741]
**Describe the bug**
Creating the Assignment was successful and I was provided an invitation link. I decided to test this link to see if I could properly create an assignment repository using the link. When attempting to do this, an error arises with no further details other than retrying. I have attempted to retry many times with the progress bar going further and further but never completing. The assignment settings were set to create Private Repositories and this seems to be the problem because when I test the exact same settings with the settings set to Public Repositories everything works. I have also been Approved under GitHub Education to create Private Repositories.

**To Reproduce**
1. Go to https://classroom.github.com/a/DWiTm1gJ
2. Accept the Assignment
3. See error Message

**Expected behavior**
I expected an Assignment Repository that was Private to be created for each student that accepts the Assignment Invitation. Instead an error message arises. 

**Screenshots**
<img width="1440" alt="screen shot 2019-01-17 at 11 32 33 am" src="https://user-images.githubusercontent.com/11413805/51405866-83c55b80-1b25-11e9-8ad1-b1bd4e8e435b.png">
<img width="1440" alt="screen shot 2019-01-17 at 11 32 45 am" src="https://user-images.githubusercontent.com/11413805/51405880-8aec6980-1b25-11e9-9f63-2efca0070a30.png">
<img width="1440" alt="screen shot 2019-01-17 at 11 27 06 am" src="https://user-images.githubusercontent.com/11413805/51405907-99d31c00-1b25-11e9-8659-c2615e4a4582.png">
<img width="1440" alt="screen shot 2019-01-18 at 1 33 19 pm" src="https://user-images.githubusercontent.com/11413805/51405922-a3f51a80-1b25-11e9-9315-daf1632415ed.png">

**Additional context**
I am a Teaching Assistant for a course at my University and my Professor and I are trying to setup an assignment for our students to use. We setup an assignment test where students simply go to a provided invitation link and a repository is setup for them within our classroom organization. For the test we allowed for the use of public repositories, I sent the students the invitation link and everything worked as intended. Now that we are setting up a real assignment for them, we want to set up the assignment to use private repositories so that students do not have access to each others code. I created the assignment and clicked the checkbox for the assignment to use private repositories, this was the only different setting setup. We also provided the students with starter code from a repository of mine. Creating the Assignment was successful and I was provided a invitation link. I decided to test this link to see if I could properly create an assignment repository using the link. When attempting to do this, an error arises with no further details other than retrying. I have attempted to retry many times with the progress bar going further and further but never completing.

**Comment by BenEmdon** [comment]
@ArthVader Thank you from writing such a detailed issue ✨ 

I just checked your organization (https://github.com/FSU-ComputerGraphics) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/FSU-ComputerGraphics/settings/billing.

I see from your final screenshot that you signed your _user_ account up for the student developer pack. To fix this issue you must sign up your _organization_ to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.
