### ISSUE TITLE
Problem when trying to accept assignments

### ISSUE THREAD

**Issue by ana-romero** [education/classroom#1742]
I'm new in github education and I plan to use it with my students the following semester. For the moment I have created a classroom called "EDSS1819" and several assignments but when I send the link to an account supposed to be a student I get the error "Creating repository Errored" and the repository is not created. I have tried with different accounts and different assigments. Thank you very much for your help.

**Comment by JoshuaJB** [comment]
I created a classroom for testing and played around with all the assignment settings to see if I could find some way in which repository creation works, and it seems like the only way is by setting the assignment repositories to be public. Maybe there's some internal issue around the recent switch to unlimited free private repositories which is causing problems?

**Comment by BenEmdon** [comment]
@ana-romero I just checked your organization (https://github.com/EDSS1819) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/EDSS1819/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories.

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.

**Comment by BenEmdon** [comment]
@JoshuaJB I also checked your organization (https://github.com/comp524-s19) and yours is also on the "free" plan. You can confirm this by going to https://github.com/organizations/comp524-s19/settings/billing.

To fix this issue see my comment above ☝️
