### ISSUE TITLE
"no seat user" when joining assignment

### ISSUE THREAD

**Issue by gbrain** [education/classroom#1743]
**Describe the bug**
When Students attempt to join an assignment, they get a validation error: "TeamMember: no seat user"

**To Reproduce**
I'm not sure what if any of the following steps caused this error, but this is my journey
1. Setup a Classroom on a Free Account
2. Upgrade to a paid account
3. Create a new private repo on paid account
4. Convert private repo to a public repo
5. make an assignment from newly public'ed repo
6. Via and incognito window, login to github as a student
7. Attempt to join the assignment either by creating a new team, or joining an existing one.
8. Notice the Validation error:  TeamMember: no seat user

**Expected behavior**
Expect to join the Team and Assignment

**Screenshots**
https://screencast.com/t/FdAyrcIn

https://screencast.com/t/93QAWqwPl

**Additional context**
From this invite: https://classroom.github.com/g/Vf8AI0WO

Note, that I attempted to create a private repo, and make a private assignment first, when I encountered the same error.  I assumed that this was because I am at my limit for users on my paid Github account that the Classroom is associated with.  So I converted the repo to public, and created a new public assignment, and am experiencing the same behavior.

Also note that I was able to join as a student to assignments before I converted classroom account to a paid account.  Now that it is a paid account, I can not join any assignments in any configuration.

**Comment by BenEmdon** [comment]
I just checked your organization (https://github.com/LEARNAcademy) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/LEARNAcademy/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories. 

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.
