### ISSUE TITLE
Students cannot accept assignments for private repositories

### ISSUE THREAD

**Issue by malziagalvani** [education/classroom#1746]
**Describe the bug**
If I create a new individual assignment and set it as private the students get the message "GitHub repository could not be created, please try again"
If I create the same assignment with a public repository everithings works well

**To Reproduce**
1. Create a individual assignment with  a private repositorie
2. Give the link to a student account
3. The student click on the link
4. The student get the error message

**Screenshots**
![capture](https://user-images.githubusercontent.com/45386801/51759503-aa0c6d80-20c8-11e9-9683-752ef28a43bf.JPG)

**Additional context**
The student has a free plan account, I'm wondering if they need to join the git hub education

This is an example assignment:
https://classroom.github.com/a/eB0Jsp8E

**Comment by BenEmdon** [comment]
I just checked your organization (https://github.com/iisgalvanimi) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/iisgalvanimi/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories.

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).
I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.
