### ISSUE TITLE
Classroom Assistant could not find assignment

### ISSUE THREAD

**Issue by eoershova** [education/classroom#1748]
**Describe the bug**
Cannot download repos via Classroom Assistant

**To Reproduce**
1. Go to https://classroom.github.com/classrooms/42267123-2018-2019/assignments/hw11-2
2. Click on Download Rep
3. Wait for Assistant to launch

**Expected behavior**
repos get downloaded 

**Screenshots**
 
![image](https://user-images.githubusercontent.com/35444491/51908534-2a89e180-23db-11e9-9059-e4401a52f240.png) 
**Additional context**

**Comment by Braythor** [comment]
Hi there @eoershova 👋, thanks for reporting this issue. When clicking on your link, it gives me a 404, are you sure that link is valid? The reason Classroom Assistant is giving you that error is because it probably got a 404 too.

**Comment by eoershova** [comment]
Hey there!
Apparently it is, I rebooted my laptop twice and after the second time managed to download the assignment via the link

Thanks for your answer anyway, I wasn’t really expecting one
King regards,



Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by Braythor** [comment]
Hello @eoershova! Since there isn't any activity on this issue, and it seems as if you resolved it, I'd invite you to close the issue, so we don't get confused by this open issue.

**Comment by eoershova** [comment]
Thanks for you response again!
