### ISSUE TITLE
GitHub Classroom Assignment Setup Fails for Students

### ISSUE THREAD

**Issue by youngwghs** [education/classroom#1749]
**Describe the bug**
The error occurs when students accept the assignment and the repository is being imported.

**Expected behavior**
The repository would be imported successfully for each student after being accepted.

**Screenshots**
![github error](https://user-images.githubusercontent.com/19416141/51928922-9f99ee80-23bc-11e9-85a5-25330935b1f8.png)

**Additional context**
This does not happen for any of my other classrooms. No matter how many times I or my students press the "Retry" button, it does not work.

**Comment by willemneal** [comment]
I too am experiencing this.  And to add some more info the accounts are linked and on the roster.

**Comment by BenEmdon** [comment]
I just checked your organization (https://github.com/WGWebDesign) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/WGWebDesign/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories.

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.

**Comment by BenEmdon** [comment]
@willemneal please check if you organization is on the "free" plan too. If you are still having issues please open a anew issue.

**Comment by youngwghs** [comment]
Thanks Ben,

I am on the Educational Discount plan and didn’t realize that I had not requested for that discount to apply to this particular class. Thanks so much!
