### ISSUE TITLE
Users cannot change teams

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#175]
Accepting a group assignment and choosing to create a new team or join an existing team is a permanent choice.

What should a participant do if they accidentally choose the wrong team. Is there any way to undo / correct a mistake?

If not, maybe we should warn them when they accept the assignment.

**Comment by tarebyte** [comment]
We should probably warn them because right now because we have no way of switching them.

**Comment by johndbritton** [comment]
Yeah, I don't think we want to allow them to change teams. It should be clear that they can't change after the fact.

Maybe at some point we'll allow admins to reorganize teams.
