### ISSUE TITLE
Cannot disable assignment URL

### ISSUE THREAD

**Issue by imbur** [education/classroom#1750]
**Describe the bug**
On the group assignment settings page after unchecking _Enable assignment invitation URL_, students can still sign up using the assignment link.

**To Reproduce**
1. Create a Group assignment
2. Check 'Enable assignment invitation URL'
3. Make sure others you invite with the link can sign up
4. Go to the assignment settings page
5. Uncheck 'Enable assignment invitation URL'
6. Observe the error: invite others using the URL - they will be able to sign up

**Expected behavior**
After unchecking the 'Enable assignment invitation URL' the invitation URL should no longer be active/valid

**Screenshots**
N/A

**Additional context**
I can also provide access to the specific classroom and assignment where I observed the issue, if needed.

**Comment by BenEmdon** [comment]
Hey @imbur 👋 thanks for reporting in.

This appears to be a known problem #1592.

**Comment by EricPickup** [comment]
Closing since this is a duplicate of #1592.
