### ISSUE TITLE
Students Cannot Clone my Assignment Repo

### ISSUE THREAD

**Issue by jashelio** [education/classroom#1751]
When the students type in the URL for the assignment from my classroom's assignment list, the repository setup fails. We have tried many times.

Although I don't think this can be the problem, I will mention that I was not asked to renew my status as an educator by sending a scan of my photo ID again this spring.

![image](https://user-images.githubusercontent.com/17816986/51932967-48047e80-23ce-11e9-8877-6a339a1def96.png)

**Comment by BenEmdon** [comment]
@jashelio I just checked your organization (https://github.com/CSCI-142-10-20185) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/CSCI-142-10-20185/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories.

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to [https://education.github.com/discount](https://education.github.com/discount).

If you have trouble upgrading your plan please contact GitHub support ([https://github.com/contact](https://github.com/contact)).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.

**Comment by jashelio** [comment]
Thanks, Ben, I found what I needed to do and have applied. I hope the approval does not take long, as I have a class soon.

I also look forward to the process becoming more straightforward!

Sincerely,
James Heliotis
