### ISSUE TITLE
Links to student repos on classroom assignment page often are missing

### ISSUE THREAD

**Issue by boyland** [education/classroom#1753]
**Describe the bug**
The assignment page is very unreliable for showing student repositories.

**To Reproduce**
Go to the assignment page listing repos.  Some student repos will be marked missing.  Refresh and a different set are marked missing.  Refresh again, and yet a different set are shown.

**Expected behavior**
All student repos that exist should be shown.  It shouldn't depend on the phase of the moon or some race conditions/random number.

**Screenshots**

The following screenshots were created within minutes of each other:

<img width="1138" alt="classroom-bug1" src="https://user-images.githubusercontent.com/1193683/52058578-60d77600-252d-11e9-9133-33fc5ab4cef6.png">

<img width="1121" alt="classroom-bug3" src="https://user-images.githubusercontent.com/1193683/52058597-692fb100-252d-11e9-85f5-71bf9c9b2c0a.png">

I could show more, but you get the idea.

**Additional context**

**Comment by BenEmdon** [comment]
@boyland I have investigated thoroughly and have noticed that one of the admins in your classroom with the login [`stevensaunders`](https://github.com/stevensaunders) doesn't have the GitHub org permissions to see all of the repositories in the organization. 

Classroom picks an admin token at random to use to request GitHub data (like such as seen in your screenshots).

A simple work around to this problem would be to do either:
* Remove [`stevensaunders`](https://github.com/stevensaunders) as an admin in the classroom admin menu https://classroom.github.com/classrooms/44908412-apc-430-spring-2019/settings/invitations
* Upgrade [`stevensaunders`](https://github.com/stevensaunders) organization role to a higher permission level in your GitHub organization 
https://github.com/orgs/UW-Extension/people

**Comment by BenEmdon** [comment]
Since we were able to resolve your issue I am going to go ahead and close this issue. If you feel it is unresolved, please reopen this issue.

**Comment by boyland** [comment]
Closed: as in "won't fix" ??  github classroom shouldn't just say that the repo doesn't exist.  It is giving the wrong output.  So don't you agree this is a bug?

And classroom does this to *avoid* rate limiting, right?  It's trying to avoid getting caught by github's rate limiting checks, not because it actually helps anything.

**Comment by mozzadrella** [comment]
@boyland I understand the frustration, and I take the feedback. We're working within constraints, which @BenEmdon helped with.

A few of your comments in this thread border on uncivil. This project is governed by our [Code of Conduct](https://education.github.community/faq) and GitHub's [Terms of Service](https://help.github.com/articles/github-terms-of-service/). Please consider this a warning.
