### ISSUE TITLE
Unable to accept assignment: "GitHub repository could not be created"

### ISSUE THREAD

**Issue by finin** [education/classroom#1754]
**Describe the bug**

I have a github classroom (https://classroom.github.com/classrooms/46271064-umbc-cmsc-471-01-s19-classroom) and created an initial assignment (https://classroom.github.com/a/dTtxskCT) but when I or students try to accept the the assignment, it fails with the message "GitHub repository could not be created, please try again".  Note: I tried deleting the assignment and recreating it, but got the same results.  The link above is to my second try.

**To Reproduce**
1. Go to https://classroom.github.com/a/dTtxskCT
2. Click on 'accept assignment'
3. See error

**Expected behavior**

You will get an initial repo for the assignment

**Screenshots**

**Additional context**

**Comment by BenEmdon** [comment]
I just checked your organization (https://github.com/UMBC-CMSC-471-01-Spring-2019) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/UMBC-CMSC-471-01-Spring-2019/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories.

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.
