### ISSUE TITLE
Error accepting assignments

### ISSUE THREAD

**Issue by amhics** [education/classroom#1756]
**Describe the bug**
I am unable to create private repo assignments for students, although other instructors can (from the same starter code repo). 

**To Reproduce**
1. Go to https://classroom.github.com/classrooms/46939023-csci142-07-spring19-classroom
2. Click on either assignment link provided, so 

https://classroom.github.com/a/QSLGDhfw
or
https://classroom.github.com/a/yLxVgfbb

3. an error results, even though my account (amhics) is approved for education/private repos

![github](https://user-images.githubusercontent.com/46656345/52171429-22a7a580-272b-11e9-98b2-65bcb804de9f.jpg)

Please help!

**Comment by amhics** [comment]
TO be more precise, I successfully "create" the assignment and have the link, but anyone trying to accept it fails right away, so they can't check out the code.

**Comment by BenEmdon** [comment]
I just checked your organization (https://github.com/CSCI142-HAMZA-SPRING19) and it looks like your organization is still on the "free" plan. You can confirm this by going to https://github.com/organizations/CSCI142-HAMZA-SPRING19/settings/billing. Organizations on the "free" plan aren't allowed to have private repositories.

To fix this issue you must sign up your organization to the education pack. To upgrade your plan please go to https://education.github.com/discount.

If you have trouble upgrading your plan please contact GitHub support (https://github.com/contact).

I am closing this for now as it appears the only problem is that your organization is still on the "free" plan. If you experience a bug with classroom, please open a new issue.
