### ISSUE TITLE
Importing Starter Code Stuck for Indeterminate Amount of Time 

### ISSUE THREAD

**Issue by joshua-doolan** [education/classroom#1759]
**Starter Code Takes Forever**
Likes issues #1623, #1732, #1731, and #1616, my starter code takes forever (12 hours and counting...) to import.

**To Reproduce**
1. Go to https://classroom.github.com/assignment-invitations/0410d22b62daa9039caa9c711c678db5/setup
2. Wait

**Expected behavior**
The starter code should import, and I should be able to access the repository.

**Screenshots**
It just stays at this point.
![image](https://user-images.githubusercontent.com/45085281/52248727-c88b1980-28bd-11e9-9917-9deb06dad28d.png)

**Additional context**
It says "created repo" but there is no repository that I can access.

**Comment by KCholod** [comment]
I have the same issue with a different assignment: https://classroom.github.com/assignment-invitations/b630df97007bc7a4bcf7a8f98e5a74f4/setup

For me, this is my first time on GitHub, although I doubt that's relevant.

**Comment by rjsvcs** [comment]
Duplicate: #1757

**Comment by BenEmdon** [comment]
@joshua-doolan I investigated your classroom and I found that it was missing webhooks (related to #1647). I went ahead and manually fixed webhooks on your classroom organization (https://github.com/harvard-ml-courses). Your students should see their assignments import.

--- 

@KCholod I investigated your classroom organization (https://github.com/umaine-mat400-2019-spring). Your classroom also missing webhooks so I fixed them on your classroom. Your students should see their assignments import.

---
I can confirm my manual fix is working as expected. I will go ahead and close this issue for now. @joshua-doolan or @KCholod please reopen this issue if you experience this again.

**Comment by moritzge** [comment]
I have the same issue. 
Classroom: https://classroom.github.com/classrooms/47527793-compfabrob19
Assignement: https://classroom.github.com/classrooms/47527793-compfabrob19/assignments/comp-fab-a0
Main repo: https://github.com/computational-robotics-lab/comp-fab-a0
Student repo: https://github.com/computational-robotics-lab/comp-fab-a0-moritzgetest/import

**Comment by BenEmdon** [comment]
@moritzge Please open a new issue with these details to ensure that your issue gets resolved.
