### ISSUE TITLE
GitHub Footer

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#176]
@johndbritton do we need to add the official GitHub footer to the site?

**Comment by johndbritton** [comment]
@cameronmcefee Should we include a footer on the site? Do you prefer the `github.com` footer, the same footer as `education.github.com`, or something like ":mortar_board: with :heart: by GitHub"

**Comment by cameronmcefee** [comment]
I think that depends on what you want the footer to do for the people using the app. Will the links in the .com or ed-web footers be relevant to these people?  If not, I think ":mortar_board: with :heart: by GitHub" (presumably in octicons) will work great.

**Comment by tarebyte** [comment]
I think the octicons should be fine since we already have a link to GitHub education

**Comment by johndbritton** [comment]
:+1: for octicons.

**Comment by cameronmcefee** [comment]
:+1:

**Comment by tarebyte** [comment]
Closed by #181
