### ISSUE TITLE
importing starter code takes forever to complete

### ISSUE THREAD

**Issue by kavinshah** [education/classroom#1762]
**Describe the bug**
Importing Starter Code takes forever to complete

**To Reproduce**
When clicking 'Accept the assignment' on previous window

**Expected behavior**
Assignment must have been completely loaded for me

**Screenshots**
![send](https://user-images.githubusercontent.com/38910831/52379713-41fb4700-2a39-11e9-84a9-53072cfebe6e.PNG)

**Additional context**

**Comment by rjsvcs** [comment]
Duplicate: #1757

**Comment by BenEmdon** [comment]
@kavinshah can you please provide the assignment link?

**Comment by BenEmdon** [comment]
@kavinshah I investigated your classroom which I looked up from the screenshot and I noticed that it was missing webhooks (related #1647). This appears to be a classroom wide problem and happens sporadically on classrooms. It is a high priority for the classroom team to fix.

We have a manual workaround on the classroom side and I went ahead and re-enabled webhooks on your classroom. All of your assignments should be able to import now.

I have confirmed everything looks good on our end so I will close this issue for now. @kavinshah  please reopen this issue if you experience this problem again.

**Comment by kavinshah** [comment]
@benEmdon thanks!
