### ISSUE TITLE
Students can not accept assignment and create repos.

### ISSUE THREAD

**Issue by hswift1** [education/classroom#1763]
I created a classroom and 2 different assignments. My students' links are not even getting through the repo creation. I have tried with two different types of assignments - one with starter code and one without - they both continue to error out.

Any assistance is greatly appreciated!
Sincerely,
Heather

<img width="1243" alt="screen shot 2019-02-07 at 8 27 48 am" src="https://user-images.githubusercontent.com/23033756/52414442-5596c400-2ab2-11e9-95c2-00e86c91eaac.png">

**Comment by klancasterprof** [comment]
I am having this problem as well.

**Comment by nourSmaoui** [comment]
I am also having similar problems

**Comment by rjsvcs** [comment]
I have seen something similar a few times when an assignment is created to use private repositories, but the organization with which the classroom is associated cannot create unlimited private repositories. Is your assignment configured such that the student repositories are private? If so, is your organization able to create the required number of private repositories (e.g. a paid account or an educational discount)?

**Comment by klancasterprof** [comment]
@rjsvcs I created the org using an educational discount (part of classroom) Github account. What else would need to happen? As an aside, the error messages are ridiculous. They provide no guidance at all.

**Comment by rjsvcs** [comment]
Once you create the org you need to explicitly apply for and receive an educational discount for the org. It's not enough that you have a discount on your own account; the org is the owner/creator of the repositories used by the classroom. 

When you create an assignment, you should see a shortcut to the right side of the screen:

![image](https://user-images.githubusercontent.com/22302214/52526655-e5db3180-2c89-11e9-9f37-dcc4f73e2506.png)

This shows up whether you already have the discount or not. If you click the link, you can see which orgs you have created that already have discounts, and you can apply for a discount for an org that doesn't already have one.

I agree that the UI can be a bit rough around the edges, but it's always improving, the devs are really great and responsive, and this is a wonderful service. I have been using it for the last 2+ years with relatively few problems.

**Comment by klancasterprof** [comment]
@rjsvcs Thanks for the response. I had already done that. When I click on the box to apply, it says that I have already applied and been approved, so I don't think that is the problem.

**Comment by rjsvcs** [comment]
Then this is definitely not the problem that I have seen before. Good luck!

**Comment by klancasterprof** [comment]
@hswift1 Have you had any luck with this?

**Comment by klancasterprof** [comment]
@rjsvcs It does appear that it is related to projects being public. Since I have already done what I think was required to have private repos, not sure where to go. Public repos on student projects is a complete non-starter.

**Comment by hswift1** [comment]
Hi, sorry I was missing on this for a couple of days. I just got back to it and tested creating the assignment with the students' repositories being public. It does work when the repos are public. I agree with @klancasterprof in regards to completing all the necessary steps to create unlimited private repos for students. I also completed the steps and should have the ability to create unlimited private repos.

Hopefully, development will be able to review and fix the issue.

**Comment by klancasterprof** [comment]
@johndbritton Can someone please look at this? This issue may cause me to have to abandon using classroom, since I must have private repos.

**Comment by mozzadrella** [comment]
@hswift1 @klancasterprof I looked at both of your accounts, and the problem is that you applied for an individual discount (for your own repositories) not for an organization. 

Here are the steps to get a Team plan for unlimited private repositories for your students:

Faculty can now easily upgrade any GitHub organization being used for academic purposes to [GitHub Team](https://github.com/pricing) with a single click.

Simply visit https://education.github.com and click the **Join GitHub Education** button. Once you sign in, you will be directed to your benefits page, where organizations you own will be listed near the bottom of the page:

![screenshot 2019-02-07 at 9 14 03 am](https://user-images.githubusercontent.com/6764844/52430022-05236480-2aba-11e9-914a-0fc03280ca38.png)

Click the **Upgrade** button next to the organization name to immediately upgrade it for free to GitHub Team.

**Comment by klancasterprof** [comment]
@mozzadrella Thanks for the response! This is overall a bit confusing. I just went through the steps and it required me to verify my academic status again, and thus creates a delay. Is there some reason that verification has to occur twice?

**Comment by mozzadrella** [comment]
@klancasterprof from time to time we will ask faculty to renew. Since we just released the ability for teachers to self-serve in upgrading their own orgs, some faculty may need to re-verify.

**Comment by klancasterprof** [comment]
@mozzadrella Ok - thanks. I just thought it a bit odd since its only been 2 weeks since I was first approved. In any case, thanks again for responding.

**Comment by hswift1** [comment]
@mozzadrella - thank you for the response - when I go to the page, it says I was already granted benefits in 2017. I will re-submit and see what happens.
Thank you!
<img width="1287" alt="screen shot 2019-02-13 at 10 07 49 am" src="https://user-images.githubusercontent.com/23033756/52721293-5b3f4e80-2f77-11e9-892e-c51f159cf4e3.png">
