### ISSUE TITLE
Deleting Student repository

### ISSUE THREAD

**Issue by elhambuxton** [education/classroom#1764]
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_

**Comment by elhambuxton** [comment]
I have a student who accepted the invitation for an assignment multiple times and created multiple repositories for the same assignment. It does not seem to be an option that allows me to delete the duplicate repositories. How can I delete a student repository for an assignment?

**Comment by kaspersoerensen** [comment]
Hi @elhambuxton 

You should be able to find the student repository when you are logged into your github organization. In the overview of repositories, find the one you want to delete, click on the link to go to the repository page, click settings and scroll down to the bottom of the page where it says "Danger Zone". Here you should be able to delete the repo.

Does this answer your question?

**Comment by luytsm** [comment]
It would be nice to be able to delete in bulk.

At the moment my organization has 532 repositories mainly of the Classroom Assigments. It would be nice to be able to delete all the repos that are associated with the press of a button

**Comment by kaspersoerensen** [comment]
@luytsm  I agree. I have noticed that when deleting the classroom all repositories are removed from your organization as well. But that also leads to the repositories being deleted for the students - which might not be what you want to do. Maybe you should open a feature request for a delete in bulk function?

**Comment by BenEmdon** [comment]
Hey @elhambuxton @luytsm @kaspersoerensen 👋 

To delete student repositories you can do so in 3 ways with varying magnitude:
* Delete an individual repository
* Delete all repositories related to an assignment 
* Delete all repositories related to a classroom

## Delete an individual repository
You can do this on any repository via GitHub. Go to the github.com/`org_name/repository_name`/settings

## Delete all repositories related to an assignment 
You can delete all repositories related to an assignment by deleting the assignment from GitHub Classroom. Here are the steps:
1. In Classroom navigate to an assignment which you want to delete the corresponding repositories from. Then go to _**Assignment Settings**_:
  ![](https://user-images.githubusercontent.com/11095731/53201122-32f7c580-35f1-11e9-9304-c4c04e010143.png)
2. Next, delete the assignment. This will delete all GitHub repos related to this assignment.
  ![](https://user-images.githubusercontent.com/11095731/53201202-5a4e9280-35f1-11e9-878c-fad03c7940af.png)

## Delete all repositories related to a classroom
Delete all repos related to your classroom by deleting your classroom.
1. Go to the **_Manage Classroom_** page:
  ![](https://user-images.githubusercontent.com/11095731/53201370-d8129e00-35f1-11e9-90c3-0d63f0dbaf82.png)
2. Delete your GitHub classroom and all associated GitHub repositories:
  ![](https://user-images.githubusercontent.com/11095731/53201371-d8129e00-35f1-11e9-9a91-5c79e2c79ca3.png)


--- 
I hope these options suffice! Please reopen this issue if you they do not.
