### ISSUE TITLE
Clone base-repository including issues and boards

### ISSUE THREAD

**Issue by bobmulder** [education/classroom#1768]
### Feature request :sparkles:
**Creating new teams/repositories will clone code from a base-repo. Why not cloning the issues and boards as well?**

We are very happy with this useful tool. However, when our students will start with a new assignment they will start with a bunch of issues. At this moment I've written my own tool to 'clone' the issues from one to another, but it would be nice to do this by 'default' (or option) within Classrooms.

I'd like to know how you think about this!

**Comment by mozzadrella** [comment]
@bobmulder hello, thanks for opening! This is actually possible with Probot: https://github.com/probot/probot

I am working on a blog post that outlines exactly how for the first week of March. Thank you!

**Comment by bobmulder** [comment]
That looks promising @mozzadrella, I'll dive into this! Thank you for your comment!
