### ISSUE TITLE
Classroom invitations are not working on my classroom

### ISSUE THREAD

**Issue by eblanton** [education/classroom#1770]
My GitHub classroom is not correctly creating assignments for student repositories.  I was asked by @BenEmdon to provide an invitation link.  Here is such a link:

https://classroom.github.com/a/DDyqbXrL

This is a fake, empty assignment.  Once you have your hands on my classroom, Programming Assignment 1 is the assignment that has been giving me grief (dozens of students were unable to use it), if that matters.  I am under the impression that it does not, and it's a classroom-wide setting at fult.

**Comment by BenEmdon** [comment]
@eblanton I was able to receive the fake empty assignment without issue. I went ahead and investigated what was going on with your _Programming Assignment 1: Conway's Game of Life_ and found there is an issue starting a [source import](https://developer.github.com/v3/migrations/source_imports/) with the starter code you have provided.

I investigated further and it appears that the starter code repo you put for _Programming Assignment 1: Conway's Game of Life_ is returning a `404` status code to classroom. That means that either the starter code repo doesn't exist or classroom doesn't have access to that repo.

To fix the issue please do the following:
1. Go to your assignment _Programming Assignment 1: Conway's Game of Life_ and go to **Assignment Settings**:
  ![](https://user-images.githubusercontent.com/11095731/53214631-4b7cd580-361b-11e9-85fb-28c77c71c8af.png)
2. Re-enter the starter code repo's name to the desired starter code repo and press **save** at the bottom:
  ![](https://user-images.githubusercontent.com/11095731/53214647-62232c80-361b-11e9-9cc2-41e696a3ec69.png)

Once you have done this could you please report back and ask a student to see if their assignment repository gets created (when they go to the assignment link).

**Comment by eblanton** [comment]
When I went there it say "Deleted repository" in that box, although the repo URL loaded just fine in my browser.  I have reentered the repository URL (I had to type it by hand, I couldn't select it, as it didn't appear as an option in the dropdown due to too many student repos starting with the same sequence) and asked a student to retry the clone.

**Comment by eblanton** [comment]
I have confirmation that it worked, thank you!
