### ISSUE TITLE
Repository setup/ Starter code import takes a long time to load

### ISSUE THREAD

**Issue by ZhengEnThan** [education/classroom#1773]
**Describe the bug**
The importing starter code progress bar when clicking on an assignment link hangs forever.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://classroom.github.com/a/Xh-s-mwL

**Expected behavior**
Everything should be successfully loaded and the page will be redirected to the assignment repository.

**Screenshots**
![image](https://user-images.githubusercontent.com/46462603/53267907-d6a0ae80-36a1-11e9-847d-31b62fe71527.png)

Hangs here.

**Comment by ZhengEnThan** [comment]
Please send help as soon as possible as I need to start this assignment immediately :'(((

**Comment by manu-msr** [comment]
I have this problem too.

![image](https://user-images.githubusercontent.com/15841718/53273598-0b206480-36ba-11e9-949b-64b258fdf06f.png)
