### ISSUE TITLE
Classroom invitations are failing to import

### ISSUE THREAD

**Issue by eblanton** [education/classroom#1778]
I have the same bug that everyone else is having.  Classroom invitations are stalling for long periods of time.  An example invitation on my classroom is below, the invitations that are failing are for Lab 04.  I have disabled Lab 04 invitations for now to avoid having a bunch of broken repos on my organization, but labs start tomorrow at 2 PM.

Invitation to fake project:
https://classroom.github.com/a/DDyqbXrL

@BenEmdon

**Comment by Hugo0** [comment]
Having the same problem here.

Progress bar stuck here
![image](https://user-images.githubusercontent.com/12943235/53307322-812df280-3897-11e9-8d80-ff513cbe5d64.png)

**Comment by BenEmdon** [comment]
@eblanton @Hugo0 do the imports ever complete or do they stay in an importing state? 
What do you see on the student repo on GitHub.com?

**Comment by eblanton** [comment]
As far as I can tell, the imports that stalled this afternoon remain stalled even now.  They show 0 commits on GitHub classroom, and clicking through to the GitHub repository shows a page that says 

```
Preparing your new repository
There is no need to keep this window open, we’ll email you when the import is done.
```

The status bar under that says "Optimizing repository and pushing commits to GitHub…"

**Comment by BenEmdon** [comment]
@eblanton thanks for the information. We are investigating the problem and it appears to be an unreported outage on GitHub.com. Will keep posted on updates.

**Comment by eblanton** [comment]
OK.  FYI I am going to destroy the broken repositories and create new ones using a script, because my students have to student.  Hopefully you don't lose any information you require when I do that.

**Comment by BenEmdon** [comment]
The starter code importer uses GitHub's [source import API](https://developer.github.com/v3/migrations/source_imports). The source imports team has reported that there is a large backlog of imports that were started over this weekend. The imports that are currently stuck will eventually finish, but it might take some time.

**Comment by BenEmdon** [comment]
## Update
The source import team have said that new imports should (imports started after this time) should just work.
Starter code imports that are currently stuck should take a couple of hours to process.

**Comment by belgort-clark** [comment]
@BenEmdon thank you for your help with this. It's very much appreciated.

**Comment by fywu85** [comment]
Thank you for working on this! Unfortunately, I could not confirm this fix from my side. My import is still stuck despite several attempts in the past three hours.

**Comment by hroncok** [comment]
It was better for a while but happened again for 3 students from 46.
It also happened again for me when creating new assignment for next week.

**Comment by kaspersoerensen** [comment]
Still experiencing this issue here unfortunately. Organization: "Sundhedsteknologi-OOP"

**Comment by gchallen** [comment]
This is still happening for us as well: `cs125-illinois-students`. We have 600 students and each failure has to be repaired by hand. It's a medium-sized PITA.

I really love GitHub Classroom, but this problem is not new and it's getting frustrating to see it recur repeatedly. Could Classroom at least put up a status page that instructors and students could check? I'm assuming (hoping...) that there is some kind of continuous testing being done—although it does sometimes seem that these things get brought to GitHub's attention through multiple duplicative issues filed by desperate instructors...

**Comment by BenEmdon** [comment]
## Update
Talking to the source imports team again this morning. They say that the import queue continued to act up over the night. I'll keep the updates coming.

@gchallen I hear you. A status page would be optimal. It's in our roadmap.

**Comment by BenEmdon** [comment]
## Update
Starter code imports will be running in  **degraded performance** today. All imports that are started will _eventually_ finish but will take some time. This should clear up later today, but if it doesn't please report back.

**Comment by nasseef** [comment]
I had the same issue earlier but it seems to be working now.

**Comment by BenEmdon** [comment]
## Update
Starter code imports will continue to run in **degraded performance**. The backlog of import jobs that GitHub is processing is very large. Fortunately the queue is shrinking.

All imports that are started will _eventually_ finish but will take some time.

**Comment by Unco3892** [comment]
The queue seems to be quite long as I have personally been waiting for 24 hours and some friends over three days, so the only way to resolve it is to wait for the import to finish over an undetermined time?

**Comment by BenEmdon** [comment]
## Update
Starter code imports are expected to run in degraded performance for about 12 more hours.
All imports that are started will _eventually_ finish but will take some time.

I added a message of the day to provide status on the situation:
![MOTD](https://user-images.githubusercontent.com/11095731/53430817-3b6b4a00-39bd-11e9-8c85-22544711af7d.png)

**Comment by kevinthayes** [comment]
I tried to have my class import code and 4 out of 19 were successful and downloading the entire repo in 50 minutes

**Comment by pinventado** [comment]
I can confirm the same issue with slow imports. I had to cancel and manually clone repos so that students can continue working in our lab class today.

**Comment by kedarabhyankar** [comment]
Happening for the classroom I'm trying to clone a project for too, for my class at Purdue University.

**Comment by desmonduz** [comment]
I can confirm the same issue. I assign labs to my students, and they cannot create their starter repos during the lab.

**Comment by Younes-Charfaoui** [comment]
The same thing also, in fact when the students refresh, or stop and redo the process some of them got the repo created fast.

**Comment by BlueTaurus** [comment]
i am facing facing the same issue. In fact few students waited about 45-50 minutes for it to be completed but it never does. All that i can suggest is for them to refresh the page or try again till it creates their stater repo.

**Comment by BenEmdon** [comment]
## Update 
The queues have reduced significantly but there still seems like there are a couple of hours of backlog to get through. Imports might take a couple of hours to complete at this time.

The message of the day will continue to be showed until this incident is over.

**Comment by BenEmdon** [comment]
## Update 
The import queues have stabilized and starter code imports should function as expected. 

If you continue to experience this problem **please open a new issue**, as the cause might be unrelated.

**Comment by shanayastephenson** [comment]
Hi I'm having an issue the bug is back :(

**Comment by srinjoym** [comment]
@shanayastephenson The source import API had an outage this morning which is likely why you were hitting this bug again. If the problem continues to happen, please open a new issue as the cause might be unrelated.

**Comment by aaryno** [comment]
Having this issue this morning. It seems the repo gets created but it doesn't finish the import.

**Comment by jessebartels** [comment]
I, too, am having this issue from this morning (same as @aaryno)

**Comment by tbartens** [comment]
This crops up so often, I'm having a problem figuring out which issue is the "current" issue related to this problem! Hint Hint.

Here's what I've shared with my student's that seems to provide some relief...

If gitHub accept is not completing for a long time (like more than an hour or so), try the following:

1. Go to the GitHub web-page, and click on the started import of the assignment in question.
2. When prompted, choose CANCEL (not restart)
3. Then go back to the invitation, and restart the accept process.
