### ISSUE TITLE
Student Repo Import Bug is back

### ISSUE THREAD

**Issue by johnboat** [education/classroom#1790]
**Describe the bug**
Student goes to Project URL to accept project and the import gets stuck. Most students worked fine, but I have one that has been "importing and optimizing" for two days and counting.

Same as #1778 but that bug has been closed.

**To Reproduce**
1. Click on a new Project URL
2. Accept Project
3. Import never finishes

**Expected behavior**
A quick import and repo creation.

**Screenshots**

**Additional context**

**Comment by SirYancy** [comment]
I am having this issue as well. It basically stops all forward progress in my classes. What gives?

**Comment by srinjoym** [comment]
@johnboat @SirYancy GitHub's source import API has an outage this morning which likely caused these issues with student repository imports. Let me know if you guys are still hitting these issues, or else I'll close this out.

**Comment by johnboat** [comment]
The problem started Monday for me. Some students reported being able to click the link on the page to the repo and that would “make it work”. All my students are fine now—the last import finished this morning.

**Comment by srinjoym** [comment]
@johnboat Good to hear that the imports finished! Thanks for reporting the issue and please open another issue if you hit any other problems
