### ISSUE TITLE
Stuck at importing starter project code

### ISSUE THREAD

**Issue by maciejjankowski** [education/classroom#1792]
Stuck after following the assignment link

**To Reproduce**
1. Open the link
2. Wait and see the progress bar not moving

**Expected behavior**
repository cloned in my account with the code in it

**Screenshots**
<img width="1038" alt="obraz" src="https://user-images.githubusercontent.com/2905995/54033226-08db0180-41b4-11e9-9100-65f2783b0f5f.png">

**Comment by BenEmdon** [comment]
@maciejjankowski can you confirm that your assignment repo is still stuck? There is a possibility that the source imports were slowed down at the time that you made this issue.

**Comment by nasseef** [comment]
I've been having the same issue yesterday and today. It hangs but it imports correctly. No feedback that it did import.

**Comment by BenEmdon** [comment]
@nasseef do you mind elaborating what you mean by _"It hangs but it imports correctly."_?

Does the import progress on classroom hang, while the import on GitHub.com complete?

**Comment by nasseef** [comment]
A student clicks on the assignment link. Progress bar completes "Creating Repository". The progress bar for "Importing starter code" never completes.  When I check my students' repos, it shows that creating and importing was done.

**Comment by BenEmdon** [comment]
@nasseef would you mind providing the assignment link? I would like to see what's going on.

**Comment by BenEmdon** [comment]
I have a feeling that this is related to #1647

**Comment by nasseef** [comment]
https://classroom.github.com/a/42v5vaVl

**Comment by BenEmdon** [comment]
@nasseef it appears that your classroom is missing webhooks (related to #1647), I'll see if I can fix that my end.

**Comment by BenEmdon** [comment]
@nasseef I went ahead and fixed webhooks on your classroom. Everything should work as expected.

**Comment by nasseef** [comment]
@BenEmdon How can I do this on my end?

**Comment by BenEmdon** [comment]
@nasseef this problem happens sporadically and we are working on a global fix in #1647. There isn't a way to fix this on your end. 

If this happens to you again, please write in.

I am going to go ahead and close this issue since it has gone stale. If the original author is still experiencing this I invite them to reopen this issue and provide details (so we can help them).

**Comment by nasseef** [comment]
@BenEmdon can you please fix this problem on a different classroom. I'm having the same import hanging issues. Here is the assignment link https://classroom.github.com/a/x3Nvwikc.  Here is the classroom link: https://classroom.github.com/classrooms/49959068-2400-fl-19-classroom

**Comment by nasseef** [comment]
@BenEmdon Never mind. It works now. It just took more than 30 minutes to complete. Thanks.
