### ISSUE TITLE
Pull all assignments from one student

### ISSUE THREAD

**Issue by zamansky** [education/classroom#1802]
### Feature request :sparkles:

Right now, via classroom assistant we can pull all the repos from one assignment and from the GitHub classroom we can access all the repos from one assignment.

At times it would be very useful to pull all the assignments for one particular students.

**Comment by johndbritton** [comment]
Thanks for the feature request @zamansky, hadn't thought about this one but it does make sense. Im labeling this as `help-wanted` and putting it on our backlog.

**Comment by spinecone** [comment]
This feature is being tracked in https://github.com/education/classroom/issues/1676 , so I'll close this one as a duplicate.
