### ISSUE TITLE
Not able to load/render Jupyter(.ipynb) files on github repositories

### ISSUE THREAD

**Issue by mohita-ajmera** [education/classroom#1804]
**Describe the bug**
Not able to load/render Jupyter(.ipynb) files on github repositories
It either never renders or takes hours to open even a 100 Kb python notebook.

**Screenshots**
![image](https://user-images.githubusercontent.com/14015331/55135750-93c77000-5152-11e9-9c86-d5732eaed51b.png)

**Comment by mohita-ajmera** [comment]
It is not loading in the end.
![image](https://user-images.githubusercontent.com/14015331/55135795-b063a800-5152-11e9-84c4-7e642ac81e2a.png)

**Comment by johndbritton** [comment]
This is not an issue with GitHub Classroom. Please contact `support@github.com` about this issue.
