### ISSUE TITLE
github classroom classroom list unhelpful

### ISSUE THREAD

**Issue by phannan** [education/classroom#1813]
**Describe the bug**
The new github classroom classroom "list" is a step back.  I have a lot of classrooms to sift through.  Up until now I changed the icon for the organization with a big stop signs for the old classrooms.  Now I don't see the icon so its hard to see my current classes.  Its unclear how it is sorted.  Is it order created or something else?  Without either a sort or some visual indicator this list is beautiful but not helpful or really useful.  Useful trumps pretty every time in my book.  

**To Reproduce**
1. Go to github classroom classrooms.
2.  Scroll down the list having to read the exact text instead of spotting your classrooms easily.

**Expected behavior**
Some way to distinguish the current classes.

**Comment by d12** [comment]
This list has a search option now. @phannan does this solve your problems?

**Comment by phannan** [comment]
Yes!  Thanks.
