### ISSUE TITLE
Accept assignment button is missing

### ISSUE THREAD

**Issue by priyank-intellial** [education/classroom#1826]
I have created an assignment and there is an invitation link for the students. I have used that link for my different account(Consider as a student) and strange there is no accept button to accept that assignment.
 
![image](https://user-images.githubusercontent.com/40655077/57602361-8ccab480-757c-11e9-94ef-f813c21b0d5b.png)

**Comment by BenEmdon** [comment]
For group assignments there is no "Accept Assignment" button. Instead the student/user needs to create or join a group, which in turn would create an assignment for the group.

Im going to go ahead and close this. If you feel that the user experience needs some tweaking I'd be happy to hear your suggestions 😄
