### ISSUE TITLE
Don't find roster management using my local server

### ISSUE THREAD

**Issue by xuyangit** [education/classroom#1829]
**Describe the bug**
I have cloned the repo and started the server in my local machine. However, it seems I cannot find the roster management page and button. Besides, I cannot choose to manage my roster when I create the classroom. Is there any option to turn this on? Or it's not supported using the master branch. Thanks!

**To Reproduce**
1. Clone the master repo
2. Start the server
3. Create the classroom and manage it

**Expected behavior**
Can manage roster in classroom management page.

**Screenshots**
![1557846090(1)](https://user-images.githubusercontent.com/9316505/57708695-5e43fb00-769c-11e9-94f1-883c5126247a.png)

**Additional context**

**Comment by d12** [comment]
@xuyangit Wow, seems like this feature is still under a flipper feature. I'll get that sorted in a bit. For now, you can run this in your local rails console:

```
GitHubClassroom.flipper[:student_identifier].enable
```

**Comment by xuyangit1** [comment]
@d12 ,Tks for your help!

**Comment by srinjoym** [comment]
@d12 I was planning on removing the `student_identifier` feature flag in #1791 and adding a new `google_classroom_import` feature flag so I can take care of it!

**Comment by EricPickup** [comment]
Closing this issue since a temporary solution is posted and the flag will be removed in #1791.
