### ISSUE TITLE
Starter code imports stuck again

### ISSUE THREAD

**Issue by talbronfer** [education/classroom#1832]
**Describe the bug**
When creating a new assignment repo, the code import part is stuck for our students for 20 minutes and more.

This is not the first time it happens and puts us in a difficult position with our customers. Can anyone urgently indicate if this is a known issue and if so, why does it happen and when is it expected to be resolved?

**Comment by BenEmdon** [comment]
@talbronfer can you confirm that the repos are created on your organization? If so, can you check if the student repositories are populated with starter code?

**Comment by talbronfer** [comment]
Repos were created, the import itself was hanging and the repos were empty. After a few hours it was back up - we had to delete and re-create all the students' assignment repos.

I realize this is a recurring problem that has something to do with the GitHub Import API - but we need at least some indication about the status of the import API and ability to report issues, this is something that happens for a few hours every few weeks.

**Comment by talbronfer** [comment]
Repos were created, the import itself was hanging and the repos were empty. After a few hours it was back up - we had to delete and re-create all the students' assignment repos.

I realize this is a recurring problem that has something to do with the GitHub Import API - but we need at least some indication about the status of the import API and ability to report issues, this is something that happens for a few hours every few weeks.

**Comment by BenEmdon** [comment]
> _@talbronfer ...we need at least some indication about the status of the import API and ability to report issues, this is something that happens for a few hours every few weeks._

We totally agree. We are working with the Source Imports team to improve the situation (and provide better insight). 

Since the situation here resolved over time, I am going to go ahead and close this.

If you experience and classroom related bugs or want to request a feature, don't hesitate to open a new issue.
