### ISSUE TITLE
warning: 2.6.3-compliant syntax, but you are running 2.6.0

### ISSUE THREAD

**Issue by duzhuan119** [education/classroom#1834]
Describe the bug
execute script :  rake db:seed   ，Error occurred :
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.3-compliant syntax, but you are running 2.6.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.

How to solve this problem? 
Thanks very much.

**Comment by d12** [comment]
This is just a warning, I wouldn't worry about it too much. The link you posted has some good information if you're interested!
