### ISSUE TITLE
Maximum number of groups

### ISSUE THREAD

**Issue by mbcastro** [education/classroom#1871]
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_
I would like to be able to limit the maximum number of groups that could be created for an assignment. This is very useful to avoid students creating lots of individual groups in a group assignment and force tham to join already created groups.

**Comment by EricPickup** [comment]
Hey @mbcastro, your feature request was implemented and is now live! Hope this helps. 🎉
