### ISSUE TITLE
SignalException every time a PR is deployed

### ISSUE THREAD

**Issue by EricPickup** [education/classroom#1887]
I've noticed on Haystack that we get 4 SIGTERM/SignalException errors every time we deploy a PR to production.

@tarebyte pointed out that 4 is also the number of dynos we're running.

Example:
```
/app/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:381:in `block in setup_signals'
/app/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:475:in `select'
/app/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/cluster.rb:475:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
/app/vendor/bundle/ruby/2.4.0/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
./bin/puma:17:in `load'
./bin/puma:17:in `<main>'
```
(https://haystack.githubapp.com/classroom/needles/IWuUfmHU5nB5bFmPMxDXcw)

![image](https://user-images.githubusercontent.com/1490434/59805845-4d903180-92a7-11e9-83fc-a53cc23ad10c.png)

**Comment by BenEmdon** [comment]
Is this issue proposing that we don't report these specific errors?

**Comment by EricPickup** [comment]
@BenEmdon not necessarily, just opening it to eventually investigate the cause. Not sure if it's something to be concerned about

**Comment by BenEmdon** [comment]
This `SIGTERM` is an expected puma related signal which we expect on every deploy on heroku.

In my opinion, exceptions in haystack should be _exceptional_ and receiving signals like `SIGTERM`  are _exceptional_. 

I realize that these could add to the noise, but removing it might take away value.

Conclusively, I think we could close this issue. If you disagree please reopen this issue.
