### ISSUE TITLE
Remove Elasticsearch dependency

### ISSUE THREAD

**Issue by d12** [education/classroom#1926]
Elasticsearch can be replaced by Postres full text search to remove a dependency that's caused availability issues in the past.

https://www.postgresql.org/docs/9.5/textsearch.html

**Comment by d12** [comment]
Re-opening, #1983 removed our dependency on ElasticSearch but lets not close this until we've actually removed ES from our Gemfile, cleaned up any ES files/logic, and unprovisioned ES in Heroku.

**Comment by d12** [comment]
As an update, I _believe_ all uses of ElasticSearch have been removed from Classroom. To close out this issue:

- [ ] Check ES provider for read/write activity. (We use a cloud provider through Heroku)
- [ ] Remove old ES logic in the app
- [ ] Remove ES related bootstrapping logic
- [ ] Remove ES gems
- [ ] Deprovision the service on Heroku
- [ ] Profit.

@andrewbredow Can I hand this off to you and your team?

**Comment by shaunakpp** [comment]
I believe https://github.com/education/classroom/pull/2107 takes care of most of the above checkboxes

**Comment by JessRudder** [comment]
I was going through the checklist and I'm fairly certain this is all done. @jeffrafter it looks like you removed elasticsearch from Heroku - if so (and you're comfortable that there's nothing else we need to do to remove ES), feel free to close this out!
