### ISSUE TITLE
Student Assignment Setup Never Resolves

### ISSUE THREAD

**Issue by brghena** [education/classroom#1927]
**Describe the bug**
I am managing a [github classroom](https://classroom.github.com/classrooms/42046610-cs-61c-summer-2019), and a few students (2 out of 200) are having issues with assignment setup. When they follow the link to setup an assignment, the process hangs and does not seem to ever complete. Refreshing the page has no effect on setup progress, and they have waited hours with no change in status. No private repo was created for the student.

It's not clear from the instructor side or the student side how they can progress in setting up the assignment. It seems likely that just starting over would make it work, but there's no obvious way for a student to do so. For the first student, we had them create a new github account and try again (which succeeded), but now we're a couple of assignments in to the course and doing so isn't a desirable option.

**To Reproduce**
Follow the normal assignment creation link and be very unlucky. I wish I had a better list of steps, and the problem occurs rarely, which would make it low severity except that there seems to be no way to overcome it short of creating a whole new github account to associate with github classroom.

The problem is actively occurring for user matteociccozzi right now, if that helps.

**Expected behavior**
The assignment would have been set up and a private student repo would have been created.

**Screenshots**
https://d1b10bmlvqabco.cloudfront.net/attach/jw6kndsic346lm/jktvgtdd2ua5d1/jxhunttqqxxl/Screen_Shot_20190629_at_11.15.52_AM.png

**Comment by EricPickup** [comment]
Hi @brghena, thanks for reporting this.

This is a known issue reported in #1591. We're currently working on a fix for this - you can track the progress there. Sorry for the troubles.
