### ISSUE TITLE
Update Octokit with ability to clone template repos

### ISSUE THREAD

**Issue by EricPickup** [education/classroom#1941]
This is a goal for after the main part of our importer deprecation project is finished.

Once Octokit is updated with the ability to clone template repositories, we should update the gem and our code to use this feature to keep consistency with the rest of our API calls.

**Comment by tarebyte** [comment]
@EricPickup we actually don't need to update Octokit (although the contribution is welcome).

**Comment by EricPickup** [comment]
@tarebyte Good to know! I'll update the description and leave this issue up as a low-priority goal to eventually refactor our code to use Octokit once it has been updated to keep it consistent with the rest of our API calls.

**Comment by cheshire137** [comment]
👋 The repo templates REST API preview is live now. See https://github.com/github/github/pull/117135#issuecomment-507844681 for some sample queries.

**Comment by EricPickup** [comment]
Looks great, thanks @cheshire137!
