### ISSUE TITLE
Proposed changes for unifying repository creators

### ISSUE THREAD

**Issue by shaunakpp** [education/classroom#1948]
For unifying the existing creators, we need to make a few changes, especially to determine if we're creating a `GroupAssignmentRepo` or an `AssignmentRepo`. Also based on that, we need to make sure that appropriate API calls are made, to do this I'm proposing the following changes:

Move the unified repo creator from `models` to `services` as the creator isn't necessarily a value object or represents a database object. Implement the following classes to communicate with each other and have concise, well defined responsibilities. This in turn will also help in testing them better:

### CreateGitHubRepoService
- Communicates with GitHub API and has public facing method to start creation
- Has all the methods required for creation
- essentially a modified `Creator` class

### Result
- Manages status and error handling(use existing code, modify if necessary)

### Broadcaster
- Sends messages to the ActionCable
- manages correct channels
- manages message content

### StatsSender
- Send stats and timings to Datadog
- based on `Entity` send appropriate stats

### Entity
- Gets attributes like `GroupAssignment` or `Assignment`, `User`or `Group` and based on this decides the appropriate methods to use and names to use for content
- Example: if its a `GroupAssignmentRepo` then our messages should contain `team` instead of `user`, so entity will determine that
- Essential Object for unifying both the existing creators.

Since this is not implemented yet, all suggestions are welcome and appreciated😄. Especially when it comes to names and responsibilities of these objects. I'm not entirely happy about naming of `Entity` and `StatsSender` 😅

_Originally posted by @shaunakpp in https://github.com/education/classroom/pull/1934#issuecomment-508186700_

**Comment by BenEmdon** [comment]
That issue name :joy:

**Comment by d12** [comment]
@shaunakpp @EricPickup The architecture and delegations make sense to me. 

Let's just make sure that refactoring and perfect design don't get in the way of shipping. There's a balance between quality and shipping, and it's easy to go too far in either direction. If there's a decision between assignment/group_assignment deduplication vs shipping the feature, I'd lean towards the later, especially considering we have a separate project planned for unifying assignment and group assignment logic and data models.

cc @andrewbredow

**Comment by EricPickup** [comment]
@d12 We'll make sure it won't get in the way. I'm almost ready to put up a PR for using template repositories and won't be depending on this refactor for it. It'll be easy to implement that PR into this once it's shipped.
