### ISSUE TITLE
Remove feature flags at 100%

### ISSUE THREAD

**Issue by stephaniegiang** [education/classroom#1951]
We should remove flags that have been at 100% for a while. Feel free to add to this list. 

A list of flags we should remove: 
- [x] student_identifier
- [x] public_home_v2
- [x] public_assistant_landing_page
- [x] multiple_classrooms_per_org
- [x] import_resiliency
- [x] group_import_resiliency
- [x] download_repositories
- [x] deadlines
- [x] dashboard_search

**Comment by d12** [comment]
`deadlines` was removed a while ago here https://github.com/education/classroom/commit/6c09575f96121f775bb8813a1bb3dece222769ad

I'll remove the feature from production flipper.
