### ISSUE TITLE
Starter Code repository not importing - wrongly identified as empty

### ISSUE THREAD

**Issue by waqarsaleem** [education/classroom#1974]
**Describe the bug**
I am trying to create an assignment from starter code in the repository at https://github.com/hu-cs-224-summer-19/hw03 which is not empty. Assignment creation fails with an error message claiming the repository to be empty.

**To Reproduce**
1. Go to Github Classroom and sign in.
2. Click on appropriate buttons to choose the classroom and create a new group assignment.
3. Complete all the steps including specifying the starter code repository at https://github.com/hu-cs-224-summer-19/hw03 and click _Create Assignment_.

**Expected behavior**
I expect the assignment to be created and to be presented with a link to share with my students.

**Screenshots**
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/13131021/60929713-f260c600-a2cb-11e9-9ec1-22345c775f44.png">

**Additional context**
This issue was also reported in [Bug #1965](https://github.com/education/classroom/issues/1965) but the fix suggested there does not apply to me as my user information appears to be correct. See the screenshot below which shows my profile picture in the commit information.
<img width="990" alt="image" src="https://user-images.githubusercontent.com/13131021/60929981-f80adb80-a2cc-11e9-902e-9d8a7a5cbf3c.png">

**Comment by d12** [comment]
@waqarsaleem This has been resolved by https://github.com/education/classroom/pull/1975, your starter code import should now work as expected!

**Comment by waqarsaleem** [comment]
> @waqarsaleem This has been resolved by #1975, your starter code import should now work as expected!

Acknowledged and homework assigned to the students. Thanks!

I hope the issue is permanently resolved by next week when the next homework goes out.
