### ISSUE TITLE
Most common use cases for GitHub by educators?

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#2]
According to http://education.github.com there are two common ways for handling assignments.

* [Forks](https://education.github.com/guide/forks)
* [Sandboxing](https://education.github.com/guide/sandboxing)

I know personally the classes that I graded for practiced sandboxing, but that may not be the most common use case.

Is there any research or data that could give us an insight as to what method(s) would be most useful to have? My goal would be to eventually handle the most common use cases, but I'd like to at least get the one that helps the most people to fit into current summer timeline.

**Comment by johndbritton** [comment]
> I know personally the classes that I graded for practiced sandboxing, but that may not be the most common use case.

This has been the preferred method, especially for introductory level courses. Forking is most commonly found in project based courses and those classrooms are usually quite capable of handling the administrative burden.

**Comment by tarebyte** [comment]
We actually used sandboxing for group projects but maybe that wasn't the most efficient way of doing it :stuck_out_tongue_closed_eyes:

In any case I'd like to have educators be able to use both cases of sandboxing (individual and group projects). This seems like a pretty reasonable thing to handle on for the application.

Do you have a preferred way of planning user flows for applications? If not I was just going to make a diagram using something like https://www.lucidchart.com/

**Comment by johndbritton** [comment]
> If not I was just going to make a diagram using something like https://www.lucidchart.com/

That works for me. Sketching out the major use cases seems like a good idea.
