### ISSUE TITLE
Octokit caching is overly aggressive

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#200]
With one of my test accounts, I went to create an organization on the classroom app. The account doesn't have any GitHub orgs, so I clicked the `create an organization on GitHub.com` button and created an org on GitHub. When I went back to the classroom app, it still said I didn't have any GitHub organizations. Probably a caching issue? Kind of a frustrating experience for a user.

**Comment by mastahyeti** [comment]
The problem was actually that I hadn't granted access for the new org to the oauth app.

**Comment by mastahyeti** [comment]
Still confusing though.

**Comment by tarebyte** [comment]
Probably should tell the user they need to grant access on that same page. Thanks for the feedback @mastahyeti!
