### ISSUE TITLE
Reusable set of teams

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#201]
I always have a hard time naming my "reusable set of teams". What if we don't let the user provide a name and just create the first set for them. The second time through we can ask them if they want to use the same teams as before, or create a different set.

Maybe give the set a name based on date or something like that.

**Comment by tarebyte** [comment]
We could also give a suggested name and let them change it if they wanted to.

I know for the classes I work with we have `Project Groups` and `Tech Teams`

**Comment by johndbritton** [comment]
That might work too. I guess my point is that it's a strange input field that I don't necessarily understand as a new user and it'd be nice if it was simpler.
