### ISSUE TITLE
Untangle Google Classroom functionality from RostersController

### ISSUE THREAD

**Issue by thebradbain** [education/classroom#2023]
Currently, Google Classroom functionality is extremely coupled with `Orgs::RostersController` and its views, so much so that almost every action within `RostersController` interacts with Google Classroom in some way.

<img width="749" alt="Screen Shot 2019-07-16 at 6 22 41 PM" src="https://user-images.githubusercontent.com/2936741/61340375-e5296700-a7f6-11e9-9769-5e294d823d2c.png">

This doesn’t seem deliberate (but I may be wrong! I haven’t interacted too much with this code), as right now it doesn't look possible to interact with Google Classroom outside of `RostersController`, including authentication.

Once LMS / Google Classroom integration is in a stable state, we should probably consider refactoring -- I'd love to help out! 

Also tagging any other interns in case anyone is looking for another project 👀

**Comment by d12** [comment]
Currently this is all in the rosters controller because all of the UI interactions with google classroom is on roster/show! We have a meeting today with @brandonrosage to discuss how to better design this feature which will help in this code untangling.

**Comment by stephaniegiang** [comment]
I'm going to take this over. Since moving the Google Classroom to a new UI, I'm already doing a lot of this. So by the end of it, it should be entirely untangled!

**Comment by stephaniegiang** [comment]
Now completely removed from Rosters Controller 🎉 
PR #2074
