### ISSUE TITLE
Strange error creating an org

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#203]
<img width="653" alt="2015-09-11 at 10 38 am" src="https://cloud.githubusercontent.com/assets/1144197/9820473/7f8af9c8-5871-11e5-8178-15ddfb2568d7.png">

I had created a classroom org with my @foobartestorg GitHub org previously, but deleted it. Trying to make the org again, I'm getting a cryptic error.

**Comment by tarebyte** [comment]
@mastahyeti something went wrong with the background job for deleting the organization, it is in a soft delete state.

**Comment by mastahyeti** [comment]
:cool:

**Comment by tarebyte** [comment]
@mastahyeti I had rejected the tokens, debugging something else and therefore the organization was not removed properly.

The organization has now been deleted.
