### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by shaunakpp** [education/classroom#2039]
**Needle**: https://haystack.githubapp.com/classroom/needles/YmQK5jIL7Eb4P2uwZMUDkw
**Rollup**: https://haystack.githubapp.com/classroom/rollups/ca7420a2466a97e9cb707cc61b95fefc

```
ActionView::Template::Error
undefined method `user_login' for #<AssignmentRepo:0x000056220c0c1cf8>
Did you mean?  user_id
```

<table>
  <thead>
    <tr>
      <th>attribute</th>
      <th>value</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>cause</td>
      <td><pre>NoMethodError: undefined method `user_login&#39; for #&lt;AssignmentRepo:0x000056220c0c1cf8&gt;<br>Did you mean?  user_id<br>	/app/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.7/lib/active_model/attribute_methods.rb:432:in `method_missing&#39;<br>	/app/vendor/bundle/ruby/2.4.0/gems/pg_search-2.2.0/lib/pg_search.rb:81:in `method_missing&#39;<br>	/app/app/views/stafftools/assignment_repos/_assignment_repo.html.erb:10:in `block in _app_views_stafftools_assignment_repos__assignment_repo_html_erb__1256608890027433574_47352123825220&#39;<br>	/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/capture_helper.rb:39:in `block in capture&#39;<br></pre></td>
    </tr>
    <tr>
      <td>class_name</td>
      <td>ActionView::Template::Error</td>
    </tr>
    <tr>
      <td>method</td>
      <td>POST</td>
    </tr>
    <tr>
      <td>params</td>
      <td>{}</td>
    </tr>
    <tr>
      <td>referrer</td>
      <td>nil</td>
    </tr>
    <tr>
      <td>remote_ip</td>
      <td>140.82.115.70</td>
    </tr>
    <tr>
      <td>ruby</td>
      <td>ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]</td>
    </tr>
    <tr>
      <td>session</td>
      <td>{}</td>
    </tr>
    <tr>
      <td>time</td>
      <td>8.012815863</td>
    </tr>
    <tr>
      <td>url</td>
      <td>https://classroom.github.com/github/hooks</td>
    </tr>
    <tr>
      <td>user_agent</td>
      <td>GitHub-Hookshot/4104263</td>
    </tr>

  </tbody>
</table>

<details>
<summary>Backtrace</summary>
<pre>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activemodel-5.1.7/lib/active_model/attribute_methods.rb:432:in `method_missing&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/pg_search-2.2.0/lib/pg_search.rb:81:in `method_missing&#39;</span>
<span class="l">/app/app/views/stafftools/assignment_repos/_assignment_repo.html.erb:10:in `block in _app_views_stafftools_assignment_repos__assignment_repo_html_erb__1256608890027433574_47352123825220&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/capture_helper.rb:39:in `block in capture&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/capture_helper.rb:39:in `capture&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/tag_helper.rb:272:in `content_tag&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/url_helper.rb:198:in `link_to&#39;</span>
<span class="l">/app/app/views/stafftools/assignment_repos/_assignment_repo.html.erb:9:in `_app_views_stafftools_assignment_repos__assignment_repo_html_erb__1256608890027433574_47352123825220&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/template.rb:157:in `block in render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/template.rb:352:in `instrument_render_template&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/template.rb:155:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/partial_renderer.rb:310:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/renderer.rb:47:in `render_partial&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/renderer.rb:21:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/helpers/rendering_helper.rb:31:in `render&#39;</span>
<span class="l">/app/app/helpers/stafftools_resource_render_helper.rb:6:in `render_stafftools_resource&#39;</span>
<span class="l">/app/app/views/stafftools/resources/_search_results.html.erb:11:in `block (2 levels) in _app_views_stafftools_resources__search_results_html_erb__3320074691705183898_47352124147820&#39;</span>
<span class="l">/app/app/views/stafftools/resources/_search_results.html.erb:10:in `each&#39;</span>
<span class="l">/app/app/views/stafftools/resources/_search_results.html.erb:10:in `block in _app_views_stafftools_resources__search_results_html_erb__3320074691705183898_47352124147820&#39;</span>
<span class="l">/app/app/views/stafftools/resources/_search_results.html.erb:4:in `each&#39;</span>
<span class="l">/app/app/views/stafftools/resources/_search_results.html.erb:4:in `_app_views_stafftools_resources__search_results_html_erb__3320074691705183898_47352124147820&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/template.rb:157:in `block in render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/template.rb:352:in `instrument_render_template&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/template.rb:155:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/partial_renderer.rb:310:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/renderer.rb:47:in `render_partial&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/renderer/renderer.rb:21:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/rendering.rb:103:in `_render_template&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/streaming.rb:217:in `_render_template&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/rendering.rb:83:in `render_to_body&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:52:in `render_to_body&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/renderers.rb:141:in `render_to_body&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/abstract_controller/rendering.rb:24:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:36:in `render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/core_ext/benchmark.rb:12:in `block in ms&#39;</span>
<span class="l">/app/vendor/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/core_ext/benchmark.rb:12:in `ms&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:44:in `block in render&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:43:in `render&#39;</span>
<span class="l">/app/app/controllers/stafftools/resources_controller.rb:11:in `block (2 levels) in search&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/mime_responds.rb:201:in `respond_to&#39;</span>
<span class="l">/app/app/controllers/stafftools/resources_controller.rb:10:in `search&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:186:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:131:in `run_callbacks&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.7/lib/action_view/rendering.rb:30:in `process&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/peek-performance_bar-1.2.0/lib/peek/views/performance_bar/process_utilization.rb:144:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:192:in `call!&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/strategy.rb:169:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/omniauth-1.9.0/lib/omniauth/builder.rb:64:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-tracker-1.4.0/lib/rack/tracker.rb:36:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/pinglish-0.2.1/lib/pinglish.rb:42:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/failbot-2.0.1/lib/failbot/middleware.rb:16:in `block in call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/failbot-2.0.1/lib/failbot.rb:113:in `push&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/failbot-2.0.1/lib/failbot/middleware.rb:13:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:19:in `block in call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/chewy-5.0.0/lib/chewy/railtie.rb:19:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/lograge-0.6.0/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/ssl.rb:68:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host.rb:19:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-4.4.0.336/lib/new_relic/agent/instrumentation/middleware_tracing.rb:92:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/configuration.rb:228:in `call&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/server.rb:657:in `handle_request&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/server.rb:467:in `process_client&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/server.rb:328:in `block in run&#39;</span>
<span class="l">/app/vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread&#39;</span>
</pre>
</details>

*Brought to you by Haystack's `!` hotkey.  Try it on a needle or rollup today!*

**Comment by EricPickup** [comment]
I noticed this happening when using stafftools search that @d12 updated. Good news is it's not user-facing. Bad news is, doesn't that mean the backfill didn't complete properly?

**Comment by d12** [comment]
Ah, this is just some old code trying to render a ActiveRecord object using logic written for ES objects. I'll update the logic today.
