### ISSUE TITLE
Direct object reference of grouping id: Can get added to any org/group-team

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#205]
Alright, this is a bit complicated, so let me know if I do a :shit: job of explaining it.

We have the good guys: @goodTeacher and @goodStudent. @goodTeacher, creates @goodOrg on GitHub and GoodOrg on the classroom app. @goodTeacher creates GoodAssignment on the classroom app with a grouping called GoodGrouping. GoodGrouping gets a database ID of 123. @goodStudent follows the assignment invite link and accepts it, creating GoodTeam on classroom and @goodOrg/goodTeam on GitHub.

Meanwhile, we have the bad guys: @badTeacher and @badStudent, both of which are actually owned by Bad Person. @badTeacher creates @badOrg on GitHub and BadOrg on the classroom app. @badTeacher creates BadAssignment on the classroom app with a grouping called BadGrouping. BadGrouping gets a database ID of 124.

Now, when creating a second assignment, BadAssignment2, @badTeacher sees a dropdown list of team groupings to choose from. @badTeacher selects BadGrouping and submits the form, intercepting the HTTP request with a proxy like Burp Suite. @badTeacher changes the `group_assignment[grouping_id]` parameter in the request from 124 to 123 and then sends the request on its way. The response comes back like normal, giving @badTeacher a invite link to send to her students.

@badStudent clicks the invite link for BadAssignment2. In the `Join an existing team` dropdown, they see that they can join GoodTeam, so they do. The classroom app adds @badStudent to the @goodOrg/goodTeam.

This process could be repeated to get access to any group team created by the classroom app.

**Comment by tarebyte** [comment]
That was very clear scenario.
