### ISSUE TITLE
Direct object reference of group id: Can get added to any org/group-team

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#206]
Similar to https://github.com/education/classroom/issues/205, an attacker can choose a team from any org on the invitation-accept page by modifying the `group_id` parameter. This will cause the attacker to be added to the victim's team on GitHub.

**Comment by tarebyte** [comment]
Should these checks be done on the controller or the model?

**Comment by tarebyte** [comment]
Also is there a better pattern for forms that I can be using for forms to prevent things like this?

**Comment by mastahyeti** [comment]
Generally the fix for a direct-object-reference issue is to scope the query. For example, instead of

```ruby
Widget.find_by_id params[:id]
```

you might do 

```ruby
current_user.widgets.find_by_id params[:id]
```

I'm not sure though if that applies to this case. Regardless, I think checking in the controller is good, so it can be caught early on. Having a model validation that ensures that the groups/groupings/repo_accesses/users/orgs all make sense would be good to have as well.

**Comment by mastahyeti** [comment]
> Also is there a better pattern for forms that I can be using for forms to prevent things like this?

Not really. Some times you just need to pass an ID.
