### ISSUE TITLE
Disable browser autocomplete on deadline text field

### ISSUE THREAD

**Issue by d12** [education/classroom#2066]
<img width="627" alt="Screen Shot 2019-07-22 at 3 17 01 PM" src="https://user-images.githubusercontent.com/30920216/61658662-d548d180-ac93-11e9-9517-099c7c9b95e7.png">

The browser autocomplete is blocking the calendar. Let's :fire: the autocomplete on this field.

**Comment by GQuirino** [comment]
can i take a look this issue?

**Comment by d12** [comment]
Please! Ping me on this issue or a PR if you need a hand :)
