### ISSUE TITLE
Move repo templates API logic to GitHubOrganization

### ISSUE THREAD

**Issue by shaunakpp** [education/classroom#2075]
We just shipped the new repo templates feature! 🎉 
As part of the quick ship and the evolving API for cloning repositories, we kept the logic for calling the API in the creators and now that the feature is deployed we can move the logic to `GitHubOrganization` and have a more consistent logic. Just like we have `GitHubOrganization#create_repository` we could have a method for repo templates on the lines of `GitHubOrganization#create_repository_from_templates`.

@d12 and @EricPickup what are your thoughts on this?

**Comment by EricPickup** [comment]
Already working on this in a PR! 😄

**Comment by d12** [comment]
:100:, sounds good to me!
