### ISSUE TITLE
Sorting classroom dashboard

### ISSUE THREAD

**Issue by EricPickup** [education/classroom#2085]
### Feature request :sparkles:
This issue/comment describes it all: https://github.com/education/classroom/issues/602#issuecomment-514722539

Currently the classroom dashboard sorts classrooms by date created (oldest first) and 12 per page. For teachers who use Classroom for multiple classes for multiple terms, this can make it very difficult to find their active classrooms.

We already have searching and can look at this recent PR: https://github.com/education/classroom/pull/1889 for help.

**Comment by thebradbain** [comment]
This should be very easy from a backend perspective thanks to #1889. #1982 specifically uses the new functionality introduced in it for searching on cached github attributes, and may be a little easier to digest.
