### ISSUE TITLE
Download Repositories disabled for Assignment with Repositories

### ISSUE THREAD

**Issue by waqarsaleem** [education/classroom#2093]
**Describe the bug**
The __Download Repositories__ button is disabled for an assignment even though students have created repositories for it.

**To Reproduce**
1. Go to the relevant assignment in GitHub Classroom.
2. Click on the __Download Repositories__ button.
3. No scrolling necessary.
4. See the error below. The button is grayed out even though student repositories exist.
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/13131021/61852103-0f9fb200-aed2-11e9-87ca-13c6975db270.png">

**Expected behavior**
The __Download Repositories__ button should be enabled.

**Screenshots**
See the screenshot above.

**Additional context**
This is the first individual assignment in the course. All previous assignments were group assignments. The assignment was initially set mistakenly without a starter code repository and some students checked out the assignment in that state. I manually pushed files to their repository and added a starter code repository to the assignment for later students. Not all students have checked out their own repository.

**Comment by stephaniegiang** [comment]
Hi @waqarsaleem 👋 thanks for the report!
Took a look into this and it seems like if not all students accepted the assignment, the button is disabled. This is isn't the expected behavior. 

We will let you know here, when this is resolved.

**Comment by d12** [comment]
cc @srinjoym

**Comment by waqarsaleem** [comment]
> Hi @waqarsaleem 👋 thanks for the report!
> Took a look into this and it seems like if not all students accepted the assignment, the button is disabled. This is isn't the expected behavior.
> 
> We will let you know here, when this is resolved.

Thanks @stephaniegiang for the quick action. I downloaded the repositories manually yesterday but am glad that I will be able to do it automatically in the future.
