### ISSUE TITLE
Students are not given access to their repos on acceptance of an assignment

### ISSUE THREAD

**Issue by belgort-clark** [education/classroom#2111]
**Describe the bug**
When a student accepts an assignment, they don't have access to the repository. The student repos are private for the assignment. I had to manually add them as a collaborator.

**To Reproduce**
1. Student accepts assignment
2. Tries to clone down the assignment using the URL after repo creation
3. Student cannot access repo
4. The instructor has to manually invite them to the repo

**Expected behavior**
This was working up until a few hours ago. New repos are having this problem

**Comment by EricPickup** [comment]
Hi @belgort-clark, I'm taking a look at this right now. Would you be able to provide some more context such as whether this was a group or individual exercise, how often this is occurring when your students accept the assignment, and the assignment link if possible?

**Comment by belgort-clark** [comment]
Hi!

Here are the two assignments experiencing the problem:

https://classroom.github.com/classrooms/16167463-ctec-121-summer-2019/assignments/module-3-problem-set-no-3

https://classroom.github.com/classrooms/16167463-ctec-121-summer-2019/assignments/module-3-problem-set-no-4

It's an individual exercise and started happening today.

Does this help?

**Comment by belgort-clark** [comment]
@EricPickup were you able to reproduce the error?

**Comment by belgort-clark** [comment]
A student just created a repo via an assignment and their name was in fact on the list of collaborators.

**Comment by EricPickup** [comment]
@belgort-clark I wasn’t able to reproduce the issue but I’ll leave this open for now in case it comes up again.

**Comment by belgort-clark** [comment]
Thanks. I will keep an eye on new repos to see if the students are being added correctly. Thank you for your assistance.

**Comment by belgort-clark** [comment]
I have not seen this issue appear again. This bug can be closed.

**Comment by EricPickup** [comment]
Thanks for keeping us updated @belgort-clark!
