### ISSUE TITLE
Multiple Repositories Created from Clicking Assignment Accept Link once

### ISSUE THREAD

**Issue by Sallenmoore** [education/classroom#2123]
When clicking on an assignment link once, multiple repositories are created with the '-n' suffix.
I have verified that this happens to almost all students, and that they are only clicking the assignment link one time.

**Comment by d12** [comment]
@Sallenmoore I tried reproducing and didn't get multiple repositories created. Could you specify exactly how you're reproducing? Thanks

**Comment by Sallenmoore** [comment]
I am just clicking on the accept assignment link. Here is a screenshot:
<img width="528" alt="Screen Shot 2019-07-30 at 10 44 32 AM" src="https://user-images.githubusercontent.com/520255/62144110-3dfd0300-b2bf-11e9-9979-e17498426cee.png">

**Comment by stephaniegiang** [comment]
Hello 👋
Just have a question, for the assignment are you using the source importer or template repos?

**Comment by Sallenmoore** [comment]
For that assignment, I used the template repository. I switched to the template repositories because I was hoping it would fix the problem (and they are a great idea!). However, I believe the problem occurred on both kinds of repos.

**Comment by stephaniegiang** [comment]
Could you give us the classroom name where this is happening?

**Comment by Sallenmoore** [comment]
binghamtonuniversity-cs110

Here is the url as well:
https://classroom.github.com/classrooms/34315140-cs-110-introduction-to-programming-with-python

-- Steven A Moore

**Comment by stephaniegiang** [comment]
We are adding some debugging info to the application. We will get back to you on this issue once we collected some data on this.

**Comment by EricPickup** [comment]
Just had this issue pop up again. Created an assignment, accepted it, got "Success" in creation progress bar then the page refreshed and restarted the creation. Ended up with 3 repos. Happened again the next time with only 2 repos created. I wasn't able to reproduce it again afterwards.

**Comment by stephaniegiang** [comment]
Looking into this, I will update this issue 😄

**Comment by Sallenmoore** [comment]
This is still happening. Any progress on the issue?

**Comment by d12** [comment]
cc @education/classroom-reviewers

**Comment by Sallenmoore** [comment]
FYI - I created a new organization, and it doesn't seem to be happening in the new organization. Could it be an old API issue that's been carried along with the organization?

**Comment by stephaniegiang** [comment]
Sorry it has taken so long to get an answer. 

> This is still happening. Any progress on the issue?

☝️ Is this happening within the same organization you mentioned earlier on?

Still looking into this to see if anything pops up our side. Will update when I have something 😄

**Comment by Sallenmoore** [comment]
Yes, it is still occurring in the previous organization. I moved the class to a new organization, and that seemed to solve the issue. For my part, I'm considering the issue solved, but I am willing to provide whatever assistance/info you may need to look further into it if you want to.

**Comment by andrewbredow** [comment]
@Sallenmoore Thank you for the update! We'll re-open this if it comes up again.
