### ISSUE TITLE
Sync Google Classroom archiving with GitHub Classroom

### ISSUE THREAD

**Issue by EricPickup** [education/classroom#2138]
With our Google Classroom integration, we can make archiving a class in GitHub Classroom archive the class in Google Classroom.

We should decide if we want to do this automatically or with a prompt.

cc @stephaniegiang

**Comment by stephaniegiang** [comment]
@d12 what do you think?

I think it would be cool for teachers in the end of the semester, to go through classrooms they want to archive and then also archive the google ones at the same time. 

But, this is something that I think would differ fro the other LMSs as that is not a functionality we could do.

**Comment by d12** [comment]
Let's hold off on this for now. I'd like to keep the integration functionality the same between all LMS's for now until we decide there's a good enough reason to start diverging. As soon as different LMS's have different functionality, user messaging gets a lot more complicated.
