### ISSUE TITLE
Organization name on mobile view needs "@"

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#214]
On mobile, the organization name doesn't have an "@" symbol prefixed in `Organizations#show`

**Comment by tarebyte** [comment]
@johndbritton Are you referring to header?

![ios simulator screen shot sep 15 2015 12 23 34](https://cloud.githubusercontent.com/assets/564113/9882821/9bdd451e-5ba4-11e5-982e-c4fd7505c52a.png)

**Comment by johndbritton** [comment]
Sorry, my bad. It's on the organization listing page, what used to be called "dashboard."
