### ISSUE TITLE
Not permitted to add organization as a classroom

### ISSUE THREAD

**Issue by greg-longo** [education/classroom#2197]
I'm following the steps [https://www.youtube.com/watch?v=MjYiNdFsvzI&feature=youtu.be](url) provided to add my organization to a classroom.  I did the following:

- Created a new organization
- Went to classroom.github.com
- Clicked 'Create your first classroom'
- Granted access to GitHub classroom
-  Returned to classroom, refreshed, and attempted to "Select an organization for your new classroom" and the following appears:

![image](https://user-images.githubusercontent.com/42187719/62655755-aa67aa00-b930-11e9-9fb9-deced6a4268d.png)

I thought perhaps it was the organization, which is why I have the 'test' organization, but the issue persists.  

One thing I noticed was in github.com my username is greg-longo, but on classroom its greglongo6.  I attempted to sign out from classroom and sign back in, but it remains greglongo6 even when logging in with username greg-longo.

Any ideas?

**Comment by d12** [comment]
Hey! Thanks for raising this issue, we did a bit of digging and caught a few bugs in the codebase. I've opened https://github.com/education/classroom/pull/2198 to fix them up, but in the mean time, I've manually fixed your user account. You should be good to go :)

**Comment by greg-longo** [comment]
Thanks!
