### ISSUE TITLE
Deleting roster entries that are not associated with an active roster

### ISSUE THREAD

**Issue by stephaniegiang** [education/classroom#2212]
We currently do not delete roster entries when we delete a roster.

With this PR https://github.com/education/classroom/pull/2211 we should think about running a job to delete the 61,000+ roster entries that are not associated to a roster.

**Comment by JessRudder** [comment]
@stephaniegiang, looks like the related PR has been merged in. Is there a cleanup issue we need to do as a follow on (to remove the roster-less roster entries)?

If not, please feel free to close this ticket!
