### ISSUE TITLE
Skewed images on Help Docs

### ISSUE THREAD

**Issue by andrewbredow** [education/classroom#2247]
**Describe the bug**

In Safari, the images in the new LMS docs are skewed... seems to be affecting all of them.

Browser|Screenshot
--|--
Safari|![Screen Shot 2019-08-14 at 9 47 03 AM](https://user-images.githubusercontent.com/96793/63026205-beebfb00-be78-11e9-88b4-1accb46296a0.png)
Chrome|![Screen Shot 2019-08-14 at 9 50 30 AM](https://user-images.githubusercontent.com/96793/63026321-fbb7f200-be78-11e9-8b08-3d922f9201f1.png)

Removing the `.d-flex` class from the image parent fixes the issue (though the images aren't centered). But maybe there is a better fix.

**To Reproduce**
1. Go to https://classroom.github.com/help/setup-generic-lms or one of the other help pages

cc @stephaniegiang @thebradbain

**Comment by thebradbain** [comment]
Very interesting. It appears to affect any support doc that has centered images, too: 

![image](https://user-images.githubusercontent.com/2936741/63040894-5fdbb580-be7b-11e9-8cc5-e949cf0b1198.png)

https://classroom.github.com/help/probot-settings

@mozzadrella should we uncenter all uncentered images in the meantime?

**Comment by d12** [comment]
cc @femmebot, Do you have ideas for why our styling classes are causing this?

**Comment by andrewbredow** [comment]
@thebradbain Another option, if that container isn't used for other content, is to center the images via margin.

Safari has some flexbox quirks (long time Safari user here).
