### ISSUE TITLE
Moodle LTS - Only allowing User IDs, not Names or Emails

### ISSUE THREAD

**Issue by dgilleland** [education/classroom#2254]
**Describe the bug**
After setting up GitHub Classroom as a preconfigured tool (etc.), when I click on the **Import from Moodle** link, the "Sync Roster from Moodle" page only give the User IDs as the student data to import (see screenshot).

I looked into the [troubleshooting](https://classroom.github.com/help/import-roster-from-lms#troubleshooting) portion of the instructions, but they didn't seem to help.

**To Reproduce**
1. In a Moodle (v.3.6) course, configure GitHub Classroom to be a pre-configured tool **as an instructor for a course** (not as a site administrator), with all appropriate settings
2. Go to GitHub Classroom to sync roster
3. Click **Import from Moodle**
4. See only one option (as per screenshot)

**Expected behavior**
I expected to see the more options on identifying students ([as per the documentation](https://classroom.github.com/help/import-roster-from-lms)):

> Select how to identify the imported students:
> 
> - **User ID:** The Student ID as stored in your institution’s learning management system
> - **Names:** Student full names
> - **Emails:** Student emails

**Screenshots**
![image](https://user-images.githubusercontent.com/4458296/63116972-1319dc80-bf58-11e9-9b44-f5192f5352d9.png)

**Additional context**
I am logged into Moodle as an instructor in the course. I do not have Moodle system admin rights. My instructor permissions allow me to set up a pre-configured tool.

**Comment by thebradbain** [comment]
Hello! 

This looks like it could possbily be a default privacy settings preference set by your school. Your institution may allow you to change the default settings for an external tool within Moodle via

1. Navigating to your pre-configured tool
2. Clicking the "gear" icon next to the dropdown for "Preconfigured tool"
3. Scroll down to "privacy"
4. For "share launcher's name with tool" or "share launcher's email with tool" (or both) select "Always" (you can leave "Accept grades from this tool" unchanged).

![image](https://user-images.githubusercontent.com/2936741/63119613-6f2f3180-bf55-11e9-88a9-6d64e73038d1.png)

**Comment by stephaniegiang** [comment]
Closing this issue as it has been resolved 😄
