### ISSUE TITLE
Private Assignment submission is viewable by the world

### ISSUE THREAD

**Issue by skrauskopf-nyos** [education/classroom#2277]
I am a CS teacher and my son happens to be in my class. So I did some testing with private assignment submission before using it in the classroom.

I created an organization.
I created a private repository in the organization (also tried doing with a personal private)
I created a classroom. 
I linked the classroom to my Google classroom.
I created a private assignment, with starter code linked to my private repository.
I received the link for the assignment.

I sent the link to my son.
My son accepted the assignment.
He uploaded some sort of response to the assignment and submitted.

From an incognito window, I can search by my son's github account and the assignment and his response shows. 

I have since removed the Google classroom from my Github classroom.

Private assignment submissions should not be visible, should they?

**Comment by stephaniegiang** [comment]
Hi @skrauskopf-nyos 👋 This shouldn't be the case. Private assignments should create private repositories. In this case, it is creating a public repository. 

We will take a look at this issue and update you when a fix has gone in 😄

**Comment by shaunakpp** [comment]
Hi @skrauskopf-nyos , thank you so much for reporting this issue to us! It has been fixed and deployed in #2280
