### ISSUE TITLE
Changing usernames messes up the accept assignment page

### ISSUE THREAD

**Issue by yttrian** [education/classroom#2313]
**Describe the bug**
After changing my username, the Accept Assignment page still wants to use my old username.

**To Reproduce**
1. Click a link for an assignment invitation (in the format https://classroom.github.com/a/some-random-code) and accept the OAuth permission request from GitHub Classroom
2. Change your username
3. Revisit the assignment invitation

**Expected behavior**
I expected the generated repository name would use my new username, not my old one.

**Screenshots**
![image](https://user-images.githubusercontent.com/5406616/63721863-219da900-c820-11e9-8dde-75d7fcc45f1f.png)
Username should be yttrian, and the profile button at the top also references the wrong username.

**Additional context**
I have not accepted the assignment yet, but need the generated repository name to use my current username in order to complete the assignment. I have tried logging out and back in, and revoking the OAuth grant.

**Comment by stephaniegiang** [comment]
Can you try again? Should be fixed now

**Comment by kw-lee** [comment]
I have the same problem. Isn't it fixed yet? 
<img width="1166" alt="Screen Shot 2019-09-17 at 10 57 36 PM" src="https://user-images.githubusercontent.com/17693194/65048185-aeaacc80-d99e-11e9-87b9-6e2da2aa6243.png">
When I clicked my profile, I was redirected to 'https://github.com/my_old_username' page
<img width="1166" alt="Screen Shot 2019-09-17 at 10 54 05 PM" src="https://user-images.githubusercontent.com/17693194/65048460-1cef8f00-d99f-11e9-89ff-ecf1e91c9912.png">

**Comment by stephaniegiang** [comment]
@kw-lee I'll take a look 😄

**Comment by stephaniegiang** [comment]
@kw-lee Can you try again? Should work now.

**Comment by kw-lee** [comment]
Yes! works very well. Thank you!

**Comment by stephaniegiang** [comment]
Awesome! I'm going to lock this issue. If there are any other issues, please open a new issue as they are easier for us to find 😄
