### ISSUE TITLE
Remove temporary logging for LMS

### ISSUE THREAD

**Issue by stephaniegiang** [education/classroom#2324]
I have added temporary logging for LMS. So we should remove this once all issues have been resolved.

Logging to remove
- [ ] https://github.com/education/classroom/pull/2323

**Comment by spinecone** [comment]
Should we consider leaving the logging in place (with a more specific rescued error like `JSON::ParserError`) to make it easier to diagnose future problems if they come up?

**Comment by stephaniegiang** [comment]
Yeah I was originally planning to do that. However, for some reason, the `JSON::ParserError` gets stuck in Papertrail and never ends up in Haystack. For now I think now we will leave the logging until we get a better idea of what is happening with Haystack.

**Comment by spinecone** [comment]
Specific error type is rescued in https://github.com/education/classroom/pull/2335

**Comment by stephaniegiang** [comment]
Going to close this issue, since we should probably leave the logging in place.
