### ISSUE TITLE
Getting Error When Attempting to Import My Roster From Canvas

### ISSUE THREAD

**Issue by cynthiateeters** [education/classroom#2336]
I'm looking for help on this error message when I try to import my Canvas roster. 

GitHub Classroom is unable to fetch membership from Canvas at this time. If the problem persists, re-launch GitHub Classroom from your learning management system and try again.

I tried multiple times installing with help from the site:
https://classroom.github.com/help/setup-canvas

I keep getting the above error. Thanks,

**Comment by stephaniegiang** [comment]
Hi @cynthiateeters 👋 When setting up your classroom, were you able to see a box called "Allow this tool to access the IMS Names and Role Provisioning Service"?

**Comment by cynthiateeters** [comment]
Hi Stephanie,

Thank you for reaching out to me.

I did finally find the discussion about that checkbox and that it is probably hidden. I have reached out to my admin with the link to the discussion and am waiting for her reply.

Sincerely,﻿


Cynthia Teeters, M.S.

Adjunct Assistant Professor

Interactive Digital Media & Web Development

Department of Arts and Design

Raritan Valley Community College

908-895-0160

Cynthia.Teeters@raritanval.edu

[1474919753230_rvcc_logo.png]
________________________________

**Comment by stephaniegiang** [comment]
Awesome! I'm going to close this issue for now. But feel free to re-open if this occurs again after the setting is turned on.
