### ISSUE TITLE
Title of Organization does not match GitHub's parameters

### ISSUE THREAD

**Issue by jules2689** [education/classroom#2337]
**Describe the bug**

My Organization has a long title:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/3074765/64078486-62c30c80-cca9-11e9-8801-c7c6ab3a3a98.png">

When I try to grant access in Classroom, it fails without a seemingly valid reason:
![2019-09-01 11-13-09 2019-09-01 11_13_47](https://user-images.githubusercontent.com/3074765/64078512-9aca4f80-cca9-11e9-883b-f2706119fefc.gif)

It took a moment to realize what was up as my org is only 5 letters long (then I remembered the long name in GitHub).

**To Reproduce**
1. Create an org with a long name
2. Grant access and try to create classroom on that org
3. Fail and see error

**Expected behavior**
Match the constraints of github.com

**Comment by jules2689** [comment]
Related PR: https://github.com/education/classroom/pull/248

@tarebyte do you have context as to why a limit of 60 was placed on orgs? https://github.com/education/classroom/pull/248#issuecomment-144863273 Seems to suggest that there's no specific reason.

**Comment by spinecone** [comment]
Looking at the validations on github.com, the limit for organization login names is only 40 characters, but profile names can be 255 characters. If we're copying over the profile name we should probably be using the 255 character limit instead.

**Comment by jules2689** [comment]
@spinecone For clarification, for [this org](https://github.com/dcsil/) where is says `Department of Computer Science Innovation Lab`, that is what failed. It used to say `Department of Computer Science Innovation Lab [University of Toronto]`

**Comment by spinecone** [comment]
Discussed with @femmebot and @stephaniegiang , the changes we'll want to make are:
- increase organization title limit to 255
- change organization thumbnails in dashboard from 4 per row to 3 per row
- remove @ from organization titles in dashboard

**Comment by jules2689** [comment]
https://classroom.github.com/classrooms/54954454-a-really-long-name-that-never-ends-it-goes-on-and-on-my-friends-some-people-starting-saying-it-not-know-what-it-was-but-they-ll-continue-saying-it-forever-just-because-goto-0-classroom-1

It works with https://github.com/testing-dcsil :smile:


I'll let you close this as it sounds you had other things you were using this to track as per https://github.com/education/classroom/issues/2337#issuecomment-528065535
