### ISSUE TITLE
Adding an organization doesn't work

### ISSUE THREAD

**Issue by giratikanon** [education/classroom#234]
When I click "Add your first organization" on the home screen for GitHub for Classrooms, then select an existing organization, I get this error message: 

![image](https://cloud.githubusercontent.com/assets/333527/10019510/e4f8d616-610b-11e5-8f8d-b3459b26b484.png)

I am one of the owners for the organization I tried.

**Comment by johndbritton** [comment]
Thanks for the report @giratikanon. What organization are you trying to add? Did you authorize the application to access that organization?

**Comment by romanpitak** [comment]
Same problem. I tried to add `romanpitak-classroom` which I created for that specific purpose. 

Note: I'm also a member of `docpad`, but not an owner and `docpad` was checked in by default in the list of organisations.

**Comment by johndbritton** [comment]
@romanpitak Would you be willing to invite me to that organization to help out with testing? I'd like to see if I can recreate the issue.

I'm able to add organizations without any issue.

**Comment by romanpitak** [comment]
@johndbritton invitation pending.

**Comment by nuk** [comment]
Same here, when trying to create an Organization attached to another with the same name.

**Comment by johndbritton** [comment]
@romanpitak I was able to add your organization without issue.

<img width="1026" alt="screen shot 2015-09-22 at 3 05 15 pm" src="https://cloud.githubusercontent.com/assets/123345/10020535/62f96ee8-613b-11e5-9a99-43b6b729bf87.png">

You should be able to access it at this url: https://classroom.github.com/organizations/13029875-software-engineering

**Comment by romanpitak** [comment]
@johndbritton Still not working for me. 

[classroom.github.com](https://classroom.github.com/) is giving me the same error as before:

> We're sorry, but something went wrong.

[your direct link](https://classroom.github.com/organizations/13029875-software-engineering) - is giving me a `404`:

> The page you were looking for doesn't exist.

> You may have mistyped the address or the page may have moved.

**Comment by johndbritton** [comment]
I think we've identified the issue, working on confirming and making a fix. Thanks for your patience.

I suspect we're experiencing something like this: https://github.com/plataformatec/faraday-http-cache/issues/38#issuecomment-40743361

**Comment by johndbritton** [comment]
@romanpitak @giratikanon @nuk Can you all give this another go and report back? I haven't been able to reproduce this myself, but I think it may be fixed.

**Comment by romanpitak** [comment]
@johndbritton seems to be working fine from my end :)

Thanks for the quick fix

**Comment by giratikanon** [comment]
Works now. Thank you!

**Comment by johndbritton** [comment]
@romanpitak Just as an FYI, I left your test organization. Thanks for your help with troubleshooting.

**Comment by nuk** [comment]
Working like a charm

**Comment by gurgelrenan** [comment]
Still not working here :(

**Comment by johndbritton** [comment]
@gurgelrenan Can you open a new issue with details of your error. I think we found the root cause of this issue, so you might be experiencing something different.
