### ISSUE TITLE
Starter Code Takes Forever 

### ISSUE THREAD

**Issue by xieyuxi1107** [education/classroom#2358]
Likes issues #1759, my starter code takes forever (10 hours and counting) to import too. The classroom is: https://github.com/EECS388-Classroom

To Reproduce Steps to reproduce the behavior:  
Go to https://classroom.github.com/a/80TPAyLe
wait 

Expected behavior The starter code should import, and I should see the starter code in the repository.  

screenshot:
![Screen Shot 2019-09-11 at 9 00 22 AM](https://user-images.githubusercontent.com/55000470/64699390-aa4c5400-d472-11e9-9466-0d96d9955f29.png)

**Comment by d12** [comment]
:wave: @xieyuxi1107, I see that assignment is using the source importer for starter code. We recently introduced a new beta method of importing source code via template repositories, would you mind giving that a try? It should resolve the timeout issues you're seeing.

To change, you can head to your assignment settings and look for the template repositories radio button under where you would select your starter code repository.

More info about template repositories: https://classroom.github.com/help/using-template-repos-for-assignments

**Comment by b2550** [comment]
I am experiencing the same issue as a student. I canceled the import after about 30 minutes of waiting but then there was no starter code so I used the invite link again. Now it is stuck again.

https://github.com/occs364s19/hw1-knn-benoberlin

**Comment by ggorman** [comment]
We are having the same issue. About half the class have no issues at all. The other half have a hanging import. Really annoying as the import should only contain a 500k README.md!

**Comment by d12** [comment]
@ggorman @b2550 I commented [earlier](https://github.com/education/classroom/issues/2358#issuecomment-530492914) about template repo imports, a new setting when creating or editing an assignment. Using this instead of the old porter method will resolve the hanging import issues.
