### ISSUE TITLE
Show exact deadline datetime on hover

### ISSUE THREAD

**Issue by d12** [education/classroom#2363]
When you set a deadline, this is what you see on on the assignment page:

<img width="252" alt="Screen Shot 2019-09-11 at 2 58 59 PM" src="https://user-images.githubusercontent.com/30920216/64726475-bc46ea80-d4a4-11e9-829a-ced78b2a31cf.png">

It's not very descriptive, it's hard to tell exactly what day it's talking about, and I don't know what time the deadline is at.

2 possible solutions:

a) Hovering can show the exact datetime
b) Change the text to be human readable but more useful. "This Friday at 8:00 am"?

cc https://education.github.community/t/github-assignment-date-what-time-zone/44939/2

**Comment by spinecone** [comment]
Right now we're using the `distance_of_time_in_words` function which is intended to convert a timestamp into human readable text; would it make sense to just add the exact time (formatted), so it would say something like `Deadline in 1 day (12/12/19 at 8:00 am)` ?

**Comment by d12** [comment]
Yes! We'll need to check what the users timezone is, we don't store it in the database so we'll have to check in JS.
