### ISSUE TITLE
I can't change the header background image

### ISSUE THREAD

**Issue by gdi2290** [education/classroom#237]
<img width="1195" alt="screen shot 2015-09-22 at 8 30 22 am" src="https://cloud.githubusercontent.com/assets/1016365/10022930/31b9e07e-6104-11e5-8801-f06e367bd57a.png">
rather than the green background I rather create my own

**Comment by johndbritton** [comment]
The header image is not configurable. We don't have any plans to implement this, but I'm marking it as a feature request to consider in the future.
