### ISSUE TITLE
Roster Management page 500 Internal Server Error

### ISSUE THREAD

**Issue by fly51fly** [education/classroom#2379]
**Describe the bug**
I tried to access Roster Management for 
https://classroom.github.com/classrooms/55371079-principle-of-web-search-2019-classroom
, then I got the 500 Internal Server Error

![未命名](https://user-images.githubusercontent.com/128885/65006631-390b1600-d936-11e9-9eec-a6409bd7bd15.jpg)

**To Reproduce**
Just access Manage Classroom - Roster Management

THX

**Comment by spinecone** [comment]
Hi @fly51fly , I've just pushed a change that should fix the problem you're seeing, could you try to access roster management for that classroom again?

**Comment by liffiton** [comment]
FWIW, I was having the exact same problem, and it is fixed now for me.

**Comment by fly51fly** [comment]
> Hi @fly51fly , I've just pushed a change that should fix the problem you're seeing, could you try to access roster management for that classroom again?

Fixed! Thank you!
