### ISSUE TITLE
daily/weekly/quarterly/yearly assignments

### ISSUE THREAD

**Issue by gdi2290** [education/classroom#238]
I'm unable to create daily assignments per-group or per-user

**Comment by johndbritton** [comment]
@gdi2290 This issue report is unclear. Are you experiencing an error, or is this a feature request?

**Comment by gdi2290** [comment]
sorry it's a feature request

**Comment by johndbritton** [comment]
@gdi2290 Could you give some more details about how you envision the feature working? We tried to keep things as simple as possible to start out, but we definitely want to listen to users and make improvements where warranted.

We can't promise to implement the feature, but we appreciate the requests, as they inform our future direction.

**Comment by gdi2290** [comment]
Ya I want to be able to assign a group of users to an assignment with a time limit and a review process

What's the workflow with an assignment? so far I see it's doing this

* create assignment
* send link to user

* secret team is created with their name
* user is added to secret team 
* user is presented with a copy of the starter repo
* assignment is the name of the assignment with a uuid


* no way to finish the assignment (finish means pull-request?)
* no way for the user to see the deadline
* no way to provide instructions other than the starter repo

**Comment by johndbritton** [comment]
@gdi2290 I think the process you outlined is beyond the scope of what we're able to commit to right now. I can see adding some additional features in the future around things like supporting a way to "finish" an assignment and have deadlines.

**Comment by gdi2290** [comment]
thanks for your time!

**Comment by johndbritton** [comment]
Thanks for the feedback, it's good to know what folks are looking for.
