### ISSUE TITLE
Unable to create a team after changing username

### ISSUE THREAD

**Issue by notslang** [education/classroom#2384]
I am a student who started using GitHub Classrooms a couple years ago for school. I changed my GitHub username from slang800 to notslang over the summer and now I am unable to create teams after being invited to a project in GitHub Classrooms.

This is the error that I get after typing in a team name on the "Accept the <assignment name> assignment" and pressing "+ Create Team":

![1568838833](https://user-images.githubusercontent.com/1049204/65184335-e8291980-da2a-11e9-96b7-a4a5063672fb.png)

It is also worth noting that the profile link in the top right corner of the page links to [slang800](https://github.com/slang800/) (a placeholder for my old profile).

I have tried having the teacher unlink my account, remove my school email address from the class entirely, and re-add me under a different non-school email address, but that changed nothing, even after I logged out and logged back in again. I also tried removing the GitHub classroom application from my own account, but after logging in and reauthorizing it I got the same error.

**Comment by d12** [comment]
:wave: @notslang, A fix for errors caused by account renames is coming soon, but I've went and fixed up your account! You should be good to go now :+1:

**Comment by halliganbs** [comment]
I am having the same issue, for the same classroom

**Comment by d12** [comment]
@halliganbs You're also all set :)
