### ISSUE TITLE
student private repos visible to other students

### ISSUE THREAD

**Issue by alexander-katrompas** [education/classroom#2392]
I have set up a classroom, set it so that only administrators can see the member (student) repos, the student repos are private, but the students can still each other's repos. How do I restrict them so students can only see their own repo?

**Comment by d12** [comment]
Hey @alexander-katrompas , did you manually add students as members of your organization, or as members of a team in the org? This can throw off the permissions system that Classroom manages. If you give us the name of your classroom and assignment, we can dig into this some more.

**Comment by alexander-katrompas** [comment]
I did manually add students as members of the organization. The organization is https://github.com/2019-Fall-COSC2436

The classroom is https://classroom.github.com/classrooms/55057076-cosc-2436-data-structures-fall-2019-classroom

The assignment is https://classroom.github.com/classrooms/55057076-cosc-2436-data-structures-fall-2019-classroom/assignments/linked-lists

I think the problem is I set permissions in the organization to "read" for members, and then in the classroom assignment I set "submit assignments using private repositories." So the student repos were private, meaning the outside world can't see them, but the students can see each other's because of the overriding "read" setting in the organization. I do not know that is true, but it's my guess because when I changed the organization permissions to "none" for members, the assignment settings worked as expected (students cannot see each other's repos).

What I was trying to achieve, and maybe I was going about it the wrong way, was letting students see organization repos (that's where I post solutions), but **not** see classroom assignment repos from other students. If that is possible to achieve, that is my goal. For now, I simply turned organization permission to "none." If there is a way to let all members of an organization see organization repos while at the same time keeping classroom assignment repos hidden from members (except me and the student owner), please let me know.

**Comment by d12** [comment]
This issue is tracking that particular problem: https://github.com/education/classroom/issues/1078

We're planning on building out something as part of GitHub Classroom that solves this, but for now, you'll have to do something more manual.

With default permissions set to "none", you can create a "students" team that all students are on. That team can be granted access to the repositories your students need access to. That should do what you're hoping to do here :)

https://help.github.com/en/articles/managing-team-access-to-an-organization-repository

**Comment by alexander-katrompas** [comment]
Thank you and that makes sense. I will work around the issue as you suggest.
