### ISSUE TITLE
Enterprise

### ISSUE THREAD

**Issue by hartmamt** [education/classroom#240]
Can this use GitHub enterprise?  We have the academic unlimited license and this would be a great service to offer on top of that.

**Comment by johndbritton** [comment]
@hartmamt Classroom for GitHub doesn't support GitHub Enterprise and we don't have a plan to add support right now.

That said, it is open source and it probably wouldn't be too hard for you to take the code and stand up an instance that works with your GitHub Enterprise. We use Octokit for all our GitHub API calls, their [enterprise docs](https://github.com/octokit/octokit.rb#working-with-github-enterprise) would be a good place to start.

Let's say it's not officially supported, but we'd consider accepting pull requests to add the feature.

Marking this as closed as there's no concrete action for us to take right now, but feel free to continue discussion.

**Comment by mdwheele** [comment]
@johndbritton I've implemented support for GitHub Enterprise to use Classroom at NC State. I've got some cleaning up to do, but the gist of the work was:

* New environment variables added to `.env.example`, `.env`, `config/secrets.yml`.
* Expand configuration of `GitHubClassroom.github_client` to pull environment variables that determine if integrated with GitHub Enterprise or not (i.e. `GITHUB_ENTERPRISE=true`, `GITHUB_ENTERPRISE_URL`)
* API / OAuth paths are resolved off the base URL of the instance according to GHE documentation.
* There were several instances of Classroom code instantiating the Octokit client directly. I patched all instances I could find to use the "singleton" reference from the `GitHubClassroom` module. There may have been specific reasons why code was doing this, so this will need extra scrutiny during code review.

For the most part, after updating Octokit configuration and wiring a few things to it, everything seems to work as expected. My next step is to verify tests are still passing and also verify that they are not passing vacuously. I intend to send a PR very soon; I just didn't want to waste your time on premature work.

Do you see anything obvious I'm missing? Not being a Rails / Ruby developer, I'm struggling a bit to find all the magic, haha.

/cc @hartmamt

**Comment by tarebyte** [comment]
@mdwheele how are you handing the use of Starter Code?

The API for that the source code importing: https://developer.github.com/v3/migration/source_imports/ is still under preview and as far as I'm aware not available for Enterprise yet.

**Comment by mdwheele** [comment]
Im open to suggestion on how to handle. Enterprise doesn't have that API yet so a simple option might be to disable the feature if integrated with GHE. Without knowing when/if that API will be released on GHE, it may be premature to carry technical debt of an alternative import implementation specific to GHE, but I'm willing. 

Most of my prospective users are currently provisioning repos with simple initial readme. Perhaps that might be an acceptable alternative (if the feature existed) for folks using enterprise right now. 

Right now, I'm down to work forwards whatever you'd prefer as far as direction. I can also put in a ticket on our support contract to see if this is coming soon or to get a general ballpark to educate our decision making here.

**Comment by hjmjohnson** [comment]
I too need an enterprise version of github classroom.

**Comment by farassadek** [comment]
I too need the enterprise github classroom

**Comment by basejumpa** [comment]
I also would like to use classroom with our GHE 2.14 instance at Continental AG

**Comment by SMUGSterling** [comment]
Agreed. GitHub Classroom on GHE would be amazing.

**Comment by mdwheele** [comment]
Hey @hjmjohnson @farassadek @basejumpa @SMUGSterling! As of #1163, Classroom can be configured to work with GitHub Enterprise. You should check it out and generate some feedback!
