### ISSUE TITLE
Downloading repositories via Github classroom - all fail

### ISSUE THREAD

**Issue by sierrajulietromeo** [education/classroom#2400]
Trying to download a set of class repositories using Github classroom helper. (Win 8 32bit).

Tried multiple times. All fail always.

![Capture](https://user-images.githubusercontent.com/30177706/65994495-51794580-e48b-11e9-948b-8032a32db872.PNG)

Assignment: https://classroom.github.com/classrooms/25031494-ada-unit-18-relational-databases-2019/assignments/python-sql-jupyter-notebooks

**Comment by d12** [comment]
:wave: @sierrajulietromeo , would you mind opening an issue in the Classroom Assistant repo? Someone should be able to lend a hand over there. https://github.com/education/classroom-assistant

**Comment by sierrajulietromeo** [comment]
Thank you. I shall close this one a few hours after posting over there.

**Comment by stephaniegiang** [comment]
Closing as duplicate issue posted in https://github.com/education/classroom-assistant/issues/147
