### ISSUE TITLE
Can't create private repos

### ISSUE THREAD

**Issue by gmporter** [education/classroom#2401]
**Describe the bug**
I applied to be a faculty member on Aug 6, and my username 'gmporter' was approved as a faculty member.  When I go into GitHub classroom, it won't let me create private repos, and instead says I need to apply.

**To Reproduce**
Scanned my ID, applied to be a faculty member on Aug 6.  On Oct 1, tried to create my first assignment and I can't select private repos.

**Expected behavior**
I should be able to create private repositories.

**Screenshots**

**Additional context**

**Comment by spinecone** [comment]
Hi @gmporter , does the organization you're using with this classroom have private repos enabled on it as well?

**Comment by gmporter** [comment]
I don't think so?  I used my person github account (gmporter) and applied
to be a faculty member and was approved.  Then I tried to create a new org
with it but that org doesn't have permission to create private repos.  Did
I do the setup correctly?

**Comment by spinecone** [comment]
@gmporter You'll also need to upgrade the organization, since the private repos will be created by the organization and not your own user account. There are more detailed instructions about this step at https://help.github.com/en/articles/applying-for-an-educator-or-researcher-discount#upgrading-your-organization

**Comment by gmporter** [comment]
Thanks.  It just keeps asking me to submit the proof that I'm a faculty
member.  Perhaps the proof expired or something?  In any case, I've
submitted proof again so hopefully that fixes the problem.
George

**Comment by d12** [comment]
I'm going to close this out, it looks like you just need to wait for approval. After being approved, there's a form at https://education.github.com/benefits that you can use to upgrade your Classroom organization. Please re-open if you need a hand :)
