### ISSUE TITLE
Student Accounts being Frozen

### ISSUE THREAD

**Issue by wmasek** [education/classroom#2406]
Students logging in to GitHub Classroom end up having their accounts temporarily frozen after multiple students login to the classroom in quick succession OR if one of them gets their password wrong multiple times. They end up with a login error citing suspicious login activity. The reason for this, I assume is because they are logging in from within the University Network and technically all share the same external IP address.

**Comment by d12** [comment]
@wmasek Unfortunately there's not much we can do on our side, it sounds like GitHub.com is blocking your students. I'd send them a message at https://github.com/support, they should be able to help you out.
