### ISSUE TITLE
"Add organization" page only shows some orgs

### ISSUE THREAD

**Issue by jrk** [education/classroom#241]
The drop down list only shows 3 of the orgs I'm involved in. I think this is only a subset of orgs I even created/own/administer. It notably doesn't include the org I just created for a new course (CS448H)

**Comment by tarebyte** [comment]
@jrk if you created the org after you authenticated into the application, then you have to give us access.

You may be able to resolve this by going here: https://github.com/settings/applications, selecting "Classroom for GitHub" and then authorizing your organization.

If that doesn't work please let me know!

**Comment by matz3** [comment]
Worked for me, thanks :+1:

**Comment by jrk** [comment]
Worked. Thanks. FWIW, I understand why app auth works this way, but it is quite confusing. It's worth thinking about ways to make the option to re-auth new repos for an app after initial registration much more straightforward. (Specifically, this should be visible in the *apps*, not just here, otherwise it appears that the apps are silently broken. I've run into this with Slack integrations and other things and always been confused before seeing this app permissions modification feature 5 clicks deep into settings.)

**Comment by johndbritton** [comment]
> It's worth thinking about ways to make the option to re-auth new repos for an app after initial registration much more straightforward.

Good point, I'll pass that along to our platform team.
