### ISSUE TITLE
Teams and assignment repos unable to load

### ISSUE THREAD

**Issue by englieh** [education/classroom#2412]
When I go to the classroom and assignment created, the teams and repo cannot be loaded.
![image](https://user-images.githubusercontent.com/6601940/66356228-e05ef400-e99c-11e9-96db-6419a12763ce.png)

**Comment by jeffrafter** [comment]
@englieh thanks for the report, I am looking into this.

**Comment by jeffrafter** [comment]
@englieh I am seeing this as fixed in production, sorry about the trouble!

**Comment by englieh** [comment]
No worries. Fixed. Thanks!
