### ISSUE TITLE
Commit count not updating

### ISSUE THREAD

**Issue by tobiasmayrtfo** [education/classroom#2417]
**Describe the bug**
On the assignment page, there is a list of teams which reports the number of students in a team and the number of commits done. Sometimes, the commit counter of certain teams stays at one, even though the teams already did push more than one commit. At the same time, the counter works fine for other teams.

**To Reproduce**
What I did to see the bug:
1. Create a team assignment, using a template repository with one commit.
2. Create teams.
3. Note that all commit counters are at one (because of the one commit in the template).
4. Commit and push to the repositories.
5. Note that the commit counter is increased for some teams, while it stays at one for other teams.

**Expected behavior**
The commit counter should always represent the correct amount of commits done to this repository.

**Screenshots**
The teams overview: Note that team "Haale Weggen" shows two commits, while "samuelsamuel" has only one commit.
![grafik](https://user-images.githubusercontent.com/32163051/66418255-fb178400-ea01-11e9-9b49-0c4f6357f2c4.png)

The two commits of team "Haale Weggen":
![grafik](https://user-images.githubusercontent.com/32163051/66418332-27330500-ea02-11e9-9b6c-3c5be58d58be.png)

The commits of "samuelsamuel", clearly a lot more than one:
![grafik](https://user-images.githubusercontent.com/32163051/66418370-3fa31f80-ea02-11e9-8872-a9585d9dbc08.png)

**Comment by d12** [comment]
@tobiasmayrtfo :wave:! The API we use to fetch commit counts ignores commits not tied to a GitHub user. It looks like those commits made by your student aren't setup to associate with their GitHub user. You can point them towards [this link](https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile#you-havent-added-your-local-git-commit-email-to-your-profile) to fix that up.

Once the student has corrected their config, all future commits will count in that sum.

Let me know if that works!

**Comment by tobiasmayrtfo** [comment]
Ooh, that makes sense, thanks!!

Tobi
