### ISSUE TITLE
Changing "View" filter results in a 406 error

### ISSUE THREAD

**Issue by robwhess** [education/classroom#2419]
**Describe the bug**
On the main classroom list page, if I make any change to the "View" filter dropdown, I am brought to an error page that says "406. Request not acceptable. The requested resource is unavailable in the format requested."  However, if I then navigate back to the main classroom list page, the change to the "View" filter appears to have taken effect.

**To Reproduce**
1. Go to the main classroom list page.
2. Click on the "View" filter dropdown.
3. Select any view option except the one currently selected.
4. See error.

**Expected behavior**
Selecting a new "View" filter option should update the classrooms displayed with no error.

**Screenshots**

![Screenshot 2019-10-08 15 18 22](https://user-images.githubusercontent.com/2029994/66437597-f9889480-e9de-11e9-8e9d-d33b84458b46.png)

**Comment by JessRudder** [comment]
Thanks for the report! We've dug in and it appears that this is an issue with Firefox the type of header Firefox is sending over in the request. It's an async request, but, it's asking for an html header instead of a js header (which seems to be a not uncommon Firefox issue).

We're working on a fix to make sure this will work correctly for Firefox.

In the meantime, you can get around this with the workaround you mentioned or by using Chrome or Safari (if you don't mind a temporary switch). Thanks for bearing with us while we get a fix in place.

**Comment by JessRudder** [comment]
@robwhess this should be resolved! You should now see the expected searching and filtering behavior on the `/classrooms` page when using Firefox.

Thanks again for letting us know about this issue!

**Comment by robwhess** [comment]
🎉 Thanks @JessRudder.  I can confirm that I'm now seeing the expected behavior.

**Comment by JessRudder** [comment]
Hey @robwhess this fix introduced a bug elsewhere that prevented accepting assignment invitations for students on some browsers so we had to revert. This means the sorting/filtering won't be working on Firefox again. We are working on fix for this again though.

**Comment by robwhess** [comment]
Foiled by my own students (#2431)!

No worries @JessRudder. This bug causes extremely minor inconvenience compared to students not being able to accept assignments.

**Comment by JessRudder** [comment]
Alright!

We should have proper sorting and filtering behavior for you (and other Firefox users).

AND the ability to accept assignments for your IE/Edge using students (and folks who use other browsers as well).

Thanks for the patience on this one.

**Comment by robwhess** [comment]
Yup, the sorting and filtering looks like it's working for me again.  Thanks for your work on this, @JessRudder 🍻
