### ISSUE TITLE
Student used assignment link to create repo, deleted repo, now cannot use link again

### ISSUE THREAD

**Issue by dcorsar** [education/classroom#2423]
**Describe the bug**
Created a new assignment, student accepted it created their own repository for it, deleted the repository, attepted to accept link again to restart but got a 404 page.

**To Reproduce**
1. Create an assignment - group or individual both have this issue.
2. Add a starter code repository. Note sure if this is necessary, but its what I did. 
3. Enable assignment invitation URL
4. Create the assignment
5. Have a student open the link, accept it, and create their own fork of the repo
6. Student then deletes their own repository
7. Student then opens the link again, accept it
8. Student get a 404 page, rather than being able to create a new repository. This is also present with group assignment

**Expected behavior**
Step 8. creates a new repository, rather than getting a 404

**Comment by d12** [comment]
Thanks for the report @dcorsar ! This is a bug, Classroom doesn't handle deleted repositories properly. We'll update this issue when a fix is put up.

In the mean time, I suppose you could make a new assignment with the same configuration for the student who deleted their repo. Sorry about that!

**Comment by dcorsar** [comment]
Thanks, for getting back to me @d12 

I'll follow your advice and create a new assignment and warn students not to delete their repo in the future!

**Comment by gstew5** [comment]
Hi, all. Is there a status update on this bug? I've also encountered it (I got the same 404 while doing a demo in class :-)).
