### ISSUE TITLE
importing class takes forever

### ISSUE THREAD

**Issue by jihelhere** [education/classroom#2424]
Describe the bug
Importing Starter Code takes forever to complete

To Reproduce
When clicking 'Accept the assignment' on previous window

Expected behavior
Assignment must have been completely loaded for me
![screenshot](https://user-images.githubusercontent.com/94481/66650147-2f708780-ec30-11e9-9721-899e605c50d2.jpg)

adding @nathanelnak @Badre-Dine

**Comment by d12** [comment]
:wave: In the assignment settings, are you using the source importer or template repo setting? 

<img width="668" alt="Screen Shot 2019-10-11 at 10 43 45 AM" src="https://user-images.githubusercontent.com/30920216/66660933-0e9a3900-ec14-11e9-9e56-15c7a52b37c8.png">

They're different methods of copying repos for students. Template repos are almost always the better choice, they don't have cloning issues like you're running into here.

Check out https://classroom.github.com/help/using-template-repos-for-assignments for more information!
