### ISSUE TITLE
How do I set up rbenv with Windows?

### ISSUE THREAD

**Issue by hmisonne** [education/classroom#2425]
I would like to access to GitHub classroom to work on projects with others.

I have forked the https://github.com/education/classroom repository and cloned it into a local repository. To get started I need to run in my command line script/bootstrap (to get the requirements). However I have this error message:
`"It looks like you don't have rbenv installed"`

I tried to go run this command :
`rbenv-installer/bin/rbenv-installer` from Git Bash and I have this message:
```
warning: gcc not found; using CC=cc
aborted: compiler not found: cc
Optional bash extension failed to build, but things will still work normally.
/c/Users/Helene/.rbenv/bin/rbenv: line 1: ../libexec/rbenv: No such file or directory
```
Then if I run :
`curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash`

I have this error message:
```
curl: (60) SSL certificate problem: self signed certificate in certificate chain.
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it.
```

How can I fix it?

**Comment by d12** [comment]
None of our developers work on Windows, we're not able to be helpful here :/ You'll find better help on StackOverflow or possibly the rbenv repository.
