### ISSUE TITLE
creating initial repository does not finish

### ISSUE THREAD

**Issue by lnazhand** [education/classroom#2429]
**Describe the bug**
In my GitHub classroom, ECE2534-F19, for the Project2 assignment, a few students are still waiting after several hours for the initial repository to be created after they accept the assignment. One of the IDs for the students is kafranz.

Thanks,
Leyla

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by d12** [comment]
:wave: In the assignment settings, are you using the source importer or template repo setting? 

<img width="668" alt="Screen Shot 2019-10-11 at 10 43 45 AM" src="https://user-images.githubusercontent.com/30920216/66660933-0e9a3900-ec14-11e9-9e56-15c7a52b37c8.png">

They're different methods of copying repos for students. Template repos are almost always the better choice, they don't have cloning issues like you're running into here. The experience for students is no different.

Check out https://classroom.github.com/help/using-template-repos-for-assignments for more information!
