### ISSUE TITLE
Open Classroom App from Third Party iOS app and preselect an account if gmail account is already logged In

### ISSUE THREAD

**Issue by mohitAppRinger** [education/classroom#2436]
I am trying to open Google Classroom App from my iOS app first, there is no Deeplink exposed from the same...then I opened the classroom app via opening classroom course URL inside the Safari browser and it is redirecting me to classroom app but it is making me select email account every time. 

Is there a way to simply pass the account email in URL and avoid the selection of email id again and again...if that account is logged in and have access to that particular course?

If the app is not downloaded...in the Safari browser if I am passing email id inside the URL it is redirecting me to the particular course instead of asking me to select email id again and again. But the same is not working in google classroom app.

**Comment by d12** [comment]
It seems like this is a question about Google Classroom, this repository is for the GitHub Classroom project.
