### ISSUE TITLE
Validation or correction of student's Github ID registration

### ISSUE THREAD

**Issue by stevecassidy** [education/classroom#2455]
### Feature request :sparkles:

I have 260 students in my class. Some have selected the wrong identifier when they signed up meaning they have the assignment repository within the organisation but they are linked to the wrong student ID. The person with that ID then can't find their ID to associate when they login, compounding the problem.  

In my case, identifiers are email addresses so sending a validation email would be possible, however I realise that this isn't generally the case. The only email we could send would be to the Github account owner. Even this might be useful though to catch cases where the user has claimed the wrong ID in error.  Send an email to the Github user: in course XXXYYY please verify that your identifier is ZZZZZZ.  

Better would be if there was a required (or optional) email address field in the roster that could be used for a validation email.  Then you could ask if @githubid is really yours to prevent someone's ID being claimed by another person. 

As an alternate, it would at least be good to allow a student to correct this error if they've made it. I'm not sure what Classroom looks like to the student but if there was a prominent display of the ID and a button to allow changing that it might be useful.

**Comment by d12** [comment]
Rolling this into https://github.com/education/classroom/issues/377

For now, there is the roster management UI where administrators can correct mistakes made by students.
