### ISSUE TITLE
IP Throttling / Blocking

### ISSUE THREAD

**Issue by THSCS** [education/classroom#2457]
It was suggested that I report this here. It's not specific to Classroom, but is a technical issue we're having using GitHub in the classroom.

**Describe the bug**
It appears that there are IP throttles in place.

In a class of about 25 students only about half were able to register for GitHub accounts at the same time. The ones that could not were getting a "Something went wrong" message in a red box near the username field. The console in Chrome was showing a 419 status header. 

Those that were not able to register were able to register later in the period so it seems like some type of throttling issue. 

In the next class we took a quiz first and then registered as they finished so registrations were spread out. Didn't have any problems that period. 

And I think related to all of us coming from the same external IP we've had issues where a couple of students mistyping their passwords has caused the entire lab to be blocked from logging in with an error about too many failed logins coming from the same IP. The ones that messed up their password only got it wrong once or twice.

**To Reproduce**
1. Multiple students go to register at GitHub. In my case it was about 25 students.

**Expected behavior**
They can register.

**Screenshots**

**Additional context**

**Comment by d12** [comment]
:wave: As you guessed, this is an issue specific to GitHub.com, not GitHub Classroom. There isn't much we can do on our side to prevent this type of rate limiting, would you mind reaching out to GitHub support at support@github.com?
