### ISSUE TITLE
Private accounts for students

### ISSUE THREAD

**Issue by oscarbenjamin** [education/classroom#2458]
Is there a way to create private Github accounts that are not visible in any way to the wider internet?

I am investigating the possibility of using Github classroom for a University class. We have to be careful about the privacy of students though. A github account has an associated publicly accessible page and makes it possible for anyone to contact the user e.g. through `@` references. We generally like our students to create an online profile but some students have good reasons for wanting not to be identifiable in any way online.

The only profile privacy setting I can see is being able to hide the email address of an account. Ideally we could create accounts for the students that have no identifiable profile and that are used for the purposes of the class only. Then afterwards those students who want to would be able to create a normal github account - I expect that most would do this but it should be their choice.

**Comment by d12** [comment]
:wave: @oscarbenjamin ! If you're using GitHub.com, the best you can do is hide email addresses and ensure your students don't put PII on their public-facing GitHub profile.

Another alternative would be to check out https://education.github.com/schools, which includes hosted GitHub Enterprise. That way, all the data is on your servers, and nothing is public-facing.

**Comment by oscarbenjamin** [comment]
Thanks @d12. I've filled out the form for the Campus Program and I'll see what happens there. Hiding email addresses might also be an option - I'll have to check...

What should I do with this issue? ISTM that many of the target users for classroom will face this problem and there doesn't seem to be any readily available guidance or advice.

**Comment by d12** [comment]
At this time, the only bullet-proof solution is to use hosted GitHub Enterprise. Because of how GitHub.com works, it'll be difficult to solve this in the mean time. I'll close this one out for now.
