### ISSUE TITLE
Stops accepting students after about 20 on an assignment?

### ISSUE THREAD

**Issue by ajarmst** [education/classroom#246]
After about 20 students accepting the invitation for an assignment, creating their repositories, the remaining students got a message claiming they'd exceeded the repository count, and suggesting they get an upgrade.  The students getting that message currently have 0 repositories.

I assume the limit they're hitting is on the classroom organization (CMPE1700-2015-Sep-A01) which should be subordinate to my program's NAIT-CNT organization.

Is this 20 repository limit a bug?  If it's a feature, I don't think it's going to work for us.

**Comment by ajarmst** [comment]
Ok, found the same issue on my organization page.  Yes, it appears we are hitting the "20 private repository" limit for the (free) plan that we were assigned when we first got our academic organization account.

If we were to use Classroom.Github, we would need on the order of (100 students * 6 courses/year * 20 assignments = ) 12,000 repositories per year.  As my tiny test run of 25 students for a single course bounced off the default limit during the very first assignment, that's a problem.

Your billing plans seem to indicate that I'd need 10 of your most-expensive "Aluminum" accounts each and every year to support the volume.  For a single Engineering program my tiny technical college.  I don't think that can be right.  I *know* there's no way I get it past capital expenditures, who have no idea at all what git, source-control or any of this is and why I might want it.

**Comment by tjhorner** [comment]
Well, it _is_ open source... you could fork it and change it to work on something like GitLab and host it yourself :)

**Comment by johndbritton** [comment]
@ajarmst The application stops making private repositories once you've reached your quota. You can request more private repositories at https://education.github.com/discount. Please be detailed in the additional information area of the request, and feel free to include a link to this comment, I'll do what I can to help you find a way to make things work for your courses.

My recommendation would be to create an organization for each course and request the number of repositories you need for each course.

**Comment by ajarmst** [comment]
Noting here for the sake of others.  After creating a new "classroom" organization, asking for a "discount" on education.github.com was honoured in a couple of days.  I can now create sufficient private repos for our needs.  Thanks.

**Comment by johndbritton** [comment]
Glad things got sorted for you, thanks for the update.
