### ISSUE TITLE
class room # creating error one 

### ISSUE THREAD

**Issue by kavindyasinthasilva** [education/classroom#2460]
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_
![Screenshot (27)](https://user-images.githubusercontent.com/49961072/68067947-bbc82300-fd74-11e9-908c-e85deb994c96.png)

**Comment by kavindyasinthasilva** [comment]
#you archived correct repository number and it use the your assigments

**Comment by d12** [comment]
This looks correct, you cannot create assignments in archived Classrooms.

**Comment by kavindyasinthasilva** [comment]
ok sir .ow it is done
