### ISSUE TITLE
Repo hangs on clone for one student for one assignment

### ISSUE THREAD

**Issue by carolinehardin** [education/classroom#2464]
**Describe the bug**
One of my students, when trying to clone the assignment, has it hang. It happens on multiple computers, but only for that student. That student has been able to clone everything else.

**To Reproduce**
Student goes to clone the repo for the assignment, clicks on it and waits

**Expected behavior**
It should complete
![IMG_20191030_134809](https://user-images.githubusercontent.com/4237204/68336193-c47d6980-0092-11ea-80cc-6323b2bc2399.jpg)

**Screenshots**

**Additional context**

**Comment by d12** [comment]
Hey @carolinehardin ! We haven't gotten any more reports lately, it seems this might have been a small hiccup. I'll close this, but please let us know if you run into this again.
