### ISSUE TITLE
Deadline calendar resets to current time when opening

### ISSUE THREAD

**Issue by EricPickup** [education/classroom#2466]
**Describe the bug**
Went to update the deadline for an assignment, and noticed that when I open the calendar, the time is reset to the current (default) time and when I close that calendar, it will update the time in the form to that time.

**To Reproduce**
1. Create an assignment with a deadline in the future
2. Edit the assignment
3. Click on the calendar
4. Date will be changed to current on the calendar widget
5. Focus out of calendar widget, date is now updated to current time (if you didn't modify it after it reset)

**Expected behavior**
When opening the widget with the deadline already set, the widget should reflect that date/time already saved.

**Screenshots**
![ezgif-2-767b1c4d16c8](https://user-images.githubusercontent.com/1490434/68611209-97142f80-0487-11ea-809f-d9447e29cc82.gif)

**Comment by d12** [comment]
Closing in favor of https://github.com/education/classroom/issues/2073 ❤️
