### ISSUE TITLE
how to verify who has committed to an assignment - multiple commits by different users

### ISSUE THREAD

**Issue by kkeoghfeduni** [education/classroom#2474]
### Feature request :sparkles:
_Please provide a description of the feature you would like Classroom to have_
It seems that students claim that their github name can be different based on what computer they use (home or university) so it is difficult to be sure that students are not having someone else doing their work. Is there a way to verify a github username with a student email for example?

**Comment by d12** [comment]
With Git, a commit can be authored as anyone, by anyone. The way to verify identities on GitHub is to use GPG key signing with Git. See https://help.github.com/en/github/authenticating-to-github/signing-commits

Commits that are signed will show as "VERIFIED" on the commits page: https://github.com/education/classroom/commits/master
