### ISSUE TITLE
Can't join group assignment after deleting associated team

### ISSUE THREAD

**Issue by maxwofford** [education/classroom#2479]
**Describe the bug**
I can't join a team or create a team on a group assignment because the "Max number of teams"  is being taken by a deleted team.

**To Reproduce**

1. Create a group assignment
2. Set the assignment's "Maximum number of teams" to 1
3. Sign up for the assignment & create a new team
4. Go to org's teams index page & delete the newly created team
5. Go to assignment's invite link
6. I can't join a team, or create a new team

**Expected behavior**
- I'd expect the deleted team to not show up on the invite page
- I'd expect the ability to create a new team

**Screenshots**
<img width="1028" alt="Screenshot 2019-11-25 16 50 31" src="https://user-images.githubusercontent.com/5891442/69583565-374e7600-0fa9-11ea-93e8-e9f10b43db42.png">
<img width="530" alt="Screenshot 2019-11-25 16 54 31" src="https://user-images.githubusercontent.com/5891442/69583683-7086e600-0fa9-11ea-978f-2dfc1f73b29a.png">

**Additional context**
Assignment in question is [here](https://classroom.github.com/classrooms/5633654-hack-club/group-assignments/dinoisseur-badge), with an invite link [here](https://classroom.github.com/g/zmuB8tC7)

**Comment by d12** [comment]
@maxwofford :wave:! Looks like we're running into some sort of undefined behavior here, we don't advise deleting teams off of GitHub.com when using GitHub Classroom. We have an open issue here for better management of teams in general when using GitHub Classroom: https://github.com/education/classroom/issues/292

The workaround for now is to create a new assignment if this were to happen. If you'd like us to repair this specific assignment, let me know :)

**Comment by maxwofford** [comment]
Seems like an issue with soft-deletion of teams. Will avoid doing this in the future. I'd appreciate it if you can disassociate the "all" team from the assignment on the backend.

**Comment by maxwofford** [comment]
I've gone ahead and just nuked the assignment & restarted from scratch– no need to make changes on the backend. Seems like this is a specific bug under the scope of #292, and seeing that other bugs commented in that issue are being closed I'll go ahead and close this.

**Comment by maxwofford** [comment]
@d12 I've managed to brick another assignment. Can I get [this repo](https://github.com/hackclub/dinosaurs) set as the assignment repo for [this assignment](https://classroom.github.com/classrooms/5633654-hack-club/group-assignments/dinoisseur-badge) manually for the time being? I'd like to send this assignment out asap & am just blocking on having a working Classroom assignment. I got stuck trying to reassign the repo & now accepting [the invite](https://classroom.github.com/g/h4El66jr) 404s.

![Screenshot 2019-11-26 13 15 03](https://user-images.githubusercontent.com/5891442/69660718-e2653b00-104e-11ea-821e-99a8a4611a04.png)

**Comment by d12** [comment]
Taking a peek at this now @maxwofford , thanks for reporting!

**Comment by d12** [comment]
@maxwofford To help our engineers debug, what steps did you take to get into this state?

To unblock, you could create a new assignment with the repository you want to use. Not totally sure why changing the starter code repo is causing these errors, but we'll dig into it.

**Comment by maxwofford** [comment]
1. Created a new assignment
2. Created a new assignment team
3. Went to the team settings, replaced the generated repo w/ an existing repo
4. Tried to accept an invite to the assignment, reached a 404

As for getting unblocked, I don't know another way to do this. My end-result is that I'd like an assignment with a single team that uses an [existing repo](https://github.com/hackclub/dinosaurs) as the assignment repo (not a copy or template, but the original with all the issue/PR/comment history)

**Comment by d12** [comment]
@maxwofford Ah, I see. This isn't a supported workflow on GitHub Classroom, we don't have a way of accomplishing what you're trying to do. Can you do this through GitHub by adding collaborators to a repository?

With GitHub Classroom, the flow is intended to be 

1. Teacher sets up "starter code" repo with instructions and frameworking
2. Teacher creates assignment and sets starter code repository
3. Students accept assignment and get a copy of the repo to work in

Are there specific parts of GitHub Classroom you're hoping to use with your flow? It seems to bypass most of Classroom's functionality.

**Comment by maxwofford** [comment]
I'm running a competition where participants all submit by PRing to a single repo. I'm using GitHub Classroom to give people access to the repo & add them to a team + org at the push of a button. Classroom has been fantastic for this & does what I need it to flawlessly.

The one change I'd like to make is for people to PR into [an existing repo](https://hack.af/pack) which has sentimental value to the community I'm running the competition in instead of a fork without issue/comment/PR history.

I've been looking at how to implement this without Classroom, and it looks like the best alternative for me is to create multiple API keys & run an oauth service that 1-click adds people to a specific team, cycling through keys when I reach the API limit (50 invites per day). This wouldn't be as polished as Classroom is, would take engineering time, and doesn't feel like it's in the spirit of GitHub's rate-limits.

I'd really love to be able to run this competition through GitHub Classroom– @mogalvanize recommended I use it for this & it's been great so far.

**Comment by d12** [comment]
It'd be a pretty big change to the way the application has worked in the past, and it'd be a pretty decent engineering project to build out the functionality. Unfortunately I can't promise anything in the short term, but we'll note the feature request and try to get to it soon.

In this case, you'd probably be better off writing some sort of integration to do this. Looking at the API docs:

> To prevent abuse, the authenticated user is limited to 50 organization invitations per 24 hour period. If the organization is more than one month old or on a paid plan, the limit is 500 invitations per 24 hour period.

Will the 500 invitations per day be sufficient here? 

Given the partnership we have with Hackclub, we're happy to help try to make this happen!

**Comment by maxwofford** [comment]
Sorry for the late response here– slipped past my unreads. I ended up going for the integration (missed that line about the raised invite limit the first time) and it's working perfectly for my use-case. Thanks for recommending it.

Max Wofford
max@maxwofford.com
Engineering & Operations @ Hack Club ( https://hackclub.com )
