### ISSUE TITLE
Open Graph metadata?

### ISSUE THREAD

**Issue by tjhorner** [education/classroom#249]
I posted a link to classroom.github.com in my team's Slack chat then I noticed that there was no title or description for the metadata!

It would be nice to give a quick overview of Classroom in a meta tag. The description of this repository fits nicely: "Classroom for GitHub automates repository creation and access control, making it easy for teachers to distribute starter code and collect assignments on GitHub."

**Comment by johndbritton** [comment]
@tjhorner That's a good idea. Would you be interested in sending a pull request for that? You'd just need to add the metadata to the [site layouts](https://github.com/education/classroom/tree/master/app/views/layouts).

If you do, I think the appropriate metadata to start with is

> Classroom for GitHub
> 
> Classroom for GitHub automates repository creation and access control, making it easy for teachers to distribute starter code and collect assignments on GitHub.

Maybe in the future we could get more sophisticated and provide metadata for the particular course that the user is looking at, but for now I think the generic information would be fine.

**Comment by johndbritton** [comment]
@leereilly you helped out with his on the pack, would you be up for getting the right images in place?

**Comment by tjhorner** [comment]
I can do it, sorry, I didn't catch the notification for your comment.

I'll look through and do it after I'm done with some other stuff.

**Comment by johndbritton** [comment]
For the image, I think you can use this screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/123345/9819714/95b26b9c-58a7-11e5-99e9-d65996d53687.png)

**Comment by tjhorner** [comment]
This look good?

```html
<meta property="og:title" content="Classroom for GitHub" />
<meta property="og:type" content="website" />
<meta property="og:description" content="Classroom for GitHub automates repository creation and access control, making it easy for teachers to distribute starter code and collect assignments on GitHub." />
<meta property="og:url" content="https://classroom.github.com/" />
<meta property="og:image" content="https://cloud.githubusercontent.com/assets/123345/9819714/95b26b9c-58a7-11e5-99e9-d65996d53687.png" />
```

**Comment by johndbritton** [comment]
:+1:

**Comment by fabriciojr** [comment]
Hi guys! I proposed this addition on #303

**Comment by johndbritton** [comment]
This is deployed and working according the the [Facebook object debugger](https://developers.facebook.com/tools/debug/og/object/):

<img width="491" alt="screen shot 2015-10-04 at 4 57 07 pm" src="https://cloud.githubusercontent.com/assets/123345/10268705/07035432-6ab9-11e5-9b9f-ae6b72a468f1.png">

**Comment by fabriciojr** [comment]
It's working on Slack as well
![screenshot from 2015-10-04 13 35 18](https://cloud.githubusercontent.com/assets/3369134/10268898/ebe60da0-6a9c-11e5-9c71-ab1f68080d94.png)

**Comment by johndbritton** [comment]
:tada: :camera:
