### ISSUE TITLE
Assignment Forks Misattributing Template Repo Commits

### ISSUE THREAD

**Issue by brrcrites** [education/classroom#2493]
**Describe the bug**
GitHub Classroom assignments which are created with starter code and use the "Import starter code using a template repository" beta feature occasionally seem to incorrectly attribute authorship of the template repo's commits in the newly forked commit history (and contributor list) to a different author. This doesn't happen in every student submission fork of the template repository only a subset.

**To Reproduce**
This issue has not presented on all student forked repos and I am unsure how to reproduce it.

**Expected behavior**
When forking from a GitHub Classroom assignment link I would expect that the commits made to the template repo (compressed or otherwise) would appear in the students forked submission repo attributed to the original author.

**Comment by d12** [comment]
Thanks for the report! I'm going to close this issue in favor of the earlier https://github.com/education/classroom/issues/2459
