### ISSUE TITLE
What's an "organization" in Classroom?

### ISSUE THREAD

**Issue by jpolitz** [education/classroom#250]
I was baffled by this page on my first test of Classroom:

<img width="1057" alt="screen shot 2015-09-22 at 7 55 24 pm" src="https://cloud.githubusercontent.com/assets/119891/10035171/31887ff0-6165-11e5-8834-79d70f96556a.png">

It says "New Organization," and then there's a box for the name, and a dropdown that says "Organization".  Am I selecting which organization I'm adding an organization to?  Or is it just that the organization is new to Classroom?  Why am I giving it a name, then?

What I expected was new, standalone organization within which I could test out Classroom stuff.  What I got was a course thing within an existing organization (happened to be brownplt).  Then when I created some test student repos, folks in the brownplt organization started getting emails that they were subscribed to the student repos, etc, which wasn't what I expected.

I didn't expect that any existing organization I had would need to be part of the workflow.  I think that perhaps what I should have done is create an organization through Github proper, then use that organization with Classroom.  In that case, the answer might be "RTFM, @jpolitz, this is documented elsewhere, go look" – where should I have found that workflow, if so?

Is there a reason each new course isn't just a brand-new organization within Github?  Why did my existing organizations need to be involved?

**Comment by GabeIsman** [comment]
+1. I also found this deeply confusing. Basic terminology problem: 'Organization' is ambiguous on this page.

**Comment by johndbritton** [comment]
This is follow up from https://news.ycombinator.com/item?id=10261303 & https://news.ycombinator.com/item?id=10262592.

**Comment by johndbritton** [comment]
Yeah, I think this experience could be better as well. Unfortunately, we don't have a way to create an organization through the API so the org must be created on GitHub first.

I think what we want to do here is change the title to "New Classroom" and use language like "Link your new classroom to an existing organization account on github.com."

@tarebyte suggested updating terminology throughout the app here: https://github.com/education/classroom/issues/252
