### ISSUE TITLE
Can no longer access shared repo, or organisation via classroom

### ISSUE THREAD

**Issue by skaragianis** [education/classroom#251]
Hey,

I thought I'd give your new service a whirl for our organisations developer test.

I shared an organisation and repo, testing it out. All good.

Made a change to the shared repo and suddenly it was no longer accessible within classroom. Link to administer it was broken. And no links to delete or remove classroom association.

Went to remove organisation and became concerned by error messages that looked like it might actually take out my whole github organisation. So revoked classroom access from within github.

Looks like a good bit of functionality but perhaps a little too MVP for prime time. Will be keen if you add features to remove and re-add repos. Or address what happened when I pushed to a repo that was shared with classroom.

Warm regards,

Steff.

**Comment by tarebyte** [comment]
@skaragianis what change did you make to the repo?

btw when you remove the organization from Classroom it only removes the items that Classroom has created.

**Comment by tarebyte** [comment]
Also what error messages are you referring to? Can you share a screenshot?

**Comment by skaragianis** [comment]
That makes sense. From the message I couldn't be sure.

As I said, happy to give it another swing. It's a good idea and I would
like to use it.

**Comment by skaragianis** [comment]
[image: Inline image 1]

Unfortunately this is all I see when I hit https://classroom.github.com
now, having revoked acess. The organisation that was linked (if you can see
traffic from me in the logs) is AssetView.

**Comment by tarebyte** [comment]
@skaragianis I can't see an image, I think it's due to the fact you are emailing me.

**Comment by skaragianis** [comment]
[image: Inline image 1]

I've attached it again. If its not coming through, perhaps its another
deficiency you can add to the backlog ;-)

**Comment by skaragianis** [comment]
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Is what the message says.

**Comment by tarebyte** [comment]
@skaragianis thanks! I'll check it out

**Comment by skaragianis** [comment]
Appreciated! I really would like to use this.

**Comment by skaragianis** [comment]
Even if you can just clear me out of classroom entirely for now, I'll
relink, not pushing any changes to the attached repo, and give it a whirl
with candidates. I did test it with a new github account and it looks like
it will work well for us.

**Comment by johndbritton** [comment]
@skaragianis You are able to remove and reset your organization by going to the settings page within classroom and clicking the DangerZone button labeled "Remove and reset."

That will remove your organization from Classroom for GitHub and delete the teams and repositories that were created by Classroom for GitHub.

**Comment by skaragianis** [comment]
Hi John,

I just tried again, visiting https://classroom.github.com which immediately
redirects to https://classroom.github.com/organizations with the same
message:

"We're sorry, but something went wrong
If you are the application owner check the logs for more information"

In "third party access" within the settings for assetview I tried "deny
access" then "grant access" for "Classroom for Github". Before and after
same message as above.

Still keen!

Warm regards,

Steff.

**Comment by johndbritton** [comment]
@skaragianis I'm trying to figure out exactly how the issue started happening, you said

> Made a change to the shared repo and suddenly it was no longer accessible within classroom.

What change did you make exactly?

**Comment by skaragianis** [comment]
I edited the readme.md in assetview/dev-test which classroom was configured
with. After I pushed and went back to classroom I got an error message when
I tried to click the settings for that repo. I'm sorry that I can't tell
you exactly what that message was. That's when I went hunting for a way to
delete the association and start again. There was no repo level action
because I could no longer access settings, and because the organisation
level action looked a bit too scary I tried killing it from the assetview
end. And now I'm getting the error above.

**Comment by johndbritton** [comment]
Update: We think we've found the source of this issue and are working on a fix. Thanks for your help with debugging.

**Comment by skaragianis** [comment]
I look forward to benefitting from your new service! :-) And good on you
for having a prominent 'report issue'. I wouldn't have bothered otherwise;
my loss and maybe yours. I'll steal that idea thank you :-)

Have fun!

Steff.

**Comment by johndbritton** [comment]
@skaragianis We deployed a fix that should resolve this issue. Can you check to see if it's working for you now?

**Comment by skaragianis** [comment]
Hi John,

Thank you very much, we're in action again! I associated the organisation
and removed/added an assignment. No issues. Looking good! I hope to trial
with real candidates in the coming days.

In future I'll do a better job of noting down issue details.

Nice talking with you.

Warm regards,

Steff.

**Comment by johndbritton** [comment]
Thanks for following up Steff, sorry for the trouble getting started.
