### ISSUE TITLE
Unable to Create New Classroom

### ISSUE THREAD

**Issue by mkfreeman** [education/classroom#2511]
**Describe the bug**
I am unable to create a new classroom, despite having provided the appropriate permissions on GitHub. 

**To Reproduce**
Steps to reproduce the behavior (see screenshots below):
1. Provide 3rd party access on GitHub
2. Go to create a new classroom
3. Select the desired organization (info340a-w20)
4. See error (_You are forbidden from performing this action on github.com_)

**Expected behavior**
A new classroom is created.

**Screenshots**
1.
<img width="918" alt="Screen Shot 2019-12-30 at 3 41 13 PM" src="https://user-images.githubusercontent.com/1373882/71605089-47fb8a00-2b1b-11ea-9da5-5a3397c3c471.png">

2.
<img width="1061" alt="Screen Shot 2019-12-30 at 3 40 39 PM" src="https://user-images.githubusercontent.com/1373882/71605085-37e3aa80-2b1b-11ea-8bea-9b6be5248739.png">

4.
<img width="1068" alt="Screen Shot 2019-12-30 at 3 40 47 PM" src="https://user-images.githubusercontent.com/1373882/71605096-521d8880-2b1b-11ea-965d-0f03001ef599.png">
[](url)

**Comment by jeffrafter** [comment]
Hi @mkfreeman, it looks like this is related to a change I shipped today that affected some classroom users. We've just deployed a fix for the fix... could you try again and see if you are still getting the error (you might need to sign out and sign back in).

**Comment by mkfreeman** [comment]
Amazing, @jeffrafter ! Thanks for the quick response around the new year. Worked just fine.
