### ISSUE TITLE
Changing "Organization" to "Classroom"

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#252]
@johndbritton there seems to be a lot of confusion what the difference between an Organization and a Classroom are. I think that is due to the fact that we intermingle the terms.

We say it's Classroom for GitHub, but we never actually use the term Classroom anywhere else.

What do you think using classroom in lieu of organization throughout the app.

**Comment by johndbritton** [comment]
Yeah, we kind of had this discussion earlier and settled on using just one term throughout the application. I think we should probably stick to using the term `Organization`in code, but in the UI use `Classroom` for everything except the explainers on pages where teachers create a classroom by "linking an organization account on GitHub."

Open to other solutions, but that makes sense to me.
