### ISSUE TITLE
After deleting a team, it still shows up when accepting an assignment

### ISSUE THREAD

**Issue by gvhagopian** [education/classroom#2522]
**Describe the bug**
After deleting a team, it still shows up when accepting an assignment

**To Reproduce**
1. set up an organization with one class and one group project and one team
2. Delete the sole team
3. While logged in to an unrelated github account, use the link to accept the assignment

**Expected behavior**
The only option should be to create a new team, since the team has been deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/1882211/72403960-a6725c00-3708-11ea-80b3-86d75dba9731.png)

**Comment by d12** [comment]
Thanks for posting this issue! We don't have the ability to delete teams at the moment, but this is an issue we're tracking in #292 . I'm not quite sure when we'll get to that issue, but if you follow it, you'll be notified when we post an update.
