### ISSUE TITLE
Stuck on Creating Repository

### ISSUE THREAD

**Issue by JRHonda** [education/classroom#2526]
**Describe the bug**
Creation of repository appears to stop making progress after 30 minutes

**To Reproduce**
1. Go to https://classroom.github.com/assignment-invitations/c1077b662e97d2063f0d655d116fa552/setup
2. Wait

**Expected behavior**
Should 1) Create the repository 2) Import starter code

**Screenshots**
<img width="1017" alt="Screen Shot 2020-01-16 at 9 38 02 PM" src="https://user-images.githubusercontent.com/29804812/72580038-cd679400-38a8-11ea-9ed3-0655c7fefd40.png">

**Additional context**
N/A

**Comment by d12** [comment]
@JRHonda This issue is resolved by using the new template repositories feature. We're working on making it a more seamless experience, but for now, this document explains how you can set it up for your assignments: https://classroom.github.com/help/using-template-repos-for-assignments
