### ISSUE TITLE
Error: (Repository: User could not be added)

### ISSUE THREAD

**Issue by developerium** [education/classroom#2527]
**Describe the bug**
I'm trying to open an assignment, but I keep getting `(Repository: User could not be added)`

**To Reproduce**
1. Open the link given to me
2. Click on the setup button
3. I see a red dialog showing me `(Repository: User could not be added)`
4. Click on retry repository setup
5. The same thing happens again

**Expected behavior**
I was expecting to be able to access the assignment and solve it!

**Screenshots**
![image](https://user-images.githubusercontent.com/7695492/72686125-8ecf1500-3b06-11ea-8b13-d2a059b12796.png)

Thanks in advance

**Comment by developerium** [comment]
Should I add the link to the assignment?

**Comment by d12** [comment]
That would help :) I will look at this soon!

**Comment by developerium** [comment]
Here it is:
https://classroom.github.com/assignment-invitations/eb6ed84883fc974fd768287c07a2c22c/setup

**Comment by d12** [comment]
:wave: @developerium!

I took a look, your account has some restrictions that are preventing you from being added to the repository. Sorry about the cryptic error, we'll try to improve that on our end. 

We're not able to help with this type of issue, you'll want to reach out to GitHub Support and let them know you're getting an error when being added to a repository. https://support.github.com/contact

**Comment by developerium** [comment]
I'm living in Iran that's why my account has some restrictions!

Thanks for clearing the issue for me

**Comment by amir-abdi** [comment]
@d12 The above is quite irresponsible of Github! Opensource and openaccess has a zero tolerance policy for racial profiling.
