### ISSUE TITLE
Cannot find assignment

### ISSUE THREAD

**Issue by gordonwatts** [education/classroom#2530]
**Describe the bug**
Using the `download repositories` button on the assignment page, Classroom Assistant displays the error message "could not find assignment" (https://classroom.github.com/classrooms/59599810-2020-winter-phys-427/assignments/02-the-abcd-background-method)

**To Reproduce**
Use classroom assistant to download the url https://classroom.github.com/classrooms/59599810-2020-winter-phys-427/assignments/02-the-abcd-background-method.

After entering it into classroom assistant, it will display the error message.

1. Start classroom assistant on your local machine
1. Log in
1. Enter the url 
1. See error

**Expected behavior**
Move to the download page

**Comment by gordonwatts** [comment]
Another assignment which I'd successfully downloaded (on this machine) last week is no longer found either.

**Comment by d12** [comment]
Something's definitely up right now, we're looking into this. I'll post an update once we have more info.

**Comment by ProfBird** [comment]
I'm having the same problem. I downloaded the repositories for this assignment last week: 
https://classroom.github.com/classrooms/59457339-lcc-cs296n-classroom/assignments/labs
Now the Classroom Assistant displays the red error message "Could not find assignment". Looks like a new bug in the Classroom Assistant!

**Comment by d12** [comment]
We are making good progress towards a fix, thanks for the patience and reports everyone!

**Comment by d12** [comment]
@gordonwatts @ProfBird We've pushed a fix upstream, you should be all set. Thanks for the reports, and sorry for the downtime!
