### ISSUE TITLE
Classroom assistant incorrect login and cannot find assignment

### ISSUE THREAD

**Issue by alexpapster** [education/classroom#2531]
I am facing a weird bug. Up to today, I did not have any issue with the classroom assistant. The only change that I did today was that I added my co-instructor as an owner of the classroom.

When I login in the classroom assistant, rather than seeing my avatar, I see his (!?) as logged in. It also no longer finds an assignment that it could find just fine up to this morning.

**Comment by d12** [comment]
Thanks for the report! We're looking into this right now, we'll update you as soon as we've resolved. I'm going to close this issue in favor of https://github.com/education/classroom/issues/2530 so that I can keep updates all in one place :)
