### ISSUE TITLE
Failed to import assignment even it uses template repository as base repo

### ISSUE THREAD

**Issue by ngAtesz** [education/classroom#2536]
**Describe the bug**
We have a classroom assignment which uses template base repository but multiple times our students can not start to work because of failing import. The import starts and after that it freezes without creating the repository. When I try to reset the import as an admin it freezes again without any further notification.

**To Reproduce**
1. Go to https://classroom.github.com/a/hE-96ViY
2. Click on Assign
4. During the process it freezes and not finishing it.

If I cancel the process as an admin because of the freeze it only creates an empty repository without any content.

**Expected behavior**
When a student accept an assignment the importer should clone the repository and import the content from the template repository to the newly created one. At least notify the user about the issue.

**Additional context**
Previously the assignment was cloned by the source importer using a standard repository. It has produced the same error. After then I modified the base repo to template repository and set the assignment settings accordingly. Unfortunately the issue remained and it appears randomly to some students.

I tried out to accept the assignment with my github account (I'm an admin as well in the classroom). In this case the import was so successful that it created 2 repositories in on time to my account.

**Comment by d12** [comment]
:wave @ngAtesz , thanks for the report! It seems the January flood of new users overwhelmed some of our infrastructure. We've increased our capacity and you shouldn't experience any more delays!
