### ISSUE TITLE
"update students" results in many duplicate students

### ISSUE THREAD

**Issue by amueller** [education/classroom#2538]
I tried to update my roster after more students enrolled.
I click on "update students" and pasted all the enrolled students. That created duplicate accounts for all the existing students.
I assumed it would not recreate existing accounts. Now I have to manually delete 150 accounts.

**Comment by d12** [comment]
@amueller :wave: That's quite annoying, we'll keep this issue open to track getting this bug fixed up.

For now, I can look into cleaning up the roster for you. If you can give me specific criteria, I can clean that up.

**Comment by amueller** [comment]
@d12 that would be great. It's all those ending with "-1" the classroom is 60368672-appliedml2020-classroom-1

**Comment by amueller** [comment]
I have done like half of it but if you can do the rest with a database query that would be sweet!

**Comment by d12** [comment]
Give me 5 min :)

**Comment by d12** [comment]
Done! And sorry for the trouble, this issue will be updated when we've made fixes.

**Comment by amueller** [comment]
Thank you so much!
