### ISSUE TITLE
Cannot enable assignment. Checking the box causes infinitely spinning wheel

### ISSUE THREAD

**Issue by lbang-hmc** [education/classroom#2539]
**Describe the bug**
I go to the assignment page, check the box next to Enable assignment invitation URL, and a little spinning status wheel comes up, never goes away, and the assignment is not made available to students using the link. 

**To Reproduce**
1. Go to assignment page
2. Click on the checkbox next to Enable assignment invitation URL
3. Spinning wheel hangs and assignment is not accessible to students 

**Expected behavior**
The assignment should be available to students. 

**Screenshots**
![2020_01_30_16_52_35_scrot](https://user-images.githubusercontent.com/46112584/73503383-f3993380-4380-11ea-896b-9698c29bb128.png)
![2020_01_30_16_47_08_scrot](https://user-images.githubusercontent.com/46112584/73503384-f3993380-4380-11ea-8dd0-28ca2cab21ce.png)

**Comment by d12** [comment]
:wave: @lbang-hmc Which browser are you using here? This is sometimes caused by very out of date browsers which aren't running our JavaScript correctly.

**Comment by lbang-hmc** [comment]
Chromium myself, but my colleague also tried on several different browsers and all had the same issue.

Eventually, I deleted the assignment and then created it from scratch. The "enable" button was then already checked when it was created, so I just left it alone. But still I would like to be able to uncheck it and then check it again without having this happen.

**Comment by d12** [comment]
Very strange, I tried it myself and didn't experience any issues. I've forwarded this to the eng team, they'll take a look soon! Thanks for the report :)

**Comment by lbang-hmc** [comment]
It is happening again. With my new assignment for Homework-03 on my github classroom, when I click the box, I just get a spinning wheel forever.

**Comment by lbang-hmc** [comment]
Here is a video of the error happening

https://www.cs.hmc.edu/~bang/ghcr-error.mp4

**Comment by d12** [comment]
@lbang-hmc This is fixed! Sorry for the delay and the issues, and thanks for the report!

**Comment by lbang-hmc** [comment]
Great! Thanks so much! :)
