### ISSUE TITLE
Cannot create new classroom

### ISSUE THREAD

**Issue by MrsSpindler** [education/classroom#2541]
**Describe the bug**
I get a 500 internal server error when I try to create a new classroom.

**To Reproduce**
1. Go to dashboard
2. Click on "New Classroom"
3. Error. (Also happens when I click on an empty plus sign near the bottom of my classroom tiles)

**Expected behavior**
I should be able to select my organization to create the classroom

**Screenshots**
N/A

**Additional context**
Not sure what is different from September when I create my first semester classes. I did sign up for the Autograding early access, but doubt that is connected.

**Comment by d12** [comment]
@MrsSpindler :wave:! Something's definitely broken, we're looking into this now. We should have the page back up very shortly.

**Comment by d12** [comment]
All sorted! Thanks for the report :)

**Comment by MrsSpindler** [comment]
Thanks for the quick response!
