### ISSUE TITLE
Pre-authorization tutorial

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#255]
It looks like the majority of issues folks are having are with authorizing the app.

Let's insert a pre-roll page before we authorize the user that explains what permissions we're asking for, why we need them, how to grant them, and also why they shouldn't de-authorize the app (at least until they've removed and reset their organization).

**Comment by nwoodthorpe** [comment]
Do we know if this is still an issue students/teachers come across often?

**Comment by johndbritton** [comment]
I think it would still be useful for us to implement an interstitial page explaining what permissions we need and why, before we land users on the GitHub authorization page. The main reason we need this is that that page is not really customizable and the entire app requires GitHub login so this happens really early for users.

**Comment by nwoodthorpe** [comment]
We could probably roll this into the new signup flow we've been chatting about. I'll make a note :+1:
