### ISSUE TITLE
Username is not updated for github education and got resource error message.

### ISSUE THREAD

**Issue by alex-s-hong** [education/classroom#2551]
**Describe the bug**
When I try to join/create a group on github classroom I got on error as 
'Resource could not be found on github.com'
When I click my profile from the page I got 404 error message with my previous username used on URL.

It seems github classroom still uses my previous username and did not update to the new one.
Would you fix it right away so that I can start my assignment as soon as possible?
<img width="1137" alt="Screen Shot 2020-02-06 at 11 04 25 AM" src="https://user-images.githubusercontent.com/19663096/73954895-787bd400-48d0-11ea-92c0-46d31a06715d.png">

**Comment by stephaniegiang** [comment]
Hey @alex-s-hong  👋 
So sorry about this inconvenience. Could you try again? It should be fixed now.

**Comment by alex-s-hong** [comment]
It has been fixed! 
Thank you!
