### ISSUE TITLE
[BUG] Cannot create/join a github classroom repository after changing account username

### ISSUE THREAD

**Issue by ilyasELBANI** [education/classroom#2554]
**Describe the bug**
If you have changed your username in the past, you can't join a github classroom repository repo and/or create a new one

**To Reproduce**
1. change your github username
2. join/create a new repository in a github classrom

**Expected behavior**
User is able to create/join the new repository 

**Temporary solution for users facing the same problem**
1. Change your current username, to the old username
2. Join or create the repostitory  you want in github classroom
3. Re-change your username to the one you want

**Screenshots**
You get error : Resource could not be found on github.com
![image](https://user-images.githubusercontent.com/50796351/74083571-00471700-4a66-11ea-913a-cb9eb88ca93c.png)

**Comment by d12** [comment]
Could you send me any user logins being affected? I'll sort it out on our
end while we're working on a long term fix :)

**Comment by ilyasELBANI** [comment]
We used the temporary solution I posted, so no no user is affected right now! Thanks!
