### ISSUE TITLE
I am Using GitHub Classroom and can't access the student's code.

### ISSUE THREAD

**Issue by rscherl** [education/classroom#2556]
On the left side I see their username/icon and on the right "Repository". If I click on Repository I get page not found. If I click on their username/icon I find other projects, but not the one for this class.

**Comment by d12** [comment]
Hi @rscherl , thanks for the report. I'll need a little more info to dig into this, could you post the repo URL you're getting "page not found" for?

**Comment by rscherl** [comment]
Thanks for the response, but shortly after posting this I found that I was able to click on Repository and access the code for all of those in the class except for those few who didn't do something correctly. So, for whatever reason it is ok, now.

**Comment by d12** [comment]
Strange. Please re-open if it happens again and we'll look into it!
