### ISSUE TITLE
Not allowing private repos

### ISSUE THREAD

**Issue by THSCS** [education/classroom#2559]
**Describe the bug**
Trying to create new assignments, it's been sporadically not letting me use private repos for students.

If I go back and try again it usually will let me. 

This seems like a fairly recent change. Never noticed this happening up until a few weeks ago. 

**To Reproduce**
1. Click on new assignment
2. Private repos not available, see screen shot. 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9141207/74263758-0c7cdf80-4cc5-11ea-8906-0809e590c138.png)

**Comment by jeffrafter** [comment]
@THSCS I think this is related to an ongoing incident on github.com. This should be resolved shortly.

**Comment by d12** [comment]
This should be resolved.
