### ISSUE TITLE
Can't access my students' repos anymore

### ISSUE THREAD

**Issue by alqahtanisarra** [education/classroom#2562]
I'm having issues to access my students repos. I used to be able to access them but now all links give me 404 errors. Any idea how to fix this issue?

Thanks

**Comment by stephaniegiang** [comment]
Hi @alqahtanisarra 👋 
Could I get the name of the classroom so I can take a look?

**Comment by alqahtanisarra** [comment]
Here it is (private though):https://classroom.github.com/classrooms/59588328-csc112-spring2020alqahtani-classroom

**Comment by stephaniegiang** [comment]
Thank you! That helped a lot.

Have you recently changed your GitHub username?

**Comment by sarraalqahtani** [comment]
Thank you! that was the problem and it is fixed now.

**Comment by stephaniegiang** [comment]
Awesome!
