### ISSUE TITLE
Remove Ads

### ISSUE THREAD

**Issue by tamberg** [education/classroom#2563]
**Describe the bug**
An advertisement for "Student Developer Pack" is shown during accepting an assignment.

**To Reproduce**
Click classroom link of an assignment.

**Expected behavior**
Let students use the system without displaying ads.

**Screenshots**
<img width="1552" alt="Screenshot 2020-02-24 at 19 31 30" src="https://user-images.githubusercontent.com/142092/75180421-758c3a80-573c-11ea-9c33-372d21ef428e.png">

**Additional context**
Showing ads to students is distracting and as far as I know against the rules in our school.

Might not be able to continue using GitHub Classroom if this does not stop.

**Comment by d12** [comment]
:wave: Does your school have a specific definition of what an "ad" is? We've never considered this an ad, it's part of our interface showcasing other functionality that we offer. It's not paid advertisement in any way. GitHub also has similar dialogs in other places on the website, e.g. on https://github.com.

<img width="346" alt="Screen Shot 2020-02-24 at 1 50 04 PM" src="https://user-images.githubusercontent.com/30920216/75181709-df8ceb80-570c-11ea-9685-c623792551ba.png">
