### ISSUE TITLE
Editing Autograding Test Case Results in Lost Newlines

### ISSUE THREAD

**Issue by sgzwach** [education/classroom#2567]
**Describe the bug**
If newlines are required as part of a test case in autograding, they are lost if a test case is edited. It seems they're not loaded back into the text area.

**To Reproduce**
1. Create a new assignment with autograding enabled.
2. Add a generic Input/Output test case that includes newlines in the Expected Output text area. 
3. Click Create Assignment
4. Click Edit Assignment
5. Click the pencil next to a test case to edit it. Any newlines in the Expected Output text area will be gone.

**Expected behavior**
Newlines should persist between test case changes. 

**Screenshots**
Expected when editing:
![image](https://user-images.githubusercontent.com/9322906/75356103-13832080-5875-11ea-876b-13f79b22566b.png)

Actual:
![image](https://user-images.githubusercontent.com/9322906/75355360-fd289500-5873-11ea-8e20-c07742667810.png)

**Additional context**
N/A

**Comment by d12** [comment]
Thanks! Added to our TODO to fix :)

**Comment by d12** [comment]
Fixed!
