### ISSUE TITLE
Repository creation hangs even with templates

### ISSUE THREAD

**Issue by boyland** [education/classroom#2568]
**Describe the bug**
When students follow the link, it starts to create a repository but hangs.  When the instructor goes to GitHub to check, the repository has a message that GitHub is working on setting up the repo and that it will just take a bit, but hours later, no progress is made.  This is happening sporadically.  Two of 70 students have reported problems to me.

**To Reproduce**
Following the invitation link for Homework #6 of
GitHub Classroom: CompSci 351 (Spring 2020)
Organization: UWM-COMPSCI-351

**Expected behavior**
The repository is created in a timely manner.

**Screenshots**
If I get another report, I can post a screenshot of GitHub saying that they're working on it.

**Additional context**
This is using templates.

**Comment by d12** [comment]
Hey @boyland , this looks like it may have been related to the GitHub incident yesterday. We'll see what we can do to better handle outages like this next time. Please let us know if it happens again and we'll dig in more!

**Comment by boyland** [comment]
Thanks.  I looked to see if there was a posted incident.  Let me know where I can find these.

**Comment by d12** [comment]
@boyland The best place to find those would be here: https://www.githubstatus.com/
