### ISSUE TITLE
How to disable the Feedback PR?

### ISSUE THREAD

**Issue by hroncok** [education/classroom#2569]
**Describe the bug**
Today, when I've created a new assignment in @3DprintFIT the following things happen that did not previously happen:

1. two commits to master from a random member of our org happen in the repo, both with the "Setting up GitHub Classroom Feedback" commit message. First creates `.github/.keep`, the other one seems empty.
2. a feedback branch with only the first commit from the above
3 a "Feedback" pull request.

**To Reproduce**
1. Crete a new individual assignment form a template repo.
2. Click the assignment link.

**Expected behavior**
Nothing special should happen unless I opt-in.

**Screenshots**

Template repo:

![_](https://user-images.githubusercontent.com/2401856/75592326-4e0dd880-5a82-11ea-9da5-1ace5f591c18.png)

Student repo:

![_](https://user-images.githubusercontent.com/2401856/75592343-59f99a80-5a82-11ea-9312-49451dbc6a18.png)

The Pull request:

![_](https://user-images.githubusercontent.com/2401856/75592365-6bdb3d80-5a82-11ea-82c7-4f0fad78c983.png)

**Additional context**

I believe your intentions are good, but this interferes with our existing workflow and the students will be confused by this.

**Comment by d12** [comment]
@hroncok Hey! Sorry about that, we're working on a new feature and I accidentally turned it on to the world. I've fixed that up, you shouldn't get these PRs again until we launch.

Out of curiosity, how does the PR interfere with your workflow?

**Comment by hroncok** [comment]
In this case, we run Jenkins CI for every commit and open issues in the repo. Now students get unrelated issues. Also, they receive feedback in those automatic issues, not in an artificial PR.

(I am not saying we cannot adapt or use this to some benefit, but not so suddenly.)

**Comment by hroncok** [comment]
FTR this is now indeed not happening any more.

Good luck with the launch :shipit:

**Comment by hroncok** [comment]
And thanks for a super fast response.

**Comment by d12** [comment]
Thanks for the info, we'll keep your workflow in mind :)
