### ISSUE TITLE
Assigning Private Repos as Starter Codes

### ISSUE THREAD

**Issue by rickyc** [education/classroom#257]
I tried to put a private repo path as the "starter code from GitHub path," but it just creates a blank repo. It seems to be fine with public repos.

**Comment by tarebyte** [comment]
@rickyc do you have access to the private repo? We use the creators token to get the starter code

**Comment by rickyc** [comment]
Yep, I have access to the private repo since I made it. I think it might be the issue where I'm trying to create a **public** assignment, but I'm assigning it a **private** repo as the starter code.

**Comment by tarebyte** [comment]
@rickyc that shouldn't be an issue, let me try it out and I'll get back to you shortly

**Comment by rickyc** [comment]
Hmm, so I was just trying to create a video depicting the problem and of course it works! Closing the issue now.

**Comment by tarebyte** [comment]
@rickyc your starter code is pushed up as a background job, there is a possibility that it was just in the queue.

**Comment by rickyc** [comment]
Ahh, I figured the problem as I was just trying to create an assignment.

1) Create a blank repo.
2) Create an assignment linking to the blank repo.
3) Push some code into the blank repo. Now repo has code, yay!
4) Have a student click on one of your invites
5) They end up having a blank repo.

When creating an assignment, does it cache the repo at the current HEAD?

**Comment by tarebyte** [comment]
@rickyc, it just clones down an exact mirror of the repo as is, and pushes it to the students repo

**Comment by rickyc** [comment]
Thanks for the clarification! It's probably the delayed job as you said.
