### ISSUE TITLE
Not able to delete classrom

### ISSUE THREAD

**Issue by mstavares** [education/classroom#2571]
Hi,

I don't know why but I'm not being able to delete this classroom. Can you please help me?

![ewfrarfwate4wfre](https://user-images.githubusercontent.com/9629936/75615996-f5eadb00-5b42-11ea-92a0-a08597ac0154.png)

Thank you!

**Comment by stephaniegiang** [comment]
Hi @mstavares 👋 
A fix just went in for this, so you should be able to delete a classroom.

**Comment by mstavares** [comment]
Hi @stephaniegiang 

Done. Thank you so much :)
