### ISSUE TITLE
Accessing invitation link returns a 404 error

### ISSUE THREAD

**Issue by yashjahit-21705201** [education/classroom#2577]
**Describe the bug**
Opening invitation link for a GitHub classrom returns a 404 error

**To Reproduce**
1. Follow invitation link
2. Login to GitHub and grant access to GitHub Classrom
3. Error appears and classroms page is empty

**Expected behavior**
Access the link without any problem

**Screenshots**
![image](https://user-images.githubusercontent.com/34451870/76238097-3de6bd80-6227-11ea-8ab3-13b6ff1f99e2.png)

**Additional context**
Some of my colleagues are able to access and some aren't

**Comment by jeffrafter** [comment]
Looking into this... thanks for the report

**Comment by yashjahit-21705201** [comment]
Just checked again, link was invalid. I will close the issue. Thanks!

**Comment by jeffrafter** [comment]
@yashjahit-21705201 is there any chance that the assignment (related to the invitation) has been deleted. This is usually the only way that we would remove an invitation.
