### ISSUE TITLE
Cannot join the team. 'Resource could not be found on github.com' appeared.

### ISSUE THREAD

**Issue by yun-kwak** [education/classroom#2578]
**Describe the bug**
I accepted the group assignment invitation. But I can't join a team. When I click the join button of my team, an error message('Resource could not be found on github.com') appear.

**To Reproduce**
1. Accept the group assignment invitation.
2. Click the join button of any team.
3. The error message('Resource could not be found on github.com') appears

**Expected behavior**
To join the team

**Screenshots**
![image](https://user-images.githubusercontent.com/29162801/76291671-ee6cc400-62f0-11ea-9764-b5fe16166fcf.png)

**Additional context**
I think the problem might have been caused by changing the user name.
My user name was `arin-kwak` and I recently renamed it as `yun-kwak`.
But my user name in Github classroom is still `arin-kwak`.
![image](https://user-images.githubusercontent.com/29162801/76291814-3986d700-62f1-11ea-8145-cacfcd83dcb8.png)

**Comment by david-kishi** [comment]
Seem this issue still exists because of a user changing their username, as seen in #2508.

@d12, would you be able to assist us with this? I'm having issues with accepting my class's assignment as well because I changed my username a few months back.

**Comment by d12** [comment]
Looking into this now, I'll get back to you very soon!

**Comment by d12** [comment]
@david-kishi @yun-kwak Your accounts are both fixed, sorry about that!
