### ISSUE TITLE
sync with roster with the classroom.google.com

### ISSUE THREAD

**Issue by arademaker** [education/classroom#2579]
**Describe the bug**

Some students from the classroom.google.com are still unlinked to github account. How the link is computed? How to solve these cases?

**To Reproduce**

1. I imported students from LMS (I choose the classroom.google.com),.
2. Imported the students. In the list, we have 4 cases of students not linked.

**Expected behavior**

all students have already submitted one assigment, so I was expecting that all of their accounts are linked.

**Comment by d12** [comment]
:wave: Students have the option to skip the linking process if they don't see their name which might be why some students in your roster are appearing as unlinked. You can manually link these students in the roster settings if you'd like!

**Comment by arademaker** [comment]
When I download the rosters, some students in the classroom.goggle.com are not listed. So I am suspecting that the classroom.google.com didn't provided all the students to the github classroom.  I have 32 students in the classroom.google.com but only 30 students in the roster. 

so I can't manually link these studetns in the roster settings because for some students github accounts I can't find the student in the roster:

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/86403/76450581-ca6eb880-63ac-11ea-8990-442295810008.png">

**Comment by d12** [comment]
@arademaker We've seen this bug in the past from Google, for some reason they don't send us all the students in the roster. We don't have bandwidth to work more on the Google integration at the moment, so the easiest way to get rolling with Classroom would probably be to unlink the LMS and manually add your 2 other students. Unlinking won't destroy the roster entries that were made by Google, so you'll only have to add two new entries.

**Comment by arademaker** [comment]
I didn't see any option for `unlink` a roster. I can only see `delete roster`.

**Comment by arademaker** [comment]
Ops! I found it in the settings. In the end, what I will be missing once I do't have the Google Classroom LMS linked to the organization?

**Comment by d12** [comment]
When you unsync, your Classroom roster won't be able to pull changes from your Google Classroom roster. That's the only difference :)
