### ISSUE TITLE
Unable to delete classroom

### ISSUE THREAD

**Issue by joewiz** [education/classroom#258]
Even after typing in the full name of the classroom, the reset and remove button remains inactive.  See this screenshot (taken in Mac OS X 10.10.5, Chrome 45.0.2454.93):

![screen shot 2015-09-23 at 10 47 28 am](https://cloud.githubusercontent.com/assets/59118/10048369/86d25de8-61e0-11e5-8d01-87cb9293ff87.png)

**Comment by tarebyte** [comment]
@joewiz you just need to type `HistoryAtState`

**Comment by joewiz** [comment]
A little scary, I'll be frank - but the text makes clear that it's only the repositories created by the classroom that are being reset. Thanks!

**Comment by tarebyte** [comment]
We don't want it to be scary, but we **DO** want you to be absolutely sure that you want to perform the action :grin:

**Comment by joewiz** [comment]
I've deleted repos before and understand the drill.  The scary bit is the feeling that I'm deleting the organization. Again, the explanatory text is clear that this isn't the action being taken, but when I type an organization name and click on a button called, "Reset and remove this organization", it feels like I'm about to, um, reset and remove the organization.

**Comment by joewiz** [comment]
Shouldn't the text be revised to say, "Reset and remove this organization's Classroom"?

**Comment by fer-rum** [comment]
Agreed, it got me too the first time. I only figured out when I stumbled upon this issue :)

**Comment by johndbritton** [comment]
> Reset and remove this organization

Yeah, I agree we can get some better terminology here.
