### ISSUE TITLE
Students cannot import assignment

### ISSUE THREAD

**Issue by canhelp2001** [education/classroom#2580]
**Describe the bug**
My students cannot import the assignment: here is the assignment link: https://classroom.github.com/a/W_5cNVSs

**To Reproduce**
just click the above link to import the assignment. It stuck at the importing page

**Expected behavior**
It stuck at the importing page

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/49698747/76475094-3e708700-63d4-11ea-8bc4-68215e1989e3.jpg)

**Additional context**

**Comment by theozinner** [comment]
I am having the same Issue. Here is the link for mine:
https://classroom.github.com/a/rkAW865U

**Comment by canhelp2001** [comment]
> I am having the same Issue. Here is the link for mine:
> https://classroom.github.com/a/rkAW865U

I cannot import yours

**Comment by jzz0060** [comment]
I am having the same issue. Here is the link for mine:
https://classroom.github.com/a/rkAW865U

**Comment by canhelp2001** [comment]
It seems Github fixed this problem

**Comment by d12** [comment]
Thanks for the report, Wwe fixed the issue shortly after your report!
