### ISSUE TITLE
classroom assignment clone stalled

### ISSUE THREAD

**Issue by ashriram** [education/classroom#2581]
**Describe the bug**
Students unable to clone classroom assignments from link.
The clone seems to simply stall at waiting. 
**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="1116" alt="Screen Shot 2020-03-11 at 5 46 43 PM" src="https://user-images.githubusercontent.com/4432524/76476760-53dbb600-63c0-11ea-8a85-40843dbe2c0b.png">

**Additional context**

**Comment by jeffrafter** [comment]
Thanks for the report! Confirmed, we've found the source of the problem and are fixing now.

**Comment by jeffrafter** [comment]
This should be solved now. Thanks!
