### ISSUE TITLE
Excessive amount of time taken for repository creation 

### ISSUE THREAD

**Issue by huzzyd** [education/classroom#2582]
**Describe the bug**
The repository download is hanging - preventing me from working on course material
https://classroom.github.com/assignment-invitations/ad7ba127898723845d35c180d537c26d/setup

**To Reproduce**
1. Access Invite Link
2. Accept Invite
3. See error

**Expected behavior**
The repository doesn't take this long to work

**Screenshots**

**Additional context**

**Comment by jeffrafter** [comment]
Thanks for the report! Confirmed, we've found the source of the problem and are fixing now.

**Comment by jeffrafter** [comment]
This should be solved now, can you try again?

**Comment by huzzyd** [comment]
> This should be solved now, can you try again?

Awesome it worked!
