### ISSUE TITLE
Assignment Starter Code - Reference branch/tag

### ISSUE THREAD

**Issue by mikeantonelli** [education/classroom#260]
As an assignment creator, I would like to be able to reference a specific tag or branch for assignment starter code so that I can create progressive assignments in the same repository. 

I'm imaging an assignment progression that would be:
- Project Setup - tags/assignment-1
- Hello World - tags/assignment-2
- Writing Tests - tags/assignment-3

Currently this would require separate repositories for each assignment.

If a student had trouble, they could reference the future tag in their project but each assignment would clone, and default to, the project specific code.

**Comment by johndbritton** [comment]
Thanks for the idea @mikeantonelli.

Is the idea that each of the branches are related and the steps build on each other? I think this could be accomplished with a single assignment in Classroom and some documentation in the README.md of your master branch.

**Comment by mikeantonelli** [comment]
I'm planning to to teach a class on unit testing javascript in ruby on rails projects. So assignment one would be project setup, and assignment two would require a successful project setup to write your first javascript test. If the student was only mostly correct, or had some trouble with assignment one, I wouldn't want to block them from writing their first test, moving on, or giving them the right answer.

Accepting the second assignment (if already participating in the lesson)  would add the branch or tag which had the correct answer for assignment one, for the student to build on. Additionally a student only interested in a level-6 assignment cloud jump right into a specific lesson without needing to cherry-pick, etc.

As a teacher, it would be nice to tag code as I commit which could be cherry-picked or branched in a way that made it easy for a lesson plan that built on itself.

**Comment by ajarmst** [comment]
Oooooh.  I want this too.

**Comment by johndbritton** [comment]
> Accepting the second assignment (if already participating in the lesson) would add the branch or tag which had the correct answer for assignment one, for the student to build on. 

This is a pretty cool concept. I could imagine a case where there's one repository and each assignment pushes an additional branch to the student's repo.

**Comment by jayvdb** [comment]
See also #673, about not being able to choose a default branch, which is a small part of this feature request.

**Comment by d12** [comment]
:wave:! We're moving conversation for this topic here: https://github.com/education/classroom/issues/2364. I'll close out this issue.
