### ISSUE TITLE
Course material creation with Classroom

### ISSUE THREAD

**Issue by bpesquet** [education/classroom#269]
Hi GitHub,

I have begun using Classroom with my students and it works fine, thanks !

The next step would be for GitHub to provide a tool or a template to create course material in a standardized way. A few adventurous teachers have already started to tweak Jekyll : [example 1](https://github.com/qrohlf/sensible-web-development/), [example 2](https://github.com/defeo/aws/) (in French). 

A standardized course creation template/process would facilitate exchange and collaboration between everyone. I hope you'll consider adding it.

**Comment by johndbritton** [comment]
> I have begun using Classroom with my students and it works fine, thanks !

You're welcome. Thanks for letting us know that it's working well, it's great to hear.

> The next step would be for GitHub to provide a tool or a template to create course material in a standardized way.

I've heard this suggestion before, and would love to work on something like that.

> I hope you'll consider adding it.

If we work on a standardized format, it probably won't impact this application directly as the app can use any repository as a starting point.
