### ISSUE TITLE
"You’re not managing any organizations yet" message even though I am the owner of an organization

### ISSUE THREAD

**Issue by malkinpage** [education/classroom#270]
After creating an organization on my account, I returned to classroom and i get the same message that I am not managing any organizations yet

**Comment by johndbritton** [comment]
Please make sure you have [granted acess](https://github.com/settings/connections/22024051) to your organization first. Then you should be able to [add it](https://classroom.github.com/organizations/new) to Classroom for GitHub.

Once you've done that, you can reopen this if there's still an issue.
