### ISSUE TITLE
Failed deletions make it impossible to re-add an organization

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#275]
Steps to reproduce:

1. Connect an organization
2. Make an assignment
3. Accept an invitation
4. Delete the created repository from GitHub
5. Reset and remove the organization from classroom

Expected:
All records, teams, and repositories deleted. Possible to add the organization again.

Actual:
Error on deleting a non-existent repository causes the background job to fail and it doesn't delete the record. The organization is missing from the dropdown on `/organizations/add`

**Comment by johndbritton** [comment]
@robsonmarques Your organization should now show up in the list on https://classroom.github.com/organizations/new

**Comment by robsonmarques** [comment]
Nice! Thank you @johndbritton for the great work :)
