### ISSUE TITLE
No aparecen mis organizaciones

### ISSUE THREAD

**Issue by josegustavo** [education/classroom#279]
luego de crear una organización noaparece en el panel de organizaciones

**Comment by johndbritton** [comment]
@josegustavo Has dado acesso de organización a Classroom? Puedes dárselo en este [página](https://github.com/settings/connections/applications/64a051cf1598b9f0658f).

**Comment by josegustavo** [comment]
Ok eso funcionó gracias.

2015-09-26 7:10 GMT-05:00 John Britton <notifications@github.com>:

**Comment by johndbritton** [comment]
De nada, buena suerte!
