### ISSUE TITLE
Any Scope of getting API access to Github Classroom

### ISSUE THREAD

**Issue by bhanuc** [education/classroom#280]
Hi ,
I am working on a Desktop Client for College Professors to manage their CoursePage  [Kalam](https://github.com/navya/Kalam) and wish to integrate github classroom in the application. Initially I had thought to just use github-pages for the course webpage but It would be awesome if API access can be thought of. I can contribute code if it helps.

**Comment by tarebyte** [comment]
@bhanuc not sure how I feel about having an API for this yet.

What were you looking to do with Classroom through Kalam?

**Comment by bhanuc** [comment]
So essentially my client aimed to give a gui interface to create a course
webpage, host it on git-pages and manage it from the application.
Now with the introduction of github classroom, using an organization for
assignment submission has become highly simplified. I wanted some hooks to
create a classroom, create a assignment, get the assignment URL etc.

**Comment by tarebyte** [comment]
@bhanuc I'm filing this as a feature request and closing this for now. An API isn't really on our radar ATM, but we really like the idea you have!
