### ISSUE TITLE
Classroom keeps saying that I don't have any organizations, but I have

### ISSUE THREAD

**Issue by jmalarcon** [education/classroom#282]
Classroom keeps saying that I don't have any organizations, but I have one and I have already authorized it explicitly.

I can't keep moving forward and trying the features in "Classroom".

Can you help with this?

Thanks.

**Comment by tarebyte** [comment]
@jmalarcon did you grant the app access? https://github.com/settings/connections/applications/64a051cf1598b9f0658f

**Comment by jmalarcon** [comment]
Yes, of course. See the attached screen capture. However it keeps saying that I need to create a new organization, since I don't have one.


Thanks.






Enviado desde Correo de Windows





De: Mark Tareshawty
Enviado el: ‎domingo‎, ‎27‎ de ‎septiembre‎ de ‎2015 ‎16‎:‎39
Para: education/classroom
CC: José M. Alarcón





@jmalarcon did you grant the app access? https://github.com/settings/connections/applications/64a051cf1598b9f0658f

**Comment by jmalarcon** [comment]
Now it seems to work.. Go figure.

Thanks anyway!
