### ISSUE TITLE
Not able to use my organization for classroom

### ISSUE THREAD

**Issue by nadirweibel** [education/classroom#284]
Hello

I wanted to start using classroom for my class, and I have a profile that has been already upgraded to Platinum with private repositories for my students.

The name of the organization is WeibelLab-Teaching and is associated with my github profile and username nadirweibel

https://github.com/organizations/WeibelLab-Teaching

When I try to use that organization for classroom, it does not show up in the available organizations. I see my other two organizations (UCSD-HCI and WeibelLab) but I don't want to use those.

Can you help me out?

Thanks

Nadir Weibel

**Comment by johndbritton** [comment]
Have you granted the Classroom application access? Check https://github.com/settings/connections/applications/64a051cf1598b9f0658f and make sure. In addition, you must be an admin of the organization in order to use Classroom for GitHub.

**Comment by kevincoakley** [comment]
Hi @johndbritton, I am having the same issue trying to add an existing organization. See the attached screenshot for the Classroom application permissions. I am in the Owner team on the organization.
![github](https://cloud.githubusercontent.com/assets/7471118/10176487/dfd1ad40-66a9-11e5-9e22-b5a9abac15a9.png)

**Comment by johndbritton** [comment]
@kevincoakley Can you hard refresh the [new organization page](https://classroom.github.com/organizations/new)?

`cmd+shift+r` or `ctrl+shift+r`

You should be able to see your organization in the dropdown list.

**Comment by johndbritton** [comment]
@kevincoakley Can you hard refresh the [new organization page](https://classroom.github.com/organizations/new)?

`cmd+shift+r` or `ctrl+shift+r`

You should be able to see your organization in the dropdown list.

**Comment by kevincoakley** [comment]
@johndbritton Sorry, that didn't help. I even tried a different browser that I have never used to login to GitHub.

**Comment by mccluresc** [comment]
Hi,

I am having the same issue. My organization also shows green (see below). I tried a hard refresh of the organization page as well as logging out / logging back in.

![image](https://cloud.githubusercontent.com/assets/4512030/10257381/fbdf14a0-6924-11e5-8a0e-5800bc1c720b.png)

**Comment by johndbritton** [comment]
@kevincoakley @mccluresc @nadirweibel We improved the flow for connecting an organization in #338. Can you try selecting your organization again and report back?

**Comment by tarebyte** [comment]
:pager: @kevincoakley @mccluresc @nadirweibel did this fix resolve your issues?

**Comment by tarebyte** [comment]
Looking through the site

* @nadirweibel looking at your page it appears that you have added your org successfully.
* @kevincoakley someone else added your org as a classroom which is why you couldn't see it. The update flow seemed to solve the issue.
* @mccluresc according to Classroom you are not an owner of the ScriptEdcurriculum org. Perhaps it's a token issue?

**Comment by johndbritton** [comment]
Since we haven't had any more reports and we haven't heard back, I'm closing this as resolved.

Feel free to reopen if the issue persists.

**Comment by deppeler** [comment]
Not sure if I am in same group as this thread.  But, my organization (U of Wisconsin - Madison) does not allow me to add external Apps to my Canvas course.  Only institution approved apps are allowed and GitHub Classroom is not on that list.  I am trying to change that.  Otherwise, its GitHub classroom without Canvas integration.
