### ISSUE TITLE
Clone repositories for grading

### ISSUE THREAD

**Issue by dmusican** [education/classroom#286]
Classroom for GitHub looks like a great tool! I just discovered it, and I'm going to try it as a replacement for teachers_pet with my class this week for setting up repos.

It doesn't appear to me that Classroom for GitHub offers the capability for cloning repos en masse for grading.  I'll still be needing to use teachers_pet for that. It would be great if this could be added, or if I missed that capability, it would be helpful to make it more obvious where it is. :)

**Comment by johndbritton** [comment]
> It doesn't appear to me that Classroom for GitHub offers the capability for cloning repos en masse for grading.

You're correct, we don't have this feature.

How would you imagine something like this working? Having a single link to download an archive of all the repositories would be great, but technically challenging to implement and error prone for large courses.

What if there was a command you could copy and paste into terminal to clone all the repositories?

**Comment by dmusican** [comment]
The teachers_pet script handles it pretty well; it clones the repositories with a single command (with the right arguments). In fact, you almost don't need to create a new functionality; you can _almost_ use teachers_pet to download the repos made by Classroom for GitHub. The one showstopper (as far as I can tell) is that they two systems use different naming conventions: teachers_pet uses projectname_studentname, whereas Classroom for GitHub uses studentname_projectname. If the two tools used the same naming conventions, they could be used interchangeably.

**Comment by mattfxyz** [comment]
I think this would be a great feature addition. I used teacher_pet's clone all repos feature for each project I had to review. I think it could as simple as a button title "clone all repos" that just provide a zip file, but as you mentioned, it's harder to implement.

Now I copy all of the repo urls into a `git clone <...> && git clone <...>` command. Would something like this, but pregenerated, work on your end?

**Comment by johndbritton** [comment]
> Now I copy all of the repo urls into a git clone <...> && git clone <...> command. Would something like this, but pregenerated, work on your end?

Pre-generating the command for copy and paste would be easy to do. I think there might be something better that's possible but I don't know what.

**Comment by samwhitlock** [comment]
I have used [this Python tool](https://github.com/josegonzalez/python-github-backup) quite extensively for the classes I have taught. It would be pretty easy to integrate with classroom. You can just specify the assignment name prefix in the "download repo" regex.

**Comment by umasshokie** [comment]
I wish I had realized this issue existed before starting to use GitHub Classroom. The lack of being able to clone every repository for an assignment at the click of the button makes Classroom completely unusable, and now I can't use teacher's pet to clone either due to the reverse naming scheme as the OP noted. Has there been progress on this issue? How could anyone use Classroom without being able to clone repos en masse?

**Comment by johndbritton** [comment]
@umasshokie I'm sorry this is causing trouble for you. It's on our list as something to implement.

**Comment by djholt** [comment]
I'd like to raise attention to this issue again. I received communication by GitHub Education today promoting this tool. And it looks amazing! But, I must agree with the other commenters: without the ability to clone (or at least download) repositories for an assignment, then this tool is sadly rendered unusable (for me, at least, and I'd assume for many others). I'm ready to use this tool in my courses starting next week, but to pull the trigger I need some hope that this feature can be realized in time to make this tool usable for us. Otherwise, for us, the tool isn't ready for use.

**Comment by umasshokie** [comment]
I wrote shell scripts to do all of this for me last semester and it worked fine. I can share these scripts if they are useful, they are super simple and just require a unix shell (cygwin on Windows, or Terminal on Mac). 

I do like that they can make their own repos through this tool, that does save me time and helps me see when they start a project. I still use teacher's pet when I need to control who is partnered for a lab though.

**Comment by umasshokie** [comment]
@djholt I've put my scripts on GitHub. They are very simple, I just slightly spruced them up from what I use myself for interacting with GitHub Classroom, and I'm sure there are others who have developed something more advanced. Feel free to use or modify to get yourself up and running with GitHub Classroom faster.

[My GitHub Classroom Scripts](https://github.com/umasshokie/classroom_scripts)

**Comment by tarebyte** [comment]
@umasshokie for context @djholt also asked the question on our new community forum https://education.github.community/t/github-classroom-clone-assignments/784/3.

We're working on a tool called [GitHub Classroom Desktop](https://github.com/education/classroom-desktop) which should help with the huge issue of getting your assignments. Feedback welcome!

**Comment by djholt** [comment]
Thank you @umasshokie and @tarebyte. I replied to the thread on the community forum, but I'll reply here as well. I also resorted to creating a simple script to accomplish what I need. Using the GitHub API, it ultimately wasn't too complicated. I also look forward to the new desktop tool, for those faculty members who are willing to step away from the terminal. :)

Here is the tool I created, for anyone who is interested: https://github.com/dsu-cit/orgclone

Thanks!

**Comment by janetlndavis** [comment]
I'd like to raise attention to this issue again. Thanks for sharing your tool @djholt!

**Comment by GrantZukowski** [comment]
I have this same issue and I am considering other options to move away from github classroom like Cloud9

**Comment by msaroufim** [comment]
Chiming in here as well, it's very frustrating to have to download 150 homework assignments manually. The way this should work is git clone "homework" where "homework" is a directory with each of the student's repos.

I'm happy to see djholt's solution and will try it out but this really feels like it should be a native feature.

**Comment by francesco-santini** [comment]
I'd like to raise attention to this issue again, as periodically done since 2015, as it appears from the top of this discussion. I guess this is a very simple feature to be added, as simple as important for teachers who need to download (and then evaluate) each assignment (over 100 even in my case).  @tarebyte @johndbritton , it seems GitHub classroom does still not include the download_all feature. Am I right?

**Comment by mozzadrella** [comment]
@francesco-santini correct--this will be part of the sprint for manage and assess: https://github.com/education/classroom/blob/master/ROADMAP.md

**Comment by rituparna89** [comment]
I was able to do it by using the ruby code at
http://tagomoris.hatenablog.com/entry/2015/03/04/180252
and it worked like a charm

**Comment by erikmd** [comment]
Dear GitHub classroom developers,

Even if the [classroom-assistant](https://github.com/education/classroom-assistant) tool is related to the feature requested in this issue, I think #286 would still deserve to be considered: it would indeed be great to be able to get the list of all Git URLs of a given assignment directly from the GitHub classroom interface. By "directly", I mean without needing to download an extra binary beyond Git, and without needing to develop one's own script relying on the GitHub API… It could thus be proposed as an alternative to the classrom-assistant feature, for teachers that want to devise their own cloning/grading command and feed it with the list of `.git` URLs corresponding to the assignment.

IMHO it is unneeded to develop a complex UI for that feature: it would suffice to have an additional button in GitHub Classroom that let the teachers download a `.csv` with several columns… for example:

```
login,project-basename,number-of-commits-in-HEAD,https-url,ssh-url,commit-if-submitted,commit-url-if-submitted
stud1,proj-stud1,9,https://github.com/org/proj-stud1.git,git@github.com:org/proj-stud1.git,,
john,proj-john,12,https://github.com/org/proj-john.git,git@github.com:org/proj-john.git,1234567890123456789012345678901234567890,https://github.com/org/proj-john/tree/1234567890123456789012345678901234567890
```
This way, teachers could rely on this info to easily clone the assignments w.r.t. the submitted commit:

```bash
$ perl -wpe 's/^([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*),([^,]*)$/git clone $5 \
    && pushd $2 && git checkout $6 && popd\n/;' downloaded.csv | sed -e '1 d' > todo.sh
$ bash todo.sh
```

What do you think of this proposal?
Kind regards, Erik

**Comment by BenEmdon** [comment]
This appears to have been resolved by [GitHub Classroom-Assistant](https://classroom.github.com/assistant). 

Are we good to close this? CC: @mozzadrella @srinjoym

**Comment by dmusican** [comment]
Agreed. Thanks for working on this!
