### ISSUE TITLE
Group Assignment - Maximum number of members

### ISSUE THREAD

**Issue by ChristianMurphy** [education/classroom#288]
This is a feature request, to add an optional field in the settings for the maximum number of members per team.

This is a setting would either: only be set on initial creation and be immutable afterwards, or could only be edited to a higher value.
Otherwise, if the value could be edited to a lower number of members per team, there would be the problems of removing members from a team, which members would be removed, and where those members would go.

**Comment by johndbritton** [comment]
Thanks for the suggestion @ChristianMurphy. I think this is a totally reasonable request and something that wouldn't be difficult to implement.

We'd welcome a pull request adding such a feature.

**Comment by nixpulvis** [comment]
Along the same lines, it would be nice to allow staff to assign groups.

**Comment by johndbritton** [comment]
> Along the same lines, it would be nice to allow staff to assign groups.

@nixpulvis Could you open another issue for that feature request? I'd be especially interested in your ideas as to how the teacher could assign the groups. When creating the assignments, we don't necessarily have the GitHub account info for all of the students yet.

**Comment by franktank** [comment]
Should the input be a field or a select list? Also, should the column for team_size or group_size be added to group_assignments?

**Comment by johndbritton** [comment]
> Should the input be a field or a select list?

It should be an optional field. Empty would mean no limit, enter an integer and we'll enforce that limit.

> Also, should the column for team_size or group_size be added to group_assignments?

Yes, the value should also be editable on the settings page for the group assignment.
