### ISSUE TITLE
Add spacing to menubar tooltips

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#289]
This:
<img width="301" alt="screen shot 2015-09-30 at 10 27 47 am" src="https://cloud.githubusercontent.com/assets/123345/10188230/ee5a7478-675d-11e5-9b25-43faf2ffd6b7.png">

Needs more space, like this: 
<img width="208" alt="screen shot 2015-09-30 at 10 28 30 am" src="https://cloud.githubusercontent.com/assets/123345/10188244/15d7fa34-675e-11e5-81e2-7820be0055bf.png">

**Comment by johndbritton** [comment]
#294 improved the icons, but the alignment with the logo is now off. Also the user's avatar is a different height that the icons. @tarebyte can you tidy that up when you get a chance?

**Comment by dpedoneze** [comment]
Can I submit a PR to fix this logo alignment and avatar size? @johndbritton

**Comment by tarebyte** [comment]
@dpedineze, absolutely you can! The help more than welcome!
