### ISSUE TITLE
Unable to Delete Organization

### ISSUE THREAD

**Issue by tabinks** [education/classroom#290]
Hi.  I was trying to delete a "Classroom Organization".  There was an alert that prompted me to type the name of my organization and offered some warnings.  I typed the organization name and the button never enabled.

Also, I found the wording on the alert to be a bit confusing as to what "organization" was going to be deleted.

**Comment by tabinks** [comment]
I tried the same process ~15 minutes later and it worked fine.

**Comment by johndbritton** [comment]
@tabinks Is it possible you tried to type the title of your organization rather than the github login of the organization? I'm trying to figure out if this is a bug or just an interface that we need to improve.

**Comment by tabinks** [comment]
@johndbritton I'm not sure which is which.  If my organization was "MyUniversity" and my classroom organization was "Bio 101", I typed "Bio 101" when trying to delete it.

**Comment by tarebyte** [comment]
@tabinks what is the url of your Organization? We use the organization title that's in the URL (the `slug`)

**Comment by tabinks** [comment]
My organization is "uchicago-bio".  The classroom organization was named "2015-Autumn".  I was able to delete it at a later attempt.

**Comment by tarebyte** [comment]
@tabinks this is a UX issue on our part, did you end up typing `uchicago-bio` to delete it?

**Comment by tabinks** [comment]
Honestly, I don't remember.  I probably tried them both until one worked.  Thanks for following up about it.
