### ISSUE TITLE
Unable to access assignment page after deleting a team

### ISSUE THREAD

**Issue by leouieda** [education/classroom#291]
First of all, thank you for making this! I'm trying this out for the first time "in the wild". Hope you keep improving!

I've created an assignment today for my students and things worked mostly OK. One student had a problem that she accidentally created a new group when she should have joined another. I tried to fix this by deleting the Team that she created and inviting her to the correct team. Unfortunately, after deleting the accidental Team, I can no longer access the assignment page. I can go as far as the organization page, but when I click on the assignment I get the following page:

![screenshot - 300915 - 18 36 46](https://cloud.githubusercontent.com/assets/290082/10207547/67397e8a-67a3-11e5-9542-0a94293a5faa.png)

I tried re-creating the Team but I'm still getting this error.

**Comment by johndbritton** [comment]
@leouieda Can you tell me the name of the organization, the team you deleted, and the user who joined the wrong team?

**Comment by johndbritton** [comment]
@leouieda I was able to reproduce this behavior and find the bug that resulted in the unfriendly 500 error you're seeing. The fix is in #293. Can you try and access the assignment page and confirm that you're seeing a disabled group rather than the error you had before?

It's a known issue that you can't move a user between teams, I've opened a separate feature request to solve that problem in #292.

**Comment by leouieda** [comment]
@johndbritton wow that was fast! The site is back to normal and the deleted group now appears as deleted. 

In the org management I see the student in the correct team (I added her manually and that worked) but that has not synced with the classroom dashboard. This is minor and the site works great now for the class purposes.

Thanks for fixing this so quickly (just in time for todays class) :smile:

**Comment by johndbritton** [comment]
> The site is back to normal and the deleted group now appears as deleted.

Great, I'm glad that's resolved. I really don't want users to see such unhelpful errors.

> In the org management I see the student in the correct team (I added her manually and that worked) but that has not synced with the classroom dashboard.

Yeah, that's expected. We don't recommend modifying anything in the organization manually when using Classroom for GitHub. In this case you'll be able to get by for now, but the real solution to your problem will come when we resolve #292.

> Thanks for fixing this so quickly (just in time for todays class) :smile:

You're welcome, thanks for reporting!

**Comment by leouieda** [comment]
OK, I'll keep an eye out for that fix then.
