### ISSUE TITLE
Classroom for GitHub is open source

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#296]
We should add a note to the footer saying something like this:

> Classroom for GitHub is [open source](https://github.com/education/classroom)

**Comment by mostlybadfly** [comment]
Hi! working on this now.  Any specific styling you recommend?  This is how it renders now.
<img width="1513" alt="screen shot 2015-10-02 at 12 28 51 pm" src="https://cloud.githubusercontent.com/assets/5193768/10253105/31fca47c-6901-11e5-9bc7-dbcd7bb73b78.png">

**Comment by mostlybadfly** [comment]
Also, some tests failed. I didn't check before updating but in master it looks to be the same thing. I changed just the footer, any thoughts?

**Comment by johndbritton** [comment]
Resolved in #301
