### ISSUE TITLE
User wrongly joined a different team, after removal he still shows as part of that team

### ISSUE THREAD

**Issue by timdams** [education/classroom#297]
A student, wrongly joined an existing team. I (organizer) removed the user from the repo (through settings/Collaborators) but the student still shows as part of the other tea when reviewing the team in the assignment overview of the teams.
The user is also unable to join another team.

**Comment by tarebyte** [comment]
@timdams we store team members on our database, so if you removed the student from GitHub we currently don't have a way of knowing that you performed that action.

**Comment by johndbritton** [comment]
This is the expected behavior, but not a great user experience.

@timdams You might want to subscribe to https://github.com/education/classroom/issues/292, which will solve this issue.

I'm closing this in favor of #292.
