### ISSUE TITLE
Inclusion of Other Organizations in Permissions

### ISSUE THREAD

**Issue by tabinks** [education/classroom#298]
I received a inquiry from a student who wondered why the permissions granted when he joined our organization were not limited to just our organization.  He claims that by accepting the invitation that he granted "delete permissions" to other organizations he was part of that are unrelated to the class.

Is this accurate?

I can not verify this for myself since I can't seem to accept an invitation from my own organization.  I get an error stating "An error occurred".

**Comment by tarebyte** [comment]
@tabinks on the authentication page, the student had the option of granting or not granting access to any of their organizations. We are working on changing the permission scope for students so that this will not confuse people.

**Comment by johndbritton** [comment]
> He claims that by accepting the invitation that he granted "delete permissions" to other organizations he was part of that are unrelated to the class.

He granted full access to multiple organization accounts. There is a way to avoid this issue, but it requires the organization owners to enable [third-party application restrictions](https://help.github.com/articles/about-third-party-application-restrictions/), which is a new feature on GitHub that older organizations have to opt in to using.

We are working on improving the user experience around requesting permissions in Classroom for GitHub as well.

**Comment by tabinks** [comment]
I just registered this organization about a month ago and this is what the default values look like.  One one student noticed (complained) about it.

<img width="762" alt="screenshot 2015-10-01 14 05 07" src="https://cloud.githubusercontent.com/assets/93689/10230919/7aef9318-6845-11e5-936a-dac7c03fefeb.png">

**Comment by johndbritton** [comment]
@tabinks It's dependent on the other organizations that your student is a member of. Each of the other organizations has a permission control that can limit access by other applications.

**Comment by tabinks** [comment]
Thank you for the clarification.

**Comment by johndbritton** [comment]
I've labeled this as feedback, we'll use it to inform our work on improved permissions in the future. Closing as there's no discrete actionable task for now.
