### ISSUE TITLE
Using full URL in 'starter code from GitHub' caused server error

### ISSUE THREAD

**Issue by BlueT** [education/classroom#299]
![2015-10-02 08 16 04](https://cloud.githubusercontent.com/assets/51141/10236892/f048cf06-68dd-11e5-800c-51fb853bd099.png)

**Comment by johndbritton** [comment]
Steps to reproduce:

1. Connect an organization
2. Create a new assignment
3. Use a url for the starter repository

Expected behavior:

User receives a friendly error

Actual behavior:

User receives 500 error

**Comment by johndbritton** [comment]
@blueT We've deployed a fix for this issue, thanks for reporting.
