### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#3]
Wasn't entirely sure what license should be used for this project. I would assume MIT copyright to GitHub but I didn't want to make assumptions.

**Comment by johndbritton** [comment]
MIT all the way. We probably want to setup the GitHub CLA as well.

**Comment by johndbritton** [comment]
MIT works for me.

**Comment by tarebyte** [comment]
> MIT all the way. We probably want to setup the GitHub CLA as well.

This showed up on my news feed but you deleted the comment, should we not setup the GitHub CLA for this project or just do it at a later time?

**Comment by tarebyte** [comment]
Added
