### ISSUE TITLE
Starter code not imported into assignment repository

### ISSUE THREAD

**Issue by dhanifudin** [education/classroom#304]
I have an assignment on @polinema-gui repository with starter code from same organization, but the starter code not imported into the assignment repository.

**Comment by wakita** [comment]
I experience the same and have no clue.

**Comment by yasuhito** [comment]
Same here. @handai-trema

**Comment by ijaureguialzo** [comment]
It's working for me now, I've created a new assignment and the starter code shows on student's repository.

**Comment by dhanifudin** [comment]
It's working now

**Comment by johndbritton** [comment]
@dhanifudin @ijaureguialzo Can you please describe the exact steps you took that resulted in this issue? It's great that it's working for you now, but any additional information you can provide will help us find any sneaky cacheing issues.

@yasuhito @wakita Please reopen this if you're still experiencing the issue.

**Comment by dhanifudin** [comment]
@johndbritton I just create an assignment with normal steps, so I don't know what caused a problem.
This issue has  occurred again, but not affect all repository. This [repository](https://github.com/polinema-gui/tugas-2015-02-ridhoaffan96) have starter code but this [repository](https://github.com/polinema-gui/tugas-2015-01-FanistyaDiasAfrilia) just empty repository. There are a delay around 7 hours for repository to import successfully. I have another issue that was affected from this issue, about different commits counter. Should I open a new issue?

**Comment by dhanifudin** [comment]
it's working now

**Comment by johndbritton** [comment]
Failed starter code pushes should be a thing of the past now, we've moved to using the GitHub Importer in https://github.com/education/classroom/pull/316
