### ISSUE TITLE
Better og:image for social sharing

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#306]
When sharing `https://classroom.github.com` on social sites, users see something like this:

<img width="491" alt="screen shot 2015-10-04 at 4 57 07 pm" src="https://cloud.githubusercontent.com/assets/123345/10268713/4645f942-6ab9-11e5-8eb1-3b4def999659.png">

There's room for improvement in that image.

**Comment by dpedoneze** [comment]
I've made an image (with some _small_ variations) to this `og:image`, can I post them here or should I open a PR for them?

**Comment by tarebyte** [comment]
@dpedoneze go ahead and open a PR and we'll start a discussion

**Comment by tarebyte** [comment]
Closed with #309
