### ISSUE TITLE
Header CSS issue on invitation redemption page

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#314]
<img width="208" alt="screen shot 2015-10-07 at 6 33 30 pm" src="https://cloud.githubusercontent.com/assets/123345/10345498/fd090808-6d21-11e5-8799-570937086927.png">

Related to #289

**Comment by dpedoneze** [comment]
I couldn't reproduce this issue (tried using FF/Chrome/Safari)

But I didn't go to this "invitation redemption page" (but I think all of them uses the same css/structure, right?)

![image](https://cloud.githubusercontent.com/assets/5757502/10355102/1d6f91b8-6d3e-11e5-8771-792bf6ac8d83.png)
