### ISSUE TITLE
Organization That I have opened access up with doesn't appear

### ISSUE THREAD

**Issue by robbyrob42** [education/classroom#315]
![screen shot 2015-10-07 at 10 39 03 am](https://cloud.githubusercontent.com/assets/2531474/10345597/b0c440da-6cdf-11e5-819f-21a0ba2cf982.png)

![screen shot 2015-10-07 at 10 38 08 am](https://cloud.githubusercontent.com/assets/2531474/10345574/8cf232e8-6cdf-11e5-86c2-4457f2038347.png)

Am I doing something wrong?

**Comment by johndbritton** [comment]
@robbyrob42 Are you an admin of that organization?

**Comment by robbyrob42** [comment]
Hi, yes I am

**Comment by tarebyte** [comment]
@robbyrob42 is your organization migrated over to the [improved organization permissions](https://github.com/blog/2020-improved-organization-permissions)?

**Comment by robbyrob42** [comment]
Yes, we just migrated yesterday. just as a test, i revoked access to classroom and readded. I am a full admin of the CodeScience Organziation

**Comment by tarebyte** [comment]
@robbyrob42 alright @johndbritton and I will take a look at it tomorrow and see what's up. Thanks for your patience!

**Comment by johndbritton** [comment]
@robbyrob42 Are you listed as an owner here: https://github.com/orgs/CodeScience/teams/owners

**Comment by robbyrob42** [comment]
@johndbritton I am an owner but we moved to individual permissions two days ago. 

![screen shot 2015-10-08 at 1 03 10 pm](https://cloud.githubusercontent.com/assets/2531474/10378305/13086144-6dbd-11e5-83b0-8ac7e6432877.png)

**Comment by johndbritton** [comment]
@robbyrob42 You should now see the organization in the dropdown list.

**Comment by johndbritton** [comment]
@robbyrob42 Were you an owner prior to taking that screenshot?

**Comment by robbyrob42** [comment]
@johndbritton yes i was an owner prior to and I am still not seeing them. am i in the wrong place?

![screen shot 2015-10-09 at 8 36 06 am](https://cloud.githubusercontent.com/assets/2531474/10398253/e18ebe16-6e60-11e5-8d35-4921a9a83198.png)

**Comment by johndbritton** [comment]
Thanks for your patience @robbyrob42, sorry for the trouble. You're in the right place, but I haven't figured out why you're not seeing your organizations in the list. I'm going to keep looking.

**Comment by robbyrob42** [comment]
@johndbritton no problem at all, thanks for your help. I'm happy to assist with any testing required to get to the bottom of it.

**Comment by johndbritton** [comment]
@robbyrob42 I think I found the issue for you, it looks like someone else in your organization has already added the organization to classroom so it's not allowing you to add it again.

**Comment by johndbritton** [comment]
This should be resolved with https://github.com/education/classroom/issues/259

**Comment by robbyrob42** [comment]
please excuse my ignorance but shouldn't I be able to see them then? Are you suggesting that I need to find the person who opened it up and have them revoke and me open it up? We are excited to use classroom to help our developers learn and I have been charged with orchestrating that effort.

**Comment by johndbritton** [comment]
The person who created the organization in Classroom had the opportunity to invite other people as managers. We're working on removing that requirement, but for now that's what you need to do.

**Comment by robbyrob42** [comment]
ok yes, got it! i had someone remove the classroom they created and it works, thanks!

**Comment by johndbritton** [comment]
If you go to the settings page of your classroom there's a link that you can share to invite other owners to manage the classroom.

**Comment by robbyrob42** [comment]
yep, now that i can see things, very straigthforward

On Fri, 9 Oct 2015 at 12:47 John Britton <notifications@github.com> wrote:

> If you go to the settings page of your classroom there's a link that you
> can share to invite other owners to manage the classroom.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/education/classroom/issues/315#issuecomment-146971243>
> .
>
-- 
Rob Jacques

**Comment by robbyrob42** [comment]
John, one last question, are you limiting organizations to one classroom at
the moment?

On Fri, 9 Oct 2015 at 13:03 Rob Jacques <robert.jacques1@gmail.com> wrote:

> yep, now that i can see things, very straigthforward
>
> On Fri, 9 Oct 2015 at 12:47 John Britton <notifications@github.com> wrote:
>
>> If you go to the settings page of your classroom there's a link that you
>> can share to invite other owners to manage the classroom.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/education/classroom/issues/315#issuecomment-146971243>
>> .
>>
> --
> Rob Jacques
>
-- 
Rob Jacques

**Comment by johndbritton** [comment]
The app only supports running one class per organization. You can create additional organizations for your other courses.

It'd probably be possible for us to allow you to run multiple classrooms out of one organization, but for simplicity we decided to limit it to one.

If that's a feature you'd really like to see, please open another issue with your rationale and we can see if other folks would find it useful.
