### ISSUE TITLE
Importing from private repository requires authentication

### ISSUE THREAD

**Issue by ryuhei-mori** [education/classroom#321]
I made an individual assignment as private setting with starter code from a private repository. The private repository was made by me. So, I can access it. I visited the invitation link for the assignment by myself. Then, the GitHub Importer requires username and password. When I tried before, the GitHub Importer didn't apear. Is it due to the private settings of the assignment and/or the private setting of the starter code repo. ? I entered a correct username and an incorrect password. Then, the GitHub Imporer didn't claim that the password is wrong, and seems to try to import starter code from the repository. But, of course, the GitHub Importer continued to show "Importing commits...0% complete". Eventually, the GitHub importer faild. I expected to reenter the username and the password. But, I couldn't. I want to retry these tasks. Now, I'm plyaing both role of a teather and a student. But, I couldn't figure out how to reassign the assignment. I could delete the empty repository made by the Classroom for GitHub. But, the repository is not made even if I revisit the invitation link.

**Comment by ryuhei-mori** [comment]
I found the following comment.
https://github.com/education/classroom/pull/316#issuecomment-146282071
If I understand correctly, the GitHub Importer has been used from 3days ago. If repo creation succeeds and starter code importer fails, undeletable garbage date is created. Even if the repo is deleted, the invitation link does not work. Is this correct ? I'm sorry about this since we plant to use the Classroom for GitHub for our class.

**Comment by johndbritton** [comment]
@ryuhei-mori Is this the screen that you saw?

<img width="613" alt="screen shot 2015-10-12 at 11 14 20 am" src="https://cloud.githubusercontent.com/assets/123345/10425788/6d9b7390-70d2-11e5-9276-03d66c6ea450.png">

**Comment by ryuhei-mori** [comment]
Yes !
If I understand correctly, it is the correct behaviour from few days ago irrespective of private/public setting.
It is not problem. Once, one enters a wrong password, there may be no way to recover.

**Comment by johndbritton** [comment]
@ryuhei-mori The Importer is a new feature, but this is indeed a bug. Thanks for reporting. I'll keep this issue updated with our resolution plans.

**Comment by johndbritton** [comment]
In the meantime, I'd suggest making the starter code repository public as a workaround.

**Comment by ryuhei-mori** [comment]
Thanks !
I think that the follwing is also independent problem.
"Once the assignment X is accepted by a student Alice, both of the student Alice and the instructor Bob who is administrator of the organization cannot remove the connection between the assignment X and Alice and connect them again."
If the above problem does not exist, the importer bug is not a serious problem. 

For the bug fixing, maybe, I chose "cancel" for the importer explicitly after the importing failiour since I expected that I could enter the username and password again.

**Comment by ryuhei-mori** [comment]
@johndbritton If the starter code repo is public, does the importer works without the bug ? I decided to use the "fork / pull request method" for our class this morning. If the Classroom works without bugs, it is nice for us.

**Comment by johndbritton** [comment]
> If the starter code repo is public, does the importer works without the bug ? 

Yes

**Comment by johndbritton** [comment]
> I think that the follwing is also independent problem.
> "Once the assignment X is accepted by a student Alice, both of the student Alice and the instructor Bob who is administrator of the organization cannot remove the connection between the assignment X and Alice and connect them again."

We're planning to address those issues in the future, if you'd like to stay up to date on progress, you should subscribe to https://github.com/education/classroom/issues/292.

**Comment by ryuhei-mori** [comment]
Thanks !

**Comment by johndbritton** [comment]
@ryuhei-mori This is now resolved, you should be able to import code from private repositories so long as the assignment creator has access to the starter code repository.

Thanks for reporting.

**Comment by ryuhei-mori** [comment]
Thanks a lot !
I'm also interested in the above problem on the reassignment. I'm afraid of using Classroom for our class unless it is implemented.

**Comment by johndbritton** [comment]
@ryuhei-mori That issue should be resolved when we fix #292.
