### ISSUE TITLE
Request for Issue Labels Associated with Classroom Work

### ISSUE THREAD

**Issue by ajarmst** [education/classroom#324]
Not really an issue, more of a suggestion:  I find that I am telling many of my students to create an issue with the label "Marking" and assign it to me when they have completed their work.  It might be of value to automatically add a few labels appropriate to a pedagogical environment for Classroom projects.  Others probably have suggestions, and the existing "question" and "need-help" labels are of obvious value.  Maybe:

"submission"
"marking"
"fix-and-resubmit"

As an initial suggestion.  Of course, a dashboard where you can change the default labels for projects in that classroom would be even groovier.

**Comment by johndbritton** [comment]
> As an initial suggestion. Of course, a dashboard where you can change the default labels for projects in that classroom would be even groovier.

That's a cool idea. Definitely something we can consider for the future. Thanks for sharing.

Labeling this as `feature-request` and closing for now, but we will regularly review feedback like this to inform our future plans.
