### ISSUE TITLE
Audit OAuth scope for students

### ISSUE THREAD

**Issue by mastahyeti** [education/classroom#327]
It seems like a lot of the OAuth scopes we ask for might only be needed for teachers. It would be awesome if we asked for less scopes for students if possible.

<img width="487" alt="screen shot 2015-10-15 at 12 25 18 pm" src="https://cloud.githubusercontent.com/assets/1144197/10523504/f7e5679c-7337-11e5-99ce-852689a36207.png">

Any sense of which scopes the student OAuth accesses use?

/cc @gregose

**Comment by johndbritton** [comment]
Thanks for the feedback, we're planning to address this in https://github.com/education/classroom/issues/263.

The general outline is that we'll have a system of "stepping up" required permissions as users access different parts of the app.
