### ISSUE TITLE
paginating to page2 does not work We're sorry, but something went wrong.

### ISSUE THREAD

**Issue by bfritscher** [education/classroom#329]
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

Airbrake Error 1534922897515050480

Some student did delete their account, maybe it broke something?

**Comment by johndbritton** [comment]
@bfritscher Can you give this another try? It should be working now.

**Comment by bfritscher** [comment]
@johndbritton Thanks for the fix! It is now working again.
