### ISSUE TITLE
Using classroom removes owner role

### ISSUE THREAD

**Issue by floe** [education/classroom#332]
Hello everyone, 

I'm trying to get GH Classroom up and running for my organization "mmbuw". I recently created a first assignment and handed out the invitation link, however, this morning, I discovered that 

a) all teams were grayed out in the classroom and deleted in the organization, and that 
b) all team repositories had been deleted, too. 

On top of that, I lost my owner role in the organization. I'm not sure if this is related, but it happened more or less at the same time, so I'm suspecting some connection.

Please advise on how to prevent this from happening again...

Best, Florian

**Comment by floe** [comment]
Apologies for the noise, the repositories are still there, I just couldn't see them due to the lost owner role.

**Comment by floe** [comment]
Sorry, spoke too early - the same issue just happened again, I lost my Owner role after viewing the classroom.

Exact sequence of events, as far as I can tell:
* created new group assignment, using existing groups
* handed out link to students
* about 8-9 students signed up with existing teams
* I viewed the classroom page to verify
* Few seconds later, all teams are suddenly grayed out and team repositories deleted again
* I no longer have my owner role for the organization.

This should be fixed ASAP, whatever the root cause, because if I hadn't had a co-owner, I'd now be locked out of my own organization.

**Comment by johndbritton** [comment]
Thanks for reporting this @floe, we're looking into the cause and will update this once we know more.

**Comment by johndbritton** [comment]
This issue has been resolved, if you need help regaining access please contact [GitHub Support](https://github.com/contact).
