### ISSUE TITLE
Question/enhancement: pull requests for assignments?

### ISSUE THREAD

**Issue by floe** [education/classroom#333]
Hi again, sorry for the noise, but I couldn't find this documented anywhere. 

I've used "plain" Github for my class last year, and was trying out Classroom for this year. One of the features I liked best last year is that students can use a pull request to the repo with the starter code to submit their assignment. The way it looks to me at the moment with Classroom, however, is that the newly created repo and the one with the starter code are not linked in any way, so they can't create a PR. Is this intended behaviour? Or did I miss some setting along the way?

In any case, thanks for working on this!
Best, Florian

**Comment by johndbritton** [comment]
> the newly created repo and the one with the starter code are not linked in any way, so they can't create a PR

This is the intended behavior.

> I liked best last year is that students can use a pull request to the repo with the starter code to submit their assignment.

This is a perfectly acceptable way to use GitHub in courses, if that works for you keep on doing it. The issue that a lot of folks have with that style is that every student is able to see every other student's work. Classroom for GitHub makes it possible to distribute starter code to students without them being able to see each other's code.

Students are still able to send pull requests against the starter code, but now each would do it within their own repository.

Feel free to ask more questions if anything is unclear.

**Comment by floe** [comment]
Thanks for the quick response! Just to clarify, would these PRs then be visible in the starter code repository?

**Comment by johndbritton** [comment]
> would these PRs then be visible in the starter code repository?

If you're using Classroom for GitHub, no. They'd be visible on each individual repository that was created for the student or group working on the assignment.

Pull requests can be sent from a fork to the root repository, to any other repository in the network, or in the case of Classroom for GitHub and in many software development teams to the same repository.

**Comment by floe** [comment]
Got it, thanks for clearing that up.
