### ISSUE TITLE
Github Classroom stole my organization

### ISSUE THREAD

**Issue by chortlehoort** [education/classroom#337]
I attached an organization to Github Classroom to assign projects to my students. Organization URL is https://github.com/nashville-software-school.  I decided later to detach the organization from Github Classroom.  When I detached, it removed all the students I added to the organization, but **it also removed me**, the owner, so now I no longer have ownership of my organization.

**Comment by chortlehoort** [comment]
Nevermind, I see that the issue (https://github.com/education/classroom/pull/334) has already been reported and is being worked on.

**Comment by johndbritton** [comment]
This issue has been resolved, if you need help regaining access please contact [GitHub Support](https://github.com/contact).
