### ISSUE TITLE
Project names include some kind of key

### ISSUE THREAD

**Issue by mattfxyz** [education/classroom#342]
Example "myFakeGroup/SuperAwseomeProject-34235-9160-4e50-ba243-545435-cool-team created by mattfxyz

**Comment by johndbritton** [comment]
I believe this is a known issue. @tarebyte can you look into this?

**Comment by tarebyte** [comment]
@mattfxyz do you know how to reproduce this? I'm working on a failing test

**Comment by mattfxyz** [comment]
I sent out two different assignments. One had it and one didn't. It was
called "JavaScript-calculator"
