### ISSUE TITLE
When going into an assignment detail I get an error

### ISSUE THREAD

**Issue by lernerd** [education/classroom#345]
at https://classroom.github.com/classrooms/15637487-fullstackdev/group-assignments/php-basic

Airbrake Error 1545795695196206831
![screen shot 2015-11-03 at 4 01 00 pm](https://cloud.githubusercontent.com/assets/1086613/10918380/1a9fdaa4-8244-11e5-913a-8e495076c175.png)

**Comment by tarebyte** [comment]
@lernerd it looks like one of your students rejected their auth token, I should have a fix for this later today.

**Comment by lernerd** [comment]
Oh yeah, it was actually myself since I'm trying it out :stuck_out_tongue: 
Sorry, I hope it helps in fixing someone else's problem as well.
Thanks!

**Comment by tarebyte** [comment]
Not a problem, thank you for the report!

**Comment by lernerd** [comment]
Thanks! :smile:
