### ISSUE TITLE
not able to give a title to the classroom 

### ISSUE THREAD

**Issue by carnevlu** [education/classroom#346]
When selecting a organization,
![screen shot 2015-11-04 at 08 44 10](https://cloud.githubusercontent.com/assets/3392707/10932371/65875dd0-82d0-11e5-96bc-79e9226d68b1.png)

er are not able to provide the input "title" that is required.
![screen shot 2015-11-04 at 08 44 14](https://cloud.githubusercontent.com/assets/3392707/10932377/69fca9a6-82d0-11e5-8508-6869ff5b0c5c.png)

behaviour found on Chrome and safari on OSX 10.9

**Comment by johndbritton** [comment]
@carnevlu I take it you're trying to add the @UNIFR organization, correct?
