### ISSUE TITLE
Add stafftools for management

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#356]
Let's add a `StafftoolsController` with restricted access for managing the application. Here's a wishlist of features (we won't necessarily add them all):
- [x] Fake login (#359)
- [x] Search for all app models (#380)
- [ ] Statistics
- [ ] Link to exceptions in airbrake for current user
- [x] User activity (last access / login)
- [ ] Staff notes / comments for all resources
- [x] Enabled features when we get Flipper (#474)

**Comment by tarebyte** [comment]
@johndbritton what kind of statistics would be most helpful?

**Comment by johndbritton** [comment]
We might want to use this as a project tracking issue and have a separate issue for each of the main features in stafftools.

Counts for all resources:
* Users
* Organizations
* Assignments
* GroupAssignments
* Groupings
* Groups

It'd be great if we could show a visual representation of the growth of these resources on a chart or graph of some sort

**Comment by johndbritton** [comment]
There should be a resource overview for each of the models as well that gives a full diagnostic overview of the resource, for example the user overview would include data on related models.

You might consider building on top of `rails_admin` or similar, but I'm not sure if we need the full set of tools included in that library.

**Comment by johndbritton** [comment]
@tarebyte How do you feel about breaking out the last few remaining tasks here to individual issues with a bit more explanation of what they should be. Maybe with more info we can attract some community contributions.

**Comment by tarebyte** [comment]
@johndbritton that sounds fine to me, do you want me to tackle it?

**Comment by johndbritton** [comment]
Sure, if you could write a short issue for each and close this one that'd be :100:
