### ISSUE TITLE
I do not have any repositories

### ISSUE THREAD

**Issue by sk11302012** [education/classroom#374]
I do not have any repositories but the system tells me that I have more than 10 and disallow my access to a project. What does it mean?
Thanks

**Comment by tarebyte** [comment]
@sk11302012 Which organization are you trying to use for Classroom?

Did you recently upgrade your orgs plan?

**Comment by sk11302012** [comment]
No, as far as  I understand. 


    On Tuesday, November 24, 2015 6:38 PM, Mark Tareshawty <notifications@github.com> wrote:
 

 @sk11302012 Which organization are you trying to use for Classroom?Did you recently upgrade your orgs plan?—

**Comment by tarebyte** [comment]
@sk11302012 what organization are you trying to use?

**Comment by sk11302012** [comment]
Mark:It works now. So the issue seems to be resolved.Thanks. 


    On Wednesday, November 25, 2015 2:28 PM, Mark Tareshawty <notifications@github.com> wrote:
 

 @sk11302012 what organization are you trying to use?—
