### ISSUE TITLE
Cannot make this private assignment, your limit of 10 repositories has been reached.

### ISSUE THREAD

**Issue by tk1221** [education/classroom#375]
I have been invited to view an assignment and upon clicking the button:
"Accept this assignment", it gives the following error message:
"Cannot make this private assignment, your limit of 10 repositories has been reached. You can request a larger plan for free at https://education.github.com/discount"

I visited the above link but it is only for academic people and it is not applicable.
Thank you.

**Comment by tarebyte** [comment]
@tk1221 you can upgrade your plan from your organization settings if you are not academic and need more repos.

Are you using Classroom for GitHub for a non academic purpose?

**Comment by tk1221** [comment]
I am not using it actually. I had only one repo from sometime ago, and today I got an invitation to view an assignment and go the message that the limit of 10 repos was exceeded. I never had 10 repos. I contacted the people with the assignemnet-invitation and they solved the problem and I viewed the assignment. It was for non-academic. Thank you for your message.



    On Wednesday, 25 November 2015, 13:30, Mark Tareshawty <notifications@github.com> wrote:
 
 

 @tk1221 you can upgrade your plan from your organization settings if you are not academic and need more repos.Are you using Classroom for GitHub for a non academic purpose?—
