### ISSUE TITLE
Memory quota exceeded errors on Heroku

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#385]
I'm seeing occasional `R14: Memory Quota Exceeded` errors in the Heroku logs.

https://github.com/schneems/puma_worker_killer is a possible solution for those errors.

cc/ @mkcode because you know a thing or two about memory issues.

**Comment by mkcode** [comment]
Yes. `puma-worker-killer` has worked very well in the education-web application. This work was done in https://github.com/github/education-web/pull/962 for reference.
