### ISSUE TITLE
Isolating requests to GitHub API in tests

### ISSUE THREAD

**Issue by beydogan** [education/classroom#390]
What would you say to create a wrapper for requests that are being made to GitHub and only mock that in tests? And then we can write unit tests for that wrapper to make sure its fine. 

This would make controller + feature specs less painful :)

**Comment by tarebyte** [comment]
@beydogan in your mind how would this spec look. Would each test have a stub method for the API call we know it's going to perform and then call the controller action?

**Comment by tarebyte** [comment]
@beydogan right now this is not very high up on my todo list.

If you want to open a PR with these changes I'd be :cool: with reviewing it.

Thanks!
