### ISSUE TITLE
Stafftools design

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#392]
@jasonlong w're currently working on Stafftools and wanted to run a few screens by you to see if you had any thoughts.

Right now we're working on #380 which lets use search for all resources on Classroom. But we're looking to make more to add on, including a dashboard of useful graphs (#391)

Here are some screenshots of what we have so far:

A single search result on the page

<img width="656" alt="screen shot 2015-12-07 at 8 53 38 pm" src="https://cloud.githubusercontent.com/assets/564113/11645722/e2bd41f2-9d24-11e5-9841-7f6b547288bf.png">

This is the main search page with results.

![screen shot 2015-12-07 at 8 53 32 pm](https://cloud.githubusercontent.com/assets/564113/11645708/c630f5ce-9d24-11e5-8e3b-f3f2c118b1a8.png)

This is what it looks like when there aren't any search results.
![screen shot 2015-12-07 at 8 53 56 pm](https://cloud.githubusercontent.com/assets/564113/11645716/d8443802-9d24-11e5-9747-45105cea5d55.png)

This is an example of a resource view
![screen shot 2015-12-07 at 8 57 39 pm](https://cloud.githubusercontent.com/assets/564113/11645766/36831bf4-9d25-11e5-94f0-f261bca19fc5.png)

Thank you for your time in advance!

/cc @johndbritton

**Comment by johndbritton** [comment]
A lot of this is still a work in progress, but it'd be awesome if you could do a pass through at some point once we've got the bulk of stafftools working and usable.

**Comment by jasonlong** [comment]
I was hoping to find time to take a look at this today, but it doesn't look like I'll be able to until tomorrow. Hopefully that's ok.

**Comment by tarebyte** [comment]
@jasonlong that's more than fine, thank you for your help!

**Comment by jasonlong** [comment]
Sorry for the delay, gents.

Taking a look at these screens with fresh eyes, the first thing that feels weird to me is calling this section "Resources". I'm not sure that name would hit me as the place to go if I wanted to look for something. I feel like there's also a cognitive disconnect between the search icon and the name Resources. So would "Search" work here?

When people search, they probably know if they're looking for a user, assignment, etc. and the current results listing is hard to scan. Could we break the results out into sections (e.g. Users, Assignments, etc.)?

On the design side, I'm wondering if it might be better to use a white background on the admin pages. The side nav looks pretty awkward floating out there and I don't think it would be as bad with a white bg.

**Comment by tarebyte** [comment]
@jasonlong I'm :cool: with renaming it to Search, this is what the page looks like with a white background

![screen shot 2015-12-09 at 3 25 36 pm](https://cloud.githubusercontent.com/assets/564113/11697746/229f66b4-9e89-11e5-9b66-0fad1c59b379.png)

**Comment by tarebyte** [comment]
> When people search, they probably know if they're looking for a user, assignment, etc. and the current results listing is hard to scan. Could we break the results out into sections (e.g. Users, Assignments, etc.)?

What would be a good way (UI wise) to do this?

**Comment by jasonlong** [comment]
Yeah, that white bg looks better IMO.

For the results sections, I was just thinking you'd have a heading for each one (an `h2` or `h3`) like:

## Users

[image] name
[image] name
[image] name

## Assignments

[image] assignment name
[image] assignment name
[image] assignment name

And so on. If there are no results for a section, I probably wouldn't show it at all. All of this in the regular boxed container for "Search".

Make sense?

**Comment by tarebyte** [comment]
Yeah makes sense to me, I'll give this a go

**Comment by jasonlong** [comment]
:cool: If you need me to make a :lipstick: pass afterwards, I can do that. 💃

**Comment by tarebyte** [comment]
:sparkling_heart:

**Comment by johndbritton** [comment]
I also like marking staff areas with a visual signal like this:

![screen shot 2015-12-09 at 1 22 55 pm](https://cloud.githubusercontent.com/assets/123345/11699204/08fb82e4-9e78-11e5-83db-a1a580e1fbe5.png)

**Comment by tarebyte** [comment]
@johndbritton, where is that usually located?

**Comment by johndbritton** [comment]
at the border between navigation and the beginning of the page.

**Comment by tarebyte** [comment]
How's this?

![screen shot 2015-12-12 at 10 22 42 pm](https://cloud.githubusercontent.com/assets/564113/11765302/ef009fe2-a11e-11e5-8db0-38b81881b84c.png)

**Comment by jasonlong** [comment]
I have some ideas that should help with readability. If I wanted to take a pass, would #380 be the place?

**Comment by tarebyte** [comment]
@jasonlong yup that would be it!

**Comment by jasonlong** [comment]
I've added my followup over in #380.

**Comment by johndbritton** [comment]
I think we're done with this. Thanks @jasonlong.
