### ISSUE TITLE
Had to abandon github classroom in full exam setting

### ISSUE THREAD

**Issue by iamgoodbytes** [education/classroom#401]
Hi guys, I'm sure this is my own problem to solve but I wanted to give you all a heads up. I have a github organization account and prepared an exam assignment for my 40+ students here in class. 

They wanted to start the assignment but 30 of them got the error saying that we have maxed out at 10 accounts. I'm abandoning github classroom right away so that my students can work on their exams.

Make sure you check how many private repo's you can create in your account or you'll have lots of angry students in front of you when the exam starts :)

**Comment by tarebyte** [comment]
@iamgoodbytes for future reference, you can request more private repos from GitHub education in advance and I'm sure they wouldn't mind helping out.

**Comment by johndbritton** [comment]
Hey @iamgoodbytes, I'm sorry for the trouble. If you need more repositories you can request them here: https://education.github.com/discount.
