### ISSUE TITLE
Possible bug when deleting an assignment repo

### ISSUE THREAD

**Issue by lifeiscontent** [education/classroom#416]
When deleting a assignment repo a student may no longer accept the assignment.

**Steps Taken**
1. Click invite link
2. Delete repo from github
3. Click invite link again
4. see the screen shot below

![49699abe132da40b32488a69bfa532f2f78ca4d6265df70397 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/180963/12081616/61a3e0de-b233-11e5-99cc-0174089890a9.jpg)

**Expected outcome**
1. Click invite link
2. Delete repo from github
3. Click invite link again
4. Create repo once again

**Comment by tarebyte** [comment]
@lifeiscontent this is not a bug. Currently deleting the GitHub repo does not delete the corresponding `assignment_repo` for the assignment.

So as far as Classroom knows the student has an assignment.

**Comment by lifeiscontent** [comment]
@tarebyte how would I revoke an assignment from a student?

**Comment by lifeiscontent** [comment]
or have the student delete the assignment and start new?

**Comment by neezer** [comment]
:+1: I'd also like to know the answer to this, as I have deleted a repo for a student and have been unable to get them to create a new one (clear the assignment for that student).

**Comment by tarebyte** [comment]
@lifeiscontent @neezer we're working on a PR to solve this problem.

Thanks for your patience!

**Comment by tarebyte** [comment]
The pull request is #418

**Comment by tarebyte** [comment]
@neezer may I ask what was the cause for you deleting the students repository? Was it because of an error by Classroom?

**Comment by lifeiscontent** [comment]
@tarebyte for us, we have students that periodicly drop out of our course because its too hard. So we need to remove their coursework.

**Comment by neezer** [comment]
@tarebyte In addition to everything @lifeiscontent said, I wasn't sure what kind of notifications activity on student repos would trigger on my account and wanted to test it out. I thought I could tweak some settings, delete the student repo, and have them try again fresh, but ran into this issue.

Think #418 provides what we're looking for, though.
