### ISSUE TITLE
Invalid repository name, use the format owner/name

### ISSUE THREAD

**Issue by meling** [education/classroom#420]
The text entry field marked *Add your starter code from GitHub (optional)* is not clear what is expected, and the example is not helpful. I've tried all the different path and URL combinations that I can think of to no avail. That is, I get the following error message:

    Invalid repository name, use the format owner/name

Suggestions?

**Comment by tarebyte** [comment]
Hi @meling an example of the format `owner/name` would be `rails/rails` or `github/gitignore` it's the owner (organization or user) and the name of the repository.

Is there we can change the wording to make this more clear?

**Comment by johndbritton** [comment]
@meling What would make the most sense to you for that field?

**Comment by guntbert** [comment]
@johndbritton This had me stumped too for a while. I'd suggest
>use account/repository (e.g. education/classroom)

instead of the current
>e.g. education/classroom

(btw I only found out just now, that pressing <kbd>-></kbd> opens useful suggestions.)

**Comment by cyhsutw** [comment]
@guntbert thanks for the feedback!

The text you suggested looks clearer, @johndbritton @tarebyte @dinever what do you think?

**Comment by johndbritton** [comment]
:+1: @cyhsutw do you want to send a pull request?

**Comment by dinever** [comment]
Looks good @cyhsutw. However, I'd suggest that we use *username* instead of *account* in that text:

> use username/repository (e.g. education/classroom)

**Comment by guntbert** [comment]
@dinever not quite my intention, as the organization's name isn't a *username* per se.

**Comment by johndbritton** [comment]
To keep consistent with the terminology on GitHub let's use

> login/repository

**Comment by guntbert** [comment]
@johndbritton remember we are talking about people (like myself) who have not got a feeling for the overall concept and therefore want to follow suggested procedures very carefully. Now I would read
> login/repository

but my login is *guntbert*, whereas the organization that owns that repo is *psysKursRE*. So telling me to use my login will not clarify things for me.
<sub> I admit though that this **is** better than the current version</sub>

**Comment by johndbritton** [comment]
@guntbert Your organization also has a login, "psysKursRE"

Maybe we're coming at this from the wrong angle. Rather than trying to make help text, how can we make the repository select box more clear?

**Comment by guntbert** [comment]
@johndbritton Ah now I see more light :smile_cat: 

As is often the case we are using the same words for different things: 
- to me a *login* is something that somebody uses (probably along with a password..) to gain access to some ressource.
- You are using *login* as a field name in your database - which is perfectly valid of course but not so obvious.

Making the repository select box more clear looks like a very good idea™. I didn't see it as a *select box* at all (until I accidentally pressed <kbd>-\></kbd>). So it might be a good idea to actually make it something like a "combobox": on being activated it flips open and reveals suggestions, starting with (some/all ?) repos in the current organization.

**Comment by johndbritton** [comment]
> on being activated it flips open and reveals suggestions, starting with (some/all ?) repos in the current organization.

An even simpler thing would be to create a blankslate that opens on focus and tells the user to search for the repository by name.

**Comment by guntbert** [comment]
Sounds good, only I have no idea what a *blankslate* is :confused:

**Comment by johndbritton** [comment]
@guntbert Sorry about that. It's just what displays on a screen when there's no data.

What I'm thinking is that we automatically open the pane and display some useful info as soon as you select the field. Then the useful information will be replaced once you begin interacting with the element.

**Comment by guntbert** [comment]
:+1:

**Comment by tarebyte** [comment]
Closing this, due to it being stale.
