### ISSUE TITLE
Connection refused in production logs

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#426]
I'm seeing the following constantly in the logs:

`2016-01-09T21:18:06.105506+00:00 app[web.1]: localhost:11211 failed (count: 0) Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 11211`

Looks like the default settings for the `dalli` gem. I see that we have memcached configured for peek, but maybe the default is being used somewhere else and is causing the log noise.

**Comment by tarebyte** [comment]
@johndbritton  We might need to change this line https://github.com/education/classroom/blob/2665578268b63c0881ae073279500307ae530b6c/config/environments/production.rb#L58
