### ISSUE TITLE
Blankslate text confusing

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#44]
I just connected my GitHub account to Classroom and landed on the blankslate page with this:

> This classroom has no organizations. Add one now.

The statement makes me think that I'm in my classroom and I might have multiple organizations for my classroom. I think it would be better stated as something along the lines of:

> You're not managing any GitHub organizations with Classroom. Add an organization to get started.

**Comment by tarebyte** [comment]
:+1: I like that, it's much clearer. I need to get better at copy in general
