### ISSUE TITLE
Improve unauthorized organization experience

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#441]
Issues like #439 are caused when the user doesn't know they need to grant organization access explicitly. This can happen easily when the user creates the organization after the first time using Classroom.

We're showing the `ProTip` that says to grant access, but perhaps that's not prominent enough. What do you think about adding an additional avatar to the list of classrooms that pushes the user through the access granting flow.

It might say something like "I don't see my organization" or "Grant access to another organization" or "Use an organization that's not listed here."

cc/ @tarebyte

**Comment by nwoodthorpe** [comment]
I actually ran into this yesterday, created an org for Classroom and couldn't figure out why it wouldn't show. The tooltip isn't very prominent, I think a separate avatar may be a good idea.

**Comment by nwoodthorpe** [comment]
It'd be nice to do this at some point. This would be a good first issue for anyone looking to contribute :)

**Comment by daibhin** [comment]
Took this on as my first contribution in https://github.com/education/classroom/pull/1106. Let me know if it needs work :)
