### ISSUE TITLE
Octospinner gets stuck when opening in new tab

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#442]
If you go to an assignment listing page and cmd+click on an assignment link to open it in a new tab, the octospinner starts, and never stops.

**Comment by franktank** [comment]
Hi John,

I see that in the organization index view, @organizations is being rendered, but I am not sure where the octospinner is called.

**Comment by tarebyte** [comment]
Hi @franktank :wave:

The markup for the spinner is here:
https://github.com/education/classroom/blob/master/app/views/layouts/application.html.erb#L16

The coffeescript is here:
https://github.com/education/classroom/blob/master/app/assets/javascripts/navigation.coffee

Hope this helps!

**Comment by franktank** [comment]
Can a temporary fix be to put a timer on the loading spinner?

**Comment by johndbritton** [comment]
> Can a temporary fix be to put a timer on the loading spinner?

I'd prefer that it not be triggered at all in this case.

**Comment by franktank** [comment]
So in the event that the user is trying to open a new tab, disable the octospinner feature?

**Comment by johndbritton** [comment]
That's the desired behavior.

**Comment by tarebyte** [comment]
> So in the event that the user is trying to open a new tab, disable the octospinner feature?

But in this case @johndbritton @franktank we lose the spinner entirely for the page load.

It would be :cool: if we could use https://github.com/turbolinks/turbolinks-classic#progress-bar to make this change.

**Comment by franktank** [comment]
Okay so I was thinking of checking for event of ctrl key being pressed, and if it is hide the octospinner.

**Comment by johndbritton** [comment]
Fixed in https://github.com/education/classroom/pull/506
