### ISSUE TITLE
Consider implementing Learning Tools Interoperability (LTI)

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#443]
[LTI on Wikipedia](https://en.wikipedia.org/wiki/Learning_Tools_Interoperability)

There's a standard for integrating tools like Classroom for GitHub with learning management systems, we should investigate and come to a decision about implementing the standard.

**Comment by nwoodthorpe** [comment]
Closing in favor of #443, I've moved your comment to that thread.

**Comment by mozzadrella** [comment]
@michaelmior LTI is a separate project from Google Classroom, but at the moment I am doing research and gathering requirements for this. Would you be open to being contacted for a brief interview about your school's needs?

**Comment by michaelmior** [comment]
@mozzadrella I don't have any specific needs at this point. I understand that LTI is a separate project. I'm just confused why this issue was closed and where I should be following.

**Comment by hinshofer** [comment]
@mozzadrella How's the research going? I am a TA at National Polytechnic University of Armenia and we are trying to integrate Moodle LMS which allows adding external tools as long as they conform the LTI.

Is there anything I can help you with?

**Comment by mozzadrella** [comment]
@hinshofer we plan to undertake this work starting 10 June :)

**Comment by dgilleland** [comment]
For those wishing to follow the development, see [this branch](https://github.com/education/classroom/tree/google-classroom) and Issue #1791

**Comment by d12** [comment]
https://github.com/education/classroom/issues/721 is tracking progress. We're targetting a launch of August 13'th for roster sync from LTI tools to Classroom.
