### ISSUE TITLE
Explanation for test env tokens

### ISSUE THREAD

**Issue by cbetta** [education/classroom#451]
I've been trying to setup the project locally and a bit confused around terminology. I understand I need to setup an organisation and then need an ID and TOKEN for 2 users (org admin and student) but I'm not quite getting what `TEST_CLASSROOM_OWNER_ORGANIZATION_ID` and `TEST_CLASSROOM_OWNER_ORGANIZATION_LOGIN` are. Can someone please explain?

**Comment by cbetta** [comment]
Ok I figured it out. Will make an update to the docs to reflect the misunderstanding.

**Comment by tarebyte** [comment]
Sorry for the confusion @cbetta thank you for your contribution!

**Comment by tarebyte** [comment]
Closing this, due to it being stale.
