### ISSUE TITLE
Testing token scopes?

### ISSUE THREAD

**Issue by cbetta** [education/classroom#452]
Can someone explain what scopes the tokens for testing need exactly?

**Comment by cbetta** [comment]
Going off the `omniauth.rb` I assume it's the same: `scope: 'user:email,repo,delete_repo,admin:org'`. Am I right?

**Comment by tarebyte** [comment]
These are the tokens that you need and the minimum scopes they require.

| Token | Scope |
| ---------|-----------|
`TEST_CLASSROOM_OWNER_GITHUB_TOKEN` | `user:email,repo,delete_repo,admin:org`
`TEST_CLASSROOM_STUDENT_GITHUB_TOKEN` | `admin:org user:email`
