### ISSUE TITLE
How to delete a list of repositories by teacher_per

### ISSUE THREAD

**Issue by bzsmz1990** [education/classroom#456]
Do you guys know if there is a scripted way with teachers pet or some other script whereby you can delete a list of repositories?

Thanks.

**Comment by tarebyte** [comment]
@bzsmz1990 it would probably be better if you asked this in the https://github.com/education/teachers_pet repository but I would image you could do something like this

```ruby
# The doc https://developer.github.com/v3/repos/#delete-a-repository
# For this example we are using https://github.com/octokit/octokit.rb

# The token should have permissions to access the repositories you are looking to delete
client = Octokit::Client.new(access_token: token)

# These can either be the name of the repo ex owner/repo_name or the repo id 
repos = ['org/assignment1', 'org/assignment2']

repos.each do |repo|
  client.delete_repository(repo)
end
```

**Comment by johndbritton** [comment]
If there's any follow up to this, please take it to https://github.com/education/teachers_pet.
