### ISSUE TITLE
Questions about assignments

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#457]
From https://github.com/education/teachers/issues/35:

> It it required that you have a starter repo when creating an assignment? I created an assignment without one, but I am now unsure how students will hand in assignments as the individual repos are not forked and thus students cannot issue pull requests.

@khatchad it is not required to have a starter repo when creating an assignment. The reason we give everyone their own repository was due to a concern about cheating. If the user has a fork of a private repo they can see everyone else's fork which means that students can see everyone else's submission.

The best solution we have right now is to clone down the students repositories and count that as the submission.

> I am curious about this, too. Also, is it possible to use the Teacher's Pet tool with repos created from Classroom for Github?

@laprej while is it technically possible to use the `teachers_pet` with repos created by Classroom, I would strongly discourage it. If you use `teachers_pet` and perform an action on GitHub like deleting the assignment repositories Classroom has no way of knowing what has happened.

/cc @johndbritton

**Comment by laprej** [comment]
@tarebyte What if I just wanted to use it to copy their repositories e.g., clone_repos?

**Comment by tarebyte** [comment]
@laprej if you just wanted to use `clone_repos` that's an ok use case.

But if you did something like `delete_repos` then you're going to run into trouble.

**Comment by khatchad** [comment]
Thanks for the info, @tarebyte. In this case, what do you recommend we use for submissions considering that pull requests are not viable?

**Comment by johndbritton** [comment]
> I am now unsure how students will hand in assignments as the individual repos are not forked and thus students cannot issue pull requests.

It is possible to create a pull request from one branch to another branch within the same repository.

> In this case, what do you recommend we use for submissions considering that pull requests are not viable?

I still suggest having students submit pull requests against their master branch.

**Comment by khatchad** [comment]
What if students don’t have a branch other than master?

**Comment by johndbritton** [comment]
> What if students don’t have a branch other than master?

A few options:

* Have them use feature branches
* Grade against master branch
* Create another branch and send a pull request from master to that branch for grading

I definitely recommend teaching students to make feature branches and send pull requests. I think it's likely that we'll be adding a feature to lock the master branch so that students must use a branch and submit code via a pull request. See https://github.com/education/classroom/issues/379#issuecomment-174479941 for details.

**Comment by khatchad** [comment]
@johndbritton Thanks for the feedback, but two of your solutions involve making branches, which we may not cover at all (if so, perhaps towards the end of the semester). Also, grading against the master branch is not ideal as it is difficult to leave comments in scattered commits.

**Comment by johndbritton** [comment]
> Thanks for the feedback, but two of your solutions involve making branches, which we may not cover at all

The only way to make a pull request is to use two branches. In a fork you have two branches, one in each repository.

> Also, grading against the master branch is not ideal as it is difficult to leave comments in scattered commits.

I don't recommend leaving feedback on individual commits. If you want to avoid students having to create branches you could make the branches in your starter code and they would already have the branches when they clone the repository.

**Comment by tarebyte** [comment]
Closing this, due to it being stale.
