### ISSUE TITLE
Add ability to auto-invite students to a team

### ISSUE THREAD

**Issue by vilhelmen** [education/classroom#459]
We don't have a lot of private repos available for our organization, so each student gets a single repo to use throughout the course, and they must update their repo to get new assignments and code updates.

Under the sandbox model, students have to add the originating repo manually as their upstream, but in order to give them access to the upstream, which is private, I have to add them to a team that has read access to the repo manually. This is, obviously, a little messy, so it would really be nice if there was a way to either add/invite a student to a team when they create their repo, or add a button to the classroom site that allows adding selected/all students to a team.

**Comment by johndbritton** [comment]
> We don't have a lot of private repos available for our organization

You can request free private repositories for classroom use at https://education.github.com/discount

>  This is, obviously, a little messy, so it would really be nice if there was a way to either add/invite a student to a team when they create their repo, or add a button to the classroom site that allows adding selected/all students to a team.

I think the best solution for this is to use a starter code repository and invite link from Classroom to distribute the code. If you need more private repositories, we can help you with that.
