### ISSUE TITLE
Private assignment with no private repositories available

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#46]
Creating a private assignment if there are no private repositories available results in a poor experience:

![screen shot 2015-06-24 at 5 14 24 pm](https://cloud.githubusercontent.com/assets/123345/8325424/87d39eac-1a94-11e5-859d-3d2b811ebe03.png)

**Comment by tarebyte** [comment]
@johndbritton the public API doesn't allow me to check to see if the user has private repositories does it. I read through the docs and it doesn't seem like it.

Any recommendations about how to safe guard against this?

**Comment by johndbritton** [comment]
@pengwynn Do you have any suggestions for this? We'd like to be able to check the number of available private repositories in the organization's plan via the API.

**Comment by pengwynn** [comment]
@johndbritton @tarebyte: I'm assuming you'd be authenticating as someone who otherwise could create a new repository? You just need a way to know if there's headroom on the plan to do so?

**Comment by tarebyte** [comment]
@pengwynn yup that's exactly it. We authenticate an organization admin who can create repos on behalf of the org.

**Comment by tarebyte** [comment]
@pengwynn @johndbritton as it turns out you can get the plan for an organization.

I just :walking: right by it.

**Comment by johndbritton** [comment]
Here's the result I'm seeing now as a student who tries to accept an invitation to a private individual assignment on an organization which has no private repositories available

<img width="1041" alt="screen shot 2015-09-01 at 1 52 12 pm" src="https://cloud.githubusercontent.com/assets/123345/9604633/b220a9be-50b0-11e5-9df0-8fc601198835.png">

Need to handle the following cases:

* [ ] accepting private individual assignment
* [ ] accepting private group assignment
* [ ] teacher creating private individual assignment (disallow if they have no private repositories and tell them what their remaining quota is)
* [ ] teacher creating private group assignment (disallow if they have no private repositories and tell them what their remaining quota is)
