### ISSUE TITLE
Student not given write permission to repo after accepting assignment

### ISSUE THREAD

**Issue by djh-** [education/classroom#460]
First of all, sorry if this has already been made an issue - I didn't see anything open, and I still see this problem happen in production.

At [Make School](http://makeschool.com) we use Classroom for Github a lot.  See our classroom organization here: https://github.com/makeschool-17

Very commonly, students won't be granted write permission to their repositories after accepting assignments.  It seems to happen somewhere between 10 to 20% of the time.  [Here's](https://github.com/MakeSchool-17/ruby-koans-cmaher92) an example repository where the student wasn't granted write permission, so I manually added him this morning.

**Comment by johndbritton** [comment]
> Very commonly, students won't be granted write permission to their repositories after accepting assignments.

I'm sorry to hear you're having this problem. We're looking into it now. In the meantime, can you please share any other examples of this problem that you come across.

**Comment by johndbritton** [comment]
@djh- Did Classroom create the repository and not give your student access, or did it fail to create the repository entirely?

It looks to me like the repository was not created by the application and that maybe you created it manually as I don't see a record of this repository in the app.

**Comment by johndbritton** [comment]
@tarebyte can you take a look into this?

**Comment by djh-** [comment]
@johndbritton It created the repository, but didn't give the student write access.  I haven't ever created any repositories manually.  

Sometimes, after clicking the accept assignment button, the repositories fail to create entirely.  I instruct the students to keep trying until it successfully creates, which happens eventually.  Perhaps that issue is related.

**Comment by djh-** [comment]
[Here](https://github.com/MakeSchool-17/introduction-to-angular-choncou) is another example of a repository that I had to add the write permission to after creation.

**Comment by johndbritton** [comment]
Thanks for the additional information @djh-. It looks to me like the repositories are being created but then they're not recorded in the Classroom app for some reason. My hunch is that it has to do with some validations we're doing on our end after creating the repository on GitHub via the API.

@tarebyte I think this is related to the rollback of a record with failed validations where the repo was created on GitHub successfully. I'd expect the repo to be removed and an error reported to the user.

@djh- Does this happen for the same students on all assignments or consistently for multiple students on certain assignments? Anything you've noticed to help us track down a pattern would be useful.

**Comment by johndbritton** [comment]
@tarebyte I believe this is the relevant [Airbrake exception](https://github-education.airbrake.io/projects/116727/groups/1590173271909693545/notices/1603090033488074427) for the case mentioned [above](https://github.com/education/classroom/issues/460#issuecomment-185432149).

**Comment by djh-** [comment]
Okay, so I have (at least) one student in particular who very often has problems.  He's Github user [DennisAleynikov](https://github.com/DennisAleynikov)

He has two different errors that are common.  He made a screen recording, and dumped the Chrome HTTP Archive for each.

[Github Classroom Issue 460.zip](https://github.com/education/classroom/files/141698/Github.Classroom.Issue.460.zip)

**Error 1**
See 422error.mov and 422classroom.github.com.har in the .zip.  In this case the repo was successfully created, though Dennis was shown the Rails error in the movie.  He was not given write permissions to his repo.  I added those later.

**Error 2**
See 302forbidden.mov and 302classroom.github.com.har in the .zip.  In this case, the repo was never created successfully.  Dennis was given two different errors, "You are forbidden from performing this action on Github.com" and "Assignment failed to be created".

Actually, I'm having trouble accepting that assignment too.  I get the same problem.  This could be a completely different issue than the permissions one.

That assignment is [this one](https://classroom.github.com/classrooms/14812411-make-school-17/assignments/trees-mazes-python/) and [here](https://classroom.github.com/assignment-invitations/742a24d0861bd7d3b4a946784fa10f37) is the invitation link.

**Comment by djh-** [comment]
Update on **Error 2**

May or may not actually matter, but even though the repo wasn't successfully created, I see updates on my news feed indicating that they were:

<img width="649" alt="screen shot 2016-02-22 at 5 52 57 pm" src="https://cloud.githubusercontent.com/assets/1690436/13240108/99097704-d994-11e5-9fb7-030c795db222.png">

**Comment by johndbritton** [comment]
> May or may not actually matter, but even though the repo wasn't successfully created, I see updates on my news feed indicating that they were:


That's really useful information, and definitely points to a validation error upon creation.

**Comment by jermowery** [comment]
Any progress on fixing this issue?
We have a team assignment going out next week and we need to know if GitHub is a viable option.

**Comment by tarebyte** [comment]
@jermowery there is a fix in the works, should be able to push it up soon for review. Sorry for the troubles.

**Comment by jermowery** [comment]
Awesome thanks!

**Comment by johndbritton** [comment]
@djh- just spent some time with @tarebyte debugging this issue. Can you do the following and report back:

1. Log out of Classroom using https://classroom.github.com/logout
2. Visit https://classroom.github.com and log in again
3. Have your student try and accept the invitation and see if it works.

We expect that this will resolve the issue, but could use your help in testing.

If it works, we'll work on a permanent fix.

**Comment by jermowery** [comment]
@johndbritton We will be starting a new assignment tomorrow, I will let you know what happens when students start accepting the assignment.

**Comment by tarebyte** [comment]
@jermowery I just checked out your permission scopes.

If you can have @djvaughn sign out of classroom and sign back in at https://classroom.github.com directly, then you should be good to go!

We use all of the organizations owners token to avoid rate limiting. Both you and @hjamal have the correct permission scope.

**Comment by jermowery** [comment]
Thanks for the info!

I had all of our owners log in to classroom, log out, and log back in.
Can you verify that the permission scope is correct for all of our owners (@cindytrieu, @djvaughn, @hjamal, @rhm12399)?

**Comment by tarebyte** [comment]
@jermowery I see the following users as owners of the Classroom

:white_check_mark: @cindytrieu
:white_check_mark: @djvaughn
:white_check_mark: @hjamal
:white_check_mark: @jermowery

All of these users have the correct scopes.

**Comment by jermowery** [comment]
Awesome thank you! We will let you know if everything goes smoothly with our next assignment.

**Comment by johndbritton** [comment]
> We use all of the organizations owners token to avoid rate limiting. Both you and @hjamal have the correct permission scope.

That explains why it was only happening in some cases.

**Comment by jermowery** [comment]
@tarebyte Students are accepting a new team assignment now and everything seems to be working correctly at the moment!

**Comment by tarebyte** [comment]
:tada:

**Comment by johndbritton** [comment]
Great, thanks for your patience and help resolving this @cindytrieu @djvaughn @hjamal @jermowery.

We now know the underlying issue and are working on a solution to fix it permanently. In the meantime, just avoid using an assignment link from your main account as it's possible for the app to reduce your GitHub oauth scopes if you do.

We're working on a solution in https://github.com/education/classroom/pull/485

**Comment by jermowery** [comment]
This still seems to be an issue. We might accidentally follow an invite link or follow one intentionally to try to help a student. Has there been progress on fixing the issue #485 looks like it hasn't been updated in awhile.

**Comment by johndbritton** [comment]
@jermowery This is still on our radar, we're working with some folks on the API team to come up with a solution for this.

**Comment by tarebyte** [comment]
@jermowery we fixed this issue in #604 please let us know if you have anymore problems.

Thanks!
