### ISSUE TITLE
Missing organization on the page to create new classroom

### ISSUE THREAD

**Issue by PeterDaveHello** [education/classroom#462]
Oops I cannot see [my new organization](https://github.com/NCTU-CSE-Introduction-to-Algorithms) on the [page to create new classroom](https://classroom.github.com/classrooms/new), the screenshot will contain some private orgs so I didn't take it, if it's required, I can send you an email, thanks!

**Comment by tarebyte** [comment]
@PeterDaveHello did you give Classroom permission to use your Organization?

**Comment by tarebyte** [comment]
![screen shot 2016-02-18 at 9 23 00 am](https://cloud.githubusercontent.com/assets/564113/13145909/3a04aaba-d621-11e5-9cdf-f2af9089fb44.png)

**Comment by PeterDaveHello** [comment]
Ah, my bad ... so careless that I didn't notice that, sorry for bothering, thanks @tarebyte
