### ISSUE TITLE
Team assignments not creating repos correctly

### ISSUE THREAD

**Issue by jermowery** [education/classroom#466]
Organization: CSC335

Today was the first time that we had students in our course accept a team assignment and attempt to use a team repo. However we ran into several problems that appear to be caused by GitHub.

The first issue that often after accepting an assignment a repository was created as expected with the correct name (the team name), but that repo would not have the team as a collaborator (so no students could access it).
Some steps to replicate for students (this doesn't always happen, it appears to be intermittent):

Have a student follow the assignment invitation link
Have the student create a new team name (for example partner1-partner2).
Have the student click "Join team"
The student will see that they were successful and a link to the repository (for example assignment-partner1-parter2) will be shown.
Upon clicking the link the student gets an error that the repo does not exist.

On the admin side, we can confirm that the repository assignment-partner1-partner2 exists, and we can confirm that the team partner1-partner2 exists, but partner1-partner2 is not added as a collaborator of the assignment-partner1-partner2 repository.

The second issue we faced was that GitHub Education stopped making repositories for students at one point. The steps are exactly the same as above, except when as admins we went to check if the repo was created it was not, but the team was created.

We started with this assignment: https://classroom.github.com/classrooms/16736830-csc-335-spring-2016/group-assignments/git-part-ii

When that encountered the problems above we created a new assignment: https://classroom.github.com/classrooms/16736830-csc-335-spring-2016/group-assignments/git-part-2

The new assignment did not fix the issues.

We also tried having students accept the assignment in an Incognito window and that also did not work.
We confirmed that we do indeed have enough private repos for the students.

**Comment by jermowery** [comment]
This could be related to this but I am not certain: https://github.com/education/classroom/issues/460

**Comment by jermowery** [comment]
It looks like the creation happens sometimes but is delayed, in one case by 8 minutes

**Comment by johndbritton** [comment]
Thanks for reporting this @jermowery.

> Some steps to replicate for students (this doesn't always happen, it appears to be intermittent):

Since it's intermittent I think it may have something to do with one of your instructors having an authentication token with not enough scopes.

> This could be related to this but I am not certain: #460

Yes, this is what I'm thinking. Can you have all of your instructors follow the steps [here](https://github.com/education/classroom/issues/460#issuecomment-193284915) and report back if the issue keeps happening.

I think this should resolve the issue for you, we're working on a permanent fix.

**Comment by nwoodthorpe** [comment]
This has been stale for over a year. It seems this isn't an issue any more, if this comes up again feel free to re-open.
