### ISSUE TITLE
Could only give read permission to student repo after accepting assignment

### ISSUE THREAD

**Issue by jtong** [education/classroom#468]
I am using classroom in remote training.
I want student use fork strategy to finish assignment, but they can push to their repo directly, so I have to correct them.
Could we make user choose only give read permission to student repo?

**Comment by howiehu** [comment]
:+1:

**Comment by johndbritton** [comment]
> I want student use fork strategy to finish assignment

You don't need to use Classroom if your students are using forks.

> Could we make user choose only give read permission to student repo?

We don't have plans to implement such a feature, as it's possible to do directly on github.com without an external application.
