### ISSUE TITLE
Undefined behavior on re-accepting an invitation link of a repo that has been deleted

### ISSUE THREAD

**Issue by hackerkid** [education/classroom#471]
If I delete a repo and try to accept the invitation by opening the invitation link again it results in an  undefined behavior 

```
You may receive an invitation to join @OOM-Blasters via email invitation on your behalf. No further action is necessary.

Your assignment has been created here: # 

```
The problem is 

1) The messsage shows `#` instead of repo name
2) It's not showing that the repo has been deleted

I have fixed [https://github.com/education/classroom/pull/470] this by displaying a message that the repo no longer exists. The fix is for individual repo. I can make a pull request for group assignment once this get merged.

**Comment by jayvdb** [comment]
This is related to #563 ; it is easily reproduced.
It would be nice if the repository can be manually created, and the invitation link works again.
