### ISSUE TITLE
api.github.com not returning a complete list of repositories

### ISSUE THREAD

**Issue by ksuderman** [education/classroom#472]
I am not sure this is a Classroom bug, or general GitHub API bug...

I am trying to fetch a list of repositories for our organization (class) via the GitHub API. i.e.
```bash
$> curl -H "Authorization: token ..." https://api.github.com/orgs/vassar-cmpu-331/repos
```
However, the returned JSON document is missing at least one repository that I know of:
https://github.com/vassar-cmpu-331/lexicalanalyzer-mayahawkins.git

I am in the process of setting up travis-ci and the above repository is not listed there either.

I don't know if it is related, but when I view our organization on the GitHub web site it shows the repository was updated four days ago, but when I actually visit the repository nothing has been updated since the original checkout.

**Comment by tarebyte** [comment]
@ksuderman if you are curling `https://api.github.com` then it has nothing to do with Classroom.

Are the repos you are missing private repos?

**Comment by ksuderman** [comment]
Yes, we are using private repositories for the assignments, and it just seems to be this one repository that isn't listed; the repositories for the other students are listed correctly.  I wasn't sure if this was a problem with the API or with the way the assignment repositories were created by Classroom.  Is there someplace else I should open an issue?

**Comment by tarebyte** [comment]
@ksuderman there sure is! The wonderful Supportocats at GitHub should be able to help you out. You can message them here: https://github.com/contact
