### ISSUE TITLE
Autocomplete for starter code repo

### ISSUE THREAD

**Issue by kenancasey** [education/classroom#480]
It'd be great if the starter code repo textbox autocompleted based repo names (instead of having the type it exactly correct).

**Comment by tarebyte** [comment]
@kenancasey that would be a pretty handy feature, unfortunately we don't really have to bandwidth to tackle this right now.

If you're really interested in this feature I encourage you to open a pull request.

Closing this just to try to clean up the issues, but please don't feel that I've closed this conversation from taking place.

**Comment by johndbritton** [comment]
Yeah, this is a great feature request. I'm going to re-open and label as `help-wanted` as this would be a great beginner contribution to the project.

**Comment by stevelaskaridis** [comment]
Hey, @kenancasey.
I am taking a look at the classroom's code and issues, as I would be interested in taking part in the classroom project for the [GSOC 2016](https://developers.google.com/open-source/gsoc/).

Could you describe me a little bit more on what you would like to accomplish?
I assume that you are referring to this textbox:
<img width="1106" alt="screen shot 2016-03-10 at 18 06 05" src="https://cloud.githubusercontent.com/assets/5221013/13677629/05a96c62-e6eb-11e5-9f54-5f5b576a52e3.png">

Is the autocomplete feature only for the repo names, after you have defined the owner?  
For example, if I have written `education/`, it would provide me with autocomplete options for:
* `education/classroom`
* `education/guide`
* `education/teachers_pet`
* `education/teachers`

**Comment by kenancasey** [comment]
I imagined it working the same way as when I assign repos to a team.

![screen shot 2016-03-10 at 1 46 31 pm](https://cloud.githubusercontent.com/assets/315883/13682306/d4a0a7d0-e6c6-11e5-866d-382a2b4e0f7d.png)

**Comment by johndbritton** [comment]
@kenancasey The only difference is that repo selection UI is scoped to repositories in the organization. In our case it can be any repository the user has access to on GitHub.

**Comment by stevelaskaridis** [comment]
I get your points. It would be something useful to have indeed.

Implementation-wise, this may sound like a "stupid" question, but bare with me:
1. Should the backend fetch the repositories from Github and serve them to the browser of the user?
**or**
2. Should the frontend of the user make a cross domain request and get the results straight from the Github backend?

With the first approach you don't tie up the frontend to Github specifically. This means that we could potentially talk to different services in the future without touching the frontend. **However**, you have the overhead that comes with it - server-side - which means asking Github for something each time some user types something in the field, which is not scalable in any case.

With the second approach, I guess it is possible to circumvent the classroom's backend and go get the results from github.

IMHO, the second approach is the most realistic one if we want the scope to be as broad as the github search itself. If we decide to limit the scope to the repos the user owns or contributes, then things change.

@johndbritton, @kenancasey What's your take on that?

**Comment by johndbritton** [comment]
You'll need to do it server side as you need to make an authenticated request to the API in order to let the user choose private repositories. I'd make an endpoint that the classroom frontend can use with the user session to make the request from the backend and then have the backend make the request to the GitHub API.

**Comment by dinever** [comment]
Hi @johndbritton,

I wonder where you expect the autocomplete endpoint to be in the routes.

We can use

```
/classrooms/:organization_id/assignments/suggestions?q=keyword
```

or setup a new namespace `autocomplete`

```
/autocomplete/repositories?q=keyword
```

**Comment by johndbritton** [comment]
> `/autocomplete/repositories?q=keyword`

I think a new namespace is cleaner. What do you say @tarebyte?

**Comment by tarebyte** [comment]
Agreed, since the search is for an API and not scoped by the models on the Classroom app it should be it's own thing.

@dinever what do you think about

`/autocomplete/github-repositories?q=keyword`

to be more explicit

**Comment by dinever** [comment]
Sure @tarebyte @johndbritton,

BTW in the future, we can add more endpoints like `/autocomplete/students?q=keyword` if necessary.

**Comment by cyhsutw** [comment]
Hello everyone,

I tried to implement this feature, here's what I got so far:

- By default, the site displays the repositories of the user (using the [list your repos API] (https://developer.github.com/v3/repos/#list-your-repositories), sorted by `updated`).
- Or, if the user put type some string like `education/t`, it will search the the repositories under namespace `education`.
- It utilize the [repository search API](https://developer.github.com/v3/search/#search-repositories) directly for other queries like `rails`.

The UI will look like this:

![autocomplete](https://cloud.githubusercontent.com/assets/1046917/13898957/3d7aeb1e-ee1d-11e5-8769-2d2aee257792.gif)

I'm refining my tests and will submit a PR soon. Would :heart: to :ear: your feedback/suggestions.

Thanks :bowtie:

**Comment by tarebyte** [comment]
@cyhsutw ascetically that looks really good so far, but I can't give give really useful feedback until I see the code :smiley:

**Comment by johndbritton** [comment]
@cyhsutw looks great. Would it be possible to add autocomplete for the org / user login component as well?

**Comment by ConnorCartwright** [comment]
Hey guys @tarebyte @johndbritton 

I also sunk a few hours into this earlier today and am at a similar point to @cyhsutw (minus the testing)

<img src="http://i.imgur.com/C1WDdLo.gif">

At the moment I have hardcoded my auth details - I wasn't exactly sure how to get hold of them from the app.

I'd love to get feedback on this - playing around with the app has been great fun, starting to like CoffeeScript :satisfied:

**Comment by cyhsutw** [comment]
Thanks for the feedback @tarebyte and @johndbritton!


>  Would it be possible to add autocomplete for the org / user login component as well?

I think this is technically possible but I'd like to know where we can use these features.

I have some use cases in my mind:

- Filter the organizations when creating classrooms.
- Filter the students who have accepted the assignment.

But these can be achieved by using simple filters (probably without sending any requests to the server).

Would like to hear the about your ideas.

Thank you :bowtie:

**Comment by johndbritton** [comment]
> I wasn't exactly sure how to get hold of them from the app.

@ConnorCartwright You should have your own OAuth application for development and store the credentials in your `.env` file. Then, the credentials will be available as environment variables like `ENV['API_KEY']` or similar.
