### ISSUE TITLE
Organization owner can't view classroom

### ISSUE THREAD

**Issue by ksuderman** [education/classroom#482]
Our classroom organization has two owners, myself and @nancyide, however I am the only one that can view the classroom/assignments through [https://classroom.github.com](https://classroom.github.com).  When Nancy visits the Classroom web site she gets the message "You're not managing any classrooms yet.".  If she tries to create a classroom she can see our organization (vassar-cmpu-331), but when she selects it she gets the message that someone else (me) has already created a classroom for that organization.

Is there something I have to do so that she can see the classroom and assignments?

![screen shot 2016-03-07 at 6 59 50 pm](https://cloud.githubusercontent.com/assets/4098072/13587889/36a14bd6-e499-11e5-98c4-3270e9e43aa3.png)

**Comment by tarebyte** [comment]
@ksuderman if @nancyide goes to the Classroom URL directly it should add her to the classroom.

Let me know if this doesn't work.

**Comment by ksuderman** [comment]
Thanks for the quick response!  I was mis-reading (mis-understanding) the instructions on the /settings page.  I was simply sending her https://classroom.github.com not the full URL to our classroom.

**Comment by johndbritton** [comment]
@ksuderman Keep an eye on https://github.com/education/classroom/issues/259, we'll be fixing this up so that owners are automatically given access even without going to the specific classroom url.
