### ISSUE TITLE
Importer Failing on New Private Assignments

### ISSUE THREAD

**Issue by crichID** [education/classroom#489]
@johndbritton This issue appears to be similar to https://github.com/education/classroom/pull/323. We are using Classroom to distribute activities to Trainer candidates. It worked well until this week when we started seeing a recurring issue with the importer.

1. The candidate accepts the assignment. The assignment template is a private repo and the assignment creates a new private repo for the candidate.
2. At the importer stage the candidate is being asked to authenticate. They cannot authenticate with their own credentials and the import fails.
3. I am able to log in as GitHubTeacher (the assignment owner) and enter my credentials to complete the import.

Ideas?

**Comment by crichID** [comment]
I wanted to rule out unverified email addresses as the reason for the failure, so I gathered the following additional info from the candidate: "I previously had a GitHub account, but I created a new account today for the activities. I verified my email prior to starting the import."

**Comment by tarebyte** [comment]
@crichID do you know specifically when this week? I made a change to the importer #486

**Comment by crichID** [comment]
@tarebyte I was first notified of the issue ~24 hours ago and it looked like we had one failure before that!

**Comment by tarebyte** [comment]
@crichID just :ship: :dash: the fix for this. Sorry for the trouble!

**Comment by crichID** [comment]
Thank you for the speedy resolution @tarebyte - all those good things people say about you are definitely true :smile:

**Comment by tarebyte** [comment]
:blush:
