### ISSUE TITLE
Design Halp

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#49]
:heart: :green_heart: :purple_heart: 

- [x] Logo/Branding #42
- [x] Landing Page #77
- [x] Dashboard Layout #61
- [x] Organizations #78
  - [x] Invite Admins #79
  - [x] Settings #85
- [x] New Assignment #80 
- [x] Assignments
  - [x] Creation #86
  - [x] Main Page #81
  - [x] Invitation Page #82 
  - [x] Settings #84 
- [x] Group Assignments
  - [x] Creation #87
  - [x] Main Page #81
  - [x] Invitations Page #83 
  - [x] Settings #84

**Comment by jglovier** [comment]
Hey @tarebyte! :wave: :sparkles:  Sorry I've been MIA here. Will start providing feedback here shortly.

**Comment by tarebyte** [comment]
Thanks @jglovier! :sparkles:

**Comment by jasonlong** [comment]
Hey guise,

I know there was some confusion around getting @tarebyte some design help here. He and I got together yesterday and cranked through some rough mockups for a handful of views. I wanted to at least let folks chime in w/ any feedback or concerns here. I know Mark needs to get this wrapped up in the next week, so I'll try to help out with the CSS based on this direction. In the meantime, feel free to give feedback.

**Assignments listing**

![assignments](https://cloud.githubusercontent.com/assets/6104/9333114/19e8ccf0-4596-11e5-9405-d97a76e36f75.png)

**Assignment details**

![assignment-details](https://cloud.githubusercontent.com/assets/6104/9333125/26634faa-4596-11e5-82fd-20f0fef76417.png)

**New assignment options**

![new-assignment](https://cloud.githubusercontent.com/assets/6104/9333137/30eafc98-4596-11e5-918b-7a73c3aa880a.png)

**Generic form example**

![form-example](https://cloud.githubusercontent.com/assets/6104/9333146/3ab86be8-4596-11e5-8540-419d37ee7512.png)

**Comment by jglovier** [comment]
@jasonlong thank you so much for jumping in here!! :heart: :metal: :bow:

Looking really good. :heart_eyes: Only note is @jasoncostello's [comment](https://github.com/education/classroom/issues/42#issuecomment-131967779) about calling it GitHub for Classroom instead.

**Comment by jasonlong** [comment]
:boom: Thx @jglovier. And :thumbsup: on "GitHub for Classrooms" – makes sense to me.

**Comment by cameronmcefee** [comment]
:+1: Looks excellent.

**Comment by johndbritton** [comment]
Thanks @jasonlong, looks great.

> :boom: Thx @jglovier. And :thumbsup: on "GitHub for Classrooms" – makes sense to me.

I'm cool with calling this whatever you all think makes sense, but please keep in mind that we also need to come up with a url for this. Simplest thing is going to be to give it it's own domain, like `githubclassroom.com` or 'githubforclassrooms.com`. Shorter is better IMHO.

**Comment by johndbritton** [comment]
My only real feedback on these mockups is that we should make space for showing organization logins in addition to their friendly titles that are stored in the classroom app. cc #92

**Comment by johndbritton** [comment]
One more thing that I just thought of:

Might be helpful to provide navigational elements to get to `education.github.com` and a link for help.

**Comment by jasonlong** [comment]
Re: domain names - does it make sense to use `classroom.github.com` following the pattern of education, government, desktop, etc.?

> Might be helpful to provide navigational elements to get to education.github.com and a link for help.

:thumbsup: Good call.

**Comment by jglovier** [comment]
>Re: domain names - does it make sense to use classroom.github.com following the pattern of education, government, desktop, etc.?

Yeah, we should really use a consistent paradigm for our properties that designates something is an actual GitHub project – at least when it's part of the name (i.e. Atom, Boxen, etc are separate things because they a) are open source projects and b) don't have "GitHub" in the name). I'm :-1: on `githubclassroom.com` (or `githubforclassroom.com`), as it may introduce confusion as to whether it's an official GitHub thing.

cc @jasoncostello & @cameronmcefee who likely have feels about this too.

**Comment by johndbritton** [comment]
> Re: domain names - does it make sense to use classroom.github.com following the pattern of education, government, desktop, etc.?

:+1:

**Comment by cameronmcefee** [comment]
Assuming this remains as a GitHub maintained property, my vote is *GitHub for Classrooms* at *classroom.github.com*

**Comment by johndbritton** [comment]
> Assuming this remains as a GitHub maintained property, my vote is GitHub for Classrooms at classroom.github.com

:+1:

**Comment by jasoncostello** [comment]
> Assuming this remains as a GitHub maintained property, my vote is GitHub for Classrooms at classroom.github.com

Ditto.

**Comment by johndbritton** [comment]
:clap:

**Comment by jglovier** [comment]
![anchorman-jump-in-air](https://cloud.githubusercontent.com/assets/1319791/9877217/77046bde-5b89-11e5-9fb5-6e871cc1576d.gif)
