### ISSUE TITLE
Collecting assignments without teachers_pet

### ISSUE THREAD

**Issue by cswiercz** [education/classroom#493]
I am uncertain of how "best" to collect assignments using the sandbox method without the `teachers_pet` tool.

Are there assignment options on http://classroom.github.com that I am missing? I ask because the [classroom guide for the sandbox method](https://education.github.com/guide/sandboxing) explains how to use `teachers_pet` to manage assignment collection. However, this seems to contradict the message on the [`teachers_pet` repo](https://github.com/education/teachers_pet) recommending that teachers use Classroom for GitHub, instead. A recommendation is just a recommendation but I was wondering where things were going with the website.

I have already written a (low-quality) Python script that reads in a students list with GitHub account names and clones repos matching the pattern `<assignment name>-<student GitHub account name>`.

**Comment by johndbritton** [comment]
> However, this seems to contradict the message on the teachers_pet repo recommending that teachers use Classroom for GitHub, instead.

Classroom for GItHub is fairly new and we'll be updating documentation to be more clear.

> I am uncertain of how "best" to collect assignments using the sandbox method without the teachers_pet tool.

Right now there's no standard way to do this. We have an open issue and plan to implement such a feature: https://github.com/education/classroom/issues/286

You might also want to check out https://github.com/education/classroom/issues/394 as well.

**Comment by cswiercz** [comment]
@johndbritton Thank you for the references! I will be keeping my eyes open.

In the meantime is there any reason why I shouldn't be using `teachers_pet` if only for obtaining student repos? I assume it's non-destructive to the organization / assignment structure.

**Comment by johndbritton** [comment]
> In the meantime is there any reason why I shouldn't be using teachers_pet if only for obtaining student repos?

You can still use it for cloning, just don't do anything that modifies the repositories. We'll be retiring `teachers_pet` eventually once we've addressed this need.
