### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by amitojsingh** [education/classroom#494]
Hello, 
I have installed classroom app successfully, but whenever I run the app it gives error 
Error 404 This is not the webpage you are looking for!
Have I missed something?

**Comment by johndbritton** [comment]
@amitojsingh What url are you using to try and access the local environment?

**Comment by amitojsingh** [comment]
I run this app and then open the URL 
`Localhost:3000`
this will open the homepage of classroom, but when I click on login with GitHub it gives an error.

**Comment by johndbritton** [comment]
@amitojsingh Make sure you've set up your `.env` file correctly. You'll need to register an OAuth application from your GitHub account [here](https://github.com/settings/developers). Once you've done that you'll have to copy `.env-example` to `.env` and set the configuration variables.

Once you've done that, let me know if you're still getting the error.

**Comment by amitojsingh** [comment]
Yeah! @johndbritton Thanks I have successfully done this but now I am getting this <a href="https://bitbucket.org/snippets/amitojsingh/KRdyj">error</a>.

**Comment by tarebyte** [comment]
@amitojsingh it doesn't look like you have elasticsearch running.

**Comment by amitojsingh** [comment]
Solved! Actually, I haven't installed java runtime for elastic search that's why it was not working. I have installed it from <a href="https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-on-an-ubuntu-vps">here</a>
Thanks!
