### ISSUE TITLE
Trying to improve the Getting Started guide

### ISSUE THREAD

**Issue by ConnorCartwright** [education/classroom#496]
Hey guys,

I'm just trying to work on making setting up the **.env** as simple as possible to make contributing to the app as easy as possible.

So far I've got:

> To find your Client ID and Secret you can register a new OAuth application at [this](https://github.com/settings/applications/new) page - after creation you should be able to see your Client ID and Secret. 
> 
> To find your GitHub user ID you can use [this](http://caius.github.io/github_id/) tool built by [caius](https://github.com/caius).
>
> To create a personal access token, you can go to [this](https://github.com/blog/1509-personal-api-tokens) page.

I think this is enough for the Development Environment variables (I'm assuming we can put our own user ID for the non staff admin id field?)

I'm more confused about the Testing Environment variables (below), to get these variables do we need to create a new organisation on GitHub?

> TEST_CLASSROOM_OWNER_GITHUB_ID	(The GitHub user_id of an organization admin)

> TEST_CLASSROOM_OWNER_GITHUB_TOKEN	(The Personal Access Token for the classroom owner)

> TEST_CLASSROOM_STUDENT_GITHUB_ID	(Test OAuth application client ID)

> TEST_CLASSROOM_STUDENT_GITHUB_TOKEN	(The Personal Access Token for the student)

> TEST_CLASSROOM_OWNER_ORGANIZATION_GITHUB_ID	(GitHub ID (preferably one created specifically for testing against))

> TEST_CLASSROOM_OWNER_ORGANIZATION_GITHUB_LOGIN	(GitHub login (preferably one created specifically for testing against))

For the classroom owner id  and the owner organisation id can we use our own GitHub ID again?

For the student ID & token, do we need another GitHub account?

What should we use for the classroom owner organisation field?

Sorry for the big post - I'd like to try and make a big push over the next week to improve what I can :).

@johndbritton @tarebyte

**Comment by johndbritton** [comment]
> To create a personal access token, you can go to this page.

Do we need a personal access token? I don't think that should be necessary except maybe for the test stuff.

> I'm more confused about the Testing Environment variables (below), to get these variables do we need to create a new organisation on GitHub?

I think these are used for recording VCR cassettes and substituting them so no real credentials end up in our test mocks, but @tarebyte is the best person to explain those.

**Comment by ConnorCartwright** [comment]
Yeah, I think the personal access token is only used for the classroom owner and classroom student tokens. 

I'm going to go take a look at VCR and try and understand how it works.

So the test env variables are needed when we change application functionality and want to add new tests/record new cassettes?

**Comment by johndbritton** [comment]
> So the test env variables are needed when we change application functionality and want to add new tests/record new cassettes?

Yeah, I believe that's the case.

**Comment by johndbritton** [comment]
From the `README`:

> Classroom for GitHub uses environmental variables for storing credentials used in testing, these values are located in your .env file (created by script/setup). If you are recording new cassettes, you need to make sure all of these values are present.

**Comment by ConnorCartwright** [comment]
Ah okay - I think seeing the empty .env file waiting for the values was a bit daunting; I'll look at seeing if I could make it a bit clearer that the test values are needed when you make functionality changes and need to add test cases.

**Comment by tarebyte** [comment]
> I'm more confused about the Testing Environment variables (below), to get these variables do we need to create a new organisation on GitHub?

Yes you need to create your own GitHub organization

> For the classroom owner id and the owner organisation id can we use our own GitHub ID again?

No they have to be two separate IDs. One is the organization owner (a GitHub user) and one is a GitHub Organization ID that the owner is an admin of.

> For the student ID & token, do we need another GitHub account?

Yes

**Comment by tarebyte** [comment]
Closed by #498
