### ISSUE TITLE
Acessar repositorio

### ISSUE THREAD

**Issue by fabiofj** [education/classroom#497]
Não consigo acessar repositório criado para mim.

Recebo essa mensagem.

You are forbidden from performing this action on github.com

https://classroom.github.com/assignment-invitations/46b8cc40c9c58f551c471389a9794776

**Comment by johndbritton** [comment]
Related: https://github.com/education/classroom/issues/461

**Comment by johndbritton** [comment]
The root issue is https://github.com/education/classroom/issues/445. What's happening is teachers are testing out the application and accepting assignments. When you accept an assignment we ask for less account permissions than we do for teachers. If a teacher accepts an assignment, we reduce the access we have to their github accounts making it impossible for us to give their students access to the repos.

To resolve the issue, all teachers for the org have to log out and log back in on the main page https://education.github.com

This is a limitation of the way OAuth tokens work in the GitHub API and we're working on a permanent solution.
