### ISSUE TITLE
An interface to groups

### ISSUE THREAD

**Issue by dinever** [education/classroom#499]
Currently we can not rename the group of teams after we have created them, so it may get a little bit messy if we have a lot of groups and always use the default group name:

![screen shot 2016-03-16 at 10 50 12 am](https://cloud.githubusercontent.com/assets/1311594/13816467/e6136744-eb64-11e5-85f9-1478639fa9c3.png)

What about we add an interface to groups so that we can rename them and have an overview of teams inside the group?

Like this:

![screen shot 2016-03-16 at 10 53 32 am](https://cloud.githubusercontent.com/assets/1311594/13816593/5ab480e2-eb65-11e5-9c11-b0d948b776b0.png)

This can be part of the [GSoC project - Enhanced user management](https://github.com/github/mentorships/issues/90)

What do you guys think? :smile:

**Comment by johndbritton** [comment]
@dinever This would definitely be part of that GSoC project. Also take a look at https://github.com/education/classroom/issues/415 for some more context around features for team management.
