### ISSUE TITLE
Application Design

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#5]
I'd like to get feedback as to where in the process this application should be designed. I'm a fan of at least doing some general template design work done near the beginning.

Also since this is a GitHub sponsored open source project what about using [Primer](https://github.com/primer/primer) as a starting point for styling?

**Comment by johndbritton** [comment]
:+1: on using Primer. Are you talking about visual design? I think you're probably going to want to use Primer as a base and add polish as you go. When we get to the end of the summer we might be able to get some visual design help if we ask nicely.

**Comment by johndbritton** [comment]
I accidentally deleted my previous post, so sorry for the duplicate notification.

Definitely recommend using Primer, some lightweight visual design up front is probably worthwhile followed by spending some more time near the end of the summer polishing things up.
