### ISSUE TITLE
Assignments should not be named `new`

### ISSUE THREAD

**Issue by dinever** [education/classroom#507]
If a user creates an assignment named `new`, the URL for the assignment would be

```
/classrooms/:organization_id/assignments/new
```

which leads the user to the assignment creating page rather than the assignment page.

Same thing happens to group assignment too.

Potential solutions:
- Adding a `reserved word` restriction on the assignment name field, like the way GitHub handles it when user tries to create a user named `signin` or something.
  
   ![screen shot 2016-03-19 at 12 10 01 am](https://cloud.githubusercontent.com/assets/1311594/13896575/f6a2b494-ed66-11e5-8bba-9ff8366a5a52.png)
  
  or
- Moving the `assignments#new`route to another URL, which does not conflict with the `assignments#show` route.

**Comment by johndbritton** [comment]
A third solution would be to change our routes to be `id` based.

**Comment by nwoodthorpe** [comment]
Looks like slugs -> id has gone stale. I'm not sure moving `assignments#new` to a new URI is a good idea, the current URI is the correct RESTful URI.

Having an assignment name blacklist seems like a fair way to do this.
