### ISSUE TITLE
Copy invitation doesn't work

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#51]
The clipboard link on the invitation link doesn't copy the url to the clipboard.

**Comment by tarebyte** [comment]
I'd hate to add flash to the site, but what do you think about using [zeroclipboard](https://github.com/zeroclipboard/zeroclipboard)?

**Comment by johndbritton** [comment]
Word on the street is that this is possible without flash using `document.execCommand('copy')` in Chrome and maybe [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1012662) too.

I'd go for zeroclipboard and maybe see if they plan to update the lib to avoid flash usage.

**Comment by tarebyte** [comment]
There is a giant thread talking about just that https://github.com/zeroclipboard/zeroclipboard/issues/171

**Comment by johndbritton** [comment]
This comment has the solution from github.com: https://github.com/zeroclipboard/zeroclipboard/issues/171#issuecomment-111130212

I'd say just go ahead with zeroclipboard. We can always upgrade once they make it work with the new hotness.
