### ISSUE TITLE
Adding all users to organizations.

### ISSUE THREAD

**Issue by dinever** [education/classroom#517]
Hi guys,

Currently, we are adding students to the organization only if they are involved in any group assignment, for individual assignments we just add them as a repo collaborator.

However, this causes some difficulties in the implementation of student management features in the future.

For example, an interface for student management is needed for the sake of #292, #448. If we want to list all students in this classroom, we can retrieve those students who involved in any group assignments directly from `organization.repo_accesses`, for the rest part of the students who are not in the organization but is assigned with an individual assignment we have to retrieve them from `organization.assignments.assignment_repos.user` and remove those duplicated items, which is a little bit inconvenient.

What about we adding all students into the classroom(organization) as members when they accept assignments to facilitate student management?

Looking forward to your feedback! :smile:

**Comment by johndbritton** [comment]
> What about we adding all students into the classroom(organization) as members when they accept assignments to facilitate student management?

The main challenge with doing this is that we'd have to migrate all existing users to the new style which is less than ideal. Also, the default permission level for organization members is not really good for Classroom as it defaults to read access for everything in the organization and there's no way to manage that setting via the API.

We'd have to ask teachers to change their org settings manually. For now, I think the best route is to do the de-duplication ourselves and continue with the existing model of using outside collaborators.

**Comment by dinever** [comment]
Thanks, this is pretty reasonable. :smile:
