### ISSUE TITLE
Why does this not let you add a description to each assignment?

### ISSUE THREAD

**Issue by crank123** [education/classroom#530]
Why does this not let you add a description to each assignment? This is something that would be very useful. This would cut down on the amount of time spent creating each assignment.

**Comment by tarebyte** [comment]
> This is something that would be very useful. This would cut down on the amount of time spent creating each assignment.

@crank123 I'm not entirely sure I follow, can you expand upon your thoughts here?

**Comment by johndbritton** [comment]
The expectation is that the assignment description is included in the starter code's `README.md` file, but would love to have your input on how we could improve the experience for you.
