### ISSUE TITLE
Use id based routing throughout the app

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#531]
Although the intention of having pretty urls is nice, it's caused way more trouble for us than it's worth. Let's move to a simpler, `id` based routing system.

The default routes for all resources should be based on `id`s.
1. Implement `id` based routes for all resources
2. Make sure slug based routes redirect to their new id based coutnerparts
3. (optional) As a follow-up, bring slug based routes back with user configured slugs rather than auto-generated slugs.

**Comment by sahilshekhawat** [comment]
To be backward compatible we need to support current slug based routes too along side id based routes, right? Also, I am not sure if I understood 3rd point. Can you please elaborate on that?

**Comment by johndbritton** [comment]
> To be backward compatible we need to support current slug based routes too alongside id based routes

Yes, we will need to redirect the existing slug based routes.

> Also, I am not sure if I understood 3rd point. Can you please elaborate on that?

Right now, slugs are auto-generated from the name of the assignment. If a user changes the name, the slug doesn't update. We might want to let teachers create a `permalink` url for their classroom that uses a manually configured slug rather than an auto-generated one.

I'd expect it to be something like `https://classroom.github.com/:slug` where slug is manually configured. In a perfect world, slug would be the organization login from GitHub, but that's not easy to do because the login can be changed and there's no way for us to detect the changes.

**Comment by johndbritton** [comment]
I think this is still a valid issue. @nwoodthorpe, maybe something you can resolve this summer.

**Comment by d12** [comment]
We're not too sure what issue slug-based URLs were causing 3 years ago. Closing, but please re-open if there's more information to add!
