### ISSUE TITLE
Automatically create team from students

### ISSUE THREAD

**Issue by khatchad** [education/classroom#533]
I would like to have a team automatically created consisting of the students in my course. Specifically, when they accept an invite into the organization, they should automatically be added to a team called "students."

**Comment by dinever** [comment]
Hi @khatchad,

What do you want to achieve by having all students added to a team?

The reason we are not adding all students to the organization is about the default permission level. The default permission level for GitHub organization members is `read`, which means students can see each other's private repo. However, we'd prefer it to be `none` as we don't really want students to have read access to everything in the orgnization, and there is no API for us to modify the default permission level so we have to ask teachers to set it manually, which is not very ideal.

Related: #517

**Comment by khatchad** [comment]
Hi @dinever,

> What do you want to achieve by having all students added to a team?

I want to share solutions with the students but I do not want to make the solution public. As such, I'd like to give *read-only* access to such repos to the *student* team.

> The reason we are not adding all students to the organization is about the default permission level. The default permission level for GitHub organization members is read, which means students can see each other's private repo. 

Is it possible to change that level? Because, I currently have all students in a student team as part of the org and they cannot see each others repos by default.

> However, we'd prefer it to be none as we don't really want students to have read access to everything in the orgnization, and there is no API for us to modify the default permission level so we have to ask teachers to set it manually, which is not very ideal.

Ah, so perhaps I set it to `none`. I can't remember, but currently the org is setup correctly. The only problem was that I needed to create the *student* team manually.

**Comment by johndbritton** [comment]
> I want to share solutions with the students but I do not want to make the solution public. As such, I'd like to give read-only access to such repos to the student team.

We've heard this feature request before and hope to offer a solution in Classroom. You may want to subscribe to https://github.com/education/classroom/issues/527 for updates.

> Is it possible to change that level? Because, I currently have all students in a student team as part of the org and they cannot see each others repos by default.

Yes, but the setting is not currently available via the GitHub API and not available to Classroom to manage for you. You can manually change the setting at `https://github.com/organizations/#{your_organization_login}/settings/member_privileges` under the "Default repository permission" section.

**Comment by johndbritton** [comment]
@khatchad Does #527 cover your use case sufficiently? I think that feature will solve your problem, even if the implementation isn't that we create a `students` team in your organization.

If so, we can close this issue. Otherwise, it'd be helpful if you could provide some more details around why creating a `students` team is the preferred solution for you.

**Comment by khatchad** [comment]
@johndbritton Yes, I think that #527 covers this request. I think that a `students` team would be useful to share multiple solutions.

**Comment by johndbritton** [comment]
> Yes, I think that #527 covers this request. I think that a students team would be useful to share multiple solutions.

Closing this in favor of #527, thanks for the feedback @khatchad.
