### ISSUE TITLE
Bring back the forking model

### ISSUE THREAD

**Issue by khatchad** [education/classroom#534]
Before classrooms, I used the forking model and pull requests. Now, there are just too many (student) repositories which are not related in anyway besides their name to the original (instructor) repository. Also, pull requests were very convenient to review and comment on student code.

**Comment by johndbritton** [comment]
@khatchad You are still able to use forks with your students on GitHub directly. For that case, there's no need to use Classroom.

We created Classroom because the forking model was not sufficient for many teachers. Particularly, the fact that all repositories in a network of forks are visible to everyone was not acceptable to teachers who wanted to keep their students from seeing each the work of their peers.

We'd be happy to consider adding additional functionality to Classroom to meet the needs of teachers. Can you expand on why the forking model is useful to you and how having it as part of Classroom would be helpful?

**Comment by khatchad** [comment]
On Fri, Apr 01, 2016 at 05:43:25AM -0700, John Britton wrote:
> @khatchad You are still able to use forks with your students on GitHub
> directly. For that case, there's no need to use Classroom.

I disagree, actually. I think that classrooms is still useful. I find the invitation link to be very useful in particular. It really makes signing students up for the course very easy.

> 
> We created Classroom because the forking model was not sufficient for many
> teachers. Particularly, the fact that all repositories in a network of forks
> are visible to everyone was not acceptable to teachers who wanted to keep their
> students from seeing each the work of their peers.

I should have been more precise. When I suggested to bring the forking model back I meant to have my cake and eat it too. That is, I would like a forking model where students are not able to automatically see the work of their peers.

> 
> We'd be happy to consider adding additional functionality to Classroom to meet
> the needs of teachers. Can you expand on why the forking model is useful to you
> and how having it as part of Classroom would be helpful?

1. Easy to see the differences between the starter code and students' submission.
2. Easy to comment on the complete submission (otherwise, I need to comment on individual commits, which is not very good at all).

**Comment by tarebyte** [comment]
> That is, I would like a forking model where students are not able to automatically see the work of their peers.

@khatchad that is impossible with the way the private forks work. All forks are connected in the same network.

So if you have a private fork there isn't anyway for us to turn off your ability to see other users private forks of the same repo.

**Comment by johndbritton** [comment]
> I think that classrooms is still useful. I find the invitation link to be very useful in particular. It really makes signing students up for the course very easy.

It would be possible for us to create an invite system and use forked repositories, but it would be impossible for us to keep the individual repositories private from the other students. This is built into the way forks work and it's not possible for us to change.

> 1. Easy to see the differences between the starter code and students' submission.
> 2. Easy to comment on the complete submission (otherwise, I need to comment on individual commits, which is not very good at all).

Both of these can be accomplished by having students use branches and submit pull requests to their master branch.

**Comment by khatchad** [comment]
Oh ok. Sorry, I thought that classrooms was owned by GitHub. As for the commenting and reviewing point, I find that scheme a bit hacky. Students are already having trouble learning git. I feel that it would be an extra burden on them to straight-away learn about branching and pull requests (that's something they can learn later, not for the first assignment, for example).

On Mon, Apr 04, 2016 at 12:10:25PM -0700, John Britton wrote:
>     I think that classrooms is still useful. I find the invitation link to be
>     very useful in particular. It really makes signing students up for the
>     course very easy.
> 
> It would be possible for us to create an invite system and use forked
> repositories, but it would be impossible for us to keep the individual
> repositories private from the other students. This is built into the way forks
> work and it's not possible for us to change.
> 
>      1. Easy to see the differences between the starter code and students'
>         submission.
>      2. Easy to comment on the complete submission (otherwise, I need to
>         comment on individual commits, which is not very good at all).
> 
> Both of these can be accomplished by having students use branches and submit
> pull requests to their master branch.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*
> 

-- 
Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad

**Comment by johndbritton** [comment]
> Oh ok. Sorry, I thought that classrooms was owned by GitHub.

This application was created and is run by GitHub. I think the confusion came from my statement above:

> but it would be impossible for us to keep the individual repositories private from the other students. This is built into the way forks work and it's not possible for us to change.

My point is that the forking feature of GitHub (the fork button) is built for collaborating on repositories across a network. All repositories in the network are visible to all members of the network and this is not something that we're going to change on GitHub. As such, it's not possible for Classroom to use a different behavior.

> Students are already having trouble learning git. I feel that it would be an extra burden on them to straight-away learn about branching and pull requests (that's something they can learn later, not for the first assignment, for example).

Pull requests require branches, there's no way around it. When using forks, you create a pull request from a branch of one network repository to a branch of another network repository. You can create a pull request from one branch in a repository to another branch in the same repository using the same steps. The only difference is that there's only one repository, not a network of repositories owned by different users.

**Comment by dato** [comment]
@khatchad You could include two branches in your "base repo": _master_ and _review_.

The copy of the repo that’s made for students includes both branches.

They write their code on master; for the PR you can give them a link like:

```
https://github.com/<orgname>/<repo>/compare/review...master
```

That should do it, I think.

**Comment by khatchad** [comment]
Interesting, thanks. I'll give that a shot.

On Sun, May 08, 2016 at 12:48:02PM -0700, Dato Simó wrote:
> @khatchad You could include two branches in your "base repo": master and review
> .
> 
> The copy of the repo that’s made for students includes both branches.
> 
> They write their code on master; for the PR you can give them a link like:
> 
> https://github.com/<orgname>/<repo>/compare/review...master
> 
> That should do it, I think.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub*
> 

-- 
Raffi Khatchadourian, PhD
Assistant Professor and Open Educational Resources (OER) Fellow
Computer Systems Technology
New York City College of Technology
City University of New York
300 Jay St., Room N913
Brooklyn, NY 11201-1909
United States
+1 (718) 260-5325
rkhatchadourian@citytech.cuny.edu
http://cuny.is/khatchad

**Comment by dhowe** [comment]
is is impossible for students to simply submit a PR on master back to the original (teachers) repo?

**Comment by nwoodthorpe** [comment]
It looks like this feature isn't possible with the current implementation of git and GitHub. Going to close, if anyone has any updates, feel free to re-open.
