### ISSUE TITLE
Students cannot join teams

### ISSUE THREAD

**Issue by pilla** [education/classroom#535]
When my students try to join an already created team for an assignment, they get the following message:

> The page you were looking for doesn't exist.
> You may have mistyped the address or the page may have moved.
> If you are the application owner check the logs for more information.

I have tried it myself with a non-admin account and it is reproducible. 

I have turned off the number of members in a team in the assignment (it was configured for two students) but it still does not work.

Creating a new team works.

**Comment by dinever** [comment]
Seems that classroom can not find the team in the related GitHub organization.

**Comment by pilla** [comment]
dinever, thanks for the reply.

Should I create teams before students create their own copy of the repository through the assignment link? In previous editions of this class I used teachers_pet, but it is not working anymore for me.

This is the invitation link, please try to join "test" team:

https://classroom.github.com/group-assignment-invitations/ea4439e60e33cff9d5576d3913ee4116

**Comment by pilla** [comment]
I just tried to add another account to the test team and compufpel organization, and I still got the same error.

**Comment by pilla** [comment]
And weirdly enough, now I received a mail telling me that I am now subscribed to the repo... and I can access it. 

So it seems like I need to:

- Create teams for my students
- Give them their team names and the link for the repositories

**Comment by tarebyte** [comment]
Hi @pilla, just jumping into this now and took a look at your issue, just to clarify a few things

> Should I create teams before students create their own copy of the repository through the assignment link?

No, that's not really the design of classroom. Also if you create the teams you could possibly degrade your access_token which could cause more problems.

According to the error logs it looks like your not able to find a singular group

Let me take a look at this today and I'll get back to you.

**Comment by pilla** [comment]
Hi @tarebyte 

Thanks for looking into my issue. If you think that can be fixed today, pray tell me. I am going abroad for a week and my students need the repos for their assignment, so if Classroom does not work, I am inclined to try teachers_pet again.

**Comment by johndbritton** [comment]
Thanks for reporting this @pilla, I think we've found the problem and are working on a resolution.

**Comment by tarebyte** [comment]
@pilla the fix for this has now shipped, I had a test user add themselves to one of your teams.

**Comment by pilla** [comment]
@tarebyte , thanks for the quick heads up.

**Comment by tarebyte** [comment]
@pilla no worries, thanks for the report!

I'll also go ahead and remove my test user from your group
