### ISSUE TITLE
API for a desktop client.

### ISSUE THREAD

**Issue by sahilshekhawat** [education/classroom#548]
To add various features like cloning all submission simultaneously we are planning to build a desktop client. We need an API (need not to be public or complete) which can be used by the desktop client. I have raised #547 to start this, which contains authentication part of the API.

**Comment by tarebyte** [comment]
@sahilshekhawat what API endpoints do you think we need, and how do you suggest we design them?

**Comment by sahilshekhawat** [comment]
Aim is to implement features which can not be implemented in web-app. Following are the main features that we plan to implement.

1. Authentication of a user.
2. List all organizations for a user and respective assignments.
3. Ability to clone all submission for an assignment simultaneously.
4. Directly create an issue in a submission repo. (Can me merged with next feature)
5. Open repo directly in browser/ or a particular file in a repo for feedback.
6. Give information about which student wrote a particular line.

For these features, right now, we just need info about organizations, assignments and submission repos.

1. Authentication endpoint. i.e. api/signin
2. GET api/organizations (i.e. GET /classrooms)
3. GET api/assignment (i.e. list all repositories and other info about assignment/group_assignment).

For the API, we can render json with a predefined structure and use it in out client. Since, right now we need to support GET requests, its pretty straightforward to implement. (e.g render json in views)

**Comment by sahilshekhawat** [comment]
We can also add more functionality in the future like:

1. Creating assignments.
2. Managing teams.

**Comment by johndbritton** [comment]
> Aim is to implement features which can not be implemented in web-app. Following are the main features that we plan to implement.

I agree here, only implementing things that we can't possibly do via the web.

> Authentication of a user.
> List all organizations for a user and respective assignments.
> Directly create an issue in a submission repo. (Can me merged with next feature)
> Open repo directly in browser/ or a particular file in a repo for feedback.
> Give information about which student wrote a particular line.

I don't think we need any of these.

> Ability to clone all submission for an assignment simultaneously.

This is the only feature we need.

> Authentication endpoint. i.e. api/signin
> GET api/organizations (i.e. GET /classrooms)
> GET api/assignment (i.e. list all repositories and other info about assignment/group_assignment).
> For the API, we can render json with a predefined structure and use it in our client. Since, right now we need to support GET requests, its pretty straightforward to implement. (e.g render json in views)

> Creating assignments.
> Managing teams.

We don't want to support these features via the API. Our goal is not to make a feature complete API, but rather to solve the problem of teachers cloning many repositories at one time in the simplest way.

We might add a full API at some point in the future, but it's really low priority for us right now. I think the simplest thing would be to generate JSON from an assignment with all the necessary data and use that to clone all the repositories.

**Comment by tarebyte** [comment]
Since this is stale, I'm closing it. Thanks @sahilshekhawat!

**Comment by sahilshekhawat** [comment]
I can work on this, if you can help me out regarding the roadmap and how
you envision it. Since, I was not able to understand that correctly.

On Tue, Jun 21, 2016 at 5:37 PM Mark Tareshawty <notifications@github.com>
wrote:

> Closed #548 <https://github.com/education/classroom/issues/548>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/education/classroom/issues/548#event-698948259>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AFnhlDgcH3J6A5lXednxNul2d76Ds2TGks5qN9PkgaJpZM4H_AgY>
> .
>
-- 
Sahil Shekhawat
https://sahilshekhawat.github.io
@sahil_shekhawat - https://twitter.com/sahil_shekhawat
