### ISSUE TITLE
How to switch a student from one team assignment to another?

### ISSUE THREAD

**Issue by orbeckst** [education/classroom#559]
What have I as the instructor or the student got to do if they wrongly joined the wrong team in a team assignment?

Can I manually delete the student from the team using the GitHub org team settings? Will this allow them to follow the classroom "accept team assignment" link again and join another team?

**Comment by johndbritton** [comment]
@orbeckst it's not currently possible to change a student from one team to another, but if you would email `education@github.com` with the username of the particular student you'd like reassigned I can fix it for you manually.

We're looking to add this as part of https://github.com/education/classroom/issues/292
