### ISSUE TITLE
Cannot Sign in;Students cant accept

### ISSUE THREAD

**Issue by Omarasifshaikh** [education/classroom#580]
Cannot sign into the website. Was able to get through with an error "you are not authorized". cannot sign in again after that. Students cannot accept the HW that was created during that time. Ive been using this for my class since a few months, so this may be a recent issue.

**Comment by Omarasifshaikh** [comment]
A temporary bug in chrome was causing hundreds of requests to GitHub, thus maxing out api.github's X-RateLimit. Thus possibly limiting the classroom app from working correctly. Fixed. Closing.

**Comment by tarebyte** [comment]
@Omarasifshaikh any chance you can link the Chrome issue?

**Comment by Omarasifshaikh** [comment]
@tarebyte 
Turns out, It was my background daemon that was the problem. I am using Travis's Ruby api to automatically query the organization and enable travis on each repository. I have assigned a process using launchd to run that script every 10 mins. It appears to be using up the limit by GitHub. Im am testing it with a 60 minute interval to see if that will fix my issue.

So no bug in Chrome. Sorry about that.

Ive had a long day...

**Comment by johndbritton** [comment]
> I am using Travis's Ruby api to automatically query the organization and enable travis on each repository.

Would you mind opening up an issue for a feature request to do this. I think we should make it possible to set up the webhooks for you.

You could also consider setting an organization wide webhook so you don't have to do this for every repo: https://github.com/blog/1933-introducing-organization-webhooks

**Comment by Omarasifshaikh** [comment]
@johndbritton 
I have gone ahead and created a new issue. Let me know if something needs to be added in there. Organization web hooks would be a lot more convenient. But I don't think Travis supports organization web hooks just yet...
