### ISSUE TITLE
Authentication issues

### ISSUE THREAD

**Issue by Omarasifshaikh** [education/classroom#581]
I am seeing repeated errors in the site saying: "You are forbidden from performing this action on GitHub".

The students are also not being assigned to their repositories. They receive the error "You are forbidden from performing this action on github.com"

It appears that the repository is being created, the template is being cloned. But the individual student is not being assigned as a contributor.

**Comment by Omarasifshaikh** [comment]
This is what a student is seeing:
<img width="582" alt="screen shot 2016-04-24 at 7 40 29 pm" src="https://cloud.githubusercontent.com/assets/6437181/14772548/8411dabc-0a54-11e6-8d29-fa8feb81d89b.png">

**Comment by dinever** [comment]
Hi @Omarasifshaikh,

> I am seeing repeated errors in the site saying: "You are forbidden from performing this action on GitHub".

This is a known problem in GitHub Classroom and we are working on a solution.

This problem occurs when teachers try to accept assignments using their own GitHub account. When accepting an invitation, we reduce the permission scope we have for them and they will not be able to create assignments anymore using the reduced permission scope.

To resolve this issue, please log out from GitHub Classroom and log back in.

> It appears that the repository is being created, the template is being cloned. But the individual student is not being assigned as a contributor.

To temporarily fix this, you can manually add the student to the assignment repo as a contributor. 

---

Sorry for causing this trouble for you. We are currently working on this problem. However, to prevent it from happening again, please notice not to try out accepting the assignment invitation using teachers' GitHub account. 

Related: #445

**Comment by Omarasifshaikh** [comment]
@dinever 
Thanks for the quick response. I have 55 students int the class, and they don't all accept the assignment at the same time. Thus would not be very practical to manually add them myself here.

Do you recommend me using teachers_pet for now?

https://github.com/education/teachers_pet

**Comment by cyhsutw** [comment]
Hi @Omarasifshaikh

Is there any other teachers in your organizations?

**Comment by tarebyte** [comment]
@Omarasifshaikh I looked at your teachers and all of them have the correct token scopes.

I'll investigate this today, sorry for the trouble.

**Comment by Omarasifshaikh** [comment]
@tarebyte 
Thanks for verifying that. Classroom is a great app and I have enjoyed using it this semester. Please let me know If I can contribute in any way to fix the issue.

Thanks!!

**Comment by johndbritton** [comment]
@Omarasifshaikh It looks like you have multiple admin users on your organization and that you have been using one of them for testing.

Please try the following steps and report back:
1. Have each administrator visit classroom.github.com and log out by clicking the sign out icon in the menu bar
2. Once the admin is logged out, sign in to Classroom again by clicking the sign in button on classroom.github.com
3. Try accepting an assignment invitation as a student. Do not use one of your administrator accounts to test accepting the assignment as this is a known way to cause issues.

It's important that all organization administrators do this. Once you've tried it out, please let us know if you're still having trouble.

**Comment by Omarasifshaikh** [comment]
@johndbritton 
I will try to get in touch with my TA and do some more testing later. For now I have used [teachers_pet](https://github.com/education/teachers_pet) to create repositories for all students (I had a list of GitHub usernames). Creation of all the repositories at once also made it easier to enable Travis on all of them in one go.
