### ISSUE TITLE
Documentation: tell teachers/classroom owners to create dummy-accounts

### ISSUE THREAD

**Issue by guntbert** [education/classroom#586]
There have been several issues ( #461 ,...) where teachers tried to see/test an assignment and thereby triggered that bug #445.

I suggest to include something in the guide to tell <strike>them</strike> us
- create some dummy-accounts to play the roles of students
- maybe even suggest a naming-scheme
- best use different browsers when testing assignments (closing the browser may still not be sufficiet when switching roles because of caching)

**Comment by johndbritton** [comment]
Thanks for the suggestion @guntbert. I'm hoping that we'll have a fix for that issue within the next couple of weeks. We really don't want to suggest creating multiple / dummy accounts. I'd rather just get this to work correctly.

**Comment by guntbert** [comment]
@johndbritton My approach was primarily born out of the desire to

1. see what exactly my students will see (that need diminishes with growing experience on teaching with github, of course)
2. be able to demo the first steps of creating an account, joining the organization, accpeting assignments,...

I asked for permission before :smile:   

Wouldn't it be useful if github created two such accounts? Only one is needed for demoing but for seeing what students see of each other's work, of repos (what permissions are useful,...) I need a  2nd one.
<sub> I have no idea how to create passwords for those dummy-accounts, and about probably a bunch of further problems with this approach.</sub>

**Comment by johndbritton** [comment]
> see what exactly my students will see 

Once this permission issue is resolved, you will be able to do this with your own account.

**Comment by guntbert** [comment]
:+1: 
Please don't forget to write some guide on the appropriate procedure.

BTW: I haven't said my **very big thanks** to the whole team for providing us with such a great tool.
So here comes
I :bow: and :clap: , you are doing tremendously, thank you!!
