### ISSUE TITLE
Students cannot join assignments

### ISSUE THREAD

**Issue by pilla** [education/classroom#588]
It is my second assignment for an Operating Systems class and students that were able to enter the first assignment cannot enter the second one. 

I first thought it might be that I was reusing the same set of groups of the former assignment and thus created a new assignment without reusing groups. Students still get the "forbidden" message when they try to get their shinny new repository. 

They can get as far as entering the group name and pressing the button to create the repo.

The assignment can be found at [this link](https://classroom.github.com/group-assignment-invitations/b03e973fff656e6e81e8a66f991a0fb5).

**Comment by tarebyte** [comment]
@pilla you need to sign back in to https://classroom.github.com

Your token scope needs to be `admin:org, delete_repo, repo, user:email` but it currently is `admin:org, user:email`

Did you try to accept an assignment?

**Comment by pilla** [comment]
I logged in again and was able to accept. But I am an admin, the problem is that students cannot accept it. Oddly enough, I was able to accept it using another account. I guess it may be an issue with my students' credentials. Will check.

**Comment by pilla** [comment]
The same student that reported me the problem tried again and it worked. Closing as I cannot reproduce it, but looks like some weird transient fault.

**Comment by johndbritton** [comment]
I think this is another case of https://github.com/education/classroom/issues/445
