### ISSUE TITLE
[Discussion] Dashboard for Students

### ISSUE THREAD

**Issue by cyhsutw** [education/classroom#599]
*This thread is for discussing the implementation of "dashboard for students" feature which is part of "visualizeing classroom activity" in #572, any feedback and suggestions are welcome!*

### Description

We're planning to add few more features for students so they can get some information they might need when they visit the Classroom site.

### Dashboard for Students

A dashboard will be built for students to:

- view the list of the assignments
	- assignment name
	- due date
	- ...etc
- view group members for group assignments
- view the status of the assignments (submitted or not, CI status, etc)
- (more to come)

These are the information I can think of, I would love the hear feedback and suggestions from both teachers and students!

**Comment by johndbritton** [comment]
> We're planning to add few more features for students

@cyhsutw One of the guiding philosophies of GitHub Classroom is that it should be as transparent as possible to the student. We don't want to build yet another learning management system that students have to learn. Instead, we want students to get hands on experience with a real tool from industry (GitHub).

I like the spirit of exposing more information to students, but I don't think we should do it through adding screens to Classroom. A better solution would be to use GitHub features via the API to provide the context students need in their repositories.

**Comment by cyhsutw** [comment]
@johndbritton Thanks for the feedback! 

> One of the guiding philosophies of GitHub Classroom is that it should be as transparent as possible to the student.

Sorry I didn't perceive this, maybe I should think about the solutions in #600 again.

Close this for for now.

**Comment by johndbritton** [comment]
> Sorry I didn't perceive this

No worries at all, that's why we're having these discussions. 😄
