### ISSUE TITLE
[Discussion] Explicit Submission & Due Date

### ISSUE THREAD

**Issue by cyhsutw** [education/classroom#600]
*This thread is for discussing the implementation of "explicit submission" feature mentioned in #572, any feedback and suggestions are welcome!*

### Description

Currently, students can only submit their assignments **implicitly by pushing commits** to the repositories. 

We're planning to provide an **explicit submission** feature so students can have information about whether their work has been submitted or not.

Also, we could build "due date" feature if we have an explicit submission procedure.

### Potential implementations

Suppose we have dashboards for students as mentioned in #599.

There're two potential implementations in my mind:
*(assuming we have organziation WebHook set)*

#### 1. Submit using GitHub Flow
	
Condition: `master` branch is protected and requires Classroom to report status before merging other branches in.
	
Student submission procedure:

1. open a pull request
2. wait for Classroom to report status
3. once the status is reported, merge the pull request into `master`
	(submitted at the time the pull request is merged)

After submitting, students can check the status using the dashboard on Classroom.

Pros:

- enforce code reviewing
- (group assignment) team members will be notified when other members proposed changes (PR notifications)

Cons:

- extra overhead for students to learn about GitHub Flow

#### 2. Submit using Classroom

Another approach is we add a "Submit" button in the dashboard so students can submit the code on the `master` branch by clicking the button.

Student submission procedure:

1. add commits to the `master` branch
2. go to dashboard on Classroom and click the submit button

(submitted at the time the button is clicked)

After submitting, students can see the status immediately on the dashboard.

Pros:

- simple workflow
- separate code management and assignment related processes

Cons:

- (group assignments) team members might not be aware of changes made directly on the `master` branch.

--

These are just potential implementations, would love to hear feedback and suggestions from both teachers and students!

**Comment by johndbritton** [comment]
In building explicit submissions, there should be one default "best" way to use the feature but we should also allow flexibility for teachers to choose to use it in the way that best suits their workflow.

> Submit using Classroom

My preference is for the submission process to happen in the GitHub interface rather than in Classroom as the idea behind Classroom is to give students hands on experience with the tool that software developers use day to day.

What about using tags / the releases feature of GitHub as a way of marking a specific commit as the student submission?

> Submit using GitHub Flow

I think we should strongly encourage the use of GitHub flow, but we probably shouldn't force it on teachers. I've heard some feedback from lower level computer science teachers that branches are difficult for their students to understand and they want a way to gently introduce Git concepts over time.

**Comment by cyhsutw** [comment]
> the idea behind Classroom is to give students hands on experience with the tool that software developers use day to day

Thank you for helping me clarify the positioning for Classroom, I will keep this in mind when designing the features.

> What about using tags / the releases feature of GitHub as a way of marking a specific commit as the student submission?

I've never used the "release" feature on GitHub before, just gave it a try and I think this is quite suitable for assignment submission as it's more visible compared to tags and source archives would be really helpful if they'd like to check the submission is successful or not.

> In building explicit submissions, there should be one default "best" way to use the feature but we should also allow flexibility for teachers to choose to use it in the way that best suits their workflow.

Let me think about how to make the submission as easy as possible for the students who are new to Git and GitHub without breaking any user experience for those who are familiar with these technologies.

**Comment by cyhsutw** [comment]
Close in favor of #667.
