### ISSUE TITLE
Workflow - What if I delete this team?

### ISSUE THREAD

**Issue by drbeco** [education/classroom#601]
Hello guys,

It is my first time using git classrom, and I'm not certain how the workflow goes.

My steps until now was:

Before EVERYTHING:

1. I've created a "startup repository" to give as assignment start point code (exwumpus)
2. I've created 6 teams and invited the students in each, accordingly to my own division of the class.

Now, with all set, I went to create a new ASSIGNMENT:
1. Set assignment title (pretty straight)
2. Private (easy)
3. Start code (done)
4. Maximum members per team: 7 (*)
5. Existing group of teams by date. (**)

Then I WAITED... :)
After a day or two, the first member created the assignment. For my surprise, I didn't know, but classroom created another team with only one member.

Lets talk with pictures.

Teams created by me are the ones in the image bellow that I can "leave". And the only one I can "Join" was created by classroom:

![image](https://cloud.githubusercontent.com/assets/5805111/15554475/d4c905f8-229a-11e6-9068-d45e57123f21.png)

Well, I don't want it. Can I delete it?

If I go to classrooms, I can see the new repo there:

![image](https://cloud.githubusercontent.com/assets/5805111/15554562/3a4c240a-229b-11e6-8371-8b5bcbf058fd.png)

So I went into the repo configuration and added the correct team:

![image](https://cloud.githubusercontent.com/assets/5805111/15554699/d3787da4-229b-11e6-9b0d-875281d56575.png)

I also went to **MY** the team configuration to check:

![image](https://cloud.githubusercontent.com/assets/5805111/15554868/7052feba-229c-11e6-9797-295282976259.png)

And the **CLASSROOM** team doesn't have any members:

![image](https://cloud.githubusercontent.com/assets/5805111/15554999/ff7cb784-229c-11e6-8445-2f08d95991b1.png)

----

Bottom line: it is duplicating the teams I already set and put members in.

Can I delete the **classroom** team, or this will break/bug my assignment?

Also, what am I doing wrong with the workflow? Why I have this effort of creating the teams and setting them not recognized by the application?

Thank you!

(*) 4. Maximum members per team: 7

I told them to create groups of 5, but let a range of +-2 to be sure there is room for everyone. So I would like to suggest to ask not only the maximum, but also the "minimum", or a range. 

(**) 5. Existing group of teams by date.

Here, just by date may be trick. Maybe if we could list in a comma-separated list all the teams it would be more precise. Maybe this is the problem I'm having here.

Thanks all for any input clarifying the workflow (and suggesting new ways of doing it, also welcomed!)

**Comment by dinever** [comment]
Hi @drbeco,

Looks like the user ![screen shot 2016-05-25 at 4 49 18 pm](https://cloud.githubusercontent.com/assets/1311594/15555858/b18299c6-2298-11e6-9436-7d9c3aea9a2f.png) accepted the group assignment invitation, and chose to create a new team named `02-ClumsyWumpus`. That's why GitHub Classroom created a team named `02-ClumsyWumpus` in your orgnization.

As you can tell from the repo name, `wumpus-02-clumsywumpus` is created by GitHub Classroom automatically for the team `02-ClumsyWumpus` to finish their assignment `wumpus`. Please don't add other teams to `wumpus-02-clumsywumpus` as other teams should work on their own repositories created by the classroom.

I saw that the team `02-ClumsyWumpus` has no members, this may be because the user ![screen shot 2016-05-25 at 4 49 18 pm](https://cloud.githubusercontent.com/assets/1311594/15555858/b18299c6-2298-11e6-9436-7d9c3aea9a2f.png) left the team manually from the GitHub organization team page after accepting the assignment.

> Well, I don't want it. Can I delete it?

I'd suggest you not to delete it. If the team is deleted from GitHub, ![screen shot 2016-05-25 at 4 49 18 pm](https://cloud.githubusercontent.com/assets/1311594/15555858/b18299c6-2298-11e6-9436-7d9c3aea9a2f.png) will not be able to accept the group assignment again due to some limitations we currently have on GitHub Classroom.

> Also, what am I doing wrong with the workflow? Why I have this effort of creating the teams and setting them not recognized by the application?

Could you please provide us with more details about how you created those teams? Did you send out the invitations and let the students accept it? Or did you created those teams manually?

**Comment by drbeco** [comment]
Hello @dinever,

thanks for looking into this .

As I've stated, I created the groups even before I went to classroom. 

I created them in the organization, manually, like any organization group. 

Then I invited the members myself, also manually. 

So, what should I do? Add the members from 
wumpus clumsy to 
02-wumpus-clumsy 
manually (again)? 

Also, what about the other groups that still need to create the assignments? 

Will they create new groups? Can I force them to use the group I've already created? 

Thank you

**Comment by dinever** [comment]
Hi @drbeco,

By using Classroom there is no need for the teacher to create groups manually. The correct workflow for group assignments in GitHub Classroom should be like this:

1. The teacher creates a group assignment.
2. The teacher sends out the group assignment invitations to students, for example, by email.
3. Students open the invitation link, sign in with their GitHub accounts.
4. Students chose whether to join an existing team or create a new empty team.
    1. If the student choose to create a new team, Classroom creates a new team in the GitHub organization, add the student into the team, and create a new repository in the organization named by the assignment title plus the team name.
    2. If the student choose to join an existing team, Classroom adds the student into the team. Then the student will have the access to the related repository.

> So, what should I do? Add the members from 
wumpus clumsy to 
02-wumpus-clumsy 
manually (again)?

If your classroom hasn't started, i.e. students haven't started their work. Then I'd suggest you to send out the assignment invitation to them and let them create teams. By this way Classroom will help you set up the repositories, there is no need to modify the GitHub teams manually.

If your classroom has already started, i.e. students have already started working on their repos, you can just go ahead without using Classroom.

> Will they create new groups? Can I force them to use the group I've already created?

If you go with GitHub Classroom, students will be able to create new teams. We currently don't have the feature for teachers to pre-defined teams, but it's on our roadmap #415.

**Comment by johndbritton** [comment]
> I've created 6 teams and invited the students in each, accordingly to my own division of the class.

> As I've stated, I created the groups even before I went to classroom.

@dinever's explanation is correct. The idea behind Classroom is that you don't have to do any administrative work to set up the teams in advance. Classroom does that for you. You just create an assignment and invite your students. When they accept the invitation they can create a team or join an existing team. The naming of teams is up to the students.

This summer we're working on adding some features that will allow you to predefine teams before inviting students to join.

My recommendation would be for you to delete the teams that you created before using Classroom and use the teams that are created by Classroom.

I'm going to close this to keep the issue list tidy as I don't think there's anything actionable from a feature / bug perspective, but please feel free to reply with comments / questions.

**Comment by drbeco** [comment]
Hi @johndbritton , although I'm very short on time right now, I still want to clarify some aspects. Can I reopen it in a couple of days? Thanks!

**Comment by johndbritton** [comment]
> although I'm very short on time right now, I still want to clarify some aspects.

Drop your questions / feedback in here when you have time, no worries.
