### ISSUE TITLE
Dashboard Layout

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#61]
This is the first page of the application, currently the user only has the ability to click on their already added Organizations, or add one to Classroom.

It currently looks like this when there aren't any organizations added.
![screen shot 2015-07-06 at 15 15 16](https://cloud.githubusercontent.com/assets/564113/8530894/d53fa080-23f1-11e5-81ec-f1ce667b0f29.png)

This is what it looks like with one or more organizations.
![screen shot 2015-07-06 at 15 16 52](https://cloud.githubusercontent.com/assets/564113/8530948/0f138704-23f2-11e5-9732-17467369eca6.png)

**Comment by jasonlong** [comment]
Closing based on work in #101.
