### ISSUE TITLE
csrf_detected -- bug? Got this message.

### ISSUE THREAD

**Issue by drbeco** [education/classroom#612]
Hello guys,

Just to help you developing, I'm reporting that today after trying to access the link:

https://classroom.github.com/classrooms

I got this error message:

![image](https://cloud.githubusercontent.com/assets/5805111/15631268/77cbb906-2536-11e6-98a3-416f22ca61f7.png)

After a few attempt, it finally went through.

Cheers

**Comment by tarebyte** [comment]
@drbeco I changed had to revoke all of the user cookie tokens a few hours ago to force everyone to log back in. That may be this issue.

Thanks for reporting!
