### ISSUE TITLE
Creating teams - interface

### ISSUE THREAD

**Issue by drbeco** [education/classroom#615]
I don't quite understand what should I write here:

![image](https://cloud.githubusercontent.com/assets/5805111/15687387/c9d3f0e0-274a-11e6-94b6-497bbd28cb9c.png)

I've already tried to create teams beforehand, and that proved a waste of time.

Now I'm starting a new assignment. What should I do?

Thank you;

**Comment by tarebyte** [comment]
@drbeco so the end goal here is that you are creating a name for your group of teams.

For example `Teams for Project 1`.

What would make this more clear?

**Comment by drbeco** [comment]
Hello @tarebyte ,

Thank you for explaining. Now that I did it the first time, it is a bit more clear.

But I'm taking naively your last question as a true question, not just rhetoric; and as such I'm taking the liberty to answer to the best of my knowledge, ok?

I believe it would be much more clear at once if the form had standardized both questions using the same vocabulary (set/group, choose/reuse, select/create). Let me explain in a low level why I think that is better.

I am very experienced in teaching programming to foreign (non-english native) students, and one thing the non-native brain thinks is that all english words can be used as a _noun_ to label a characteristic. That means you can read things like "eu criei um conjunto 'set' e outro 'group'" and that makes sense. It will translate roughly as "I've created a set 'set' and other 'group'", but this translation doesn't grasp what it really means. A more explicit translation would be "I've created a set nominated _set_ and another set nominated _group_", and because it is in another language you don't mix the meanings. This is one hand; on the other hand, reading technical texts may be confusing if the author, a native english speaker, start to use synonymous for style. If you change one word to another, in a romance, it sounds better, avoid repetition; but in a technical text, when you do, you are just implying that what you are saying is not related, but another characteristic. So, after explaining a bit of the reasoning, let me give some solutions that will fit this brain-theory of mine and see if we can get things a bit more clear.

For example:

Option 1:

![github3-groups](https://cloud.githubusercontent.com/assets/5805111/15694644/ed14cc5c-2775-11e6-8c73-4d0a212a1168.png)


Option 2:

![image](https://cloud.githubusercontent.com/assets/5805111/15693505/05e1710e-276c-11e6-9ca0-ad0bd0171b2a.png)


Not only the words repeat itself, but also the gray area gives an example. 

The current example is based on dates. My first group/set was created just by chance with a strange name that mislead me to think that I need to know a range of dates to setup the team.

`Teams formed on may 24th, 2016:`

![github2-dates](https://cloud.githubusercontent.com/assets/5805111/15694643/ed0da6de-2775-11e6-9bd5-4777db27ddf4.png)

Not a good option. Maybe if it suggests a more understanding name based on the repository name.


Even better, if a single field with the drop-menu offers create and reuse:

![github1-menu](https://cloud.githubusercontent.com/assets/5805111/15694638/e3a74a82-2775-11e6-8c6b-af2f57a8e665.png)

Also, *groups of teams* is a new concept that I didn't see before in github. I believe it only apply inside classroom. That means a bit of introduction is necessary. Maybe a mouse-hover text (tip)?

Thanks for allowing the feedback.

**Comment by drbeco** [comment]
( BTW, this form was the first barrier to confuses me regarding #601 )

**Comment by tarebyte** [comment]
Thank you for the feedback, I'm going to list it add it on our list of things to improve.

Thanks @drbeco!

**Comment by tarebyte** [comment]
Closed by #617
