### ISSUE TITLE
Advanced settings UI for Assignments and Group Assignments

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#616]
https://github.com/education/classroom/pull/614 and https://github.com/education/classroom/pull/608 both add awesome new settings for teachers to further customize their assignments.

However this seems like a lot of checkboxes, and I would love if there was a way to better handle this in the UI.

@jasonlong is there a normal pattern we use here for stuff like this?
- [x] Organization settings
- [ ] Assignment settings
- [ ] Group assignment settings

**Comment by dinever** [comment]
👍 I was thinking about using a sidebar menu like the GitHub repo settings page:

<img width="1007" alt="screen shot 2016-06-03 at 2 42 14 pm" src="https://cloud.githubusercontent.com/assets/1311594/15789314/746f9db0-2999-11e6-9b28-e7ab09f47480.png">

**Comment by jasonlong** [comment]
The sidenav idea seems :ok_hand: to me.
