### ISSUE TITLE
unable to create classroom

### ISSUE THREAD

**Issue by canance** [education/classroom#625]
Hi,

I'm trying to create a github classroom.  I've created an organization 'Cory-Nance-Classrooms' and my main account 'canance' is an admin.  When I go to create a classroom though it does not see my organization and claims I need to create one.  I've checked that github classrooms has been granted access to the following:

 Full control of orgs and teams
 Delete repositories
 Full control of private repositories
 Access user email addresses (read-only)

Best regards,

Cory

**Comment by tarebyte** [comment]
@canance can you try this link https://github.com/settings/connections/applications/64a051cf1598b9f0658f and see if you have granted Classroom permission to your organization?

Thanks!

**Comment by canance** [comment]
Hey Mark,

Thanks for the reply.  Yes, it shows 'revoke access' and that Github classroom currently has the following permissions:


 Full control of orgs and teams
 Delete repositories
 Full control of private repositories
 Access user email addresses (read-only)

Best regards,

Cory Nance, MS
Lecturer
Department of Computing Sciences
Coastal Carolina University
P.O. Box 261954
Conway, SC  29528-6054
843-349-2646
canance@coastal.edu
www.coastal.edu

________________________________________

**Comment by cyhsutw** [comment]
Hi @canance,

Did you see your organization **Cory-Nance-Classrooms** in the Organization Access section?

<hr>

Mine looks like this:

![access](https://cloud.githubusercontent.com/assets/1046917/15862938/ddc54e32-2d03-11e6-996d-1a1425e20ac2.png)

In this picture, permissions for administrate *JAC-Security* and *HopApp* have not been granted for Classroom. 

<hr>

Please click the <kbd>Grant Access</kbd> button on the right of the organization **Cory-Nance-Classrooms** if there's one.

**Comment by canance** [comment]
I do.  Please see the attached screenshot.

Best regards,

Cory Nance, MS
Lecturer
Department of Computing Sciences
Coastal Carolina University
P.O. Box 261954
Conway, SC  29528-6054
843-349-2646
canance@coastal.edu
www.coastal.edu

________________________________________

**Comment by tarebyte** [comment]
@canance I'll look into this later today, may be a caching thing.

**Comment by canance** [comment]
Ok sounds good.  Thanks!

Cory Nance, MS
Lecturer
Department of Computing Sciences
Coastal Carolina University
P.O. Box 261954
Conway, SC  29528-6054
843-349-2646
canance@coastal.edu
www.coastal.edu

________________________________________
