### ISSUE TITLE
Unjoin a team

### ISSUE THREAD

**Issue by drbeco** [education/classroom#628]
A student of mine mistakenly created a new group using a computer logged with a friend's username.

Now how can we undo this mess?

I'm happy to give any information needed.

Thank you.

**Comment by drbeco** [comment]
I think this refers to issue #292 , right?

**Comment by tarebyte** [comment]
> I think this refers to issue #292 , right?

Yup

@drbeco if you email me the information, I can undo it for you in the mean time.

**Comment by drbeco** [comment]
Thank you, @tarebyte ! I've sent an email.

**Comment by drbeco** [comment]
Hello @tarebyte ,

Did you got my email? I'm afraid it went to SPAM or something.

The students are very sad because they are in a deadline and they are losing time.

Thank you and really sorry to bother!

**Comment by drbeco** [comment]
Hello there guys, @tarebyte ,

I've sent you a new email reporting this bug. In the email I told some students probably are having the issue. It turns out that everyone really is, including me.

The error message is:

![image](https://cloud.githubusercontent.com/assets/5805111/15970767/abe80d2c-2f0c-11e6-949d-2f1e4fb0aebb.png)

I don't think this is for classroom in general because we had a manual intervention in the database, but still, just for registering the info.

Thank you for looking into that!

**Comment by tarebyte** [comment]
Yup it was for the manual intervention, taking a look now

**Comment by tarebyte** [comment]
@drbeco I deleted the Group but for got to delete the assignment that with it.

It works now

**Comment by tarebyte** [comment]
Sorry again for the trouble
