### ISSUE TITLE
Cache issues? Two users login in with the same computer

### ISSUE THREAD

**Issue by drbeco** [education/classroom#629]
Reporting a possible bug:

During a class a noticed this problem.

* Student A logs in, click the classroom assignment link and join certain team, using a shared computer with a friend.
* Student A logs out
* Student B logs in in the same computer
* Student B clicks on the classroom assignment link and gets a message:

`already joined the team`

**Comment by tarebyte** [comment]
It could possibly be, I'll look into it.

Thanks @drbeco!

**Comment by dinever** [comment]
Hi @drbeco,

Could it be that student A logs out only GitHub Classroom and forgot to log out GitHub, then student B visited the invitation page and was actually signed in with the account of student A?

**Comment by drbeco** [comment]
Hi @dinever , I can check if that is the case.

Talk to you soon.

--
To be edited.
