### ISSUE TITLE
Unable to add new classroom to org

### ISSUE THREAD

**Issue by ryanburns31892** [education/classroom#632]
![screen shot 2016-06-11 at 20 27 38](https://cloud.githubusercontent.com/assets/13726773/15988835/e76055aa-3013-11e6-8d64-0271686b3d5d.png)

Getting this message when trying to add a new classroom to this organization. This doesn't make sense,right?

**Comment by diraulo** [comment]
@ryanburns31892 I was trying to do the same thing, but it seems this feature is not supported. See https://github.com/education/classroom/issues/595

**Comment by tarebyte** [comment]
@diraulo is correct, as of right now there is a 1:1 relationship between a Classroom and an Organization.

Sorry for the inconvenience, if you need another org for a class please feel free to create another one and request what you need at education.github.com.
