### ISSUE TITLE
Something when wrong when accepting an invitation

### ISSUE THREAD

**Issue by whatwho** [education/classroom#637]
Hey guys,

today morning we get an error 500 when trying to open a specific assignment's page, or accept an invitation to it. Could you please take a look on the following assignment?

https://classroom.github.com/classrooms/19305404-codecool_bp_2016_1

Thanks,
Miki

**Comment by ohcibi** [comment]
Hi. We have the same issue with our assignments. Its not even possible to create new assignemnts

**Comment by tarebyte** [comment]
@whatwho @ohcibi my apologies it looks like my last PR broke this, even though I thought I tested it out 😢 .

Can you try it again and see if it works now?

**Comment by whatwho** [comment]
hey @tarebyte, it seems to be working now! thanks for your help!

**Comment by tarebyte** [comment]
Not a problem sorry again for the trouble!
