### ISSUE TITLE
Not recognising I have setup organisation

### ISSUE THREAD

**Issue by ptrobson** [education/classroom#646]
Hi,

I am a secondary school teacher. I have setup on github the organisation 
Cramlingtonlearningvillage. All done. Went onto classroom to have a play and it won't let me setup a classroom as keeps saying no organisation. We want to use this in school so having a play about to see if can have an organisation then a class. Then a set of tasks for them to do so it will self mark and tell us if they are getting it easily.

**Comment by tarebyte** [comment]
@ptrobson can you try this link here https://github.com/settings/connections/applications/64a051cf1598b9f0658f to make sure you have your organization authorized to use GitHub Classroom.

Thanks!

**Comment by tarebyte** [comment]
📟 @ptrobson did this work for you?

**Comment by ptrobson** [comment]
Yes sorted.
