### ISSUE TITLE
Wrong team members after changing a username

### ISSUE THREAD

**Issue by n2o** [education/classroom#657]
Hello,
we configured GitHub Classroom to create teams with maximum of 5 members. Then 4 students joined a team and one of them changed his name from, for example, "foobar100" to "foobar". Now, switching the username is correctly handled inside the created repository itself (e.g. https://github.com/orgs/my-organization/teams/lieblingsprojekt), but not inside GitHub Classroom. Here are the original 4 members plus the old username "foobar100". Classroom then says, that the team is full, because the old username is still listed.

This is an image from Classroom showing the team's repository on the assignment page with the 4+1 members:
![bildschirmfoto von 2016-06-21 10-31-40](https://cloud.githubusercontent.com/assets/1507474/16223003/78614da0-379b-11e6-84c9-6631e5807f70.png)

And this is the "classical" detail page directly in GitHub showing the real 4 members:
![bildschirmfoto von 2016-06-21 10-13-25](https://cloud.githubusercontent.com/assets/1507474/16223004/7e796236-379b-11e6-9e73-c6e698b50116.png)

This is not a big problem, because I can manually add the missing student, but this error should be fixed. It is one of the "unintended side effects" you are warning for when changing a username ;-)

Thanks for your help! I really like GitHub classroom.

**Comment by tarebyte** [comment]
@n2o did the student just change their login, or did they create a new account?

We don't perform any action against their GitHub login specifically for reasons like the one you mentioned above.

**Comment by n2o** [comment]
He told me that he changed his username, but as I can find both of these usernames on GitHub, he might have not tell the truth...

**Comment by tarebyte** [comment]
@n2o looking at the pictures above, and looking at our production data, it looks like:

- The student removed themselves from the GitHub team on github.com
- Then added their new account to the group

Since GitHub currently doesn't have a way for us to see when a team member has left the team, we're kind of put in a pickle.

If you email me personally, I can fix the bad data in production for you.

**Comment by n2o** [comment]
I thought this might be a general problem and expected Classroom to create a free space in the team, since one team member left, but is still listed. Thanks for your help, I'll email you more details.

**Comment by tarebyte** [comment]
@n2o since we don't have a way for GitHub to notify us when a team change was made on GitHub, we are working on #652 so that teachers can manually remove students from groups.
