### ISSUE TITLE
what when the student finish?

### ISSUE THREAD

**Issue by drbeco** [education/classroom#661]
Hello guys,

I just watched my students presentation, and after that I deleted the repositories and teams.

![image](https://cloud.githubusercontent.com/assets/5805111/16510400/06689e1e-3f1c-11e6-822a-04740c688909.png)

But I wonder, (again the workflow is not clear to me), do they have any option to finish the assignment?

Also, I deleted all but one. They didn't get the necessary score (just 3 of them in the team), so I deleted the other students by hand, and let these 3 use the repository to be evaluated a second time (university rules for the last test).

They have another week. The others either finished successfully or didn't score to earn a second chance; so any way, they are out of the team.

Thank you!

**Comment by tarebyte** [comment]
> I just watched my students presentation, and after that I deleted the repositories and teams.
>
> But I wonder, (again the workflow is not clear to me), do they have any option to finish the assignment?

I'm not entirely sure I understand your question here. If you both deleted the teams and the repositories what is it you expect the students to do here?

I think what you're looking for is granular team and assignment management. Am I wrong in this assumption? Right now all you can do through Classroom is delete the Assignment, and it will delete the repos for everyone.

**Comment by drbeco** [comment]
Hi @tarebyte , thanks for your answer.

In this specific case I'm not expecting any more actions (future).

I was hypothesizing what if I didn't delete the repos (past).

When the assignment is over, is there something the student would do to point that out to the teacher?

Thank you!

**Comment by tarebyte** [comment]
@drbeco @cyhsutw is working on something that would do just that. See https://github.com/education/classroom/pull/626

**Comment by drbeco** [comment]
I'll, tx for pointing out the link. Closing here. Bye
