### ISSUE TITLE
Github Pages assignments

### ISSUE THREAD

**Issue by jayvdb** [education/classroom#665]
One assignment type I would like to use is a "Set up a real github pages website" , and "Add github pages post", which obviously needs to be named "<username>.github.io" , and needs to be public.

This would be used to require regular devlogging of the students work.

While this doesnt need to be done within Classroom, it would help keep the tracking of student assignments in one place.

**Comment by cyhsutw** [comment]
Hi John,

I'm not sure if this fulfills your teaching goal, but GitHub has pages for individual repositories.
Students can put contents under the `gh-pages` branch and they can access the website at `org_name.github.io/repo_name`.

For example, [Octokit.rb](https://github.com/octokit/octokit.rb) has its code for website under [`gh-pages` branch](https://github.com/octokit/octokit.rb/tree/gh-pages) and you can access the site via http://octokit.github.io/octokit.rb/

Reference: https://help.github.com/articles/user-organization-and-project-pages/

**Comment by jayvdb** [comment]
Yea, a repo Github Pages would work for the first 'setup' assignment, but can they resubmit the same repo for additional assignments requiring additional posts?

It would still be preferred for it to be their main username based Github Pages, as the intention is to help these high school students to develop their online OSS profile with guidance on doing it safely.

**Comment by Em-AK** [comment]
> a repo Github Pages would work for the first 'setup' assignment, but can they resubmit the same repo for additional assignments requiring additional posts?

Assignment titles must be unique and the name of the student repo for an assignment is directly derived from the assignment title. So I guess currently a student can not use the same repo for two different assignments.

I think the submission process described in #667 is going in this direction with the use of a *Release* for the student to explicit what version should be reviewed. But I see no obvious solution on how to allow *recurring assignments* on the same repo.

**Comment by robmuh** [comment]
We have 'Create Your First Site' as one of our [*Prep*](http://prep.skilstak.io) assignments and have found through trial and error that it is best not to clutter up a student's personal GitHub repo of any kind with educational repos. With GitHub Classrooms now there is absolutely no need. IMHO, nothing in a student's repo should be there that they do not want to show potential employers and peers. I talk about this a little in [this article](https://medium.com/@robmuh/github-as-text-book-and-work-book-828ffada9542#.xeu5p9u16).
