### ISSUE TITLE
Integration of Classroom Wiki + MathJax

### ISSUE THREAD

**Issue by ataiya** [education/classroom#675]
Hello everybody, I am wondering whether this is something that "traditional" github cannot do because it has to deal with others constraints, but that could easily be a modded module of github classroom.

Take a look at [this page](https://github.com/ataiya/dgp/wiki/hw1_reconstr), all these equations should be typeset. I am a professor teaching math & computer science, not being able to eleganty write math on the wiki pages is **really** painful.

I am wondering what your thoughts are

**Comment by jayvdb** [comment]
Ya, a workaround for this world be very helpful. https://github.com/github/markup/issues/897

I am using https://github.com/imsky/PocketEuler (actually an Indonesian translation of it) but we need to build a custom version of it because of this problem.

**Comment by ataiya** [comment]
How are you using PocketEuler exactly? 

My "hot-fix" is to pipe raw markdown from github wiki into PHP where I re-assemble a CSS page myself. Basically my web server acts as a latex translator by adding MathJax.

This is an example of markdown rendering within a generic page:
http://gfx.uvic.ca/teaching/index.md

**Comment by jayvdb** [comment]
Converting it to HTML and serving it via github.io
http://wikimedia-id.github.io/projecteuler/

**Comment by ataiya** [comment]
Right, so basically what I am also doing, but you live within the github webpage system

**Comment by cyhsutw** [comment]
Another hack is utilizing the [Jupyter Notebook](http://jupyter.org/). 

GitHub has [built-in support for rendering `.ipynb` files](https://github.com/blog/1995-github-jupyter-notebooks-3). You can write inline and display LaTeX code in the notebook and GitHub will render it for you. 

Here's a sample notebook file: https://gist.github.com/cyhsutw/d5983d166fb70ff651f027b2aa56ee4e

**Comment by ataiya** [comment]
Again, this should not be a hack, it should be something easily and natively supported by the markdown renderer!

**Comment by tarebyte** [comment]
Since this isn't really relevant to the GitHub Classroom project _per se_ I'm going to close this issue.

Please feel free to continue this discussion here or on the education.github.community discourse site.

Thanks!

**Comment by ataiya** [comment]
I don't see why this is not relevant to classrooms. 
Can't classrooms have wiki which override GitHub default's behavior and add MathJax support?

I am failing to identify the correct split interface between github and github/classroom.

**Comment by ataiya** [comment]
@cyhsutw the jupyter notebook you posted is pretty cool:
https://gist.github.com/cyhsutw/d5983d166fb70ff651f027b2aa56ee4e

However, with that you simply lose the embedded GitHub markdown editor :'(

**Comment by jayvdb** [comment]
It would be nice if we could embed `.ipynb` files in `.markdown` files.
