### ISSUE TITLE
Delete assignment button unresponsive

### ISSUE THREAD

**Issue by battis** [education/classroom#696]
I was experimenting with GitHub Classroom and wanted to delete a test assignment. When I tried, the **Delete this assignment** button was unresponsive (expected, based on a scan of the source, a modal dialog confirming the deletion).

[![Screencast](https://img.youtube.com/vi/N_oZwD_1Vwk/0.jpg)](https://www.youtube.com/watch?v=N_oZwD_1Vwk)

Referring to the Chrome Javascript console, I notice that, matching my 3 clicks in the screencast above, there were three identical errors:

```
Uncaught TypeError: Cannot read property 'open' of undefined
```
[application-a0ef6d291eaafa8a1f8ce657c6c6de2153cd6b49e519fc2aa86cdfb6a1427fe5.js:5](https://classroom.github.com/assets/application-a0ef6d291eaafa8a1f8ce657c6c6de2153cd6b49e519fc2aa86cdfb6a1427fe5.js)

**Comment by tarebyte** [comment]
Thanks for reporting @battis!

We'll take a look at this and get back to you.

**Comment by tarebyte** [comment]
@battis I think I've fixed this in #701. Mind trying this out again?

**Comment by battis** [comment]
@tarebyte Totally works now! Thank you!

**Comment by roboticsTUe** [comment]
I have a similar problem: I cannot
1. Reset and remove this classroom
2. Delete this group assignment

The button is unresponsive.

**Comment by timalcon** [comment]
I can't delete an assignment, possibly because I deleted its associated repository first.  When I try, I get "500 internal server error".
