### ISSUE TITLE
:session not kill on /auth/failure action and bypass authentication

### ISSUE THREAD

**Issue by RaminFP** [education/classroom#697]
Hi,

1- i have valid request with "state" parameter on github and callback to https://classroom.github.com 

## Response Callback Details
```
GET /auth/github/callback?browser_session_id=a03ca05330e94445450191d7e2ce777313121f01&code=ca2b276786f344365921&scope=user%3Aemail%2Crepo%2Cdelete_repo%2Cadmin%3Aorg&state=62faaffddc8afe8aba9ffff2ac97fd9a78ed9635d5310884 HTTP/1.1
Host: classroom.github.com:443
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cookie: _octo=GH1.1.88038072.1446795782; logged_in=yes; dotcom_user=RaminFP; 
_ga=GA1.3.200551282.1446795782;_classroom_session=ZmNaOTJ1MmpycXBLYmRmeEtvcXZ5aG1jTjA0T0VHbmVNUE12V1YxTXFoK0JwNmo3bGFaSndNR3J5dy9Ubnd2WWR0UFRQRTQ5aVhQcnJsdHZHRTlaVmNDTzZKVm1ZcHJOVzFXcUI0RTV3NUVHa2ZmS0VuVXNDOE5MazdMKzRxSE5rTEVFR0tjcExvYitzTjh0SEh1YnhyL0RJUTJia05GcEZZOHN6MjNTbXBDYnFUQzBNYXR3c0FxTkw2NGVBS3NTOUV1SUdxNmQ4d05iZ3F6RElaVnlaMlkvYnVBdHNuUEM3Y3B3eUppZmdHV2tGeUgrYkxkSFJTaXpOT0NlKzkzZks4WTBMV012SFRkbVNuVUNkdTYwQXRvYzFKZGRscXBGeHVkd3hnaHUwTzdDazU1N2pSb2p5NXoxNTg5OUU5YVRTY2Z2dUJNSnJCT1NPQXA4RjZWSlJYM0g4RFRHVERPU2JwY0p6WU95bTI0bGxTUThGYkVnS0ZkMVU1dThDRUozNndnaU1GY2pDSC9jdVpBMjQ5NzFtaGpvS1RCeFZLOG1qY1Axb2VhaWNVYz0tLWJmWTJ6d3oxUWUwbE8ycGlOU1NhVkE9PQ%3D%3D--
bd7c8c232d9c39e3c72f6cebdd4bc2c305a8fe1a; _gat=1; _ga=GA1.2.200551282.1446795782
Referer: https://github.com/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: 0a48f04e-0839-4e28-b169-c977a9640276

HTTP/1.1 302 Found
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 105
Content-Type: text/html; charset=utf-8
Date: Tue, 16 Aug 2016 15:27:42 GMT
Location: https://classroom.github.com/classrooms
Server: Cowboy
Set-Cookie: 
_classroom_session=d05ETGhKNnNUS29wOW40aWNDd2hXbFZKUXJrMzJnd2MvMmhTUzB6N2JvTUpTZWV4RkowcGVXMGdEbS9ZaWwrdWp2M1Nldkp3QlhETGNwMDNSWFBocTV1L3lQaGUxRWZvWUZ4NnVCbDZtK21zRDNhM3IxR1BVR09BTDA0VENVQXd6OUxLaWJYY01JSVlIRENSd2FIYnVlVFBwdmp0U0dwUUpKcEpxa3A2b3BkQ3FvYkR2T0RnNG9xb1UxdkJQSDFINS9qUE0rUHdNQmpyNE5Od1BXZnU5WlRxNThGL3c3QUNFWWdnbERVMWpIZ05ERlljd056enpZUkxwWHZZMG9vdUFia2VNVk9iZUJkZFVKNXVIcjQxSHc9PS0tVlR1bXBGbjdRS0J3OEVkS2dzZWxjQT09--df0ec0c257618761ad1ff2ec3562c28c623183ed; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
Via: 1.1 vegur
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: b5305580-af2d-42c2-989f-22986167c9a2
X-Runtime: 0.464687
X-Xss-Protection: 1; mode=block
```
you see HTTP/1.1 302 Found Status Code and redirect to  
`https://classroom.github.com/classrooms `

2- Now without  "state" parameter or empty "state"  on github 

```
GET /auth/github/callback?browser_session_id=8a52f54303737e6fe71ab694c6759fd72c167ba7&code=97c41e54a41ba9eb4f4c&scope=user%3Aemail%2Crepo%2Cdelete_repo%2Cadmin%3Aorg HTTP/1.1
Host: classroom.github.com:443
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
Cookie: _octo=GH1.1.585468633.1439878595; _classroom_session=MXdQcWpCcTBzSFAwZzhWZU9WaGpCeUFCMGxDa0J0QzdxaUF6YVp6cDhCUXZyb3RBd3FUZ1VkMnk1R29Zd0pVWi8ydmErMTlBWFlPMTEreUlvb1dSMnNjMVdkeGRSdjRGTTBBTEZrM2lvYW50ditSWFVXZUVlVVlYclY4QXZSMTZaeWdER09KMVNLdFBqeWZ3aG11ZEZ3OU5sbmtienBnalRXS3lzbDhFMVBJODJteEFjZHhMaTV4V08zclBZQkNydTRPaE1acWtKa2c2Rk1ZU3c2dkpiK1hURmtTdjkwUWtNcFovazR1bXF3R2VzMnR1K1lLeUVsa1Z0ci9NNkkxRVVxSzhsL0QzbUJOUCtzMnZGdW0vTlZoRkYvenE0VDBZTHZBOEVneFJOQVZpcUlFWjFlRzV0V0ZCdzMySlh0aGV3c21NQ2psQzU3SXVQc3EwQmo4ajBXU2k5SlB6aENjNlZCeFNGaWZwVjBES08wd2I4QkxualpWNlRWVnU2QnF1dlo4VE1zeXhDRlovY2RmMitVNUx3bDYrb0hULzJzdDN3RjROcEF2VTQwdTZPdnd5VHNoLy9EQnlXd0g3MitRbC0talVaNUIxVXlrbm1XN2h0WnNScnFwQT09--e3db8d81842b68acc2e331cd537cf6f5f0f8dd59; _gat=1; logged_in=yes; dotcom_user=RaminFP; _ga=GA1.2.1203552576.1439878593
Referer: https://github.com/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

HTTP/1.1 302 Found
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 9
Date: Tue, 16 Aug 2016 15:43:14 GMT
Location: /auth/failure?message=csrf_detected&strategy=github

Server: Cowboy
Set-Cookie: _classroom_session=dndGd3lObk1qY3BhaFZ6MVlxdmJqYUlGWkdlVWswV1h4bGIraDZVUkdsRXJHYU4zS0VnQ1M3Q3dRaG9sRHZRS2Y5RzRVSW0zZkJVY1o3ZXR5SVNDdzFBNVpPVWNFMlQ1R01FcXVSU1B2U1ZML2p5b1lhaTBxUGlqR3NBbi9oSVZESU9IL2Q1YWVnY2xYcmZocUp5VmVWamh0OFl2S21XdFFWejYxZHF4RzU2SU5UczFIMlNGUGtyekZHMXd4MVk4SGtJMXNpVW5XeTlvbTQrTjYxdWUydmFKd0d1cXlTRFZkUlZUUWJXd1U5dUxsRFBUQ1lQSWk0bHU2TlE4MVlkMytLMjhSekUyN3FmZUxyZ0ZHMnlJekFaRklhYVBCamtnaXdnbWdNSVVNcDNGbTZTRVVjUkpPZVplSWF1WWVPM0ROZTBTaERCakV1SDI5eEZ0R2lKcTVnPT0tLUVZc0twMzYyYjM0dlYwRnFoT3lEOHc9PQ%3D%3D--e979f9356b81f5c241eea9620a90415ce86eef08; path=/; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
Via: 1.1 vegur
X-Request-Id: 086760f8-8832-47f6-9bcb-ddee466a79eb
X-Runtime: 0.005038
```
but now you see HTTP/1.1 302 Found Status Code and redirect to  
`/auth/failure?message=csrf_detected&strategy=github ` you see here call `failure` action method 

```
HTTP/1.1 302 Found
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 9
Date: Tue, 16 Aug 2016 15:43:14 GMT
Location: /auth/failure?message=csrf_detected&strategy=github
Server: Cowboy
Set-Cookie: 
```
any kill session user if action is `failure`  

https://github.com/education/classroom/blob/master/app/controllers/sessions_controller.rb#L35&L37

and i have access to page https://classroom.github.com/classrooms with session,

![Image](http://i.imgur.com/CWJRB4k.png)

Thanks,
Ramin

**Comment by johndbritton** [comment]
Thanks for reporting this @RaminFP.

I've taken a look, and this is expected behavior. In the case that you're showing, you already have a valid session when you remove the state. We detect the issue and show the alert, but your account is still logged in.

If you clear your cookies / log out and then try modifying the state again, you will find that you remain logged out.

We'd also request that you report any other potential security issues according to responsible disclosure best practices via a private channel such as our [Bug Bounty Program](https://bounty.github.com) or via email: education@github.com.

**Comment by RaminFP** [comment]
Hi,
@johndbritton  Thanks,

` but your account is still logged in.` first i login with valid state , but for test without state i remove github classroom https://github.com/settings/applications with revoke and tested without state parameter

but i remove state you should not create session,but you have create session with invalid state this means state not work and you should display error to users,without login , "clear session" but is not,

`
We'd also request that you report any other potential security issues according to responsible disclosure best practices via a private channel such as our Bug Bounty Program or via email: education@github.com.` 
github security answer : 
`
Other applications
GitHub builds and operates a number of web properties and applications. Not all of them are currently part of an open bounty, however, we still appreciate the effort researchers put forth to identify vulnerabilities. Vulnerabilities found in applications not specifically listed on the Open bounties are not currently eligible for cash rewards.`

**Comment by RaminFP** [comment]
Hi @johndbritton ,

route.rb:
https://github.com/education/classroom/blob/master/config/routes.rb#L10
here you set route when user logout for clear session
session_controller action "destroy" : 
https://github.com/education/classroom/blob/master/app/controllers/sessions_controller.rb#L30&L33

for action "failure" you show display error but there is session on browser if happen fail request with change state parameter,

Looks like this just sends you to an error page if the CSRF's detected, doesn't really fixed the issue. –
https://github.com/education/classroom/blob/master/app/controllers/sessions_controller.rb#L35&L37

this is a valid security issue,

Thanks,
Ramin

**Comment by mostafafp** [comment]
@RaminFP
