### ISSUE TITLE
Can't remove classroom and start over

### ISSUE THREAD

**Issue by eduvik** [education/classroom#698]
I tried creating a classroom as a test, but it defaulted to using an organisation that I don't want to have access to classroom. I tried to de-authorise this org but was unable to do so. So I de-authorised classroom entirely from my account, but now if I go to classroom.github.com I get a server error:
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by tarebyte** [comment]
@eduvik would you mind clearing your cookies for classroom and try logging in again.

Thanks!

**Comment by johndbritton** [comment]
@eduvik Once you've cleared your cookies, you should be prompted to re-authorize. If you don't want to give Classroom access to all of your orgs, make sure that you have enabled third party access restrictions for your organization.

You can read more in this thread: https://education.github.community/t/github-oauth-permissions/1047

**Comment by johndbritton** [comment]
Closing this issue as it's not actionable for us, but feel free to reopen if your problem isn't resolved.
