### ISSUE TITLE
No Organizations Under My Account

### ISSUE THREAD

**Issue by waleedahmed3045** [education/classroom#706]
Hi I am trying to create a class room but it says I don't have any Organization under my Account. But I actually do

**Comment by tarebyte** [comment]
@waleedahmed3045 apologies if you're already tried this. Would you mind going [here](https://github.com/settings/connections/applications/64a051cf1598b9f0658f) and seeing if you've granted us access to any organizations?

Thanks!

**Comment by waleedahmed3045** [comment]
Thank you!!
