### ISSUE TITLE
Include tutorial video on logged out homepage

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#713]
[![screen shot 2016-08-19 at 5 00 06 pm](https://cloud.githubusercontent.com/assets/123345/17814095/67d9090c-662e-11e6-810e-2874275dd9ef.png)](https://www.youtube.com/watch?v=ChA_zph7aao)

https://www.youtube.com/watch?v=ChA_zph7aao

**Comment by dinever** [comment]
Hey @johndbritton, I have two potential options for this one.

One option is that we place the video on the left side of the home page, like this:

![screen shot 2016-08-21 at 5 40 41 pm](https://cloud.githubusercontent.com/assets/1311594/17840187/1d265c34-67cd-11e6-8ae2-37e5a30f5e1f.png)

However, the thumbnail looks pretty weird with the same color background.

Another option is that we place a button on the page, once the user clicks the button, a youtube video modal pops up and plays the video:

![screen shot 2016-08-21 at 6 26 32 pm](https://cloud.githubusercontent.com/assets/1311594/17840196/631d7128-67cd-11e6-812a-a15da91dd412.png)

Live preview:

![youtube_video](https://cloud.githubusercontent.com/assets/1311594/17840192/4b116828-67cd-11e6-8f34-fc5e35ea4d1a.gif)

Please share your thoughts. 😄 

/cc @jasonlong @tarebyte

**Comment by jasonlong** [comment]
Definitely agree that the green thumbnail doesn't work well with the green header. I also fear that the play icon sitting by itself in the second option could easily be overlooked as a call to action. 

Taking that idea though, maybe something along these lines?

![video](https://cloud.githubusercontent.com/assets/6104/17855995/69782438-6849-11e6-9c3f-630c175be2c8.png)

**Comment by johndbritton** [comment]
I like the lightbox treatment in the second option, but not really a fan of the play icon.

What do you think about just having two buttons:

<kbd>📺 Watch video</kbd> <kbd>:octocat: Sign in </kbd>

**Comment by Youssefares** [comment]
Hey @johndbritton , anyone working on this or should I just go ahead?

**Comment by tarebyte** [comment]
@Youssefares, please feel free to work on this!
