### ISSUE TITLE
Can't create a 2nd classroom.

### ISSUE THREAD

**Issue by robustUTEP** [education/classroom#719]
I teach two courses, so I'd like to setup two  classrooms.

I created a organization and a classroom within it: 2016-fall-arch1@utep-cs-classes.

I want to create a second.  however, the web interface to "create a new classroom" won't let me select utep-cs-classes.  The error is "Another owner has already added this organization to GitHub classroom.

**Comment by tarebyte** [comment]
@robustUTEP currently you can only make one classroom per GitHub organization.

However we're currently working on changing that so you can have multiple classrooms per org (see #595 for the original request).
