### ISSUE TITLE
Integrate with Google Classroom / LTI

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#721]
Google Classroom has an [API](https://developers.google.com/classroom/) and could be a good option for us to integrate with for gradebooks and other course administrative things that are not specific to GitHub.

Specifically, they recently added the [Coursework API](https://developers.google.com/classroom/guides/manage-coursework) which could be used to integrate GitHub Classroom assignments with Google Classroom.

Would anyone be interested in this? If so, I'd love to hear why you think it's worthwhile.

**Comment by Winbobob** [comment]
Hi @johndbritton, I think it is interesting and beneficial to integrate GitHub Classroom with Google Classroom or other Learning Managements Systems (LMSes), such as Blackboard, Moodle.

In this paper ([Student experiences using GitHub in software engineering courses: a case study](http://dl.acm.org/citation.cfm?id=2889195)), one concern the author mentioned is that GitHub lacks administrative functions such as gradebooks and announcements. Basically, I agree with the author. And another concern is that as far as I known, universities usually not allow instructors to store course scores in third-party tools. So if GitHub Classroom could integrate with these LMSes managed by universities, more instructors may willing to use GitHub Classroom.

**Comment by nwoodthorpe** [comment]
This would be a cool bigger project to do. Allowing GitHub to integrate with generic LMSs, and not just Google Classroom would be interesting. I don't know enough about how these work, is exposing a rich REST API for them to hook into not enough? Creating the integration ourselves seems scary because there's no way all these LMSs share a common interface

**Comment by nwoodthorpe** [comment]
> because there's no way all these LMSs share a common interface

I was totally wrong

From #443 (which I've closed in favor of this),

> [LTI on Wikipedia](https://en.wikipedia.org/wiki/Learning_Tools_Interoperability)
>There's a standard for integrating tools like Classroom for GitHub with learning management systems, we should investigate and come to a decision about implementing the standard.

I think this is definitely something worth looking into. At the very least, figure out how much work would go into making this happen.

**Comment by miltonlab** [comment]
I am the same question @adamfdotnet . I am theaher and researcher and thinking propose a Researh Project at my university related with this but i need to know the really status please @mozzadrella .

**Comment by ramlaxman** [comment]
Kindly reopen this issue as it is helpful for all trainers and teachers across the world to use both classrooms.

**Comment by d12** [comment]
I'm unsure of the status on this. @BenEmdon @srinjoym or @mozzadrella may know more.

**Comment by srinjoym** [comment]
Hi @ramlaxman 👋

We're actively working on integration with Google Classroom in #1791. I'll update this thread when we're getting ready to release the feature to everyone.

**Comment by d12** [comment]
We're still working on this in #1791. Getting very close to merging now.

**Comment by ramlaxman** [comment]
Thanks for updating. I'm really excited to use it and share the feedback.

**Comment by d12** [comment]
Hey @ramlaxman ! We're targeting an August 13'th ship date right now. I'll update this issue again when we ship :)

**Comment by ramlaxman** [comment]
Thanks for the great work and contribution. @d12 and all.

**Comment by adamfdotnet** [comment]
Hi. Is there a reason why you are only focused on Google Classroom and not a standard integration with other LMSs via LTI? This would be far more useful for use at universities as very few use Google Classroom. Or am I misunderstanding something? Thanks.

**Comment by d12** [comment]
@adamfdotnet Thanks for noting that, I've changed the issue title to be more accurate. Google Classroom isn't an LTI tool which is why development for it has been separate, but we are also launching LTI integration alongside Google Classroom integration!

**Comment by stephaniegiang** [comment]
Hey everyone! 👋 
We have just launched the GitHub Classroom + LMS integration (that includes Google Classroom).

Check out the blog post here: https://github.blog/2019-08-13-use-github-classroom-with-your-own-tools/
And here are the docs to help set you up: https://classroom.github.com/help/connect-to-lms

Try it out and let us know what you think! If there are any problems, feel free to open an issue 😄

**Comment by stephaniegiang** [comment]
Closing this issue as GitHub Classroom now integrates with LMSs for roster import. We have plans to expand the capabilities in the future to more of GitHub Classroom.
