### ISSUE TITLE
Not recognizing my organization.

### ISSUE THREAD

**Issue by devinberg** [education/classroom#722]
In attempting to create a classroom, it says I don't have any organizations on my account and that I need to create one and come back. I do have an organization created for this purpose.

**Comment by devinberg** [comment]
Nevermind. Was a permissions issue that wasn't clearly communicated.

**Comment by tarebyte** [comment]
@quizzy226 you need to ensure that your organizations have granted us access.

You can check it here: https://github.com/settings/connections/applications/64a051cf1598b9f0658f
