### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by hollenberry** [education/classroom#724]
Hey team! I know that we've documented this somewhere, but I can't seem to find it (if we locate it, feel free to close this out). 

It appears that there's an authentication bug that's affecting several of our users, in both 
On-Demand and our New Hire Trainings. 

After following the link to a GitHub classroom for the first time, there's potential for this screen to pop up:
<img width="743" alt="screen shot 2016-08-29 at 2 34 12 pm" src="https://cloud.githubusercontent.com/assets/13326548/18068607/0adfc8fa-6df7-11e6-9576-f6086ffd6fe7.png">

Using the `githubstudent` account, I was able to reproduce the error on both Safari and Chrome. Here's how:

1. Log into `githubstudent`
2. Click here: https://classroom.github.com/group-assignment-invitations/5fb54829a139ec1362f058626a559f7c
3. The page will appear to hang, but it will complete and you'll see the above error.

I believe that this _only_ happens because `githubstudent` hasn't yet Authorized `GitHubClassroom`, and once we authorize it, it will cease to be an issue. I've deliberately avoided authorizing it so that you can reproduce the error.  

cc: @hectorsector, @bonnieC, @tarebyte, @johndbritton

**Comment by hollenberry** [comment]
Alternatively, you don't need to log-in to any GitHub account. You'll be routed to the same error page, just by navigating to the link, above: https://classroom.github.com/group-assignment-invitations/5fb54829a139ec1362f058626a559f7c

That link is also the url that remains on reaching the error.

**Comment by brianamarie** [comment]
## More information

#### Linking relevant context/conversations: 

- [#support-technical](https://github.slack.com/archives/support-technical/p1472567536000282)
- [#education](https://github.slack.com/archives/education/p1472572254000480)
- [Daily notes](https://github.com/github/services/issues/2412)
- [Gitter conversations](https://gitter.im/githubschool/on-demand?at=57c3804d42e38279218144bb)

#### My steps to recreate: 

1. Go to github.github.io/on-demand
2. Click continue onto the next page
3. Verify I am logged into GitHub (using @cwilliams09, not been to this site before with that username or computer)
4. Click the link to navigate to the classroom at the bottom of 'Exploring GitHub' page
5. Sent to page asking to authorize application, click "Authorize application"

  ![authorizeapplication](https://cloud.githubusercontent.com/assets/9906718/18096891/6c871c48-6ea1-11e6-85c1-e995aaca1797.png)

6. Sent to error page, https://classroom.github.com/group-assignment-invitations/5fb54829a139ec1362f058626a559f7c

  ![applicationerror](https://cloud.githubusercontent.com/assets/9906718/18096897/6fd39cd2-6ea1-11e6-9cdf-f6a63dc7c797.png)


--- 

We are also very welcome to suggested temporary workarounds for this problem, as joining the repository is a key step in completing the [on-demand curriculum](https://github.github.io/on-demand/). ✨ 

---
There is some odd behavior that may be unrelated but is worth noting. It appears that many repositories are being created in the `githubschool` org with similar names, like unintentional forks.

---

🙇 Thank you @johndbritton @tarebyte for your keen eyes and help as we collaborate and join efforts to bring more people to GitHub! ✨

**Comment by brianamarie** [comment]
cc @crichID @matthewmccullough @jordanmccullough @beardofedu for awareness of continued troubleshooting github classroom authentication inconsistencies

**Comment by hollenberry** [comment]
> I believe that this only happens because githubstudent hasn't yet Authorized GitHubClassroom, and once we authorize it, it will cease to be an issue. I've deliberately avoided authorizing it so that you can reproduce the error.

After testing with @brianamarie, the above theory is incorrect. This is reproducible even after following the Auth screen.

**Comment by brianamarie** [comment]
> I believe that this only happens because githubstudent hasn't yet Authorized GitHubClassroom, and once we authorize it, it will cease to be an issue. I've deliberately avoided authorizing it so that you can reproduce the error.

I'm not _sure_ if this is what you're talking about...but I tried a few things:

## Going back to the URL (https://classroom.github.com/group-assignment-invitations/5fb54829a139ec1362f058626a559f7c)

- This causes the exact same error page to come as before

### In the **same tab**, hitting the back button to click the 'authorize application' button **again**

- Same page at first
  
![authorizeappagain](https://cloud.githubusercontent.com/assets/9906718/18097479/89a3b352-6ea3-11e6-9b93-43015e4fc65f.png)

- Upon clicking, a new error page is given

![newerrrorrr](https://cloud.githubusercontent.com/assets/9906718/18097485/940ed556-6ea3-11e6-8e0b-f299aa6ce548.png)

Not sure what this means, but I want to document it here for a thorough picture of behavior.

**Comment by hollenberry** [comment]
For reference: Issue was caused by large class size (data from tons of accounts pulled, causing timeout). Mark updated the request + we were able to test to see a successful result.
