### ISSUE TITLE
Duplicate repositories created concurrently for the same student

### ISSUE THREAD

**Issue by jayvdb** [education/classroom#729]
I just released a set of assignments, and two students have managed to create three repositories for their assignments (two different assignments), named `x`, `x-1` and `x-2`, all created one minute apart, concurrently.

I havent also been able to reproduce this by using one of the invitation links a second time, after the first import had concluded. i.e. consecutively.

They are private repos.  I can send more details privately, if necessary, but it seems pretty easy to reproduce.

**Comment by jayvdb** [comment]
This is happening to me very regularly on https://github.com/BesutKode .

To make matters more annoying, if I delete the `x-1` repo, the Classroom UI shows it as a deleted repository, despite the fact the student is busy working in the repository without the `-1` suffix.  This might be related to #734 . ping @tarebyte .

An example of this deleted repository problem is https://classroom.github.com/classrooms/18556752-besut-kode/assignments/tantangan-ketiga-wikimedia-pywikibot

**Comment by nwoodthorpe** [comment]
Restricting students to one assignment repo per assignment makes sense to me. This should be an easy fix, added to the TODO

**Comment by jayvdb** [comment]
@nwoodthorpe , has this been done?

**Comment by jayvdb** [comment]
I am still encountering this problem on private assignment creation.

**Comment by nwoodthorpe** [comment]
I haven't seen this behavior before. I'll re-open and we'll try to get to this when we can!

**Comment by ekimgit** [comment]
I have the same problem with some students. What to do? Should I remove the -1 Repos?
