### ISSUE TITLE
Teams cannot be deleted from Classroom once created

### ISSUE THREAD

**Issue by crichID** [education/classroom#730]
### The Problem
- We are currently using GitHub Classroom to manage the on-demand courses for GitHub Training. 
- We are adding all new students to a single team, however I feel confident this would also be an issue if we had any number of teams. 
- At this time, **there is no way to prevent users from creating new teams for the assignment.** 
- There is also **no way to delete a team from classroom** once it has been made (even if we delete the associated team from the github org).

Are these features we can consider adding? 

Thank you!

**Comment by nwoodthorpe** [comment]
Regarding users creating new teams, this was mentioned here #861.

Not having a way to delete a team sounds like a bug though (or a feature we really should have). Added to the todo. :+1:

**Comment by BelieveC** [comment]
I would like take this on

**Comment by nwoodthorpe** [comment]
That would be great!

**Comment by d12** [comment]
Teachers can now set a maximum number of teams which solves this issue: https://github.com/education/classroom/pull/1876
