### ISSUE TITLE
Organization not recognized in Classroom

### ISSUE THREAD

**Issue by amesbah** [education/classroom#731]
Hi,

I'd like to connect my educational organization https://github.com/UBC-CPEN422/ to GitHub Classroom, but Classroom says I don't have any organizations.

Could you please look into this?

Thanks,
Ali

**Comment by tarebyte** [comment]
@amesbah would you mind checking https://github.com/settings/connections/applications/64a051cf1598b9f0658f and looking to see if you have authorized your Organization to use Classroom?

Thanks!

**Comment by tarebyte** [comment]
Closing this out, please feel free to reopen if this doesn't resolve your issue.

Thanks!
