### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Repairio** [education/classroom#747]
Unable to authenticate; cannot push to my class' repo.

**Comment by tarebyte** [comment]
@Repairio just to make sure I understand your issue, you don't have access to the GitHub repository?

**Comment by Repairio** [comment]
@tarebyte

I did have access when I experienced the error. I then left so I might rejoin in hopes to solve the issue, but the join page views as if I still have access.

I think the authentication error may be on my side, since I am also unable to push to my own repo.

**Comment by nwoodthorpe** [comment]
GitHub and GitHub Classroom authentication are actually separate, it's possible to have both be logged in to different accounts, or have one logged in and one logged out. It sounds like the later was happening in this case. The solution is to re-login to whichever app got logged out.

If this pops up again, feel free to re-open!
