### ISSUE TITLE
Error message for URL in starter code

### ISSUE THREAD

**Issue by jayvdb** [education/classroom#748]
If I add a Github URL to the starter code box, the error message is "The listed users and repositories can not be searched. ...."

It should say to use a SLUG, not a URL.

**Comment by tarebyte** [comment]
@jayvdb looking at the screenshot below
<img width="520" alt="screen shot 2016-09-23 at 08 52 47" src="https://cloud.githubusercontent.com/assets/564113/18786307/3255e93c-816b-11e6-981e-cefd607d4baf.png">

We don't actually specify how to search for the repositories. Would this make it more clear?

<img width="480" alt="screen shot 2016-09-23 at 08 55 13" src="https://cloud.githubusercontent.com/assets/564113/18786358/767e8ab0-816b-11e6-9580-188f62407c16.png">

**Comment by jayvdb** [comment]
Yes.
