### ISSUE TITLE
Commits needed on starter import?

### ISSUE THREAD

**Issue by robmuh** [education/classroom#766]
I noticed during the creation of assignments that had several commits that the import took notably longer. I realize after a while the assignment repo can be rebased to contain nothing but one commit, but is there any way this could be built into the classroom assignment process? Could it just look at the last version and not include the commit history? Thanks in advance.

**Comment by jayvdb** [comment]
This is undesirable IMO.  Not including the commit history means creating an incompatible repository.  i.e. it wouldnt be possible to use git features, e.g. to compare the student repo with the starter repo.

If a teacher wants to optimise their starter repo, they can & should do it themselves.  Maybe some documentation could be added to assist.

**Comment by robmuh** [comment]
Can you provide a scenario where having the previous starter repo commits is valuable? I'm honestly curious.

**Comment by jayvdb** [comment]
All of my assignments are existing OSS repositories, with important commit history.

**Comment by robmuh** [comment]
Ok, I can get behind that—especially when teaching OSS software itself or as an exercise in OSS contribution practice.
