### ISSUE TITLE
Import notification goes to wrong email

### ISSUE THREAD

**Issue by jasonnutter** [education/classroom#768]
When a student accepts a Github classroom invite and their repo is imported into the organization, the notification goes to the main email address for your account, instead of the email address you have configured to receive notifications for that organization.

Repro:
1. Setup your organization and Github classroom, and [configure notifications for that organization to go to a different email address](https://github.com/settings/notifications) (custom routing).
2. Create an assignment in Github classroom and send that invite to your students.
3. When students accept the invite, their repo for that assignment will be created in your organization.
4. You will receive an email letting you know that the import process for this repo has finished, however, it will go to your main email address, not the email address you specified in step 1.

Email in question:

```
Subject: Import to <your organization>/<starter repo name>-<student user name> is finished!

Hi <your Github user name>!

The import to https://github.com/<your organization>/<starter repo name>-<student user name> is finished!



Happy cloning!

--
Your friends at GitHub
```

Please let me know if I am missing a configuration step somewhere, or if I should share any additional information.

Thanks!

**Comment by johndbritton** [comment]
Thanks for reporting this @jasonnutter. This is a bug in the GitHub import API. I reported the issue to the team a while back and it's in the backlog to be addressed. I'm going to leave this issue open so that we can update you when the fix is made but just wanted to let you know we're aware of the issue.

**Comment by johndbritton** [comment]
@jasonnutter We've rolled out a fix for this, thanks for reporting.
