### ISSUE TITLE
More elegantly handle multiple assignment URL clicks by the same student

### ISSUE THREAD

**Issue by robwhess** [education/classroom#769]
Currently, if a student who's already accepted a particular assignment follows the assignment link and clicks the button to accept the assignment again, a second assignment repo is created for that student with a "-1" appended to its name.  If they do it again, another repo is created with a "-2" appended, and so forth.

In my opinion, a more elegant behavior would be this: if a student (identified by GH username) has already accepted a particular assignment and they click the button to accept it again, they should just be brought to their already-created assignment repo.

This seems especially important because I think hiding within this issue is a more pernicious one: sometimes, when a student clicks the button to accept the assignment a second time, something fails in the repo creation/import process, and the repo they originally created (into which they may already have pushed work) is overwritten with an empty repo.  I've had this happen to more than one student, causing them to lose work.

**Comment by jayvdb** [comment]
Dup of #729 
Allowing only one repo creation at a time will solve this.

**Comment by nwoodthorpe** [comment]
Restricting students to one assignment repo per assignment makes sense to me. This should be an easy fix, added to the TODO

**Comment by nwoodthorpe** [comment]
Going to close as a dup of #729 and move my comment there.
