### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#77]
When the user hits Classroom for the first time, this is what they currently see. I'm not entirely sure what to do with this, but it could possibly be a page to show off the highlights of the app.

<img width="1552" alt="screen shot 2015-08-05 at 12 39 06" src="https://cloud.githubusercontent.com/assets/564113/9091573/fb730154-3b6e-11e5-81c9-807631bca7a4.png">

**Comment by jasonlong** [comment]
The app currently shows the "no orgs" blank slate. Is that ok or do we need something else here?

**Comment by tarebyte** [comment]
@jasonlong this the front page before authentication.

We may want something here just to show what classroom is about.

**Comment by johndbritton** [comment]
Here's the current logged out dashboard:

<img width="1004" alt="screen shot 2015-09-01 at 12 24 38 pm" src="https://cloud.githubusercontent.com/assets/123345/9602915/731bca52-50a4-11e5-836e-31b725350c5c.png">

What do you think about having a simple explanation of Classroom for GitHub there in the style of a herobox with sign in button down below. Then, on the logged in dashboard we can include the same herobox content above the Organizations section. That way logged in and logged out users both see the explainer copy.

<img width="1002" alt="screen shot 2015-09-01 at 12 27 12 pm" src="https://cloud.githubusercontent.com/assets/123345/9602960/cccaf208-50a4-11e5-9469-52feddc687e5.png">

**Comment by johndbritton** [comment]
@jasonlong Are you able to help out with the landing page?

**Comment by jasonlong** [comment]
Sure, I can help out here.

My initial thoughts here are that we'd want to show a couple of sentences explaining **what** Classroom is and **why** you might want to use it – and then have the big sign in button. For people who are already signed in, they're already (at least somewhat) bought into the idea and don't need persuaded. They basically need to know what to do next. With that in mind, maybe we simply tweak the no-organizations blankslate copy.

I'll put together a couple mockups shortly.

**Comment by johndbritton** [comment]
> With that in mind, maybe we simply tweak the no-organizations blankslate copy.

:+1: Thanks for your help.

**Comment by jasonlong** [comment]
For the logged out state, how about something like this? I'll let you guys hash out the actual copy. Or you could ask `github/copy` for input.

![screen shot 2015-09-01 at 11 23 19 am](https://cloud.githubusercontent.com/assets/6104/9608356/03aba140-509c-11e5-8efc-9c2918dbdea2.png)

I just picked those particular Octicons, but they could be whatever – or be removed altogether.

For the text styles, I'd make them similar to the section headings on https://github.com/home

The logged in blankslate feels :ok_hand: to me personally, but there might be some better copy that could be used here as well.

**Comment by johndbritton** [comment]
Maybe start with this:

> __Your course assignments on GitHub__
>
> Classroom for GitHub automates repository creation and access control, making it easy to distribute starter code and collect assignment submissions on GitHub.

Some other features that might be worth calling out:

* Public and private repositories
* Individual and group assignments
* Students can form their own groups
* View student progress on GitHub
* Easy to navigate to submissions for each assignment

cc/ @bernars @gjtorikian We're working on copy for the landing page of `Classroom for GitHub` would love your input on the copy.

Background:
The app connects to a GitHub organization and allows you to create assignments. The assignments can be for individual work or group work and can be in private or public repositories. Group assignments have a nice flow where students can create new teams or join existing teams on the fly. Once an assignment is created, the teacher gets a unique url that they can distribute to students. Anyone with the URL will be added to the organization, have appropriate repositories created, and access granted to those repositories. The app also has the ability to upload starter code to the newly created repository. As students sign up, the teacher can see a list of links to student submission repositories on the assignment page within the app.

**Comment by johndbritton** [comment]
@jasonlong I think we should go ahead with the following copy:

> __Your course assignments on GitHub__
>
> Classroom for GitHub automates repository creation and access control, making it easy to distribute starter code and collect assignment submissions on GitHub.

**Comment by jasonlong** [comment]
That sounds good to me.

@tarebyte Are you able to get this wired up? We had our :baby: this morning, so I'm going to be mostly offline for a while.

**Comment by tarebyte** [comment]
Yeah, I can do it. Congrats!

**Comment by johndbritton** [comment]
Congrats @jasonlong!
