### ISSUE TITLE
Repository Import Fails

### ISSUE THREAD

**Issue by sxlijin** [education/classroom#772]
When students import a repository, that import may fail and leave their repository in an unworkable state. The workaround seems to be for either (1) the student to delete the repo and re-import (i.e. re-create their repo for the assignment) or (2) someone to force-push a clone of the repo to the repo with the failed import.

It seems to me that if it really has to be the case that this process should fail, then there should be a cleaner way of fixing it - perhaps some kind of automatic retry or something.

This has happened 3 times so far, n ~ 330.

Below is a screenshot I received from a student:

![image](https://cloud.githubusercontent.com/assets/512410/19504225/2d1f74c0-957e-11e6-8286-6d98c5e2bf7b.png)

**Comment by tarebyte** [comment]
@sxlijin thanks for reporting this, so the importer is outside of the control of Classroom as it's part of the GitHub.

However I will take a look to see if there is a better way of doing a retry on the Classroom side.

Thanks!

**Comment by sxlijin** [comment]
@tarebyte is there somewhere on the GH side where I can/should open this as an issue?

JW if this is a known bug or if there's someone that could use more details about this.

**Comment by sxlijin** [comment]
@tarebyte has there been any progress on this?

I only ask because we're seeing (slightly) more reports of failed imports.

**Comment by sxlijin** [comment]
Bump - @dhowe has collated a list of related issues, which I'm reiterating below to link the GH topics:

* #779 - "Assignment failed to be created"
* #784 (duplicate)
* #786 (duplicate)

@tarebyte I'm happy to help out with a solution if you can point me at something in the codebase.

**Comment by tarebyte** [comment]
@sxlijin looking at this again, unless we constantly pull from the [GitHub API](https://developer.github.com/v3/migration/source_imports/#get-import-progress) we don't know if the source import was successful.

I'm not sure how I feel about it because that could be really expensive depending on the size of the repo and the number of assignments.

What do you think?

**Comment by sxlijin** [comment]
Would it make sense to perhaps clone the repository to Classroom when the assignment is first set up, and then clone from Classroom to GH every time a student creates their own repo?

**Comment by tarebyte** [comment]
@sxlijin we made the decision a long time ago to not do something like that just because we didn't want to store other users code if it is private.

It's also tough because Heroku doesn't let us write to disk so we'd have to send it to an S3 bucket or something like that.

**Comment by sxlijin** [comment]
@tarebyte that's a fair concern, but I imagine most of the Classroom user base uses private organizations is to make sure students do their own work, not because their livelihood depends on the confidentiality of their IP. I do understand, though, and agree that it is something that does merit effort in avoiding.

Is there something you could do on the GH side to see why it might be that the importer fails so frequently? (Because to be honest, the ~1% failure rate that's indicated by the anecdotes here seems disturbingly high for production code.)

One possibility could be forking and then disconnecting the fork, although I don't think disconnecting is exposed via the API.

Another Classroom-side alternative: clone the repo to Classroom (maybe as a .zip?), leave it as a binary blob in memory, upload it back to GH as the student, then drop the blob? There are obviously some practical concerns here, but if it turns out most repos used with Classroom are small enough (on the order of KB, maybe MB) then this may be a viable alternative.

**Comment by tarebyte** [comment]
> Is there something you could do on the GH side to see why it might be that the importer fails so frequently? (Because to be honest, the ~1% failure rate that's indicated by the anecdotes here seems disturbingly high for production code.)

I don't think frequently is quite accurate, there are way more imports that are successful. I don't have hard data, but I don't think that it's even 1% tbh.

I can ask my colleagues at GitHub, the porter is not really in my wheel house.

> One possibility could be forking and then disconnecting the fork, although I don't think disconnecting is exposed via the API.

You're correct you can't do that, there isn't a way to do that in GitHub in general. The way someone would "detach" a fork is by pushing it up again as a new project.

There are more points of failure with that solution there than with the importer, at least with the importer we can kick off the job again. Doing all of the git operations ourselves is something I really don't want to do.

> leave it as a binary blob in memory, upload it back to GH as the student, then drop the blob? There are obviously some practical concerns here, but if it turns out most repos used with Classroom are small enough (on the order of KB, maybe MB) then this may be a viable alternative.

The problem with that is if we deploy the site while the blobs are in memory we'll lose them 😢

**Comment by sxlijin** [comment]
> I don't have hard data, but I don't think that it's even 1% tbh.

Could be just an issue of the vocal minority here, so I suppose that's fair. 

> The way someone would "detach" a fork is by pushing it up again as a new project.

It's my understanding is that GH staff have the ability to disconnect forks, although obviously I don't know any of the details behind how this works.

> The problem with that is if we deploy the site while the blobs are in memory we'll lose them :cry:

And now I understand the S3 mention...

<hr/>

To clarify, so that I'm not missing anything, the tool that's used for repository clones is the [GitHub Importer](https://help.github.com/articles/about-github-importer/), right?

What about just destroying a repository after a failed import (compare `ls-remote`s, perhaps)? There are some implementation issues that come to mind, but this simultaneously (1) avoids the how-many-retries issue and (2) minimizes the Classroom-side Git failure points while also improving the student UX. Errors still suck, but at least then there would be a path to recovery.

Although I'm also noticing now that [the API for source imports is still in preview...](https://developer.github.com/v3/migration/source_imports/#get-import-progress).

**Comment by tarebyte** [comment]
> It's my understanding is that GH staff have the ability to disconnect forks, although obviously I don't know any of the details behind how this works.

It may be a staff tool (I honestly have no idea), however this is an open source project which means that everything we use must be available to everyone.

> To clarify, so that I'm not missing anything, the tool that's used for repository clones is the [GitHub Importer](https://help.github.com/articles/about-github-importer/), right?

That is correct

> What about just destroying a repository after a failed import (compare `ls-remote`s, perhaps)? There are some implementation issues that come to mind, but this simultaneously (1) avoids the how-many-retries issue and (2) minimizes the Classroom-side Git failure points while also improving the student UX. Errors still suck, but at least then there would be a path to recovery.

This could be done via the API, in what I call an API transaction where if one part of the process fails everything else is undone ([example](https://github.com/education/classroom/blob/a0975fa566daaf2a3349d50c2ee883d19591334d/app/models/assignment_repo/creator.rb#L77-L81)).

I'm going to make the call here and say we're not going to use Git under the hood. That's another whole set of dependencies I don't want us to deal with as part of the infrastructure.

> Although I'm also noticing now that [the API for source imports is still in preview...](https://developer.github.com/v3/migration/source_imports/#get-import-progress).

It is, the features we are using are stable. It's not coming out of preview yet because there are some other features that teams wants to work on first. An example feature would be to turn off the email notifications for an import via the API.

**Comment by sxlijin** [comment]
> I'm going to make the call here and say we're not going to use Git under the hood. That's another whole set of dependencies I don't want us to deal with as part of the infrastructure.

Agreed on not using Git under the hood; the `ls-remote` suggestion was more of a "the API should support this, I just don't know the API call off the top of my head".

Tangent: I like [this commit message](https://github.com/education/classroom/commit/b3fe03e7bfc72499ce46c626835213cafec20918), by the way.

> This could be done via the API, in what I call an API transaction where if one part of the process fails everything else is undone ([example](https://github.com/education/classroom/blob/a0975fa566daaf2a3349d50c2ee883d19591334d/app/models/assignment_repo/creator.rb#L77-L81)).

:+1: the main issue that comes to mind, though, is that right now the user flow redirects the student to GH itself once the importer is kicked off, which means if the importer fails, the user is left on GH, not a Classroom page.

Also, does [this bit](https://github.com/education/classroom/blob/a0975fa566daaf2a3349d50c2ee883d19591334d/app/models/assignment_repo/creator.rb#L127-L128) seem right to you? It seems like something more deserving of a verbose error message on the user's end.

**Comment by tarebyte** [comment]
> An implementation question: right now the user flow redirects the student to GH itself once the importer is kicked off, which means if the importer fails, the user is left on GH, not a Classroom page. Would adding this require major changes in the user flow here?

It would, we'd have to wait for all parts to complete and then redirect the student.

> Also, does [this bit](https://github.com/education/classroom/blob/a0975fa566daaf2a3349d50c2ee883d19591334d/app/models/assignment_repo/creator.rb#L127-L128) seem right to you? It seems like something more deserving of a verbose error message on the user's end.

Unless the student has admin rights to the repository there isn't anything they can do about the repo deletion failure, so I didn't bother letting them know about it.

**Comment by ms-studio** [comment]
Just mentioning that I'm trying out Github classroom assignments, and in a group of 9 students, three imports have failed. Two of the failures were resolved after a second attempt. 

The third failure could not be resolved, every attempt to create the repository displays the message "There was an error pushing commits to GitHub."

Here's the repository that keeps failing to get created: https://github.com/eracom-gr351/mini-examen-test-JoWanna/

**Comment by nwoodthorpe** [comment]
This is going to be tricky to solve, considering the failing code is part of a dependency and out of our control. For the cases where a retry solved the issue, it would be trivial to add retry logic [here](https://github.com/education/classroom/blob/a0975fa566daaf2a3349d50c2ee883d19591334d/app/models/assignment_repo/creator.rb#L77-L81) that errors after 2 or 3 attempts. 

Perhaps something like this:
```
    def perform(attempt_number = 1)
      verify_organization_has_private_repos_available!

      assignment_repo = assignment.assignment_repos.build(
        github_repo_id: create_github_repository!,
        user: user
      )

      add_user_to_repository!(assignment_repo.github_repo_id)

      if assignment.starter_code?
        push_starter_code!(assignment_repo.github_repo_id)
      end

      begin
        assignment_repo.save!
      rescue ActiveRecord::RecordInvalid
        raise Result::Error, DEFAULT_ERROR_MESSAGE
      end

      Result.success(assignment_repo)
    rescue Result::Error => err
      delete_github_repository(assignment_repo.try(:github_repo_id))

      if attempt_number == 3
        Result.failed(err.message)
      else
        perform(attempt_number + 1)
      end
    end
```

**Comment by ms-studio** [comment]
Thanks for looking into it. Not sure if anything has changed, but I tried some further assignments with groups of circa 10 students, and didn't encounter any failures anymore.

**Comment by jjcoy** [comment]
Hello,  I encountered a failure today.  Just 1 failure in about 35 created in the last week or so.

**Comment by drstearns** [comment]
I just had over a dozen students in a class of 40 experience this problem. I sent out the GitHub classroom link early, but many students had not yet clicked it, so many students clicked it at roughly the same time during class. The import began, but never finished. When they clicked the link in the GitHub Classroom confirmation page, it showed a status bar that never advanced. 

I had to cancel the import, have them manually add a remote to the starter repo, and pull commits to seed their empty repos. Kind of defeats the point of using GitHub classroom.

Was this just a temporary problem occurring now, or is this a more systemic bug? If the latter, I may need to reconsider using GitHub Classroom.

**Comment by witchel** [comment]
I think this is still an issue.  Out of 14 repositories (so far), 3 of them failed to import.

**Comment by elray1** [comment]
Also confirm that this is still a problem.  I had a high enough failure rate (~10 in 40) that I decided continuing to use this tool is infeasible.

**Comment by AjitZero** [comment]
This is still a problem. There are no clear directions regarding importing in case of repeated failure.

**Comment by photoszzt** [comment]
@AjitZero  in that case, you can manually mirror the starter code repo to student's repo yourself. You can follow this instruction: https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository

**Comment by nguyenngocphuongnb** [comment]
your repository may contain files with size larger than 100MB, try to remove these files using  [BFG Repo-Cleaner](https://rtyley.github.io/bfg-repo-cleaner/). There is a tutorial about [How to solve Github import error: "We found an error during import"](https://cloudreports.net/how-to-solve-github-import-error-we-found-error-during-import/). Remember to backup your project source code and git database
