### ISSUE TITLE
Group assignment creation is impossible with Firefox 49

### ISSUE THREAD

**Issue by bpesquet** [education/classroom#776]
Hi,

**Update**: this doesn't happen in Chrome.

When I try to create a group assignment for my organization (@ensc-glog), the **Create Assignment** button stays disabled event after filling all the fields. I am able to create an individual assignment for the same orga.

In both cases, the search field for adding starter code from a repo doesn't work.
![bug classroom](https://cloud.githubusercontent.com/assets/1837749/19827914/99156a62-9db8-11e6-9de5-0a63cceaf665.gif)

**Comment by yingjerkao** [comment]
Similar behavior for Safari 10.0.1  on MacOS 10.10.5

Works fine on Chrome too.

**Comment by tarebyte** [comment]
Hi @bpesquet apologies for the inconvience, I've revert the JS changes and confirmed that I can make a group assignment on Firefox.

![firefox](https://cloud.githubusercontent.com/assets/564113/19890111/0e5f7652-a00f-11e6-89b0-0f6d4cd737dc.gif)
