### ISSUE TITLE
Student cannot create repo

### ISSUE THREAD

**Issue by tmandel** [education/classroom#779]
A student is unable to create a repo for an assignment in the course I am TAing by clicking the invitation link.  They simply get an "assignment failed to be created" error (see attached screenshot).  They tried several times last night, logging out and logging back in, nothing worked.  They've been able to create repos in this manner before (using the same Github account). Any idea how to fix this?

![screenshot 3](https://cloud.githubusercontent.com/assets/126192/19970618/8711f736-a1aa-11e6-9fd0-41c04d137071.png)

**Comment by cyhsutw** [comment]
@tmandel I was facing the same issue you described a few hours ago. And I think this is due to the temporary failure of GitHub's source import function.

I just tried a couple of minutes ago and it works fine for me now.

**Comment by tmandel** [comment]
@cyhsutw Thanks! I contacted the student and he was finally able to do it today.  Hopefully this doesn't happen again.

**Comment by tmandel** [comment]
Another student is having the same issue tonight.  Seems to be a recurring theme, and is very frustrating as some students will inevitably wait to accept the assignment until shortly before the deadline, leaving little margin for error.  Anything we can do as instructors beyond telling the student to wait it out?

**Comment by tarebyte** [comment]
@tmandel I'll take a look at it now, not entirely sure what's causing your issue.

**Comment by dhowe** [comment]
same problem here, recurring quite often (maybe 5% or more of the time )
very frustrating for everyone involved...

**Comment by nwoodthorpe** [comment]
Closing in favor of #772
