### ISSUE TITLE
Organization Page

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#78]
Each user can have many Organization that are apart of Classroom. When a user chooses their organization on Classroom, this is what it looks like right now.

<img width="1552" alt="screen shot 2015-08-05 at 12 42 08" src="https://cloud.githubusercontent.com/assets/564113/9091673/880fbf4e-3b6f-11e5-8721-101a6730c92b.png">

<img width="1552" alt="screen shot 2015-08-05 at 12 42 24" src="https://cloud.githubusercontent.com/assets/564113/9091671/82cc1d66-3b6f-11e5-86c3-c0756591686a.png">

From this page a user should be able click on creating a new assignment (Individual or Group) see assignments that exist, or invite other Org admins to join classroom. See (issue about invitations)

**Comment by jasonlong** [comment]
Closing based on work in #101.
