### ISSUE TITLE
Private repositories should be the default for new individual assignments

### ISSUE THREAD

**Issue by mcoblenz** [education/classroom#781]
A student just emailed me to tell me he could see other students' repositories! I changed the visibility setting, but it seems to me that "private" is the safest default for new assignments.

**Comment by nwoodthorpe** [comment]
@tarebyte thoughts? My only concern is that many (most?) users don't actually have private repositories, so these users would all have to switch back to public each time.

**Comment by tarebyte** [comment]
I think having private as default is fine, however...

I'd really like it if the page to be smarter, it would be cool if we could tell a teacher before they create their first assignment whether they can even make a private repository.

**Comment by nwoodthorpe** [comment]
Maybe the page would default to private if they have private repositories, or default to public with private grayed out if they don't have private repos?

**Comment by tarebyte** [comment]
@nwoodthorpe I think that'd be a fine solution, we have access to the org's billing information since we have the right credentials from their OAuth token.

**Comment by mcoblenz** [comment]
Thanks, everyone!
