### ISSUE TITLE
Feature request: find repo by name/email

### ISSUE THREAD

**Issue by lindsaymarkward** [education/classroom#783]
See https://education.github.community/t/find-students-repos-by-name/5599 for details
I would like to be able to:
a) search for a repo within an assignment by using the name and/or email of a 'student'
b) see all of the repos on one page (no pagination)

Thank you.

**Comment by weilandia** [comment]
@tarebyte I can work on this if no one else has started. Let me know!

**Comment by tarebyte** [comment]
@weilandia feel free to!

**Comment by nwoodthorpe** [comment]
@weilandia Was this ever done? If not, no worries. We can free it up for other users looking to contribute :)

**Comment by weilandia** [comment]
@nwoodthorpe let's open it up.  My bad for not mentioning sooner.

**Comment by nwoodthorpe** [comment]
Np, thanks for getting back to me!

**Comment by nwoodthorpe** [comment]
This really isn't possible without `n` API requests. I'm not sure this is feasable for classroom right now.
