### ISSUE TITLE
Broken link to forum on GH Classroom

### ISSUE THREAD

**Issue by lindsaymarkward** [education/classroom#785]
Hi. When I'm logged in at https://classroom.github.com/classrooms there's a link to the forums (looks like two speech bubbles). This takes me to a broken page:
https://education.github.community/t/introduce-yourself/32
"Oops! That page doesn’t exist or is private."

**Comment by tarebyte** [comment]
@lindsaymarkward I think it may have just been a Discourse issue, the page is back now.

Thank for reporting it though 💖
