### ISSUE TITLE
Inviting new Org Admins to Classroom

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#79]
When a user creates an Organization if there are other admins that they want to add, they have the option of doing so after they add their Organization or later on from the Organizations page.

The GitHub API doesn't allow us to see a users email if it isn't public so I had to give them optional text boxes.

<img width="1552" alt="screen shot 2015-08-05 at 12 51 23" src="https://cloud.githubusercontent.com/assets/564113/9091877/b356ac52-3b70-11e5-8b6a-853a01cdb1d4.png">

**Comment by jasonlong** [comment]
Does the design in #101 cover this ok?

**Comment by tarebyte** [comment]
The form here has to change, but that's trivial. I can do that when I'm working out some other issues.
