### ISSUE TITLE
Suddenly, all of my links to student assignments look like this

### ISSUE THREAD

**Issue by bnmnetp** [education/classroom#794]
<img width="1099" alt="screen shot 2016-11-26 at 3 01 35 pm" src="https://cloud.githubusercontent.com/assets/51115/20643868/9dd06092-b3e9-11e6-8c02-ec796ea51cb1.png">

**Comment by tarebyte** [comment]
@bnmnetp I took a look and I can't seem to reproduce your issue. Does it consistently happen for you?

**Comment by bnmnetp** [comment]
Well, it is happening consistently in Safari 10.0.1
I don't see any messages in the Javascript Console, and I have cleared all cookies, cache and local storage for GitHub.   This is on a new MacBook Pro so there isn't much of anything installed (yet) that could be causing conflicts.

Using Chrome on the same machine I can get to the student assignments, so at least I have a workaround.

**Comment by tarebyte** [comment]
@bnmnetp everything should be good now. Sorry for the inconvience!
