### ISSUE TITLE
Selecting between an Individual Assignment or a Group Assignment

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#80]
When you choose to create a new assignment from the Organization Page, you can choose to create one of the following

- Individual Assignment (each student gets their own repository)
- Group Assignment (students are in teams and those teams each get a repo)

Currently the selection looks like this:

<img width="1552" alt="screen shot 2015-08-05 at 12 59 58" src="https://cloud.githubusercontent.com/assets/564113/9092135/32d5829a-3b72-11e5-9d7c-cfb98e17b666.png">

**Comment by jasonlong** [comment]
Closing based on work in #101.
