### ISSUE TITLE
Students cannot use a public assignment repository

### ISSUE THREAD

**Issue by tamastompa** [education/classroom#808]
We have a public repository for a public individual assignment:
https://classroom.github.com/classrooms/19305404-codecool_bp_2016_1/assignments/from-python-to-java-pokerclient/settings
Base repository (also public):
https://github.com/CodecoolBP20161/from-python-to-java-pokerclient

But when our students would like to accept the invitation for this assignment, they get an error:
"Cannot make this private assignment, your limit of 0 repositories has been reached. You can request a larger plan for free..."

**Comment by immanuelfodor** [comment]
At another school group, we have a public individual assignment which also behaves like @tamastompa described.
Assignment: https://classroom.github.com/classrooms/21174577-codecool_bp_2016_2/assignments/python-oop-si-exercises-2/settings
Public base repo: https://github.com/CodecoolBP20162/python-application-process-base

A student of ours sent this screenshot from the same error:
![image](https://cloud.githubusercontent.com/assets/21174107/21181627/0f95f016-c1ff-11e6-9498-8fe78ca5fe07.png)
He also tried to use a different account than he used before for other assignments, a basic user account with default settings, but no matter what he does, the error is present. This is why we think there is a problem with the assignment itself, however it was created like others that work fine.

**Comment by tarebyte** [comment]
Sorry for the trouble, I'm taking a look at this issue right now.

**Comment by tarebyte** [comment]
Sorry for trouble 😢  I just merged #809 which fixes your issue.
