### ISSUE TITLE
Allow staff to remove `Users` from `Organizations`

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#812]

**Comment by nwoodthorpe** [comment]
Cheers 🎉 

For the button, I was thinking of one of these two types of buttons. I found both of them in the GitHub settings, so I'm not sure what the preferred one is. I made mocks in Photoshop, which do you prefer? 

Trashcan, like in the Emails section of the settings
<img width="770" alt="trashcan" src="https://cloud.githubusercontent.com/assets/4149056/21444682/6bd70a88-c87e-11e6-9e89-d36cff5c0cf8.png">

Red button, like in the SSH key section of the settings
<img width="770" alt="remove-a" src="https://cloud.githubusercontent.com/assets/4149056/21444701/9185b46e-c87e-11e6-8529-88bf58324345.png">

Red button, one hovered
<img width="770" alt="remove-afixed" src="https://cloud.githubusercontent.com/assets/4149056/21444706/97d213ee-c87e-11e6-82e4-dd523b7c1b46.png">

**Comment by tarebyte** [comment]
@nwoodthorpe if you use the `danger` class on the buttons it will have both styles from 2 and 3. I'd like the explicit text instead of just the icon.
