### ISSUE TITLE
Allow staff to delete `Groups` and `Grouping`

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#813]

**Comment by nwoodthorpe** [comment]
@tarebyte Finally put some time into looking at this! Few questions:

As I understand, we have Groups that represent a group of students working together on one repository, and Groupings that represent the collection of Groups working on a group-assignment. Is that right?

When we delete a Group, do we want it's repository on GitHub removed?  And when we delete a Grouping, do we want all of it's Groups deleted?

**Comment by tarebyte** [comment]
> When we delete a Group, do we want it's repository on GitHub removed?

For the meantime I'd say let's play it on the safe side and not do that.

> And when we delete a Grouping, do we want all of it's Groups deleted?

Yes

**Comment by nwoodthorpe** [comment]
There's a PR out for this, let's not close it.

**Comment by d12** [comment]
Reopening, the fix hasn't merged yet. https://github.com/education/classroom/pull/839
