### ISSUE TITLE
Students are unable to accept an assignment

### ISSUE THREAD

**Issue by DouglasUrner** [education/classroom#817]
I've created an assignment in GitHub Classroom where I want students to be able to upload work that they started before we started using Classroom. My thought was to create an empty repository to which students would upload work, so the assignment has no starter code. You can see this assignment here: https://classroom.github.com/assignment-invitations/cc958fa0a39a2994ca5ad87a8c150b4b

When students in my lab try to accept the assignment they get the message "We were not able to add you to the assignment as a collaborator on this assignment. Please try again."

When I had the link tested from outside of school it seems to work just fine. Student had been able to accept an assignment earlier in the year from the classroom.

**Comment by Gaelan** [comment]
My account was the one that worked from outside the school. My account is several years old (unlike student accounts, created recently), so there are probably various things about it which make it different. Also, I have my own GH Classroom on my account (for testing), so maybe GH Classroom has a different OAuth token for me than the one it has for students?

**Comment by tarebyte** [comment]
@DouglasUrner @Gaelan I've just pushed a fix that should resolve your problem. Please let me know if you run into any other issues!

**Comment by yanneta** [comment]
Hi @tarebyte,
I am getting the same issue with my students.

Any ideas on what the problem could be?
Thanks!
Yannet
<img width="1033" alt="screen shot 2018-02-16 at 1 01 50 pm" src="https://user-images.githubusercontent.com/2998885/36329651-8f4618cc-131b-11e8-9f61-137da2fbf50e.png">

**Comment by Kadaaran** [comment]
Hi @yanneta !

Please refer to #1271 for more informations, we are currently working on it and a fix should be implemented soon 🙏

**Comment by yanneta** [comment]
@Sarik-bot There is no solution yet. I am asking my students to submit to the repo from the previous assignment. (-:
