### ISSUE TITLE
Students cannot accept assignment invitations

### ISSUE THREAD

**Issue by tamastompa** [education/classroom#819]
When we create a new assignment, we have the invitation link.
When a user clicks on that, the Github asks "Authorize application", and "Reauthorization required".
Then when the user clicks on the "Authorize application" button, it doesn't do anything, but redirects to the same page.
So finally the user cannot make a new repo for the assignment :-(

**Comment by tarebyte** [comment]
@tamastompa apologies for the issues, I had to ask for more permissions due to a change in a Beta API which is why you're getting the reauthorized screen.

Is there an error that comes up for your students when they click on the link to make a new assignment?

**Comment by tamastompa** [comment]
No. Basically the reauthorization doesn't work. When a student clicks on the "Reauthorization" button, it does something, but then the very same page comes back. So the student cannot apply the new permissions and continue to the assignment, because of (an unknown) problem.

**Comment by tarebyte** [comment]
@tamastompa can you email me (tarebyte AT github dot com) and I can see if I can help you resolve this.

Thanks!

**Comment by tamastompa** [comment]
Ok, I've sent you an email with a screenshot.

**Comment by tarebyte** [comment]
@tamastompa from your screenshot and description (apologies for the misunderstanding) I _think_ this is a GitHub issue not a Classroom issue.

Would you mind reaching out to support and mentioning that I asked you to reach out?

**Comment by RivasAlejandro** [comment]
I have the same issue, i dont know what to do , the same problem
