### ISSUE TITLE
Allow staff to transfer Assignments to another creator

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#823]
Had an idea from the conversation in https://github.com/education/classroom/issues/812 with @nwoodthorpe 

It would be ✨ if as staff members we could change the `creator` of an assignment to another user in the organization.

/cc @wilfriedE as this would be a good first feature

**Comment by wilfriedE** [comment]
@tarebyte  happy to take this on. Should the new creator have to confirm by accepting to becoming the creator of the assignment before assuming the role?

**Comment by tarebyte** [comment]
> Should the new creator have to confirm by accepting to becoming the creator of the assignment before assuming the role? In the case that the individual doesn't want to be the creator.

That sounds like a good idea to me.

/cc @johndbritton for thoughts

**Comment by tarebyte** [comment]
@wilfriedE I didn't read your comment properly. Since this is a Staff tool we don't need permissions from users right now.

We can just do the transfer.

**Comment by wilfriedE** [comment]
@tarebyte what should changing the creator look like. Bellow is an approach that I am currently thinking about. 
![change_creator](https://cloud.githubusercontent.com/assets/1964213/21945389/ffccbad6-d9a8-11e6-803f-11f268f841ee.png)

**Comment by tarebyte** [comment]
@wilfriedE I'm that looks ✨

**Comment by nwoodthorpe** [comment]
@wilfriedE Any progress on this?
