### ISSUE TITLE
can't create classroom

### ISSUE THREAD

**Issue by robustUTEP** [education/classroom#826]
Hi.  I need to create two classrooms for the semester that starts tomorrow

2017-spr-nets
2017-spr-arch1

The error: "another user has added this user to github classroom.
My username is robustUTEP

My email: efreudenthal@utep.edu  
My phone: 915-747-6954 or (cell) 917-279-6208

Thanks, Eric

**Comment by tarebyte** [comment]
@robustUTEP looking at your classroom page, I can't see those two organizations.

Would you mind verifying that you've granted Classroom access to these organizations https://github.com/settings/connections/applications/64a051cf1598b9f0658f

Thanks!

**Comment by robustUTEP** [comment]
yes.   I haven't made any orgs for the spring yet.   The system asks me for a credit card!

**Comment by tarebyte** [comment]
@robustUTEP looking at your discount requests, we can't accept them because you didn't finish filling out the information.

Once we have all of the information we'll be able to approve your requests.

Thanks!
