### ISSUE TITLE
Readthedocs hard (?) to use with classrom

### ISSUE THREAD

**Issue by amueller** [education/classroom#830]
See https://education.github.community/t/continuous-integration-for-each-submission/8347/4

I'm trying to make the students use readthedocs to build some documentation they write.
This is one build per student.
Because this is homework, the repositories are private, so readthedocs.org doesn't show them. They could use readthedocs.com (I think) but that doesn't show the repositories, because the students are not members of the organization.
I think for readthedocs the students would need to be administrators of their repository, but I'm not entirely sure.
For now I think we gave up on using readthedocs.

The theme seems to be that services that integrate with github assume that you either own the repository you want to do something with or you are at least a member of the organization the repository belongs to.
With classroom neither is true, though I could use octokit to do that. It seems there is no obvious way to collect all the github handles, either, but I guess that would also be possible with octokit after they clicked on the link.

**Comment by nwoodthorpe** [comment]
Hey @amueller, thanks for your comments.

You're completely right, in it's current state, Classroom has trouble working with a lot of GitHub integrations. There isn't an immediate solution, but it's something that should be addressed for sure. I'll give you a shout when there's progress on this.
