### ISSUE TITLE
"make students admin" is not applied to existing repositories

### ISSUE THREAD

**Issue by amueller** [education/classroom#831]
I checked the "make students admins" and it seems this was not applied to existing repositories. Is that by design? It would be great if I could change that - instead of having to go through 100 repositories one by one.

**Comment by tarebyte** [comment]
@amueller just to make I understand this was an assignment that has existing submissions?

Right now you're correct we don't do that, the work to update all of those would be similar to https://github.com/education/classroom/pull/788

**Comment by amueller** [comment]
Not sure what submission means in this context. I mean people clicked on the link and had a repository created for them. If I update the permissions after that happened, they are not updated.

I tried to be conservative when creating the assignment, but it turns out that not having admin rights makes using gh-pages somewhat less intuitive, so I wanted to change it.
It would be a great feature to have this, as doing this manually would be quite cumbersome.

**Comment by tarebyte** [comment]
@amueller yup I see what you mean, this would be similar to the work done in: https://github.com/education/classroom/pull/788

**Comment by nwoodthorpe** [comment]
@tarebyte does #788 being merged close this issue?

**Comment by tarebyte** [comment]
Sure does!
