### ISSUE TITLE
Identify the owner who has added the organization to a classroom

### ISSUE THREAD

**Issue by sanicki** [education/classroom#845]
Currently there is a 1:1 relationship between organizations and classrooms.

If a classroom has already been added to an organization the tooltip "Another owner has already added this organization to GitHub Classroom" appears.

<img width="572" alt="another" src="https://cloud.githubusercontent.com/assets/6764844/22832146/26f5aefc-ef6a-11e6-8ecd-a0f0f2b21d79.png">

This is confusing for both organizations with a single owner, where the owner may not be aware of the 1:1 relationship, and to organizations with multiple owners, where the identity of the owner who established the classroom could be useful.

Since non-owners will not see the tooltip there is no privacy issue if the name of the owner is stated rather than using "Another owner."

**Comment by nwoodthorpe** [comment]
@sanicki How about the text "<%= username %> has already added this organization to GitHub Classroom."? I think this implies organizations can only be added to Classroom once. Explaining that there is a 1-1 relationship AND organizations for classrooms must be unique through the entire app will be tricky to fit in a tooltip!

**Comment by sanicki** [comment]
Sounds good. 👍
