### ISSUE TITLE
Sort assignment repositories

### ISSUE THREAD

**Issue by janetlndavis** [education/classroom#847]
When viewing the list of repositories associated with an assignment, there is no way to change the sort order. It would be helpful to be able to sort them alphabetically so the order in the Web interface matches the order of the cloned repos in my local filesystem.

**Comment by janetlndavis** [comment]
See, for example, https://classroom.github.com/classrooms/22714409-whitmanswdesignspring2017/group-assignments/project1

**Comment by danwallach** [comment]
Adding to this feature request: it would be handy to be able to sort on multiple fields, such as GitHub ID, lastname/firstname, or our university identifier if that's associated with a given GitHub Classroom instance.

**Comment by athityakumar** [comment]
@tarebyte - I'd like to take up this issue, with ability to sort by name, firstname and lastname. I roughly understand the changes that would be required for this functionality, and will try to get back as soon as possible.

**Comment by BU-AWolfe** [comment]
## MORE FEATURES:
- Folders and hierarchies for student repositories
- compact view with one student repository per line of text
- filter on "overdue" students
- look for pull requests
