### ISSUE TITLE
Org owners that have rejected auth tokens can't be removed from a Classroom in stafftools

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#848]
Ran across an issue today where if the org owner has rejected their auth token for Classroom, we can't remove them from the Classroom in stafftools.

/cc @nwoodthorpe

**Comment by BelieveC** [comment]
I would like to work on this!

**Comment by nwoodthorpe** [comment]
It's all yours!

**Comment by BelieveC** [comment]
Thanks :smile:

**Comment by BelieveC** [comment]
@tarebyte @nwoodthorpe 
Is this the workflow you want to implement ->

`stafftools/user/x` -> `x has Access token: rejected` -> `Destroy user/x`

Or Do you suggest something else by
> remove them from the Classroom

**Comment by tarebyte** [comment]
I want to remove them from the Classroom not delete thi account.

Or it would be cool if we could mark them as disabled.

**Comment by BelieveC** [comment]
Users with rejected auth token will not be able to sign in. If so then I'm confused with the motto to disable the user from a classroom. Maybe I'm wrong somewhere. Looking forward to suggestion

**Comment by nwoodthorpe** [comment]
So Organizations have `users` which represent the owners of the org. This is decoupled from GitHub, we only shows owners that have been invited to the classroom as an owner.

I think all we want to do is remove them from `organization.users`, but them having an invalid token is making this fail for some reason. 

If you want to look into disabling them, that would probably mean temporarily removing their privileges until they've re-authenticated, unless @tarebyte was thinking of something different.

@BelieveC does that make sense?

**Comment by BelieveC** [comment]
@nwoodthorpe 

> I think all we want to do is remove them from organization.users, but them having an invalid token is making this fail for some reason.

I tried removing owner with rejected auth token and it works fine with my instance.

Is it something else you were conveying ?

> If you want to look into disabling them, that would probably mean temporarily removing their privileges until they've re-authenticated

That's what I'm pointing out. Unless the user is re-authenticated he won't be able to log in. So what is the point of disabling the user? Again when he would be re-authenticated user would be enabled or something else?

**Comment by nwoodthorpe** [comment]
Hm ok, I actually haven't tried replicating this, and your question about disabling is a good one as well.

@tarebyte do you have replication steps?

**Comment by BelieveC** [comment]
@tarebyte @nwoodthorpe what should we do with this?
