### ISSUE TITLE
Error when students accept assignment (sometimes solved with refresh)

### ISSUE THREAD

**Issue by greensam** [education/classroom#851]
Any reason in particular this is happening? Students have been reporting it for the last 24 hours or so.

**Comment by tarebyte** [comment]
@greensam does the page just error out? Or is there a flash message that shows up?

**Comment by greensam** [comment]
Sorry for the delay -- it was showing them an application error page (looked like the RoR default page for a 500)

**Comment by mozzadrella** [comment]
@tarebyte @greensam @dinever other users are encountering similar "erratic" behavior": https://education.github.community/t/erratic-behavior-when-accepting-assignments-solved-with-refresh/10540

I was able to reproduce the error: 
Lab 1. Accepted the assignment successfully. 
![screen shot 2017-03-16 at 10 09 37 am](https://cloud.githubusercontent.com/assets/1874003/24000461/abab4eea-0a31-11e7-9d63-ac818ac2eccc.png)

Lab 2. Got the error you were experiencing. When I reloaded the page, I was able to accept the assignment.
![screen shot 2017-03-16 at 10 09 54 am](https://cloud.githubusercontent.com/assets/1874003/24000482/b8dcfe10-0a31-11e7-8c7d-f87f980c0bed.png)
![screen shot 2017-03-16 at 10 10 22 am](https://cloud.githubusercontent.com/assets/1874003/24000483/b8e1c800-0a31-11e7-9eba-20c276a1514a.png)

**Comment by nwoodthorpe** [comment]
Since this error pops up so infrequently, it'll be difficult to find a cause without more information. 

When the server throws 500's like this, a bunch of information is dumped into the server production logs. If anyone else comes across this issue, pasting these logs would help us out a lot!

**Comment by nag92** [comment]
I am having similar issues. Some of my studets are having trouble creating and joining teams.
