### ISSUE TITLE
"An error occurred" from Google search results

### ISSUE THREAD

**Issue by newmerator** [education/classroom#852]
<img width="765" alt="screen shot 2017-03-04 at 10 21 09 am" src="https://cloud.githubusercontent.com/assets/1458245/23580327/1acc1960-00c5-11e7-9b28-4ea59482f8d8.png">

**Comment by tarebyte** [comment]
Will look into it, thanks @newmerator!

**Comment by tarebyte** [comment]
Looks like it's resolved now

<img width="603" alt="screen shot 2017-03-18 at 14 04 41" src="https://cloud.githubusercontent.com/assets/564113/24074688/da9a9fa4-0be3-11e7-9456-686d7b42bcd5.png">
