### ISSUE TITLE
URL Shortener: Assignments' invitation link

### ISSUE THREAD

**Issue by emersonmello** [education/classroom#853]
**Feature request:** 

Currently assignments' invitation link is really big and it is not suitable to be included in lecture' slides. 

Github Classroom could offer a URL shortener for that, like bit.ly or goo.gl.

Cheers,

**Comment by tarebyte** [comment]
So we had bit.ly support early on in the project but it turns out that using bit.ly would expose all of the assignment URLs (see https://github.com/education/classroom/issues/112) so we had to ✂️  it.

We could add our own URL shortening possibly though.

**Comment by emersonmello** [comment]
Great, thanks! My point was exactly that, classroom could offer this feature by itself. 

PS: I didn't know https://git.io .

**Comment by ItsPugle** [comment]
What about an URL shortener, like git.hub? That might work, and from a marketing perspective, is basically free branding and advertising.

**Comment by ccannon94** [comment]
Now that git.io is officially a thing, is there any chance of integration here @nwoodthorpe ?

**Comment by nwoodthorpe** [comment]
Absolutely, I think thats a great idea. I've added it to my TODO :)

**Comment by nwoodthorpe** [comment]
Chatted with @technoweenie today, he says we should look into alternatives to Git.io, it hasn't been worked on in years and has no active devs. 

It would be simple enough to roll our own url shortening in Classroom. Thoughts @johndbritton ?

**Comment by nwoodthorpe** [comment]
This has been in production for a little bit!
