### ISSUE TITLE
Can't switch account when accepting assignments once the assignment link is opened with one of the accounts.

### ISSUE THREAD

**Issue by ubiclassanirban** [education/classroom#858]
I have two GitHub accounts. After opening an assignment link with one of my accounts, if I wish to log in with a different account to accept that assignment, that just doesn't seem to be possible. Even if I open GitHub on a new tab, log out and log in with my second account, the assignment link still opens with me logged in with my former account.

**Comment by tarebyte** [comment]
@ubiclassanirban did you sign out of Classroom?

It may also help to sign in using an Incognito window to make sure all the cookies are clear.

**Comment by ubiclassanirban** [comment]
Ok, I didn't realize that the classroom and the regular GitHub website have separate login sessions.
