### ISSUE TITLE
Creating a new Individual Assignment

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#86]
When a user creates a new Individual Assignment they can give it a name, choose whether the assignment repos will be public or private and choose a repository for starter code if they want to.

<img width="1552" alt="screen shot 2015-08-05 at 14 06 02" src="https://cloud.githubusercontent.com/assets/564113/9093670/64b72026-3b7b-11e5-86f0-f1bf3570e417.png">

**Comment by jasonlong** [comment]
Closing based on work in #101.
