### ISSUE TITLE
Lock new members

### ISSUE THREAD

**Issue by drbeco** [education/classroom#861]
I'd like to be able to create an assignment with a deadline to join.

After that, students should not be able to create new teams/groups nor enter the existent ones.

Thank you.

**Comment by drbeco** [comment]
addendum: another way of looking at it is a "link expire date" (if that makes any sense to the developers inspiration)

**Comment by drbeco** [comment]
Please: what if I edit one group assignment that was previously set to 6 members, current state: some groups full, some groups with 4 or 5 members.

Edition: change the numbers of members to, say, 0.

Will this prevent new groups to appear? Will this edition creates an error in the database somehow?
If so, what if I change to 1, to prevent new members to join groups with currently open spots?

Thank you for clarifying this "workaround".

**Comment by drbeco** [comment]
:thinking: @tarebyte :question:

**Comment by tarebyte** [comment]
@drbeco I think it's an interesting idea, I honestly just don't have the time to implement this right now.

**Comment by drbeco** [comment]
What about this workaround @tarebyte :

> Please: what if I edit one group assignment that was previously set to 6 members, current state: some groups full, some groups with 4 or 5 members.
> 
> Edition: change the numbers of members to, say, 0.
> 
> Will this prevent new groups to appear? Will this edition creates an error in the database somehow?
> If so, what if I change to 1, to prevent new members to join groups with currently open spots?
> 
> Thank you for clarifying this "workaround".

**Comment by tarebyte** [comment]
@drbeco the work around you mentioned above will work.

See https://github.com/education/classroom/blob/master/app/controllers/group_assignment_invitations_controller.rb#L52-L56

**Comment by d12** [comment]
@drbeco There is now an option in the assignment settings for individual/group assignments to disable the invitation link :)
