### ISSUE TITLE
Repository failed to import

### ISSUE THREAD

**Issue by drbeco** [education/classroom#862]
Hello guys,

One of my students got an empty repository instead of the draft code I used as template.
(Of course, I don't know if internally all the database of classroom is coherent)

Could you please take a look at this:

https://github.com/BecoSystems/guess32-Rodrigodpompilio

https://classroom.github.com/classrooms/9666573-becoroom/assignments/guess32

I should point out that all others until now (more or less 30 students out of 40) got their repo ok. This is the only case of failure.

Thank you!

PS. I also wrote an email to Mark, so to let you guys know. It is kind of urgent because of the deadline of the assignment.

**Comment by tarebyte** [comment]
I emailed back @drbeco and fixed for him in  the console. We need to have a better way to handle failed imports, not sure what that should be yet though.

**Comment by drbeco** [comment]
Yes, everything is dandy! Thank you so much. We can close this now.

**Comment by drbeco** [comment]
Or you may want to keep it open to discuss that?

One suggestion: allow the professor to "delete" and "retry". It is a work around, but it is really good to have such power and not need to bother you guys every time.

**Comment by tarebyte** [comment]
@drbeco did you go to the import page and see if you could reimport?

**Comment by drbeco** [comment]
I went only to the classroom assignment page and there is no such option. Where is the import page again, please?

* Also: I went to the repository itself, and I saw it created empty. I could manually copy my template into it and commit/push.

**Comment by tarebyte** [comment]
The import link would've been https://github.com/your-class/the-assignment/import

I _thought_ there was a retry button, but my memory might be failing me, it's been a long week.

**Comment by drbeco** [comment]
Could you clarify the link. I've tried:

* https://classroom.github.com/becoroom/guess32/import
* https://classroom.github.com/9666573-becoroom/guess32/import
* https://classroom.github.com/classrooms/9666573-becoroom/assignments/guess32/import

To no avail

**Comment by tarebyte** [comment]
@drbeco to be clear my example is a github URL, I think you're trying to reach the import via classroom.

**Comment by tarebyte** [comment]
@drbeco the import URL is only available when the repository is being imported

If it's done it will redirect you to the repo

**Comment by drbeco** [comment]
Oh, ok then. I've tried a dozen of others and I was thinking I'm autist or something.

**Comment by drbeco** [comment]
@tarebyte just to register:

It should be:

* https://github.com/9666573-becoroom/guess32-Rodrigodpompilio/import

right? (with the numbers ?)

Just in case someone needs to try this anytime soon (hopefully not)

**Comment by drbeco** [comment]
Now I got! :smiley:  Aahahaha

* https://github.com/becosystems/guess32-Rodrigodpompilio/import

It is actually

* https://github.com/Your-Organization/The-Assignment/import

**Comment by tarebyte** [comment]
Sorry I wasn't more clear @drbeco glad you got it!
