### ISSUE TITLE
Importing also "issues" and other things

### ISSUE THREAD

**Issue by drbeco** [education/classroom#863]
I have a simple question:

* When we have a "template" repository used to generate the assignments, will the classroom import also the issues, milestones and labels that we create in the template?

Thanks

**Comment by tarebyte** [comment]
Unfortunately classroom only support code cloning, we can't do issues and so on as of right now.

**Comment by drbeco** [comment]
Thanks for your reply! 

I've created a script to generate multiple issues in an "individual assignment" to help with this for now. I'll share it here soon.

**Comment by drbeco** [comment]
Here it is. The first version at least. I like very much the way you guys handled the repositories' names when creating a individual assignment. It makes scripting easier.

https://github.com/drbeco/githubin

* The first script I published here is the `github-issue.sh` , but I have another. It is just that the code is a mess right now, and I cannot publish out of shame. It will come soon.
