### ISSUE TITLE
Changing the maximum number of members won't take effect

### ISSUE THREAD

**Issue by drbeco** [education/classroom#865]
I have this assignment, originally with 6 members each group.

There are 6 groups. Before the change they had:
* A: 6 members
* B: 6 members
* C: 5 members
* D: 4 members
* E: 5 members
* F: 4 members

I changed the configuration to be 5 members maximum.

I just saw someone entering group D, turning it into a 6 members group!

--

Link to the assignment:
https://classroom.github.com/classrooms/9666573-becoroom/group-assignments/canibal

Link to the group:
https://github.com/orgs/BecoSystems/teams/chomsky

**Comment by nwoodthorpe** [comment]
Thanks for the bug report!

I've tried to reproduce using the steps below, but I was unable to add an extra user to the team.

1. Created a group assignment with maximum 2 users per team
2. Added 1 user to the team
3. Updated the group assignment to be 1 user per team maximum
4. Attempted to add another user to the team. Button was grayed out.

Have you been able to replicate the issue? If so, replication steps would be great!

Assignment updates are implemented as jobs that perform when the server is less busy, so it's possible a student joined the team in-between you making the change and the job being performed. In this case, the maximum would be enforced for future attempts, but the "extra" student in the group would not be kicked out.

Typically these jobs are performed within seconds, but they can be delayed if the server is under stress. 

I'm going to close the issue for now, if you come across the issue again or have replication steps, feel free to re-open or make a comment :)
