### ISSUE TITLE
Pricing for GitHub Classroom?

### ISSUE THREAD

**Issue by ItsPugle** [education/classroom#866]
Hey there,

I was just wondering how the pricing of GitHub Classroom goes, and well if GitHub Classroom is even a paid service?

Thanks,
Tim/ItsPugle

**Comment by ItsPugle** [comment]
Just going to tag, @sanicki and @mozzadrella - Who may (or may not) remember me from the GitHub Education Community.

**Comment by tarebyte** [comment]
Hi @ItsPugle, GitHub Classroom is and will always be free.

It's meant to be accessible to anyone who needs it.

**Comment by ItsPugle** [comment]
Jesus. That was a fast as reply.
Oh my... xD

Thanks for that! <3

**Comment by sanicki** [comment]
@ItsPugle Just a quick clarification to @tarebyte's response:

[GitHub Classroom](https://classroom.github.com) is and always will be free. GitHub Classroom may be used in conjunction with free or paid [GitHub organizations](https://help.github.com/articles/about-organizations). Free GitHub organizations allow you to create unlimited public repositories, while [paid GitHub organizations](https://help.github.com/articles/organization-billing-plans) include private repositories. Teachers and schools must simply apply for an academic discount from [GitHub Education](https://education.github.com), which provides the benefits of a paid GitHub organization plan at no cost.

Please let us know if you have further questions, or close this issue if you do not.

Have a great weekend!

**Comment by pannirbr** [comment]
@ItsPugle  , what  the  teachers need tom pay  as it is not  clean discountes   can be  at no cost  as  written by you Teachers and schools must simply apply for an academic discount from GitHub Education, which provides the benefits of a paid GitHub organization plan at no cost.
This is an good investments  as  google  classroom is free for schools and teachers  , as  all startup need  crowd  to earn
