### ISSUE TITLE
Creating a Group Assignment

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#87]
This has all of the same options as the Individual Assignment (#86) but the user has to either create a new group of teams, currently known as a grouping, or choose an existing one.

The grouping aspect isn't really super clear at this point, and I'm not really sure what's the best way to show that to the user.

<img width="1552" alt="screen shot 2015-08-05 at 14 06 14" src="https://cloud.githubusercontent.com/assets/564113/9093695/98d8af78-3b7b-11e5-958a-aafae4f34900.png">

**Comment by jasonlong** [comment]
Closing based on work in #101.
