### ISSUE TITLE
Individual & Group assignments should use the same type of validation.

### ISSUE THREAD

**Issue by nwoodthorpe** [education/classroom#871]
Was just tackling a quick win and noticed this. Individual assignments are validated at the model level with nothing on the frontend.  Group assignments are validated on the front end and at the model level.

It's odd because users see errors for group assignments as not being able to click submit, but for individual assignments it shows an error dialog. We should make this more uniform. Either nuke the front end validations on group assignments or add front end validations for individual assignments.

**Comment by johndbritton** [comment]
> Either nuke the front end validations on group assignments or add front end validations for individual assignments.

I think we should add front-end validations across the board.

> as not being able to click submit

We should also make sure it's clear what is preventing them from submitting.

cc/ @tarebyte for background and general awareness

**Comment by nwoodthorpe** [comment]
Got a PR out for making this more uniform #872. 

I like the idea of some sort of identifier of what's causing the issue. :+1:
