### ISSUE TITLE
Way to deal with students that do not own a GitHub account?

### ISSUE THREAD

**Issue by GhostMonk3408** [education/classroom#874]
There is likely (and I'm dealing with) instances where a student or an entire class of students will not have a GitHub account already, and in a short, fast-paced class (say a week-long summer camp course) there may not be time to create an account for each student before it is needed. There should probably be a way to deal with this without hosting GitHub enterprise locally to avoid violating ToS due to controlling multiple accounts at once in order to be able to provide the students with them.

**Comment by nwoodthorpe** [comment]
If you give your first assignment link to the students, they'll be prompted to create an account if they don't have one which takes about 5 minutes. This way, you don't need to do any extra work, the students can manage creating an account. Would this work for your use-case?

**Comment by liam-a-wms** [comment]
Due to limited internet speeds at the summer camp (last time I measured, it was between 2 and 20 Mb/s) it might sink more time than preferable. Though I guess I should be able to reasonably expect my students to be able to multitask account creation and discussion/work.

Liam Williams 
Communications Chairman
C: (410) 245-4781
BOY SCOUTS OF AMERICA
Nentico Lodge 12

**Comment by nwoodthorpe** [comment]
I looked into it, GitHub actually doesn't expose an API endpoint for creating accounts. That means Classroom isn't able to deal with this task, the only way is for your students to do it themselves unfortunately.

Perhaps asking them to have a GitHub account prepared before coming to the camp would work well for your situation?

**Comment by liam-a-wms** [comment]
The way I was thinking being able to do it was to simply create a bunch of @bakna.net accounts (I own the domain) and hand them the credentials at the start of class, and clean up the accounts afterwards; locking and/or removing them.

Liam Williams 
Communications Chairman
C: (410) 245-4781
BOY SCOUTS OF AMERICA
Nentico Lodge 12

**Comment by nwoodthorpe** [comment]
Unfortunately they'll have to do it during your class then. GitHub doesn't offer a way to automate account creation, and trying to create all the accounts yourself may get you banned for "owning too many accounts". Im sorry we aren't able to offer you a better solution :/
