### ISSUE TITLE
Create assignment with starter code from private repo of another organization?

### ISSUE THREAD

**Issue by webdif** [education/classroom#891]
GitHub classroom does not allow multiple classroom per organization (yet #595), so at our school we have created an organization per class.

To make things easier, we create a separate organization that contains all starter code repos for student assignments.

But right now, it's impossible to create an assignment with adding a starter code from a private repo from another organization, even if I'm the owner of the two (the organization that contains all repos and the organization of my class). Currently, I clone from starter orga, then push to class orga, then create assignment. Not very handy…

What can I do? Is there a way to accomplish what I want to do here?
Thank you for your help! And thank you for all the great work you are doing with GitHub Classroom ✌️

**Comment by obcode** [comment]
same here

**Comment by tarebyte** [comment]
@webdif you can in fact use private repos as starter code! We (GitHub Classroom) just need the proper permissions to see it.

> To make things easier, we create a separate organization that contains all starter code repos for student assignments.

So there's your issue 😄 you need to grant the app access to that organization. You grant us access by going to this link https://github.com/settings/connections/applications/64a051cf1598b9f0658f and verifying it on the page.

We have this link on https://classroom.github.com/classrooms/new

<img width="459" alt="screen shot 2017-06-23 at 14 05 53" src="https://user-images.githubusercontent.com/564113/27494774-3cf0f556-581d-11e7-9baa-f9683f0b9e4c.png">

But it's not the most visible

Let me know if that helps!

**Comment by jfiksel** [comment]
Thanks @tarebyte ! So just to confirm, let's say we have an organization called class-master with the private starter repos and an organization class-fall-2017. By granting GitHub Classroom access to both of these organizations, we can make assignments for the class-fall-2017 organization using the private repos from class-master as the starter code?

**Comment by tarebyte** [comment]
@jfiksel sure can!

**Comment by webdif** [comment]
@tarebyte It works :tada:
I think we can close this issue, I have another problem, but not related.

In the repository, there is a branch `master` with the starter code, and a branch `solution` with the expected code. Is there a way to use this repo as starter code, but just clone the `master` branch when a student accepts the invitation?

**Comment by tarebyte** [comment]
@webdif right now the [Source Imports API](https://developer.github.com/v3/migration/source_imports/) (which we use to make the repos for the students) doesn't support branch selection. You get all or nothing.

I've been wanting that as well, and I've talked to the team in charge of that API to see if we can make something like that happen. Will let you know when I hear back!

In the mean time I think we're good to close this issue.
