### ISSUE TITLE
Unable to create new assignment

### ISSUE THREAD

**Issue by Leslie-C** [education/classroom#899]
I cannot create any new assignments from the web interface. As soon as I type in any of the text fields, the "Create assignment" button becomes greyed out and unclickable.

I can refresh the page and press "Create assignment" before entering anything, but, of course, that returns an error since I haven't completed any of the required fields. Am I missing something? Thanks!

<img width="606" alt="image" src="https://cloud.githubusercontent.com/assets/1646180/26797797/fabe5b08-49e2-11e7-8d6b-95c83565347c.png">

**Comment by tarebyte** [comment]
@Leslie-C nope that's totally a bug on our end, I'll take a look and see what's going on.

Sorry for the trouble!

**Comment by Leslie-C** [comment]
Thanks for checking it out. Let me know if you need additional info.

**Comment by robwhess** [comment]
I don't know if this is related, but I and some of my students are currently experiencing a similar problem trying to create a team for a group assignment.  Whenever text is entered in the box to name the team, the "Create team" button is disabled:

<img width="646" alt="screenshot 2017-06-05 12 54 05" src="https://cloud.githubusercontent.com/assets/2029994/26800443/2afd3464-49ee-11e7-885a-a245cc3cc276.png">

**Comment by tarebyte** [comment]
@Leslie-C @robwhess apologies for the issue, I've deployed a fix https://github.com/education/classroom/pull/900 to solve your issue until I can come up with a more proper way to solve it 😄

**Comment by robwhess** [comment]
Thanks @tarebyte!  The fix looks like it's working.  My students are able to sign up for teams again.

**Comment by Leslie-C** [comment]
@tarebyte, works for me too. Thanks again!
