### ISSUE TITLE
I am getting the below issue when i am running inspec remotely .

### ISSUE THREAD

**Issue by krishnapaladugu** [education/classroom#909]
D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:597:in `initialize': A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for "52.172.222.116" port 5985 (52.172.222.116:5985) (Errno::ETIMEDOUT)
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:597:in `new'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:597:in `create_socket'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:742:in `block in connect'
        from D:/opscode/inspec/embedded/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        from D:/opscode/inspec/embedded/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:735:in `connect'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:497:in `query'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient/session.rb:170:in `query'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient.rb:1238:in `do_get_block'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient.rb:1021:in `block in do_request'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient.rb:1129:in `protect_keep_alive_disconnected'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient.rb:1016:in `do_request'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient.rb:858:in `request'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/httpclient-2.7.2/lib/httpclient.rb:761:in `post'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/http/transport.rb:220:in `init_auth'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/http/transport.rb:168:in `send_request'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:152:in `max_envelope_size_kb'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:80:in `max_fragment_blob_size'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:198:in `fragmenter'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:162:in `block in open_shell_payload'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:161:in `map'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:161:in `open_shell_payload'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/power_shell.rb:122:in `open_shell'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:168:in `block in open'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/retryable.rb:37:in `retryable'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:166:in `open'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:129:in `with_command_shell'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/winrm-2.2.3/lib/winrm/shells/base.rb:81:in `run'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/train-0.24.0/lib/train/transports/winrm_connection.rb:62:in `run_command'
        from D:/opscode/inspec/embedded/lib/ruby/gems/2.3.0/gems/train-0.24.0/lib/train/extras/os_detect_windows.rb:13:in `detect_windows'

**Comment by tarebyte** [comment]
@krishnapaladugu so I have a few ideas from just looking at this stack trace, but could you expand on what kind of setup you're got going on here?

It also looks like you may be running an out of date version, I see you're using ruby `2.3.0` but we now run `2.4.1`

**Comment by nwoodthorpe** [comment]
It looks like this is related to an outdated Ruby version. Feel free to re-open if you have more info :)
