### ISSUE TITLE
Allow teachers to configure black-box testing through CI for students submissions

### ISSUE THREAD

**Issue by nwoodthorpe** [education/classroom#913]
It would be cool if teachers could configure some sort of black-box testing through a CI provider for submissions.

E.g. Students are making a simple web-app, and when submitted, this CI system compiles it and sends a few sample requests and compares responses with expectations.

This could also be expanded to anything else that a CI system can do, which is basically anything.

We don't have support for this right now, but I wouldn't be surprised if some professors had home-rolled their own solution. @mozzadrella have you heard of anything like this being done before?

**Comment by johndbritton** [comment]
@nwoodthorpe Is the idea here that the tests wouldn't be visible to the students? Technically I think this can be done already with some off-the-shelf CI tools but it'd take some work on the teachers' part.

**Comment by nwoodthorpe** [comment]
@johndbritton By black-box, I meant more in terms of specs that hit the running application (integration vs unit specs) since those are usually independent of implementation. 

This can 100% be done right now, but the teacher has to set up each assignment repo 1 by 1 with the CI system. A professor with 100 students and 10 classrooms would have to configure CI 1000 times.

**Comment by ryansobol** [comment]
We include an automated test suite in all our assignment repositories. Running the suite allows both students and teachers to know how close a student is to completing the assignment. 

However, we'd love to include a TravisCI badge at the top of the `README.md` file and a webhook for each student assignment. That way, our teachers wouldn't have to manually clone and run the test suite for each assignment when grading.

**Comment by nwoodthorpe** [comment]
Thanks for the feedback!

This is 100% a feature we're looking to implement at some point. It's on our roadmap, so once we find a bit of time, we'll get it done. We'll give you a shout when there's movement on this :)

**Comment by obcode** [comment]
@ryansobol if you have access to a Jenkins server, you can use Jenkinsfile with the Jenkins-GitHub-Plugin to automate the process.
