### ISSUE TITLE
Specify server port in Readme and script/ngrok

### ISSUE THREAD

**Issue by wilfriedE** [education/classroom#914]
The Readme has [the running port](https://github.com/education/classroom#development-environment-variables) to be 5000 however when running the application it points to 5200 instead. Similarly script/ngrok still uses port 5000. 

Also on first run it was pointing to 5300 and then to 5200 on second run. @tarebyte should a specific port be enforced for foreman ?

**Comment by tarebyte** [comment]
Yeah we should enforce those so it's consistent
