### ISSUE TITLE
Dashboard: Overview over all assignments grouped by student

### ISSUE THREAD

**Issue by obcode** [education/classroom#918]
In most of my classes, students have to finish different assignments, sometimes all of them must be finished and sometimes 5 out of 6 or something like that.

It would be useful for graduation to have a view in the dashboard, showing the repositories grouped by students along the information whether CI was successful or not.

GitHub Username | Assignment 1 | Assignment 2 | Assignment 3 | ...
------------------ | ------------- | -------------- | ------------- | ----------
student 1 | repo 1.1 :white_check_mark: |  repo 1.2 :white_check_mark: | repo 1.3 :x: | ...
student 2 | repo 2.1:white_check_mark:  | repo 2.2 :x: | repo 3.3 :white_check_mark: | ...
...

Relates to #708

**Comment by nwoodthorpe** [comment]
I'm not sure exactly what form this would take on, but I like the idea of more classroom summary views. I'm working on some other features right now, but if you want, @obcode you can try tackling this. Contributions are always welcome :)

**Comment by obcode** [comment]
@nwoodthorpe unfortunately I have not enough time to do this work, since I never worked with Ruby on Rails so far :weary:

**Comment by nwoodthorpe** [comment]
No worries!! We'll get to this when we can and ping you when it's implemented :)

**Comment by Youssefares** [comment]
Hey, I'd like to work on this. Still up for grabs?

**Comment by tarebyte** [comment]
Go for it @Youssefares!

**Comment by Youssefares** [comment]
Hey, fired up the repo locally. Thanks for the detailed guides ;)
A couple of questions though, 
1. Does classroom support showing a status from the github APIs for the latest commit in a repo for instance, to be able to display the CI status as originally requested in this issue?
 
If not, should we add a checkbox preference to the assignment settings page, to show CI status, so administrators view a simple :x:  or :+1: like you see on github commits beside the link of the student's repository or sth like that?

2. This end result page will be like tableview component. So in the codebase, did you guys write something similar before? Or can you refer me to another summary page so I can have a reference for design guidelines and keep things consistent :smile: and at the same time not rewrite bits already implemented (a generic component lying somewhere :laughing: ) 

Cheers

**Comment by athityakumar** [comment]
@Youssefares - Though not exactly table UI, I feel that the `orgs/assignment_repos/assignment_repo` partial can be re-used to display the assignments of a student. 😄

**Comment by d12** [comment]
Closing as duplicate of https://github.com/education/classroom/issues/918
