### ISSUE TITLE
Install elasticsearch during setup

### ISSUE THREAD

**Issue by wilfriedE** [education/classroom#919]
Elasticsearch is not installed during setup

`13:25:26 elasticsearch.1 | unknown command: elasticsearch`

**Comment by tarebyte** [comment]
This is kind of surprising, we have elasticsearch as part of the [`Brewfile`](https://github.com/education/classroom/blob/master/Brewfile#L14)

**Comment by wilfriedE** [comment]
Looks like it gets installed however the `elasticsearch` command is not available

```
>> brew list
autoconf		launchdns		node			pkg-config		redis
elasticsearch@1.7	libevent		openssl			postgresql		ruby-build
icu4c			memcached		openssl@1.1		rbenv			terminal-notifier
launch_socket_server	nginx			pcre			readline		yarn
>> elasticsearch
-bash: elasticsearch: command not found
```

**Comment by nwoodthorpe** [comment]
@mozzadrella Sorry this is a little confusing, this is actually a developer setup problem, not a teacher setup one!

**Comment by nwoodthorpe** [comment]
@wilfriedE was this fixed?

**Comment by wilfriedE** [comment]
Nope, but Docker implementation resolves this issue, I am going to close it.
