### ISSUE TITLE
Show organization login on organization page

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#92]
In this case my organization `title` is "August 2015" but there's no indication of the organization login on the page. I think it might be confusing to users to have a separate title from the actual organization login. Perhaps we should show `@classroom` next to the title?

<img width="984" alt="screen shot 2015-08-13 at 12 32 46 pm" src="https://cloud.githubusercontent.com/assets/123345/9248859/7bfcf1a6-41b7-11e5-9345-be67fad2110e.png">

**Comment by johndbritton** [comment]
Also probably worth showing on the dashboard:

<img width="713" alt="screen shot 2015-08-13 at 12 49 04 pm" src="https://cloud.githubusercontent.com/assets/123345/9249090/b6efc638-41b9-11e5-88e2-a19355a9ec02.png">

**Comment by tarebyte** [comment]
@johndbritton something like this?
<img width="1552" alt="screen shot 2015-08-21 at 08 13 29" src="https://cloud.githubusercontent.com/assets/564113/9408010/94171fe8-47dc-11e5-9282-2d39a146121f.png">

/cc @jasonlong for feedback

**Comment by tarebyte** [comment]
This could also be an option

<img width="1552" alt="screen shot 2015-08-21 at 08 17 43" src="https://cloud.githubusercontent.com/assets/564113/9408057/235f9fd6-47dd-11e5-9916-d25ed564b016.png">

**Comment by johndbritton** [comment]
Yeah, those both work. I prefer to use `@` with the login.

**Comment by jasonlong** [comment]
I dig the `@` version as well and I think using 2 lines would be better to allow for longer names. The spacing could be a little better – I'll make a commit w/ some proposed styling.

**Comment by johndbritton** [comment]
If you go with 2 lines, I think the edit button might need some vertical adjustment.

**Comment by jasonlong** [comment]
I updated #101 w/ this placeholder:

![screen shot 2015-08-21 at 10 08 38 am](https://cloud.githubusercontent.com/assets/6104/9410215/f77096ae-47ec-11e5-8d65-e3c27632ce37.png)

**Comment by tarebyte** [comment]
:sparkles:

**Comment by johndbritton** [comment]
This still needs to be wired up:

<img width="445" alt="screen shot 2015-08-25 at 3 09 45 pm" src="https://cloud.githubusercontent.com/assets/123345/9468800/65daccd0-4b3b-11e5-862f-756305d54536.png">

**Comment by johndbritton** [comment]
Looks like it's only needs to be fixed on the invite users page.

**Comment by tarebyte** [comment]
Closed with #132
