### ISSUE TITLE
Explain individual vs group assignments

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#93]
On the new assignment page we should explain a bit more:

<img width="366" alt="screen shot 2015-08-13 at 12 35 12 pm" src="https://cloud.githubusercontent.com/assets/123345/9248903/d7c59128-41b7-11e5-99ef-46b2d75b33b6.png">

Maybe something like this:

__Individual assignment__ - Each student works independently
__Group assignment__ - Students work in self-selecting groups

**Comment by tarebyte** [comment]
Completed in #101
