### ISSUE TITLE
Creating new team causes application error

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#94]
Visiting an assignment URL for a group assignment with starter code of `rails/rails` gives an application error after trying to join a new team.

URL: https://classroom-staging.herokuapp.com/group_assignment_invitations/5ba3f9f295292f846c56bcd72bc9ba56/accept_invitation

Don't really have any more insight into the issue.

**Comment by johndbritton** [comment]
It looks like the repository was created and the starter code was successfully added. Teams were also created and I was given access. Might have been a timeout due to the size of the repository?

**Comment by tarebyte** [comment]
Not sure, I tried to read through the logs but couldn't find anything, I just tried your invitation and it worked for me without errors.

Will investigate further

**Comment by johndbritton** [comment]
I just recreated this error again using `rails/rails` as my starter code. I think it's due to a timeout of the git clone / push that's happening in the background.

I think you should either adjust the timeout and messaging, saying "This might take a few minutes" or move the cloning stuff to the background and render the success page with a message saying "your starter code will be available shortly."
