### ISSUE TITLE
Proposal for Classroom nomenclature

### ISSUE THREAD

**Issue by mozzadrella** [education/classroom#958]
### Current nomenclature:

* Classroom is the product, and a Classroom is a collection of Assignments
* Assignments are repository of starter code, any other materials inside the repository
* Teachers distribute the Assignment via an invitation link
* Students accept Assignments via an invitation link
* Groups of students can be re-used in "groupings"
 
### Problems we’re solving for:

* "Assignment" is too specific and inflexibile, and can get awkward in interface decisions. 
* Teachers want to include materials other than starter code: tests, permissions settings, pre-populated issues and labels.
* Nomenclature doesn’t encompass self-directed learning (do you assign things to yourself? Hmm. No.) 
 
### Proposed nomenclature: 

* When a user signs up for Classroom, the get a **template** to create an **exercise**
* A template is repository with prompts to fill in 
     - Public information (samples, core libraries, public tests, instructions)
     - Unique information (automation, starter code, permissions, repo settings, teacher-specific configurations)
* A user distributes their exercises
* Students work on or complete the exercise
* Teachers publish their exercises 
* Exercises have a due date
 
### Three flows we imagine:
* Teacher (default) create an exercise
* Teacher (adapts content) use an exercise 
* Student completes an exercise
 
### If folks want to help:
* Try using these new terms to refer to your Classroom and see how they sound
* Do the terms apply to your materials?
* What other terms might you suggest?

**Comment by mozzadrella** [comment]
Feedback from a narrative UX expert:

>Exercise: assigned by teacher (tests and other timely, top-down work)
>Activity: stuff that leads up to exercises (self-directed learning, pre-populated issues)

**Comment by mozzadrella** [comment]
* need to revise groups/groupings

**Comment by ryansobol** [comment]
We're using the term "assessment" for all things assignmenty/exercisy. Just food for thought at this point.
