### ISSUE TITLE
Student email issue.

### ISSUE THREAD

**Issue by deepakkoirala** [education/classroom#973]
I have a student email id from my college that is deepak@mycollege.edu.np. So will this email be accepted for student pack ? As I have heard only it has to be .edu email but my email is .edu.np.

So how does it work ? It would help a lot.

**Comment by johndbritton** [comment]
@deepakkoirala Issues on this repository are specifically for GitHub Classroom. You can contact us with your questions about the Student Developer Pack at https://education.github.com/contact.
