### ISSUE TITLE
Unstyled textbox

### ISSUE THREAD

**Issue by nwoodthorpe** [education/classroom#974]
This textbox when accepting a group-assignment is unstyled. Also the submit button is kind of awkwardly right against the textbox. It should look the same as the textboxes in our other forms. 

<img width="1051" alt="screen shot 2017-06-28 at 4 35 32 pm" src="https://user-images.githubusercontent.com/4149056/27665423-eab043a6-5c21-11e7-89c0-d6783a0c8193.png">

**Comment by nwoodthorpe** [comment]
@anglinb could you take this on? I can't assign you since you aren't a contributor

**Comment by anglinb** [comment]
@nwoodthorpe On it!
