### ISSUE TITLE
Launch Check List

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#99]
- [x] Domain name `classroom.github.com` :zap:
- [x] Google Analytics
- [x] Blog Post
- [x] Heroku app
- [x] Documentation
- [x] No blocking [issues](/education/classroom/issues)

/cc @johndbritton

**Comment by johndbritton** [comment]
I think we've got all the administrative stuff done, anything else you can think of @tarebyte?

**Comment by tarebyte** [comment]
That looks fine to me!

**Comment by johndbritton** [comment]
Let's do this :rocket:
