### ISSUE TITLE
Mobile views are broken

### ISSUE THREAD

**Issue by nwoodthorpe** [education/classroom#995]
Not sure which commit we regressed, I thought we checked in the Primer bump.

Mobile views are all messed up, and they all have tons of blank space on the right if the user scrolls that way.

<img width="337" alt="screen shot 2017-07-05 at 2 12 10 pm" src="https://user-images.githubusercontent.com/4149056/27885247-29e1c4b8-618c-11e7-9479-ff997d6c6c5f.png">

<img width="338" alt="screen shot 2017-07-05 at 2 12 16 pm" src="https://user-images.githubusercontent.com/4149056/27885255-2e1468ce-618c-11e7-8b27-398326096689.png">

**Comment by nwoodthorpe** [comment]
@wilfriedE `git bisect` shows it was Primer that introduced this. /classrooms looks fine, but all the other views are bad.

```
➜  classroom git:(50304a30) ✗ git bisect bad
50304a30ea1264fe83225c693066eae8f6452aed is the first bad commit
```

**Comment by wilfriedE** [comment]
@nwoodthorpe , taking a 👀  
Primer is also at version 8 now so I am going to submit a PR with these fixes.

**Comment by nwoodthorpe** [comment]
8?? Wow. I'll make an issue to track the bump, we should do that soon™️ so we don't have to do 4 major version bumps when we want new features like we did with Primer 6.

**Comment by nwoodthorpe** [comment]
I can tackle that if you're getting sick of front end :laughing: Just let me know
